WEEK3 [STEP1] Lily
yagom-academy/swift-starter-week3 pull request #109
Opened 2022-05-08 21:19 UTC by hililyy

@leeari95 
안녕하세요! week3 step1 PR 드립니다!!

week3을 공부하면서 몇가지 궁금한 점이 있어서 질문드립니다!!

먼저 미션에서 어려웠던 점이 카페의 메뉴판을 만드는 부분이였는데, 커피의 종류와 가격을 담을때 커피의 종류가 미션에서 제시한 Coffee 타입 열거형과 어떻게 엮어서 만들어보라는 의미인걸로 해석했는데요! 그래서 enum으로 만든 Coffe타입을 상속받아 사용하려고 시도했는데 enum 타입은 상속이 안된다고 해서 고민하다가 그냥 따로 struct로 적어주었어욤.. 근데 이게 올바른 답은 아닌것 같은데 더 좋은 방법이 있을까요? 힌트 부탁드립니다..🤣

그리고 Person과 CoffeeShop의 타입을 결정할 때 class를 사용하였는데요! 클래스와 구조체의 차이점을 고려했을 때 값 타입을 사용하면 수정되는 정보가 반영되지 않는다고 판단해 class로 작성하였습니다!!

이번 PR도 잘 부탁드립니다!!!😆

2022-05-09 03:09 UTC, leeari95 requested changes
릴리님 안녕하세요~ 🤗
이번에도 스텝1을 구현해주시느라 고생많으셨어요!

메뉴를 만드는 방법에 대한 힌트는 코멘트로 드렸습니다!
구조체와 클래스에 관해서도 코멘트로 질문 남겨드렸는데 확인 부탁드릴게요!

궁금하시거나 어려운 점은 편하게 DM 부탁드릴게요~
이번주도 화이팅입니다! 😉

2022-05-09 03:09 UTC, leeari95 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Bool?
픽업 테이블에 어떤 커피가 올라와있는지 알 수 있는 방법은 없는거 같아요!

2022-05-09 03:09 UTC, leeari95 commented on CodeStarterCamp_Week3/main.swift
> +    func takeOrder() {} // 주문을 받습니다.
전달받는 파라미터가 없어서 어떤 손님에게 주문을 받는지 모르겠네요.

2022-05-09 03:09 UTC, leeari95 commented on CodeStarterCamp_Week3/main.swift
> +    }
힌트 드려봅니다 ㅎㅎ
2주차에 배웠던 [Collection Types](https://docs.swift.org/swift-book/LanguageGuide/CollectionTypes.html#) 중 하나를 활용하면 어떨까요?
그리고 메뉴는 프로퍼티로 있어야 할 것 같아요!

2022-05-09 03:09 UTC, leeari95 commented on CodeStarterCamp_Week3/main.swift
> +class CoffeeShop {
구조체를 사용해도 프로퍼티 값을 수정할 수 있어요. 어떻게 할까요?
한번 알아보도록 합시다!!!
그리고 난 후 아래 질문을 답변해주세요!

> 구조체와 값타입의 차이점을 설명해주실 수 있으신가요? 😊

2022-05-09 15:32 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +class CoffeeShop {
mutating을 사용하면 자신의 프로퍼티의 값을 변경하는 메서드를 사용 가능합니다!

그리고.. 먼저 구조체는 값타입인데, 인스턴스를 생성한 뒤 구조체 밖에서 프로퍼티의 값을 변경하면 생성한 인스턴스의 프로퍼티의 값은 변경되지만 구조체 내의 값은 변경되지 않습니다.
구조체와 값타입의 차이점은 제가 판단하기로는 구조체는 값타입에 속한다는 개념으로 이해했는데 명확한 차이점은 잘 모르겠습니다 ..ㅠㅠ😭

2022-05-09 15:32 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +    }
딕셔너리로 구성해 보았습니다!!!

2022-05-09 15:33 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Bool?
구조체로 묶어서 프로퍼티를 만들어서 구성해주었습니다!..!

2022-05-09 15:34 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +    let gender: String
enum에 male과 female을 가지도록 수정하였습니다!

2022-05-09 15:34 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +    func payMoney() {}  // 돈을 지불합니다.
추가하겠습니다!

2022-05-10 00:51 UTC, leeari95 approved these changes
릴리님~ 수정사항 잘 확인했습니다!😊

큰 문제 없어서 머지해드리겠습니다~ 👋🏻
추가 코멘트도 남겨드렸는데 확인해주세요!
다음 스텝에서 뵐게요 화이팅!! 💪🏻

2022-05-10 00:51 UTC, leeari95 commented on CodeStarterCamp_Week3/main.swift
> +        var pickUpCoffee: String?
이미 커피라는 타입이 있는데 String으로 해주신 이유가 무엇인가요?

2022-05-10 00:51 UTC, leeari95 commented on CodeStarterCamp_Week3/main.swift
> +    var menu: Dictionary<String, Int> = ["americano" : 2000, "espresso" : 2500, "cafeLatte" : 3000, "cafeMoca" : 3500, "vanilaLatte" : 4000]
이 부분도 커피타입을 활용하면 좋을 것 같아요!

2022-05-10 00:51 UTC, merged

2022-05-10 05:10 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +        var pickUpCoffee: String?
아 ..ㅠㅠ 커피타입을 활용할 생각을 못했던것 같아요..! 수정하겠습니다!

2022-05-10 05:10 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +    var menu: Dictionary<String, Int> = ["americano" : 2000, "espresso" : 2500, "cafeLatte" : 3000, "cafeMoca" : 3500, "vanilaLatte" : 4000]
넵!! 감사합니다!!!😆