WEEK3 [STEP2] Lily
yagom-academy/swift-starter-week3 pull request #113
Opened 2022-05-10 21:40 UTC by hililyy

@leeari95 
안녕하세요😆 week3 step2를 진행하면서 궁금했던 몇가지 질문사항 드립니다!

1. 기존에는 Person과 CoffeeShop를 struct으로 작성했는데 이번에는 class로 변경하였습니다. 
struct으로 작성하던 중 mutating을 이용하여 문제없이 코드를 작성하였는데, 카페 수익금을 계산하는 부분에서 금액이 누적되지 않아 고민하다가 struct가 값 타입이라는 특성 때문에 그런가 해서 class로 변경하여 작성하였습니다! 
이 부분을 제가 옳게 판단한건지 궁금합니다..🥺

2. 기존 문제에서 제시되었던 ```order(_ coffee: Coffee)``` 대신 커피가 픽업테이블에 올려졌을 때 주문한 사람을 함께 출력하기 위해 person이라는 매개변수를 추가하여 ```order(_ coffee: Coffee, who person: String)``` 와 같이 작성하였습니다. 
제가 생각하기에 주문한 사람의 이름을 출력하려면 order함수를 호출할 때 누가 주문했는지를 전달해주어야 주문한 사람이 누군지를 CoffeeShop클래스에서 파악할 수 있을것 같더라고요.. 
근데 문제에서 제시한 조건과 맞지 않아서 다른 방법이 있는지 궁금해 질문드립니다!🤣

이번 PR도 잘 부탁드립니다!!😆

2022-05-11 01:02 UTC, leeari95 requested changes
릴리님~ 안녕하세요 !
이번 스텝도 구현하시느라 고생 많으셨습니다!
먼저 질문의 대한 답변은 정답이 아니라는 것을 꼭 인지하시고 참고만 하셨으면 좋겠어요!

## 저의 의견

>기존에는 Person과 CoffeeShop를 struct으로 작성했는데 이번에는 class로 변경하였습니다.
struct으로 작성하던 중 mutating을 이용하여 문제없이 코드를 작성하였는데, 카페 수익금을 계산하는 부분에서 금액이 누적되지 않아 고민하다가 struct가 값 타입이라는 특성 때문에 그런가 해서 class로 변경하여 작성하였습니다!
이 부분을 제가 옳게 판단한건지 궁금합니다..🥺

네! 판단 잘해주신 것 같습니다. 다만 struct는 mutating을 통해서 자신의 속성을 변경할 수 있는데, 어떻게 변경하는 건지 원리를 파악하시면, 값타입의 구조를 이해하는데 큰 공부가 되지 않을까 싶네요.
[Methods - Modifying Value Types from Within Instance Methods
](https://docs.swift.org/swift-book/LanguageGuide/Methods.html)

>기존 문제에서 제시되었던 order(_ coffee: Coffee) 대신 커피가 픽업테이블에 올려졌을 때 주문한 사람을 함께 출력하기 위해 person이라는 매개변수를 추가하여 order(_ coffee: Coffee, who person: String) 와 같이 작성하였습니다.
제가 생각하기에 주문한 사람의 이름을 출력하려면 order함수를 호출할 때 누가 주문했는지를 전달해주어야 주문한 사람이 누군지를 CoffeeShop클래스에서 파악할 수 있을것 같더라고요..
근데 문제에서 제시한 조건과 맞지 않아서 다른 방법이 있는지 궁금해 질문드립니다!🤣

`order(_ coffee: Coffee) 가 호출되면, 카페의 바리스타는 커피를 추출합니다.`
이 조건때문에 말씀 주신거 같네요! 넵! 다른 방법도 있습니다.
Preoperty Observer를 활용한다면 가능합니다!!

#

이 외에 자세한 피드백은 코멘트로 달아드렸습니다. 🤗
고생많으셨어요!!!

2022-05-11 09:12 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +            self.money = self.money - myMenu
그러네요 ㅠ.ㅠ 돈이 부족한지 먼저 확인하도록 수정하였습니다!

2022-05-11 09:13 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +    var revenue: Int = 0
제가 생각하기에는 처음 커피숍을 생성했을 때 수익이 있거나 없을 수 있다는 것 보다는 수익이 0원이라는게 더 적합하다고 판단해서 0으로 초기화 하였습니다!

2022-05-11 09:14 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +    var menu: Dictionary<Coffee, Int> = [.americano : 2000, .espresso : 2500, .cafeLatte : 3000, .cafeMoca : 3500, .vanilaLatte : 4000]
헙 저도 모르게 이동한 것 같아요..! 프로퍼티는 프로퍼티끼리, 메서드는 메서드끼리 모이도록 수정하였습니다!

2022-05-11 09:18 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +    }
이 부분에 고민을 해 보았는데요!.. 제가 생각했을 때, 손님이 돈을 지불하는 placeOrder 함수에서 돈이 부족한지에 대한 여부를 판단해 주었기 때문에 커피숍의 입장에서 돈이 있는지 한번 더 확인하는게 뭔가.. 똑같은 일을 두번 하는 것 같은 생각이 들어서 추가적으로 작성해주지 않았는데요! 제가 질문을 잘못 이해한 걸까요..? 추가 답변도 부탁드립니다!..!

2022-05-11 09:18 UTC, hililyy commented on CodeStarterCamp_Week3/main.swift
> +        pickupCoffee.isExist == true ? giveCoffee(to: person, with: coffee) : print("픽업테이블에 \(coffee)가 존재하지 않습니다.")
두번 검증하는 작업일거라고 생각을 못했네요 ..! 수정하였습니다!

2022-05-12 01:32 UTC, leeari95 commented on CodeStarterCamp_Week3/main.swift
> +    }
손님이 돈을 지불할 수 있는지 파악하고 오더를 내리는 형태라면 문제 없을 것 같습니다 😊

2022-05-12 01:33 UTC, leeari95 approved these changes
릴리님~ 수정사항과 주신 답변 모두 잘 확인했습니다.
더이상 큰 문제가 없어서 머지해드리도록 할게요.
다음 스텝에서 봐요!! 화이팅~~! 🥳

2022-05-12 01:33 UTC, merged