WEEK3 [STEP2] 제리
yagom-academy/swift-starter-week3 pull request #121
Opened 2022-07-07 15:40 UTC by gwd0311

@yeahg-dev

## 고민했던 점

- 커피숍을 머릿속으로 떠올리며 객체로 구현해보기 위해 노력했습니다🔥

---

## 해결이 되지 않은 점

- 이번 과제에서는 딱히 해결되지 않은 부분은 없었습니다..!

---

## 조언을 얻고 싶은 부분

- 보통 객체를 만든 후에 값을 할당할때, 각각의 변수별로 다른 속성을 가질 수 있다고 생각해서 구조체를 많이 이용하게 되는데 혹시 클래스는 현업에서 어떤 경우에 사용하게 되는지 궁금합니다🧐

2022-07-08 09:09 UTC, yeahg-dev commented on CodeStarterCamp_Week3/main.swift
>  }
`if else` 구문의 띄어쓰기 컨벤션을 스스로 정하고 준수를 잘하고 계신점은 칭찬드리고 싶습니다! 
그런데 `if else`의 띄어쓰기는  아래와 같은 형식으로 통일적으로 사용하고 있어요~ 그래서 이건 다수의 문법을 지켜주시는게 더 좋을 것 같습니다🙂
```swift
if money < price {
     print("잔액이 \(price - money)원만큼 부족합니다.")
} else {
    ...
}

2022-07-08 09:18 UTC, yeahg-dev commented on CodeStarterCamp_Week3/main.swift
>  }
`money`와 `price`두 변수를 이어서 안전하게 옵셔널 언래핑하여 사용하신 점은 매우 좋습니다!
그런데 조건문안에 조건문이 들어가니 이른 바 "장풍코드"가 연상이 되는 모습이에요🥲 장풍코드는 가독성을 해치고, depth가 많이 들어가서 분기를 많이 해야하는 상황이 있다면 하나의 함수가 너무 많은 역할을 가지고 가고 있는게 아닌가 하는 의심도 가져볼 만하다고 생각해요. 
이 코드에선 `guard let`을 사용해서 돈이 없다면 다음로직을 실행하지 않고 빠른 종료를 하도록 설계해볼 수 있을 것 같아요. 제가 제시한 방법외에도 조금 더 가독성을 높이고, 함수가 한가지 일만 하도록 리팩터링해보시는 건 어떨까요?

2022-07-08 09:19 UTC, yeahg-dev commented on CodeStarterCamp_Week3/main.swift
> +    var salesRevenue: Int = 10000000
판매수익이라는 의미가 명확하네용!

2022-07-08 09:26 UTC, yeahg-dev commented on CodeStarterCamp_Week3/main.swift
>      var pickUpTable: Array<Coffee> = []
`pickUpTable`에 프로퍼티 옵저버를 구현해서 커피가 테이블에 올라갈 때마다 안내문("missKim 님이 주문하신 카푸치노(이/가) 준비되었습니다. 픽업대에서 가져가주세요.")이 출력되도록 구현해주세요!

2022-07-08 09:28 UTC, yeahg-dev commented on CodeStarterCamp_Week3/main.swift
> +                    money = money - price
이미 만들어둔 Person의 인스턴스 메서드를 활용할 수 있겠네요! 🧐

2022-07-08 09:29 UTC, yeahg-dev commented on CodeStarterCamp_Week3/main.swift
> +missKim.money = 500
`Person(money: 500)`으로도 인스턴스 생성할 수 있다는 점도 알고 계시죠??

2022-07-08 09:31 UTC, yeahg-dev commented on CodeStarterCamp_Week3/main.swift
> +    var menu: Dictionary = [Coffee.아메리카노:4000, .카푸치노:4500, .에스프레소: 3800]
딕셔너리를 활용해서 메뉴와 가격을 훌륭하게 짝지어주셨네요👍

2022-07-08 09:54 UTC, yeahg-dev requested changes
안녕하세요 제리님~
스텝2에 이어서 스텝3도 훌륭하게 기능을 추가 구현해주셨네요! 
각 객체의 메서드를 호출해서 소통하고 `pickUpTable`의 값을 변화시키는 것 까지 훌륭해요!👍 
그런데 여기서 나은 설계를 위해 조금 더 생각해볼 거리가 있어요.

현재 Person타입의 `order`메서드 내부에서 `CoffeeShop`의 프로퍼티인 `salesRevenue`를 수정하고 있어요. 객체지향의 설계에서 지키면 좋을 규칙 두가지를 적용해볼 수 있는 코드라고 생각해요.
- 각 객체의 프로퍼피(상태)는 스스로 관리해야하고, 
- 객체의 프로퍼티를 다른 객체가 바꾸려고 한다면 정해진 인터페이스(함수)를 통해서만 가능하도록 해야함
위 방법을 지키면 더 자율적이고 안전한 객체를 만들 수 있는 방법이라고 생각해요. 커피숍의 이익을 손님이 마음대로 가져가거나 줄이면 안되는 것 처럼 객체를 설계할 때도, 이익을 줄이고 늘이고자 한다면 이익을 증감시키는 커피숍의 인스턴스 메서드를 구현하고, 메서드 호출을 통해서만 이익을 수정할 수 있도록 하는 것이죠. 

제가 위에서 말씀드린 건 객체 지향의 사실과 오해를 통해 얻은 인사이트를 공유 드린 것이고, 이 외에도 SOLID 원칙은 확장 가능하고 유연한 객체지향 설계를 위해 꼭!! 공부해보고 적용해보면 유익한 내용이니 읽어보시길 바래요!

## 조언을 얻고 싶은 부분
> 보통 객체를 만든 후에 값을 할당할때, 각각의 변수별로 다른 속성을 가질 수 있다고 생각해서 구조체를 많이 이용하게 되는데 혹시 클래스는 현업에서 어떤 경우에 사용하게 되는지 궁금합니다🧐

값타입의 구조체는 프로퍼티가 새로운 변수에 할당되거나 메서드 파라미터로 넘겨질 때 복사되어 전달됩니다. 이렇게 복사되어 값이 전달되면 기존 A의 프로퍼티와 복사된 프로퍼티는 다른 주소 영역에 존재하게되고  별개의 라이프사이클을 가지게 됩니다. 그런데 프로그래밍을 하다보면 A의 프로퍼티의 값을 다른 곳에서 공유해야할 상황이 생기기도 해요. 객체의 아이덴티티가 필요할 수도 있구요! 이런 상황에서는 클래스로된 객체를 설계해서 사용하고 있습니다. 그리고 iOS의 UI요소를 제공하는 UIKit 프레임워크의 경우 대부분 클래스로 구현되어 있어, 클래스를 알게 모르게 많이 사용하고 있네요..!

라인별 코멘트도 확인해보시고 추가적 질문이나 이해안되는 점 있다면 디엠이나 댓글 남겨주세요🙂

2022-07-08 14:11 UTC, gwd0311 commented on CodeStarterCamp_Week3/main.swift
>  }
넵 가독성을 높이는 방법으로 리팩터링해보겠습니다🙂

2022-07-08 16:50 UTC, gwd0311 commented on CodeStarterCamp_Week3/main.swift
> +                    money = money - price
살짝 수정해서 활용해보도록 하겠습니다 ㅎㅎ

2022-07-08 16:51 UTC, gwd0311 commented on CodeStarterCamp_Week3/main.swift
> +missKim.name = "김여자"
넵 ㅎㅎ 확인 위해서 그렇게 생성하는 방법으로 수정해보겠습니다!

2022-07-11 05:56 UTC, yeahg-dev commented on CodeStarterCamp_Week3/main.swift
>          }
전보다 훨씬 가독성도 좋아지고, 함수의 재사용도 증가되었어요🚀

이건 사소한 팁인데,  두개의 변수를 한꺼번에 언래핑 할 수도 있다는 사실도 참고해두세용~
(지금 제리님의 구현이 어디에서 nil이 발생했는지 파악하기 쉽기 때문에 더 좋은 구현인 것 같아요)
```swift
guard let price = yagombucks.menu[coffee],
           let money = money else {
            print("There is nil in price")
            return
        }
```

2022-07-11 05:58 UTC, yeahg-dev commented on CodeStarterCamp_Week3/main.swift
> +    }
프로퍼티 옵저버를 훌륭하게 활용하셨어요!👍👍👍👍
`willSet(newValue) `의 `newValue`는 기본 파라미터명이라 `willSet(newOrder)`와 같이 파라미터에 의미를 담아 네이밍 하면
구현부에서 더 잘 읽힐 수 있겠네요:)

2022-07-11 06:01 UTC, yeahg-dev approved these changes
프로퍼티 옵저버, `guard let`, 컨벤션 준수 모두 잘 반영하셨어요💯
수고 많으셨습니다~!!!

다음 스텝도 많이 성장해가는 한 주 만들어보아요💪

2022-07-11 06:01 UTC, merged