Week3 [STEP 1] dasankim
yagom-academy/swift-starter-week3 pull request #124
Opened 2022-07-08 11:57 UTC by DasanKim

@jsim27  

나무님 안녕하세요! 즐거운 불금에 PR를 합니다😅

## 고민했던 점
### Person 타입
1. Person을 `class`로 선언한 이유
  - Person(사람)이라는 타입은 지금 당장은 아니어도, 상속을 하게 될 가능성이 많을 것 같아 class로 선언하였습니다.
  - 사람을 상속받아 "학생" 이나 "개발자" 조금 더 좁은 타입을 만들 수 있기 때문입니다.
2. nickName
- Person의 프로퍼티 중, nickName은 초기값이 꼭 필요하지 않을 것 같아 아래와 같이 선언하였습니다.
```
var nickName: String?
```
3. 이니셜라이저
  - class는 모든 프로퍼티가 반드시 초기화되어야 합니다.
  - 따라서 모든 프로퍼티를 초기화 시키는 `init(name: String, age: Int, nickName: String, money: Int)`와
  - nickName의 초기화를 생략한 `init(name: String, age: Int, money: Int)`를 구현하였습니다. 
  - (nickName은 후에 초기화 가능)
4. order메서드
  - 열거형 Coffee 타입을 매개변수로 받는 메서드로 생각해보았습니다.

### CoffeeShop
1. `struct`로 선언한 이유
  - Person 타입보다 상속의 가능성이 낮다고 판단하여 struct로 선언하였습니다. 
  - 또한, struct의 `memberwise` 이니셜라이즈를 사용해보고싶어서...🙄 => 후에 객체를 생성할 때 저절로 init메서드가 실행되는 것을 확인하였습니다! 싱기방기
2. takeAnOrder() 메서드와 makeCoffee() 메서드
  - 두 기능으로 나눌 수 있을 것 같아서 두 메서드로 나누었습니다. 
  - makeCoffee()같은 경우, CoffeeShop타입(자신의 타입) 안의 프로퍼티에 접근하게 되므로 메서드 앞에 `mutating` 키워드를 사용하였습니다.(mutate의 사전적인 의미: 변형되다)

## 조언을 얻고 싶은 부분
- Dictionary vs enum
  - 메뉴판(커피 종류, 가격) 프로퍼티를 만들 때에, 딕셔너리와 열거형 중에서 어떤 것으로 만들지 고민이 되었습니다.
  - 딕셔너리의 key값은 유일해야 하기에 커피종류가 key값이 되기에 충분한 조건을 가지고 있다고 생각했습니다.
  - 다만, 딕셔너리는 값은 optional이므로 그 값을 활용하기 위해서는 옵셔널 바인딩을 해야하는 번거로움이 있었습니다.
  - 그래서 enum의 rawValue를 사용하여 커피 종류와 가격을 가질 수 있게 할까 고민했습니다.
```
enum Menu: Int { 
  case americano = 2000, latte = 2500 
}
```
  - enum을 많이 사용해보지 않아서(잘 몰라서) 그런지, 딕셔너리보다 enum 타입 프러퍼티의 활용도가 조금은 떨어질 것 같은 느낌이 들었습니다.
  - 이럴 때 딕셔너리와 열거형 중에 어떤 것을 사용하는 것이 효율적인 것일까요?
  - 아니면 무엇이 효율적이다. 라고 결정할 수 있는 기준이 있을까요?

2022-07-10 20:38 UTC, jsim27 requested changes
## 고민했던 점 코멘트

### Person 타입
- Person을 class로 선언한 이유
> Person(사람)이라는 타입은 지금 당장은 아니어도, 상속을 하게 될 가능성이 많을 것 같아 class로 선언하였습니다. 사람을 상속받아 "학생" 이나 "개발자" 조금 더 좁은 타입을 만들 수 있기 때문입니다.

-> 좋습니다! 상속 가능성 이외에 class와 struct의 차이점은 또 무엇이 있을까요?
(이와 관련된 공식문서를 찾아 보셨을 것 같은데, 이 부분이 오랫동안 이해가 안되던 기억이 나네요^^;)

- 이니셜라이저
> class는 모든 프로퍼티가 반드시 초기화되어야 합니다.
따라서 모든 프로퍼티를 초기화 시키는 init(name: String, age: Int, nickName: String, money: Int)와
nickName의 초기화를 생략한 init(name: String, age: Int, money: Int)를 구현하였습니다.
(nickName은 후에 초기화 가능)

-> nickName은 후에 초기화 가능하다고 하셨는데, 후라 함은 언제일까요? 초기화 하기 전에는 nickName은 어떤 상태인가요?

## 조언을 얻고 싶은 부분 코멘트

- Dictionary vs enum
```swift
enum Menu: Int { 
  case americano = 2000, latte = 2500 
}
```
> enum을 많이 사용해보지 않아서(잘 몰라서) 그런지, 딕셔너리보다 enum 타입 프러퍼티의 활용도가 조금은 떨어질 것 같은 느낌이 들었습니다.
이럴 때 딕셔너리와 열거형 중에 어떤 것을 사용하는 것이 효율적인 것일까요?
아니면 무엇이 효율적이다. 라고 결정할 수 있는 기준이 있을까요?

-> 
각 CoffeeShop마다 메뉴 별 가격을 다르게 하고 싶다면 `dictionary`가 적합한 것 같고, Coffee메뉴별 가격이 커피샵과 무관하게 항상 동일한 경우에는 enum의 프로퍼티로도 충분할 것 같아요!
타입 설계 시 이런 고민을 자주 하게 되실텐데, 나중에 어떤 기능이 추가될지, 혹은 어떤 기획이 변경되기 쉬울지를 상상해 보시고 판단하시는게 좋을 것 같습니다. 
- 요구서에는 커피샵 인스턴스를 하나만 생성하도록 되어 있지만, 커피샵이 여러 개 추가될 가능성이 있어 보이죠? 또한 각 커피샵마다 취급하는 커피의 종류가 다를 수도 있고, 메뉴별 가격이 상이할 수도 있을 것 같아요.
이렇게 예측되신다면, 키-값 을 원하는 대로 각각 지정하기 쉽도록 dictionary가 좋을 것 같네요!

- 하지만, 절대 변하지 않고, 모든 상황에서 공통된 - 한정된 선택지를 프로퍼티로 갖는 경우도 있어요.
그럴 때는 열거형 및 열거형의 프로퍼티로 구현해 주는 것이 효율적일 것 같아요!

---

타입에 대해서 배우면 처음에는 혼란스러운 부분이 참 많지만, 갈수록 타입을 중심으로 생각하는 습관이 자리잡으실 거에요! (그걸 객체지향 프로그래밍 패러다임이라고 하죠!ㅎㅎ) 
저는 특히, `이니셜라이저`에 대해 고민하는 과정에서 타입과 객체, 인스턴스에 대한 이해가 많이 늘었던 것 같아요.
`String(someNumber)` 와 같이 형변환을 해 줄 때, 자연스럽게 사용하던 이 `String()` 타입명 뒤에 오는 소괄호가 사실은 이니셜라이저였다는 것이 참 놀랍게 느껴졌던 기억이 나네요.
그 외에도, 공식문서의 여러 항목들 중에서도 굉장히 어려운 파트에 속하는 [공식문서 - 초기화](https://docs.swift.org/swift-book/LanguageGuide/Initialization.html) 파트를 여러 번 읽는 것이 도움이 많이 되었어요. 처음에는 반도 이해가 안가지만요ㅎㅎ

특별히 major한 수정 요청은 없지만, 코멘트에 답변 및 수정하신 후에 merge하도록 할게요!
@DasanKim

2022-07-10 20:38 UTC, jsim27 commented on CodeStarterCamp_Week3/main.swift
> +    var barista: Person?
memberwise 이니셜라이저를 사용하여 CoffeeShop 인스턴스를 생성하면, `옵셔널`인 `var barista`는 초기화되나요? 
- 된다면, 어떤 값이 할당되나요? 
- 안된다면, 초기화 하기 전에 `var barista`에 접근을 시도하면 어떻게 되나요?

2022-07-10 20:38 UTC, jsim27 commented on CodeStarterCamp_Week3/main.swift
> +    var nickName: String? // String? 프로퍼티의 초기값이 꼭 필요 없을 때 사용.
`init(name: String, age: Int, money: Int)` 생성자를 통해 `Person` 인스턴스를 생성하면 `옵셔널`인 `var nickName`은 초기화가 되나요?

- 된다면, 어떤 값이 할당되나요?
- 안된다면, 초기화 하기 전에 `var nickName`에 접근을 시도하면 어떻게 되나요?

2022-07-10 20:38 UTC, jsim27 commented on CodeStarterCamp_Week3/main.swift
> +    }
함수명 `takeAnOrder`와 같은 경우, `An`과 같은 관사는 주로 생략하는 것 같습니다!

2022-07-10 20:38 UTC, jsim27 commented on CodeStarterCamp_Week3/main.swift
> +    }
이니셜라이저에 쓰인 소문자 `self`는 무엇을 의미할까요?
대문자 `Self`도 있는데, 무엇이 다를까요?

2022-07-12 10:51 UTC, DasanKim commented on CodeStarterCamp_Week3/main.swift
> +    }
주문을 받는 행위와 커피를 만드는 행위가 다르다고 생각하여
현재로써 makeCoffee 메소드에는 큰 기능이 없지만
하나의 기능, 하나의 함수를 생각하며 나눴습니다.

나무님의 질문을 받고 조금 더 생각해보니,
주문을 받고 커피를 만드는 것을 하나의 흐름으로 본다면
processOrder(guest: Person, orderedCoffee: Coffee)이라는 하나의 메소드에서 안에서 주문을 받고 커피를 만드는 기능을 하면 좋을 것 같습니다!

2022-07-12 12:15 UTC, DasanKim commented on CodeStarterCamp_Week3/main.swift
> +    var barista: Person?
```
struct CoffeeShop {
    var sales: Int
    var menu: [Coffee: Int] = [.americano: 2000, .cappuccino: 2500, .espresso: 1500, .flatWhite: 3000, .latte: 2500, .macchiato: 3000, .mocha: 2500 ]
    var pickUpTable: [Coffee] = []
    var barista: Person?
...
}
```
CoffeeShop은 자동으로 제공되는 2가지 이니셜라이저를 보여줬습니다.
1. CoffeeShop(sales: ) 
2. CoffeeShop(sales: , menu: , pickUpTable:, barista: )

1. 같은 경우 menu, pickUpTable은 초기값이 들어가 있고, barista 경우는 옵셔널이기 때문에, 초기값 설정이 되어있지 않는 sales만을 인수로 보여주고 있습니다.
2. 같은 경우 모든 프로퍼티를 인자로 받아 초기화를 합니다.

이렇게 쓰고보니,
1,2번 모두 멤버와이즈 이니셜라이저가 맞나요...?

-----

- **옵셔널인 barista은 초기값이 할당되지 않으면 `nil`로 초기화 됩니다!**
- 초기화 하기 전에 barista에 접근을 시도해보았습니다.
```
var someCoffeeShop = CoffeeShop(sales: 20000)
print(someCoffeeShop.barista)
```
- Expression implicitly coerced from 'Person?' to 'Any' 이런 워닝 문구가 뜨면서
- 콘솔창에는 'nil'이라고 출력되었습니다.

2022-07-12 12:23 UTC, DasanKim commented on CodeStarterCamp_Week3/main.swift
> +    }
아 맞다!😂

2022-07-12 12:50 UTC, DasanKim commented on CodeStarterCamp_Week3/main.swift
> +    }
- 이니셜라이저에 쓰인 소문자 self
  - 지금 현재의 인스턴스를 나타내는 키워드
  - 모든 인스턴스들이 암시적으로 생성하는 프로퍼티로 **자기 자신**을 가리키는 프로퍼티다.
  - 이니셜라이저에서 많이 사용하는 이유는, 매개변수의 이름과 프로퍼티의 **이름이 같을 때**  컴파일러에게 명확히 알려주기 위함입니다.
- 대문자 Self
  - 프로토콜을 준수하는 Type을 나타냄.
  - Self 타입은 타입의 이름을 반복해서 쓰는 대신에 현재 타입을 쓸 수 있도록 도와준다.
  - 즉, 클래스, 구조체, 열거형 등에서 Self를 사용하면, 그 타입을 가리킴.
```
extension BinaryInteger { // BinaryInteger protocol 은 모든 integer types의 기초가 되는 프로토콜.
    func squared() ->  Self { 
        return  self * self
    }
    
    func plus() ->  Self {
    	return  self +  self
	}
}
```
`2.squared()`를 실행하면 4가 출력된다.
```
extension BinaryInteger {
func squared() ->  Self { 
        return  self * self
    }

이 부분이
extension Int { // 2는 Int 타입이므로.
func squared() ->  Int { 
        return  2 * 2
    }
```
이렇게 된다는 것! 


---
정리!

self
- 인스턴스 내부에서 인스턴스 속성을 가리킬 때
- 타입속성 메서드에서 타입자체를 가리킬 때
- 타입자체의 형태를 가리킬 때


Self
- 프로토콜에서 채택하는 타입을 지칭할 때
- 타입을 확장할 때 내부에서 타입을 선언할 때
- 타입 내부에서 타입 속성 및 타입 메서드를 지칭할 때

정리 부분은 정리되어 있는 블로그를 그대로 적은 것이나 아직 무슨 말인지 잘 와닿지 않습니다😂

2022-07-12 13:19 UTC, DasanKim commented
공식문서는 영어로 되어있어, 영어실력이 부족한 저는 번역 및 이해하는 데에 시간이 많이 걸리네요.
하지만 꾸준히 읽으면 읽는 속도도 처음보다 빨라지고, 이해 안되던 부분들이 이해되는 날이 오겠죠?🥲



  | Class | Struct
-- | -- | --
타입 | 참조 타입 | 값 타입
상속 | O | X
Extension | O | O
초기화 | Deinit 제공 | Memberwise 제공
자신의 프로퍼티 값 변경 |   | Mutating 키워드 사용
기타 | Apple 프레임워크 구성 | Swift 대부분 구성

으로 정리해보았습니다. 

- 클래스의 기능 범위가 구조체보다 더 크다. 구조체를 할 수 없지만, 클래스는 할 수 있는 기능들
  - 상속 : 클래스의 특성을 다른 클래스에게 물려줄 수 있다.
  - 타입 캐스팅 : 실행 시 컴파일러가 클래스 인스턴스의 타입을 미리 파악하고 검사할 수 있다.
  - 소멸화 구문 : 인스턴스가 소멸되기 직전에 처리해야 할 구문을 미리 등록해 놓을 수 있다.(Deinit)
  - 참조에 의한 전달 : 클래스 인스턴스가 전달될 때에는 참조 형식으로 제공되며, 이때 참조가 가능한 개수는 제약이 없다.

- 구조체를 사용하기 좋은 경우
  1. 서로 연관된 몇 개의 기본 데이터 타입들을 캡슐화하여 묶는 것이 목적일 때
  2. 캡슐화된 데이터에 상속이 필요하지 않을 때
  3. 캡슐화된 데이터를 전달하거나 할당하는 과정에서 참조 방식보다는 값이 복사되는 것이 합리적일 때
  4. 캡슐화된 원본 데이터를 보존해야할 때
- 그 외: 클래스로 정의
  - 상수나 변수에 할당할 때도 값의 복사가 발생하지 않기 때문에 여러 곳에 할당하더라도 메모리 낭비 없음
  - but 클래스가 동시에 참조되고 있는 경우 메모리 해제 시점을 잘 계산해야함.

2022-07-12 21:20 UTC, jsim27 commented on CodeStarterCamp_Week3/main.swift
> +    }
지금은 `self`만 잘 알아 두셔도 충분합니다. 공부하신 내용이 완전히 와닿지 않더라도, 이런게 있구나 하고 한 번 보고 넘어가면 나중에 도움이 되실거에요!

핵심은 `self`는 **인스턴스 자신**을 지칭하는 것이고, Self는 인스턴스 자신의 **타입**을 지칭한다는 것!

2022-07-12 21:31 UTC, jsim27 commented on CodeStarterCamp_Week3/main.swift
> +    var barista: Person?
하나의 인스턴스를 생성하면 (클래스 / 구조체 공통)
"내부의 저장 프로퍼티는 모두 초기화"된다는 기본적이지만 중요한 내용을 짚고 넘어가고 싶었습니다ㅎㅎ (연산프로퍼티, lazy는 제외)

옵셔널은 추후에 초기화하는 것이 아닌, 다른 프로퍼티와 동일한 시점에 초기화되며, 별도로 할당한 값이 없다면 자동으로 **nil이 할당**되지요! (뒤에 `= nil`이 생략되어 있다고 생각하셔도 됩니다.)

역시나 너무 잘 이해하고 계셨네요!ㅎㅎ

2022-07-12 21:34 UTC, merged