Week3 [STEP2] dasanKim
yagom-academy/swift-starter-week3 pull request #137
Opened 2022-07-14 05:01 UTC by DasanKim

@jsim27 
나무님 안녕하세요! 셋째주 두번째 미션 PR입니다:)
class와 struct의 참조 타입과 값 타입에 대해서 이해했다고 생각했는데,
실제 코딩 제 마음과 다르게 움직이는 것을 보고 엄청 헤매다가 클래스와 구조체에 대해 하나 더 배웠습니다.

# 고민했던 점
### 1. 요구서 해석 문제
> missKim은 커피를 구매하는 order(_ coffee: Coffee) 메서드를 실행해 yagomBucks의 make(_ coffee: Coffee, from name: String) 메서드를 호출합니다.
- order(_ coffee: Coffee) 메서드를 실행하여
-  yagomBucks의 make(_ coffee: Coffee, from name: String) 메서드를 호출
인데, `order 메서드`를 실행하면 자동적으로 `make 메서드`를 호출하게 만들라는 뜻인가...?
라고 해석하였습니다. 그래서
- Person 안에 CoffeeShop 타입의 `favoriteCoffeeShop` 프로퍼티를 선언하여
- Person의 order메소드 안에서 `favoriteCoffeeShop.make` 메소드를 호출하도록 하였습니다.

### 2. struct와  class
지난 스텝 때, `CoffeeShop` 타입을 구조체로 구현하였었습니다.
구조체로 구현했던 이유는 상속이 필요하지 않다고 판단했기 때문이었는데요,
그 상태로 step2를 진행하다보니 아래와 같은 난관에 부딪혔습니다.
```swift
struct CoffeeShop {
    var sales: Int = 0
    var menu: [Coffee: Int] = [.americano: 2000, .cappuccino: 2500, .espresso: 1500, .flatWhite: 3000, .latte: 2500, .macchiato: 3000, .mocha: 2500 ]
    var pickUpTable: [Coffee] = []
    var barista: Person?
            
    mutating func make(_ coffee: Coffee, from name: String) {
        if let price = menu[coffee] {
            print("[CoffeeShop]: \(name)에게 \(coffee) 주문을 받았다.")
            print("\(name)님, \(coffee)는 \(price)원 입니다.")
            //sales += price
            //print(sales)
            pickUpTable.append(coffee)
        } else {
            print("해당 커피의 가격이 정해지지 않았습니다.")
        }
    }
}

// 1
print(yagomBucks.sales)

missKim.favoriteCoffeeShop = yagomBucks 
missKim.order(.flatWhite)

// 2
print(yagomBucks.sales)

```
위와 같이 sales의 값을 테스트 해보았습니다.
제가 예상했던 1의 `yagomBucks.sales` 값은 `0`, 2의 `yagomBucks.sales` 값은 `3000`이었지만
실제 실행결과는 `둘 다 0`이었습니다. make 안에서 구현이 잘못되었나 하고 한참을 헤매다가
```
missKim.favoriteCoffeeShop = yagomBucks 
```
구조체는 값만 복사한 다는 것을. 위 코드는 값만 할당하는 것일 뿐 같은 주소를 가리키고 있는 게 아니라는 것을 몸소 체험하였습니다. 의도한 바대로 결과를 얻고싶다면,
`yagomBucks.sales`가 아닌 `missKim.favoriteCoffeeShop.sales` 값을 봐야했던 것이죠!
- **yagomBucks 인스턴스를 missKim만 사용하는 것이라니라, coda도 사용하기 때문**에
- 데이터를 전달하거나 할당되는 과정이 값을 복사하는 것보다 **참조하는 것이 좋겠다**고 판단하여
class 타입으로 바꾸었습니다.

### 3. CoffeeShop의 이니셜라이저
- 지난 스텝의 공부로 모든 프로퍼티에 초기값이 들어있다면, 기본 이니셜라이저 `CoffeeShop()`을 사용할 수 있다는 것을 알게되었습니다. 기본 이니셜라이저를 사용하기 위해 옵셔널 값을 제외한 다른 프로퍼티들을 선언할 때 초기화도 함께 해주었습니다.

### 4. pickUpTabl의 didSet 사용
> pickUpTable에 커피가 올려지면 다음과 같은 문구가 출력됩니다.

에서 **"커피가 올려지면"**이라는 말은 보자마자 week3에서 배웠던 `프로퍼티 감시자`가 딱 떠올랐습니다. 한번 didSet을 사용해보자! 해서 pickUpTable 프로퍼티에 값이 변경될 때 실행되는 didSet을 통하여 원하는 문구를 출력하고자 했습니다.
문구에 필요한 name과 coffee 이름을 가져오기 위하여
- curretGuestName 프로퍼티를 따로 만듦.
- pickUpTable에 인덱스로 접근하기 위한 상수 선언 등

이 마음에 조금 걸립니다.
didSet을 사용해보고자 한 것인데, 이렇게 좀 더 복잡(?)해질 경우에 **make 메소드 안에서 원하는 문구를 출력하는 것이 나았을까요?**

# 해결하지 못한 점 및 조언을 얻고 싶은 점
### 현실 세계를 표현하기 위한 객체
- 하나의 함수는 하나의 기능을 한다를 지키고 싶었고,
- 객체지향프로그래밍을 생각하며 현실세계의 주문 과정과 비슷하게 구현을 하고 싶었지만 구현하다보니 뜻대로 되지 않았습니다.
- 특히 돈을 계산하는 부분에서는, menu에서 해당 커피의 가격이 필요했는데, 이것을 Person과 CoffeeShop 타입 중에서 `어디서`, `어떻게` 처리해야 하는 것이 좋은 것인지에 대한 고민은 지금도 계속 되고 있습니다ㅠㅠ

2022-07-14 12:06 UTC, jsim27 requested changes
# 고민했던 점 코멘트
### 1. 요구서 해석 문제
-> 저도 요구서에 대해서 동일하게 해석했습니다!

### 2. struct와 class
> ...
yagomBucks.sales가 아닌 missKim.favoriteCoffeeShop.sales 값을 봐야했던 것이죠!
yagomBucks 인스턴스를 missKim만 사용하는 것이라니라, coda도 사용하기 때문에
데이터를 전달하거나 할당되는 과정이 값을 복사하는 것보다 참조하는 것이 좋겠다고 판단하여
class 타입으로 바꾸었습니다.

문제 상황에 대해서 정확하게 원인을 파악하시고 테스트를 통해 검증까지 해보신 점 너무 좋네요!
struct와 class 사이에서 선택을 할 때 실질적으로 가장 차이가 나는 부분이 `참조/값`의 특성인 것 같아요.
지금과 같이 객체의 identity가 보장될 필요가 있는 경우에는 참조 타입을 활용해야겠죠!
직접 시행착오를 통해 깨닫게 되셨으니 절대 잊지 않으실 것 같네요😄 

### 3. CoffeeShop의 이니셜라이저
항상 동일한 상태값을 가진 커피샵 객체만을 만들 것이 확실하다면 기본 이니셜라이저를 활용하는 것이 좋겠죠!
초기화 시 다양한 상태값 옵션의 가능성을 열어두고 싶다면, 필요에 맞는 이니셜라이저를 추가로 구현해 둬도 좋을 것 같네요!

### 4. pickUpTabl의 didSet 사용
**"커피가 올려지면"** 이라는 요구사항이 있기에, 프로퍼티 옵저버를 통한 구현도 타당한 것 같습니다!

이런 요구사항이 없을 때, 객체를 직접 설계하신다면 예외 발생 가능성 등 여러 요소를 고민하여 구현하시면 될 것 같아요. 
사실 make 메서드를 통해 커피가 제조될 때에만 해당 문구가 출력되어야 하는 상황이라면, 커피 제조 - 문구 출력은 서로 독점적으로 연관된 기능이기 때문에 make 메서드 안에서 호출하는게 더 타당할 것 같아요.
정말 합리적인 고민을 하신 것 같습니다! 다만 이번에는 프로퍼티 옵저버에 대해 공부해 볼 기회로 삼아서 현재 구현대로 가 봐도 좋을 것 같네요 :)

# 해결하지 못한 점 및 조언을 얻고 싶은 점 코멘트

> 하나의 함수는 하나의 기능을 한다를 지키고 싶었고,
객체지향프로그래밍을 생각하며 현실세계의 주문 과정과 비슷하게 구현을 하고 싶었지만 구현하다보니 뜻대로 되지 않았습니다.
특히 돈을 계산하는 부분에서는, menu에서 해당 커피의 가격이 필요했는데, 이것을 Person과 CoffeeShop 타입 중에서 어디서, 어떻게 처리해야 하는 것이 좋은 것인지에 대한 고민은 지금도 계속 되고 있습니다ㅠㅠ

현재 구현하신 내용을 제가 이해해 보자면,
```
Person 인스턴스가 특정 커피메뉴(coffee)를 order를 하는 과정에서 
favoriteCoffeeShop의 메뉴판(menu 프로퍼티)의 coffee 부분을 보고 가격을 확인 후, 
돈이 충분하면 지불하고 favoriteCoffeeShop에게 만들어달라는 요청을 한다
```
인 것 같아요. 충분히 현실 세계의 주문 과정과 닮아있는걸요..?

현실 세계에서 음료를 주문할 때 내 지갑을 점원에게 줘버리고 점원이 메뉴 가격과 잔액을 비교하지는 않기에, 지금 구현하신 모습이 충분히 각 객체의 역할에 맞게 기능이 할당되어있다고 생각합니다! 👍 
(다만 금액 차감 관련 로직은, 코드의 코멘트를 확인해주세요!)

조금 더 현실과 비슷하게 객체를 설계하자면, `missKim 님이 주문하신 카푸치노(이/가) 준비되었습니다. 픽업대에서 가져가주세요.` 등의 메세지를 CoffeeShop이 직접 출력하는 것이 아닌 baristar의 메서드를 호출하여 baristar가 출력하도록 설계해 볼 수도 있겠네요...! (수정요청이 아닙니다😂) 

---

전반적으로 객체지향에 대한 감을 확실히 갖고 계신 것 같고, 바람직한 방향으로 고민을 하시는 것 같아요!!
이번에는 코드에서 특별히 수정 요청드릴 부분이 많이 없어보이네요.
코드에서 수정요청 드린 부분만 개선해 주시면 바로 Merge 하겠습니다!
@DasanKim

2022-07-14 12:06 UTC, jsim27 commented on CodeStarterCamp_Week3/main.swift
> +                favoriteCoffeeShop?.make(coffee, from: name)
- 이와 같이 `?`를 사용하여 옵셔널 프로퍼티의 하위 프로퍼티 및 메서드에 접근하는 방법의 명칭이 무엇인가요?
- `favoriteCoffeeShop`이 현재 `nil`이라면 34번과 35번 라인은 각각 어떻게 작동할까요?

2022-07-18 12:56 UTC, DasanKim commented
말씀하여주신 부분들을 수정하고, 공부하였습니다:)

# 궁금한 점
> price = favoriteCoffeeShop?.menu[coffee]
이것이 옵셔널 체이닝이라는 것을 눈치채지 못햇었는데, 나무님 덕분에 공부한 것들이 연결되는 기쁨을 느꼈습니다.
그래서 `favoriteCoffeeShop?.menu[coffee]` 값이 아래와 같이 nil일 경우가 2가지라는 것을 깨닫게 되었습니다.

1. favoriteCoffeeShop이 nil일 경우
2. favoriteCoffeeShop의 menu 딕셔너리 타입에서 coffee에 해당하는 값이 없어, nil일 경우

현재는 "좋아하는 카페가 정해지지 않았거나, 해당 커피의 가격이 정해지지 않았습니다." 라고 한번에 처리하였는데요,
옵셔널 체이닝에서 아래처럼 따로 처리할 수 있는 방법이 있을까요?

1. 좋아하는 카페가 정해지지 않았습니다.
2. 해당 커피의 가격이 정해지지 않았습니다.

2022-07-18 14:30 UTC, jsim27 commented on CodeStarterCamp_Week3/main.swift
> +namu.order(.espresso)
🌳🌳🌳🌳

2022-07-18 14:35 UTC, jsim27 commented on CodeStarterCamp_Week3/main.swift
> +            }
`willSet`에서 미리 값을 저장하고 `didSet`에서 비교를 수행하셨네요!
사실 제가 의도한 것은, `willSet`의 `newValue` 프로퍼티와, `didSet`의 `oldValue` 프로퍼티를 활용하는 것이었어요...!

작성하신 `beforeCount`같은 역할을 하는 프로퍼티가 필요하기 때문에 구현이 되어있는 것 같네요! ㅎㅎ
다음부터는 위 프로퍼티들을 요긴하게 활용해보셔요!

2022-07-18 14:35 UTC, jsim27 commented on CodeStarterCamp_Week3/main.swift
> +        }
👍👍👍

2022-07-18 14:53 UTC, jsim27 commented
## 궁금한 점 - 답변
> price = favoriteCoffeeShop?.menu[coffee]
이것이 옵셔널 체이닝이라는 것을 눈치채지 못햇었는데, 나무님 덕분에 공부한 것들이 연결되는 기쁨을 느꼈습니다.
그래서 favoriteCoffeeShop?.menu[coffee] 값이 아래와 같이 nil일 경우가 2가지라는 것을 깨닫게 되었습니다.<br>
> 1. favoriteCoffeeShop이 nil일 경우
> 2. favoriteCoffeeShop의 menu 딕셔너리 타입에서 coffee에 해당하는 값이 없어, nil일 경우 <br>
>
>현재는 "좋아하는 카페가 정해지지 않았거나, 해당 커피의 가격이 정해지지 않았습니다." 라고 한번에 처리하였는데요,
옵셔널 체이닝에서 아래처럼 따로 처리할 수 있는 방법이 있을까요?<br>
>1. 좋아하는 카페가 정해지지 않았습니다.
>2. 해당 커피의 가격이 정해지지 않았습니다.

```swift
guard let price = favoriteCoffeeShop?.menu[coffee] else {
    print("좋아하는 카페가 정해지지 않았거나, 해당 커피의 가격이 정해지지 않았습니다.")
    return
}
```
말씀하신대로 nil이 될 가능성이 두 가지가 존재할텐데요!
모든 경우의 수에 대해 같은 방식으로 예외처리를 하고자 할 때 이렇게 옵셔널 체이닝을 활용하는 것이구요,
질문하신것과 같이 각 경우의 수에 대해 다르게 예외처리를 하려면 옵셔널 바인딩을 따로 해 줘야 합니다...!

```swift
guard let coffeeShop = favoriteCoffeeShop else {
    print("카페가 정해지지 않았습니다.")
    return
}
guard let price = coffeeShop.menu[coffee] else {
    print("커피의 가격이 정해지지 않았습니다.")
    return
}
```
이런 식으로요.

번거롭게 느껴지실 수도 있지만, 각 상황에 대한 처리를 명시해주기에 읽을 때도 그 의도가 더 잘 이해될 수 있겠죠..!

2022-07-18 14:55 UTC, jsim27 commented
@DasanKim 

수정 멋지게 반영해 주셨네요! 고생하셨습니다.
머지하고, 이제 다음 미션으로 가 보아요!! 🚀🚀🚀

2022-07-18 14:56 UTC, merged