Week3 [STEP 1] Rowan
yagom-academy/swift-starter-week3 pull request #146
Opened 2022-11-01 11:07 UTC by Kyeongjun2

@wongbingg
안녕하세요 웡빙! 👋
3주차 STEP 1 PR 보내드립니다. (오늘은 이상하게 태그가 안되네요...)
이번 주 학습 내용은 처음부터 조금 어려웠던 것 같습니다.
지난 주 옵셔널 부분도 다시 복습이 필요하다고 느꼈어요. Dictionary 데이터 추출이 잘 기억나지 않았습니다.😢
이번 주도 잘 부탁드립니다!

# 고민했던 점
## 구조체? 클래스?
- 타입 정의 시작부터 고민이 됐습니다... 클래스 타입을 만들어야하나 구조체 타입을 만들어야하나.
- 참조와 복사의 차이점을 생각해보고 나중에 문제가 없을 것 같다고 느껴서 구조체로 Person, CoffeeShop 타입을 생성했습니다.
## 열거형
- Coffee 타입을 생성할 때, 이후 메뉴 관련 print함수를 사용하면서 rawValue를 사용하고 싶었습니다.
- rawValue 할당 후 왜 출력이 rawValue 값이 아니라 case에 들어있는 메뉴 이름이 나오는지 고민했습니다.
## 구조체 안에서의 함수
- 구조체의 프로퍼티를 변경하는 함수는 앞에 ```mutating```을 붙여줘야 한다는 점!
- 까먹고 안붙였다가 오류를 계속 봤습니다ㅎㅎ...
## 카페 메뉴에 Coffee 열거형 case와 메뉴의 가격 할당하기
- 구조체 내부에서 Dictionary에 멤버를 추가하고 싶었습니다. 메서드 선언 후에도 내부에서는 멤버 할당이 불가능 했던 것으로 기억합니다.
- 이럴 때 static을 붙여 타입 메서드나 타입 프로퍼티를 선언한다면 구조체 내부에서도 메뉴를 작성하는게 가능할까요?? CoffeeShop 타입의 공통된 프로퍼티니까 가능하다면 아메리카노, 에스프레소 등 기본적인 메뉴는 추가해 놓는 것이 좋지 않을까 생각해봤습니다.
- 열거형의 CaseIterable 프로토콜에 대해 찾아봤습니다. -> 해당 프로토콜을 채택할 시, case 들을 배열과 같이 사용할 수 있다! 
```swift
enum someEnumeration: CaseIterable {
       case A, B, C
}

for case in someEnumeration.allCases {     // 반복문에 적용 가능!
print("\(case)")
}
```
- menuList 데이터 할당 시 사용해보려 했지만 price값을 반복문에서 따로따로 넣어주기 힘들어 적용하지 않았습니다...
## memberwise initializer
- 구조체는 따로 이니셜라이저를 설정하지 않으면 memberwise initializer가 작동하는 것으로 배웠습니다!
- 구조체는 memberwise 때문에 프로퍼티 초기값이 없어도 인스턴스 생성이 되는 것으로 이해하고 있었는데 프로퍼티 초기값을 입력하지 않으면 생성이 되지 않더군요. 
- 인스턴스 생성이 아니라 구조체 생성 시 초기값이 없어도 된다는 의미가 맞겠죠?
### memberwise initializer 학습내용 간략하게
- struct는 따로 이니셜라이저를 설정하지 않아도 내부의 프로퍼티와 같은 이름으로 Argument 이름이 생성된다.
- 개인이 추가로 이니셜라이저를 설정할 경우 memberwise는 구동하지 않는다.

---

# 해결이 되지 않은 점
- 메뉴 할당을 노가다로 하지 않고 좀 더 간단하게 나타내고 싶습니다.

---

# 조언을 얻고 싶은 부분
- menuList를 타입 프로퍼티로 적용할 경우엔 지금보다 더 어려워질까요..?
- 어떻게 하면 .appendCoffeeMenu 메서드를 반복문을 이용해서 간단히 사용할 수 있을까요? price값을 메뉴별로 따로 입력할 방법이 떠오르지 않습니다. 😓
- "."을 이용해 rawValue까지 접근하는데 코드가 아주 길어지는 것 같습니다. 조금 더 간단한 방법이 있다면 알고 싶어요.

2022-11-01 23:38 UTC, wongbingg commented
안녕하세요 로웬님 Week3 STEP1 고생하셨습니다 ☺️

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] Person 타입과 CoffeeShop 타입에 요구된 프로퍼티와 메서드가 작성되었는지


### ✅ 고민했던 점에 대하여

#### 구조체? 클래스?
- 잘 생각해 주셨군요. 👏 클래스와 구조체에 대한 내용은 [Swift Programming Language - Structures and Classes](https://docs.swift.org/swift-book/LanguageGuide/ClassesAndStructures.html) 에 자세히 나와있으니 여유되실 때 꼭 읽어보시기 바랍니다 !

#### memberwise initializer
네 맞습니다. class 의 경우 초기값 선언이 되어있지 않으면 initializer를 통해 값을 부여해달라는 요구를 받게 됩니다. 그래서 이 경우 필수적으로 initializer를 작성 해주어야 하지만, 이에 비해 struct는 memberwise initializer를 지원하기 때문에 프로퍼티에 초기값이 없는 상태여도 initializer를 작성하지 않아도 된다는 장점이 있지요.

### ✅ 조언을 얻고싶은 부분

Coffee enum타입에 계산프로퍼티로 각 케이스별 가격을 정해줄 수 있을 것 같아요!
위에 말씀하신 CaseIterable을 채택해서 allCases 반복문 통해 각 케이스별 이름, 가격을 구해 딕셔너리에 넣어줄 수 있지 않을까요?

---

PR 메세지에서 로웬님의 고민 흔적이 보이네요 고생하셨습니다 👏
나머지는 코드를 보며 코멘트로 남겨놓도록 할게요 💪

2022-11-02 00:10 UTC, wongbingg requested changes

2022-11-02 00:10 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +}
Person 구조체를 만드셨군요. 요구사항에 맞게 프로퍼티와 메서드가 잘 작성 되었네요 👏

21번줄의 개행은 로웬님의 컨벤션 인가요? 다른 타입의 끝줄에는 이런 개행이 없는 것 같아요
이런 줄바꿈 규칙도 일관성있게 통일해주면 좋습니다 🧐

2022-11-02 00:10 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +}
커피숍도 요구사항에 맞게 타입이 잘 만들어 졌네요 👍
`revenue` 프로퍼티는 옵셔널 타입으로 선언하신 이유가 있을까요?
CoffeShop 에 e 가 빠진 것 같아요 🧐

2022-11-02 00:10 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +}
커피의 열거형도 잘 만들어 주셨네요! 👍
여기 가격을 나타내는 계산프로퍼티를 만들어줄 수 있을 것 같아요 가능하다면 한번 적용 해볼까요~?

2022-11-02 03:59 UTC, Kyeongjun2 commented on CodeStarterCamp_Week3/main.swift
> +}
```revenue```는 초기값을 0으로 하려다가 나중에 옵셔널 연습 겸 사용해봤습니다!
이미 판매 내역이 있는 경우에는 나중에 초기값을 설정할 수 있을거라고 생각했어요.
e는 수정하겠습니다~~

2022-11-02 03:59 UTC, Kyeongjun2 commented on CodeStarterCamp_Week3/main.swift
> +}
계산 프로퍼티 적용해보겠습니다!! 👍

2022-11-02 05:14 UTC, Tediousday93 commented
PR 수정요청사항 반영해서 푸시 했습니다~!
커피 열거형 내부에 계산프로퍼티로 가격을 case별로 만들어봤어요.
```CaseIterable``` 프로토콜을 사용해서 ```.allCases```로 접근할 수 있도록 했습니다.

그에 따라 CoffeeShop 구조체에서 ```appendCoffeeMenu```함수도 수정했습니다!
간단해지긴 했지만 Coffee 열거형에 있는 case 전체가 메뉴로 들어가는 건 어쩔 수 없네요!
반복문에서 선택적으로 할당하는 방법이 있다면 더 좋았을 것 같습니다.

2022-11-02 05:20 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +            menuList[menu] = menu.returnPrice()
간편하게 menu.price 로 가격에 접근해도 좋을 것 같습니다

2022-11-02 05:23 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +// yagombucks 메뉴 할당
다음 스텝부터 불필요한 주석을 제거 해볼까요 ? 
현재 코드만 봐도 내용이 이해가 가는데, 주석으로 인해 가독성이 떨어질 수 있습니다.

2022-11-02 05:24 UTC, wongbingg commented
고생하셨습니다 로웬님 ~ ! 요구사항 수정이 모두 완료되어 머지 시키겠습니다 👍
코멘트는 참고해보시고 다음 스텝에 적용 해주세요 ! 🙏

2022-11-02 07:16 UTC, merged