Week3 [STEP 1] 500beckwon
yagom-academy/swift-starter-week3 pull request #147
Opened 2022-11-02 07:08 UTC by 500beckwon

@llingo

 ## 고민했던 점
 ### 주제
 - 자신의 잔고를 보는 메소드가 있으면 좋을 것 같아 잔액 조회 함수를 Person안에 만들었습니다
 ---

 ## 조언을 얻고 싶은 부분
 ### 주제
 - CoffeeShop은 struct로 작성했지만 class로 작성했어도 문제가 없었을까요?
 ```

2022-11-02 15:34 UTC, llingo requested changes
안녕하세요 @500beckwon 님!
3주차 미션의 첫번째 PR을 완료하신 것을 축하드립니다 🎉

이번 STEP의 중점사항은 다음과 같습니다.
- [x] 타입과 인스턴스의 관계에 대해서 정확히 이해하고 사용
- [x] 프로퍼티와 메서드의 정의부(타입내부), 호출부(인스턴스가 호출)를 구분하기

요구사항에 맞게 필요한 프로퍼티, 메서드를 구현해주셨습니다 👍 
클래스와 구조체를 사용하셔서 구현해주셨는데 클래스와 구조체는 어떠한 차이점이 있을까요?
남겨드린 코멘트에 대해 확인하시고 디스코드로 DM 주시면 빠르게 Merge 해드리겠습니다 :)

---

**Q1. CoffeeShop은 struct로 작성했지만 class로 작성했어도 문제가 없었을까요?**
A. 코멘트 남겨드린 것처럼 클래스와 구조체의 차이에 대해 고민해보시면 좋을 것 같아요!

2022-11-02 15:34 UTC, llingo commented on CodeStarterCamp_Week3/Step1/Person.swift
> +    }
Person을 왜 클래스로 구현하시게 되셨나요? 구조체로 구현했을때와 비교하여 어떠한 차이가 있을까요?

2022-11-02 15:34 UTC, llingo commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    lazy var totalSales = 0
CoffeeShop을 왜 구조체로 구현하시게 되셨나요? 클래스로 구현했을때와 비교하여 어떠한 차이가 있을까요?

2022-11-02 15:34 UTC, llingo commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    mutating func orderCoffee(coffee: Coffee) {
mutating 키워드는 어떤 기능을 하는 키워드인가요? 🤔

2022-11-02 15:34 UTC, llingo commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    lazy var totalSales = 0
lazy var를 사용해주셨군요 😮 
lazy var와 let는 어떠한 차이가 있을까요? lazy var로 프로퍼티를 구현하시게된 이유가 있으실까요?

2022-11-02 15:34 UTC, llingo commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    }
출력만 하는 메서드이지만 mutating이 붙게된 이유가 무엇일까요? 🤔

2022-11-03 01:30 UTC, 500beckwon commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    mutating func orderCoffee(coffee: Coffee) {
struct의 인스터스 내에서 값을 수정하기 위해 사용하는 기능입니다

2022-11-03 01:30 UTC, 500beckwon commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    lazy var totalSales = 0
### 사용한 이유
- CoffeeShop을 초기화 했을 때 pickUpTable(주문받은 커피)과 totalSales(매출액)은 발생하지 않기에 지연저장 프로퍼티를 사용하여
필요할 때만 사용할 수 있게 선언하였습니다
### let과의 차이
- lazy로 선언된 프로퍼티는 해당 값에 접근(호출) 할 때 변경될 가능성이 있다고 간주되기 때문에 불변 선언인 let을 사용할 수 없습니다

2022-11-03 01:30 UTC, 500beckwon commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    }
lazy var 프로퍼티는 값이 필요할때 계산됩니다. 그 프로퍼티에 호출되는 시점에 프로퍼티의 값이 계산됩니다 즉 struct 내부의 값을 변경하게 되는 것으로 간주되기에 mutating을 사용하지 않으면 컴파일 에러가 납니다

2022-11-03 01:56 UTC, 500beckwon commented on CodeStarterCamp_Week3/Step1/Person.swift
> +    }
Person은 사람을 형상화하는 속성을 가지고 있기 때문에  초기화 할 때 값을 복사하여 할당하는게 아닌 참조 값으로 하는게 맞을 것 같아
class로 선언하였습니다

2022-11-03 02:19 UTC, 500beckwon commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    lazy var totalSales = 0
커피샵을 새롭게 만들 때 참조값을 가진 class보단 복사하여 할당하는 struct로 제작하는게 적합할 것 같아 struct를 사용하였습니다

2022-11-03 02:44 UTC, 500beckwon commented
## 학습한 내용
### class와 struct의 차이점
- class는  참조타입(Reference Type), struct는 값타입(Value type)입니다.
- class는 초기화 시 프로퍼티의 초기값을 init()을 선언하여 설정해야 하지만 struct는 기본 선언하지 않아도 기본 init()이 지원됩니다.
- class는 인스턴스를 다른 변수에 할당 후 값을 변경하면 할당한 변수에도 변경한 값이 적용되지만 struct는 복사하여 변수를 할당하기에 변경한 값이 적용되지 않습니다.

### class와 struct의 공통점
- 프로퍼티 선언이 가능합니다.
- 생성자 init()을 통해 초기 값을 설정할 수 있습니다.
- 인스턴스 내부에 함수 사용이 가능합니다.

## 해결이 되지 않은 점
### struct와 class의 사용 구분
- 알쏭달쏭한 것이 많아 이번 학습 과정에서 배운 class, struct, enum을 다 사용해보고 싶어서 다 사용한게 첫 번째 이유이지만 왜 그것을 사용했나? 에 대한 답은 아직 시원하게 대답할 정도로 숙달 된 것 같지는 않습니다.
-  다만 꾸준히 하다 보면 언젠가 알게 될 것 같아 구글링, 학습 자료 반복 읽기, 과제 내용 다시 해보기 등등을 하고 있습니다

## 조언을 얻고 싶은 점
- Person, CoffeeShop 둘다 class로 하거나 struct로 해도 사용이 가능했습니다. 그렇지만 struct로 했을 때는 인스턴스를 실체화 했을 때 즉
let 이나 var 로 선언 했을 때 class는 let으로 해도 사용이 가능했지만 struct 는 var 로 해야 컴파일 에러가 나지 않았습니다.
이 부분에서는 struct 가 값 타입이기에 내부 프로퍼티의 값을 변경하는 것은 class 와 달리 참조가 아닌 값을 변경하는 것이기에 var 로 선언해야 하는 게 맞는 이유일까요?

2022-11-03 05:42 UTC, llingo approved these changes
@500beckwon 님

이번 스탭 수고하셨습니다 :)
클래스와 구조체, lazy var와 let, mutating 키워드에 대해 잘 작성해주셨습니다. 👍 
다음 스탭도 화이팅입니다 🎉

---

**Q1. 이 부분에서는 struct 가 값 타입이기에 내부 프로퍼티의 값을 변경하는 것은 class 와 달리 참조가 아닌 값을 변경하는 것이기에 var 로 선언해야 하는 게 맞는 이유일까요?**
A. 맞습니다. 클래스의 경우 참조타입이므로 변수는 해당 인스턴스의 메모리 힙 영역의 주소를 나타내므로 let으로 선언해도 문제가 없지만 구조체의 경우 값타입이고 mutating 키워드로 값을 변경할 수 있기 때문에 var로 선언해야합니다. :)

2022-11-03 05:42 UTC, merged

2022-11-16 12:35 UTC, ElonPark commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    lazy var totalSales = 0
현재 코드에서 lazy var를 사용하는 것은 큰 의미가 없어보여요. 내부에서 사용되는 변수들이라면 private(set)을 붙이는걸 추천드려요.
앞으로 작성하는 코드에 적절한 접근제어자를 붙이는 습관을 들여보는건 어떨까요?

2022-11-16 12:37 UTC, ElonPark commented on CodeStarterCamp_Week3/Step1/Person.swift
> +    }
실제 코드상에서 레퍼런스를 참조할 일이 없기 때문에 struct로 선언하는게 적절해보여요.
class와 struct를 선택하는 기준을 찾아보시는것도 좋을거 같아요

2022-11-16 12:38 UTC, ElonPark commented on CodeStarterCamp_Week3/Step1/Person.swift
> +    }
이 글도 도움이 될거에요
https://zeddios.tistory.com/596