Week3 [STEP 1] 무리
yagom-academy/swift-starter-week3 pull request #148
Opened 2022-11-02 10:51 UTC by parkmuri

@wongbingg 
좋은 오후입니다! 오늘은 스터디하며 STEP 1을 공부했습니다🙂
아직까지 개념을 응용하는데에 많은 어려움이 있네요😵‍💫 피드백 기다리고있겠습니다! 

---
## 고민했던 점
 ### 타입 선정
 - 먼저 미션에서 제시하고있는 특별한 타입이 enum밖에 없었기때문에, class와 struct중에 어떤것을 사용할지 고민을 많이했습니다!
 - class와 struct의 차이가 선택의 기준이 될것같아 다시한번 되짚어보는 시간이 되었습니다.
 - 결과적으로 특별히 Reference Type을 사용할것같지는 않아서 struct type을 사용하려고 했으나, class도 써봐야 적응이 될것같아 두개 다 사용해보기로 했습니다🥲!
 
 ### .RawValue의 늪@-@...
 - 출력문에서 영어로 나와 가독성이 떨어질바에야 Coffee.RawValue를 쓸까..? 하고 고민을 많이 하게됐습니다.
 - RawValue를 안하고 메뉴판을 출력하게되면 아래처럼 출력되어 모두 RawValue로 사용했습니다...!
 - ```swift
   print(yagombucks.menu)
   // CodeStarterCamp_Week3.Coffee.americano : 4000, CodeStarterCamp_Week3.Coffee....
   ```

 ### Dictionary 메뉴판
 - 딕셔너리로 만든 메뉴판을 어떻게 사용할 것인가에도 많은 고민이 됐습니다. 
 - 아래의 해결되지 않은 점과 연결되는 이야기인데, enum 값들을 사용하여 dictionary에 key로 넣어줄 수 있을것같았습니다...!
 - 물론 현재도 넣어져있기는 하지만, 반복문을 이용하면 더 쉽게 가능하지 않았을까? 하는 생각이 들면서 어떤 방향으로 해야할지 감이 오지 않았습니다...
 - 하지만 해결이 되지않아 한땀한땀 손으로 쳐서 넣게되었습니다😭...
 
---

 ## 해결이 되지 않은 점
 ### 열거형에 있는 Coffee를 어떻게 응용할것인가?
 - 위의 고민과 같습니다! enum Coffee안에 들어있는 case들을 어떻게 하면 반복문으로 깔끔하게 넣을수 있었을까요...? 혹은 이 생각이 잘못된걸까요?

---

 ## 조언을 얻고 싶은 부분
 ### 타입선정에 대해서
 - 코드를 짜면서 특별히 class나 struct의 이점이 없다고 생각될때, 웡빙이라면 어떤 타입을 더 선호하시나요?
 - 아직까지는 class도 struct도 익숙하지않아 어느부분에 활용해야할지 감이오지 않습니다 ;-;..!

---
그럼 좋은 저녁 보내시길 바라며, 피드백 기다리고있겠습니다!

2022-11-02 13:15 UTC, wongbingg commented
안녕하세요 무리님 Week3 STEP1 고생하셨습니다 ☺️

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] Person 타입과 CoffeeShop 타입에 요구된 프로퍼티와 메서드가 작성되었는지





### ✅ 고민했던 점

- enum 타입의 case 들을 뽑아서 배열로 만드는 방법이 있습니다. 한번 찾아볼까요? 
- enum 타입의 계산프로퍼티에 대해서도 찾아보시면 유용하게 사용하실 수 있을 것 같아요 

### ✅ 해결이 되지 않은 점

#### 열거형에 있는 Coffee를 어떻게 응용할것인가?
case 를 반복문으로 넣어주는 방법은 없는 것으로 알고 있어요. 마치 클래스에 프로퍼티를 반복문으로 넣어주는 것과 같은 개념일 것 같아요 😭
### ✅ 조언을 얻고 싶은 부분

#### 타입선정에 대해서

[Swift Programming Language - Structures and Classes](https://docs.swift.org/swift-book/LanguageGuide/ClassesAndStructures.html)

시간이 있다면 이 문서를 읽어보시는 것을 추천드려요. 둘의 특성과 차이점을 알게 되신다면, 적절하게 타입을 선정할 수 있을겁니다 🧐

2022-11-02 13:33 UTC, wongbingg requested changes

2022-11-02 13:33 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +}
Person 타입이 잘 작성되었네요 👍

`buyingCoffee`  라는 메서드 명이 적합할까요? [API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines) 를 참고하여 적절한지 확인 해봅시다!

2022-11-02 13:33 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +}
CoffeeShop 타입도 잘 작성이 되었네요 👍

한가지 의문점은 딕셔너리의 key타입, 함수의 파라미터 타입으로 Coffee.RawValue 타입을 사용하는 이유가 있을까요? 
Coffee 타입의 RawValue 가 String 으로 되어있습니다. 이 String 값이 필요한 곳에서만 rawValue 를 사용해주면 되지 않을까요?

2022-11-02 13:33 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +}
커피의 종류가 다양하군요 👍
rawValue 값을 사용하기 위해 타입선언을 잘 해주셨네요

2022-11-02 13:33 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +}
`selfIntroduce()` 메서드는 자기소개를 하는 메서드명으로 보여집니다. 
하지만 내부에선 음료를 찾아가라는 메세지를 출력하는 것까지 포함되어 있네요 !
하나의 함수는 하나의 기능만 해야하기 때문에, 이 부분이 분리되면 더욱 좋을 것 같아요

2022-11-02 13:33 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +yagombucks.selfIntroduce()
인스턴스화를 잘 해주셨네요 👍
이제 해당 타입으로 내가 원하는 사람과, 커피숍을 만들 수 있게 되었어요 👏


`Type Annotation` 이 필요할까요 ? 한번 고민 해봅시다 !

2022-11-02 13:33 UTC, wongbingg commented on week3.txt
> + hi
이건 무슨 파일인가요 !? 불필요한 파일은 제거해주는 것이 좋습니다 👀

2022-11-03 04:12 UTC, parkmuri commented
@wongbingg 
피드백 기반으로 수정해보았습니다! 

--- 
### enum을 배열로 만드는 법
 - 열거형 이름 뒤에 CaseIterable을 작성, 활성화 하여 allCases 프로퍼티를 사용하니 배열로 출력이 가능했습니다!
 - 하지만 현재 상황에서 사용할곳이 없어보여 코드에서는 삭제했습니다.
 
### enum타입의 계산 프로퍼티
 - enum타입의 계산 프로퍼티를 찾으려고 구글링해봤지만😵‍💫 무엇을 의도하고 말씀하신건지 이해를 못했어요😭 
 
### buyingCoffee 메소드 네이밍
 - buyingCoffee대신 orderingCoffee로 변경해보았습니다!

### 함수 파라미터, 딕셔너리 키로 .RawValue를 사용한 이유
 - 가장 큰 이유는 CoffeeShop.menu를 출력하게되면 파일명과 함께 열거형이 출력되는것이 가독성이 좋지 않다고 생각했습니다.
 - 필요한데에 rawValue를 사용할 수 있지만 Dictionary인 menu는 출력시 .RawValue가 불가능했기때문입니다🥲

### Type Annotation이 필요할까?
 - 피드백 주신것을 보고 Type Annotation에 대해 찾아보게되었습니다! 타입 추론과 반대되는 개념으로 사용되는것같더라구요!
 - 사용된 곳에서는 type annotation으로 타입을 지정해주지 않아도 인스턴스를 생성하며 프로퍼티에 대한 값들을 할당해주었기 때문에 꼭 사용할 필요는 없겠구나 하는 생각이 들었습니다! 

---
그럼 또 피드백 기다리고있겠습니다 😄!

2022-11-03 05:31 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +     Coffee.affogato : Coffee.affogato.price, Coffee.caramelMacchiato : Coffee.caramelMacchiato.price]
개인적으로는 initializer 에서 해당 dictionary 의 값을 채워줘도 좋다고 생각했습니다
그래서 allCases를 활용하여 반복문을 돌면서 dictionary 의 key, value 값을 넣어주게 되면  코드가 더 간단해질 수 있지않을까 생각했습니다 ☺️

2022-11-03 05:50 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
드렸던 참조링크에서 함수네이밍 `-ing` 에 대해서 찾아보셨나요 ~?
`-ing` 또는 `-ed` 형태의 네이밍은 mutating과 nonmutating 을 구분할 때, 일관성 있는 구분을 위해 사용한다고 나와있는데요, 
현재 orderingCoffee 는 이를 구분해줄 필요가 없다고 보여집니다

2022-11-03 05:51 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
계산 프로퍼티를 적용 해주셨네요 👍

2022-11-03 05:55 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +yagombucks.takeOrder(coffee: Coffee.caramelMacchiato)
파라미터는 이미 들어올 타입을 알고있기 때문에 `Coffee.caramelMacchiato` 대신 `.caramelMacchiato` 로 사용할 수 있습니다 ☺️

2022-11-03 05:56 UTC, wongbingg commented
수정사항이 잘 반영되었네요 👏
추가 코멘트는 보고 판단하신 후 다음 스텝에 잘 녹여내주시면 될 것 같아요
고생하셨습니다 👍 다음 스텝도 화이팅입니다 💪

2022-11-03 05:57 UTC, merged