Week3 [STEP 2] Rowan
yagom-academy/swift-starter-week3 pull request #152
Opened 2022-11-03 09:00 UTC by Kyeongjun2

@wongbingg 
안녕하세요 웡빙! 이번 주 학습도 끝이 보이고 있네요~~ 👍
다음 주에 어떤 미션이 기다리고 있을지 기대가 됩니다 !!
이번 PR도 피드백 잘 부탁드립니다 🙏
다른 구조체의 메서드임에도 호출하면 외부 메서드에 내부 프로퍼티가 자연스럽게 전달되는 상호작용이 신기했어요!
서로 많이 얽혀있어서 어려웠습니다!

# 고민한 점
## 객체간 상호작용 순서
- 역시나 처음 해보는 구조체 간의 의사소통이 제일 처음으로 걸렸는데요! 물론 미션 내용을 잘 읽어보면 어떤 순서로 진행되어야 할지 알 수 있지만... STEP1에 작성해둔 상태에서 고칠게 많다보니 어디부터 손봐야 할 지 꽤 오래 고민했던 것 같습니다.
- 항상 문제에서 요구하는 내용이 중요하다는 말씀에 고민하고 있기 보다는 ToDo 내용의 순서로 코드 작성을 시작해 봤습니다!!
- 금액 지불과 커피를 만드는 순서도 고민해서 작성해봤습니다.

## pickUpTable 프로퍼티
- CoffeeShop 구조체 pickUpTable 프로퍼티를 STEP1 때 Array 타입 변수로 선언했었는데, didSet을 사용하려고 하니 make 함수에서 프로퍼티 값을 할당할 때 ```.append()```,```.removeAll()```메소드를 사용해야하는 번거로움이 있어 Coffee? 타입으로 변경했습니다.
- 제일 처음에는 주문한 사람 이름을 같이 받고 싶어서 Dictionary 콜렉션 타입으로 설정했지만 이도 마찬가지로 didSet 사용 시 Key값과 Value값을 따로 추출해 print하는 방법이 잘 생각나지 않았습니다.
- ```make``` 함수에서 튜플 타입으로 Argument를 받아볼까도 고민해봤습니다만 이 방법도 didSet에서 출력에 어려움이 있다고 느꼈습니다.
- didSet 에서 출력할 내용에 주문한 사람의 이름이 필요해서 새로운 프로퍼티 ```var nameOfOrderedPerson = String?```을 만들었습니다. 

## struct 초기화
- 새롭게 만든 프로퍼티의 값을 나중에 make 함수가 호출됐을 때 할당하기 위해 옵셔널로 만들었습니다.

## Person 구조체 order 메서드
- 메서드 내부에 balanceCheck 상수를 선언해 중복된 코드 ```self.money - coffee.price```를 줄이고자 했습니다.
- if-else구문에서 금액이 모자랄 때 출력되는 값을 ```단항 음수 연산자 -```를 통해 부호를 바꿔주었습니다.

---
# 해결이 되지 않은 점
### Dictionary 콜렉션 타입에 데이터를 할당했을 때 Key값과 Value값을 따로 추출하는 방법
- 꽤나 고민했던 부분입니다. ```Dictionary[Key] = Value```로 데이터를 할당하고 나서 print 함수에서 어떻게 Key와 Value를 따로 뽑아내는지 더 공부해야겠습니다.
- 생각해본 것은 새로운 함수를 만들어서 Key와 Value를 각각 parameter로 받아주는 방법이에요. 🧐

--- 

# 조언을 얻고 싶은 부분
## Array 콜렉션 타입으로 여러개의 주문을 받는 방법
- 스터디에서 캠퍼 혜모리님의 STEP1 코드를 봤었는데 pickUpTable에 다수의 주문을 받을 수 있도록 작성한게 인상적이었어요.
- 저도 시도해보고 싶은데 didSet에서 항상 막힙니다... 구현하기 위해서 공부해볼 내용이나 팁 주시면 감사드리겠습니다!!

2022-11-04 02:43 UTC, wongbingg commented
안녕하세요 로웬님 ☺️ step2 고생하셨습니다

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] 요구된 문구가 출력되는지
- [x] 객체간 소통이 잘 이루어졌는지 

### ✅ 고민했던 점

전반적으로 잘 처리 해주셨네요 👍 로웬님의 고민의 흔적이 보입니다.

### ✅ 해결이 되지 않은 점

#### Dictionary 콜렉션 타입에 데이터를 할당했을 때 Key값과 Value값을 따로 추출하는 방법

1. 어떠한 딕셔너리에서 key 값만 따로 추출한 배열, 또는 value값만 따로 추출한 배열 을 만들고 싶다고 말씀하시는 걸까요 ~? 
2. 각각의 (key, value) pair 에 접근하고 싶으신 걸까요?



## ✅ 조언을 얻고 싶은 부분

#### Array 콜렉션 타입으로 여러개의 주문을 받는 방법

가장 좋은 방법은 캠퍼 혜모리님께 그 방법을 직접 물어보고 벤치마킹 하는 것입니다. 캠퍼분들 끼리 스터디를 하시는 것도 그런 이유에 있습니다. 

아니면 willSet, didSet을 사용하는 `property observer` 에 대한 개념 학습과 예시코드를 많이 작성해보시는 방법도 추천드려요, 활용방안은 무궁무진 하기 때문에 블로그에 나온 예시코드도 따라해보시고, 직접 아이디어를 내서 실험적인 코드를 짜보시는 것도 좋을 것 같아요 ☺️

2022-11-04 02:57 UTC, wongbingg requested changes

2022-11-04 02:57 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +        }
요구사항에 맞게 order 함수를 잘 작성 해주셨네요 👍

- 불필요한 `Type Annotation` 이 있는 것 같아요 !

2022-11-04 02:57 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
pickUpTable 의 기능이 잘 수행되고 있네요  👍
다만, step1 의 요구사항에서는 pickUpTable을 배열로 선언하라고 되어있군요.
이 부분 수정해볼까요 ?

2022-11-04 02:57 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +        pickUpTable = coffee
커피을 만듦으로써 커피값 만큼의 수익이 올라갔네요 👍

2022-11-04 02:57 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +        }
현재 요구사항에 맞게 잘 작성 해주셨지만, 추가적으로 요청사항을 드리려고 해요.

yagombucks 라는 프로퍼티가 현재 전역으로 선언되어 있어 struct  정의부 안에서 바로 접근이 가능한데, 
이는 객체간의 결합도가 높아져서 나중에 유지보수 하기에 힘들 수 있을 것 같아요. 예를들면 다른 로웬벅스, 웡빙벅스 라는 커피숍이 생겼다고 하면 사람(Person)이 커피를 주문할 수 있는 커피숍이 3개나 있지만, order() 메서드를 통해 주문하게 되면 야곰벅스밖에 이용하지 못하게 되겠죠 ? 
커피를 어디카페에서 주문하는 것 까지 파라미터로 받아볼까요 ?

2022-11-04 05:08 UTC, Kyeongjun2 commented on CodeStarterCamp_Week3/main.swift
> +        }
그렇군요!! 카페가 여러개일 경우를 생각하지 못했네요.
수정해보겠습니다~~

2022-11-04 05:12 UTC, Kyeongjun2 commented on CodeStarterCamp_Week3/main.swift
> +    }
배열이 맞는 거였네요...!!
수정해보겠습니다 ㅎㅎㅎㅎ

2022-11-04 08:47 UTC, Kyeongjun2 commented
피드백 적용해서 수정본 push 했습니다~!

1. Person 타입의 구조체에서 주문할 때 카페를 고를 수 있도록 order 메서드에 at cafe parameter를 추가했습니다.
2. pickUpTable을 Array<Coffee>로 재설정했습니다.
3. 추가적으로 Array를 통해 2개 이상의 메뉴를 주문 받을 수 있도록 order메서드, make메서드에 coffee parameter로 전달될 argument를 [Coffee] 로 수정했습니다.
4. Array 타입 데이터를 print 할 때, 대괄호 없애는 방법은 trimmingCharacter로 해보려고 했는데.. Coffee case들의 원시값 사용에 어려움이 생겨 Week2 STEP2,3 PR을 참고하였습니다.
5. ```pickUpTable.removeAll()``` 을 make 메서드 내부에 선언했더니 didSet이 2회 실행되어 didSet 실행 후 removeAll이 수행될 수 있도록 위치를 didSet 내부로 조정했습니다.

아직도 부족함이 많아보이네요.. 이번에도 감사합니다!

2022-11-06 02:56 UTC, wongbingg commented
메뉴도 여러개 시킬 경우를 고려해주셨군요 👍
다른 수정사항도 잘 반영되었네요 👏 고생하셨습니다
이번 스텝 머지 하겠습니다 ! 다음 프로젝트도 화이팅입니다 💪💪

2022-11-06 02:56 UTC, merged