Week3 [STEP 2] kokkile
yagom-academy/swift-starter-week3 pull request #154
Opened 2022-11-04 01:30 UTC by kokkilE

안녕하세요. @wongbingg 
3주차 스텝2 과제를 PR 보냅니다.

## 고민했던 점
### 과제의 요구사항에 명시된 파라미터를 준수해야 할까요?
- missKim은 커피를 구매하는 order(_ coffee: Coffee) 메서드를 실행해 yagomBucks의 make(_ coffee: Coffee, from name: String) 메서드를 호출합니다.

`Person` 클래스의 메소드인 `order()`에서 `CoffeeShop` 정보를 파라미터로 받지 않으면, `yagomBucks`의 `make()`함수를 호출하기 위해 다음과 같이 전역 변수인 `yagomBucks`에 접근해야 합니다.

`yagomBucks.make(coffee, from: self.name)`

`Person.order()`함수 내에서 `yagomBucks` 객체의 메소드에 직접 접근하는게 어색하다고 느껴졌고, 카페 정보까지 받는게 자연스럽다고 생각해서
`order(_ coffee: Coffee, coffeeShop: CoffeeShop)`와 같이 `CoffeeShop` 정보를 파라미터로 받게끔 구현하였습니다.

## 해결이 되지 않은 점

## 조언을 얻고싶은 부분

2022-11-04 04:08 UTC, wongbingg commented
안녕하세요 kokkilE님 ☺️ step2 고생하셨습니다

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] 요구된 문구가 출력되는지
- [x] 객체간 소통이 잘 이루어졌는지 
- [ ] pickUpTable을 잘 활용했는지

### [아쉬운 점]

`pickUpTable` 에 `Property Observer` 를 활용하여 pickUpTable에 커피가 추가될 때마다 프린트문을 출력하도록 구현 해봅시다! 

### ✅ 고민했던 점

잘 생각 해주셨네요 👍 말씀하신 것과 같이 yagombucks 객체가 현재 전역으로 선언되어있기 때문에 Person의 구현부에서도 바로 접근이 가능한데요, 이는 객체간의 결합도가 높아질 뿐 아니라, 확장성에도 막혀있어 좋지 않은 코드구조인 것 같아요. 이를 잘 간파하셔서 처리 해주셨군요 👏👏

2022-11-04 04:19 UTC, wongbingg requested changes

2022-11-04 04:19 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
>      }
CoffeeShop 타입을 프로퍼티로 잘 받아서 처리 해주셨군요 👏
yagombucks 말고도 다른 커피숍에서도 주문을 할 수 있게 되었어요 👍

2022-11-04 04:19 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    func order(_ coffee: Coffee, coffeeShop: CoffeeShop) {
```swift
func order(_ coffee: Coffee, at coffeeShop: CoffeeShop) {

```

이렇게 파라미터 네이밍을 적용해주면 조금 더 문장처럼 이어질 수 있을 것 같아요 🧐

2022-11-04 04:19 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
>      }
이 부분을 `Property Observer` 에서 적용 해볼까요 ? 🧐

2022-11-04 04:19 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
>      }
제가 제안드렸던 형태는 `barista` 프로퍼티는 그대로 옵셔널로 두고

```swift
init(sales: Int, barista: Person? = nil) {
```

이런 형태였습니다 ☺️ 이렇게 변경 후 CoffeeShop의 생성자가 어떻게 나오는지 한번 확인 해볼까요 ?

2022-11-04 04:19 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
>      }
앗 바리스타 프로퍼티가 옵셔널이 아닌 필수 프로퍼티로 변경되었군요 ! 그럼 이 내용도 참고만 해주세요 ☺️

2022-11-04 06:21 UTC, kokkilE commented on CodeStarterCamp_Week3/main.swift
> +    func order(_ coffee: Coffee, coffeeShop: CoffeeShop) {
반영했습니다 :)

2022-11-04 06:21 UTC, kokkilE commented on CodeStarterCamp_Week3/main.swift
>      }
addPickUpTable 함수를 제거하고 Property Observer에서 적용하였습니다.
Property Observer에서 손님의 이름을 알기 위해 coffeeShop 클래스에 guestName 프로퍼티를 추가하였습니다.

2022-11-04 06:21 UTC, kokkilE commented on CodeStarterCamp_Week3/main.swift
>      }
`guestName` 프로퍼티를 추가하며 말씀하신 부분을 적용해봤습니다 :)

2022-11-06 02:01 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +            }
잘 처리해주셨네요☺️

- guestName 과 중괄호 사이 공백을 넣어주면 좋겟네요

2022-11-06 02:01 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
>      }
지금은 사실 init 에서 guestName을 처리해주지 않아도 될 것 같아요. 왜냐하면 옵셔널 변수는 값이 부여되지 않으면 자동으로 nil 값을 가지기 때문이에요🧐

2022-11-06 02:01 UTC, wongbingg commented
요구사항이 모두 수정되었네요. 고생하셨습니다 👏
추가적인 코멘트는 참고만 해주셔도 좋을 것 같아요 
이번 스텝 머지 하겠습니다 ~ 다음 프로젝트도 화이팅입니다 !!👍

2022-11-06 02:02 UTC, merged