Week3 [Step1] 송중
yagom-academy/swift-starter-week3 pull request #155
Opened 2022-11-04 03:14 UTC by kimseongj

## 고민했던 점

### struct와 class 중 무엇을 어디에 쓸까 고민을 했습니다.
- 첫번째로 Person은 sturct 타입으로 구현했습니다. 그 이유는 Person은 값타입으로 인스턴스 생성 혹은 데이터를 전달할 때 값을 복사하기 때문입니다. Person은 여러명이 나올 수 있고, 그 여러명의 정보는 다 다르기 때문에 값의 주소를 참조하기 보단 값을 복사하는게 좋아보여 struct를 사용했습니다.
- 두번째로 CoffeeShop은 struct 타입으로 구현했습니다. 그 이유는 위와 같습니다. 

### Guard let을 사용한 옵셔널의 안전한 추출
- 딕셔너리의 value는 옵셔널 타입이기 때문에 옵셔널을 풀어줄 필요가 있습니다. 이때 if let을 사용하면 if let 구문 안에서만 옵셔널이 풀리지만 guard let을 사용하면 변수 자체의 옵셔널이 풀립니다.

## 궁금한점
### 처음에는 enum Coffee에 한글 이름 대신 가격을 적을려고 했습니다. 하지만 런타임 에러가 났고 해석해보니 enum의 rawValue는 겹치면 안된다는 속성이 있는거 같습니다? 맞는 걸까요??

2022-11-04 10:29 UTC, llingo requested changes
안녕하세요 @kimseongj 님!
3주차 미션의 첫번째 PR을 완료하신 것을 축하드립니다 🎉

이번 STEP의 중점사항은 다음과 같습니다.
- [x] 타입과 인스턴스의 관계에 대해서 정확히 이해하고 사용
- [x] 프로퍼티와 메서드의 정의부(타입내부), 호출부(인스턴스가 호출)를 구분하기

요구사항에 맞게 필요한 프로퍼티, 메서드를 구현해주셨습니다 👍 
클래스와 구조체를 사용하셔서 구현해주셨는데 클래스와 구조체는 어떠한 차이점이 있을까요?
남겨드린 코멘트에 대해 확인하시고 디스코드로 DM 주시면 빠르게 Merge 해드리겠습니다 :)

---

**Q1. 처음에는 enum Coffee에 한글 이름 대신 가격을 적을려고 했습니다. 하지만 런타임 에러가 났고 해석해보니 enum의 rawValue는 겹치면 안된다는 속성이 있는거 같습니다? 맞는 걸까요??**
A. 네 열거형의 RawValue는 Unique 해야합니다! case를 구분할 수 있어야하기 때문이죠 :)

2022-11-04 10:29 UTC, llingo commented on CodeStarterCamp_Week3/Step1.swift
> +    var money: Int
Person을 왜 구조체로 구현하시게 되셨나요? 클래스로 구현했을때와 비교하여 어떠한 차이가 있을까요?

2022-11-04 10:29 UTC, llingo commented on CodeStarterCamp_Week3/Step1.swift
> +    mutating func orderCoffee(coffeeShop: CoffeeShop, coffee: Coffee) {
mutating 키워드는 어떤 기능을 하는 키워드인가요? 🤔

2022-11-04 10:29 UTC, llingo commented on CodeStarterCamp_Week3/main.swift
> +//yagombucks.baristar = misterLee
사용하지 않는 코드는 제거하는 것이 좋습니다 :)

2022-11-04 10:29 UTC, llingo commented on CodeStarterCamp_Week3/Step1.swift
> +    mutating func makeCoffee(takeOrder: [Coffee]) {
takeOrder는 어떤 의미인가요?

2022-11-06 10:04 UTC, kimseongj commented on CodeStarterCamp_Week3/Step1.swift
> +    mutating func orderCoffee(coffeeShop: CoffeeShop, coffee: Coffee) {
mutating은 class의 경우 메서드를 통해 자기 자신의 객체에 들어 있는 프로퍼티들을 변경시킬 수 있지만, struct의 경우 mutating 키워드를 입력하여야만 객체 내 프로퍼티들을 변경시킬 수 있습니다.

2022-11-06 10:07 UTC, kimseongj commented on CodeStarterCamp_Week3/Step1.swift
> +    mutating func makeCoffee(takeOrder: [Coffee]) {
takeOrder는 "주문을 받는다"라는 뜻으로 알고 있습니다. 주문을 받아 커피를 만들기 때문에 사용했습니다.

2022-11-06 10:08 UTC, kimseongj commented on CodeStarterCamp_Week3/Step1.swift
> +    var money: Int
struct는 값타입으로 인스턴스 생성 혹은 데이터를 전달할 때 값을 복사합니다. person은 여러명이 나올 수 있고, 그 여러명의 정보는 다 다르기 때문에 값을 복사하는게 좋아보여 struct로 구현했습니다.

2022-11-06 18:11 UTC, llingo approved these changes
@kimseongj 님

이번 스탭 수고하셨습니다 :) 다음 스탭도 화이팅입니다 🎉

2022-11-06 18:11 UTC, merged