Week3 [STEP 2] 무리
yagom-academy/swift-starter-week3 pull request #156
Opened 2022-11-04 06:59 UTC by parkmuri

@wongbingg 
웡빙! 좋은하루 보내고 계신가요?
STEP 2 미션 수행 후 PR 보냅니다😄!

---
## 고민했던 점
 ### class냐 struct냐😵‍💫
 - step 2를 진행하며, Person타입의 인스턴스가 주문이라는 메소드를 수행 하게되면 CoffeeShop타입의  커피만드는 메소드를 호출해야하는 상황이 발생했습니다.
 - step 1을 진행했던 상태 그대로에서 호출하게되자 다음과 같은 오류가 발생했습니다.
 ``` swift
func orderCoffee(coffee: Coffee, coffeeShop: CoffeeShop) {
        if money >= coffee.price {
            print("\(name) 님이 \(coffee.rawValue)를 주문합니다.")
            money = money - coffee.price
            coffeeShop.makeCoffee(coffee: coffee, from: name) // Cannot use mutating member on immutable value
        } else {
            print("잔액이 \(coffee.price - money)원만큼 부족합니다")
        }
    }
```
 - **Cannot use mutating member on immutable value**
 - 구글링하여 살펴보니, struct는 value type이고 반환하는 값이 불변값이기 때문에 호출이 불가능했다...! 라고 합니다.
 - ~~사실 이 오류에 대해 아직도 이해는 잘 가지않지만... 변수에 값을 담아주거나 class타입을 사용하면 된다는 답이 있었습니다...~~
 - 그래서 class를 사용하게되었습니다! 

 ### initializer에서 dictionary값 채우기
 - 생각해보면 간단한 방법일수도 있었던것을 많이 돌아왔구나! 하고 느꼈습니다.
 - 일일이 이니셜라이저에서 키와 값을 넣어주어도 되었겠어요! 
 - allCases를 이용하여 반복문을 돌면 쉽게 넣어줄수 있었겠다, 라는 말을 듣고 menuUpdate() 메소드를 만들어보았습니다!
 - 먼저 이니셜라이저에 빈 딕셔너리를 할당해주고, 인스턴스에서 메소드를 호출해주었습니다!
 - 웡빙이 의도하신방법이 이것이 맞는지 궁금합니다...!
 
---
## 해결되지 않은 부분
### 네이밍🥲
 - 저번 피드백에서 주신 네이밍에 관한 api 문서를 읽어보았습니다.
 - -ed와 -ing의 차이를 알고 네이밍을 해야한다고 하셔서, 읽어보고 생각한 바로는
 - 함수로인해 값이 변할수있는 경우(mutating한 경우) 동사원형을 사용하고, 값이 변하지 않는 경우 -ed나 -ing로 명명한다... 라고 이해했습니다.
 - 그렇게 orderingCoffee()메소드를 orderCoffee()로 바꾸게되었습니다!
 
 ---
 ## 조언을 얻고 싶은 부분
 ### 에러발생 시 대처
 - 위와 같은 에러 발생 시, 구글링으로 방법은 찾았으나 이해가 가지 않을때 웡빙은 어떻게하나요?...😭
--- 
그럼 피드백기다리고있겠습니다💪🙂 !!

2022-11-06 02:29 UTC, wongbingg commented
안녕하세요 무리님 ☺️ step2 고생하셨습니다

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] 요구된 문구가 출력되는지
- [x] 객체간 소통이 잘 이루어졌는지 
- [ ] pickUpTable을 잘 활용했는지

### [아쉬운 점]

`pickUpTable` 에 `Property Observer` 를 활용하여 pickUpTable에 커피가 추가될 때마다 프린트문을 출력하도록 구현 해봅시다! 

### ✅ 고민했던 점

#### class 냐 struct 냐

struct 내에서 사용되는 `mutating` 키워드에 대해 알아보시면 좋을 것 같아요. 이 오류가 발생하게 된 이유는 orderCoffee 메서드에서 해당 타입의 프로퍼티인 money 값을 변경시켰기 때문인데요, 값이 불변해야 되는데 변해버려서 여기서 오류가 발생된 것 같아요.

#### initializer에서 dictionary 값 채우기
코드를 보고 코멘트 남겨두겠습니다

### ✅ 해결되지 않은 부분

#### 네이밍
잘 처리 해주셨군요 👏 

API Design Guidlines 문서내용 중 일부 입니다

>Name Mutating/nonmutating method pairs consistently. A mutating method will often have a nonmutating variant with similar semantics, but that returns a new value rather than updating an instance in-place.

mutating 메서드는 비슷한 의미를 가진 nonmutating 변형을 가지지만, update 하는 것이 아닌 새로운 값을 반환한다. 라고 해석되네요. 

이 내용을 기반하면, 이렇게 비슷한 기능을 하는 `mutating` 과 `nonmutating` 쌍이 있을 때, 이 둘을 구분지어 주기 위해 `mutating` 함수는 동사원형 네이밍으로, `Nonmutating` 함수는  `-ed`,`-ing` 를 붙인 네이밍으로 지어주어 구분하게 되는 것이죠. 

`orderCoffee()` 라는 메서드는 이 쌍을 가지지 않은 하나의 메서드이기 때문에 저런 네이밍을 사용할 필요가 없다는 것을 말씀드리고 싶었어요 🧐☺️

### ✅ 조언을 얻고 싶은 부분
- 구글링을 해본 뒤에도 찾지 못한다면 바로 저에게 질문 주세요! 저도 질문을 많이 했던 것 같아요 🧐

2022-11-06 02:40 UTC, wongbingg requested changes

2022-11-06 02:40 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
>      }
```suggestion
    func orderCoffee(_ coffee: Coffee, at coffeeShop: CoffeeShop) {
        if money >= coffee.price {
            print("\(name) 님이 \(coffee.rawValue)를 주문합니다.")
            money = money - coffee.price
            coffeeShop.makeCoffee(coffee: coffee, from: name)
        } else {
            print("잔액이 \(coffee.price - money)원만큼 부족합니다")
        }
    }
```

이렇게 전달인자 레이블을 활용해봐도 좋을 것 같아요. 문장형태로 만들어졌죠?

2022-11-06 02:40 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +var coffeeList = Coffee.allCases
꼭 전역에서 선언되어야 할까요? 이 변수가 어디서 사용되고 있을까요?

2022-11-06 02:40 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +yagombucks.menuUpdate()
`menuUpdate()` 이 작업을 initializer 에서 하면 어떨까 생각 했었습니다 🧐

2022-11-06 02:40 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
initializer 의 역할이 무엇이고 어떤 책임을 가질까요 ?

현재 initializer에서 해주지 않아도 되는 것은 무엇일까요 ?

2022-11-07 05:05 UTC, parkmuri commented
@wongbingg 
피드백 감사합니다 웡빙! 
피드백받은곳 수정해보았습니다👀!!
이니셜라이저에 대한 피드백을보고 웡빙이 의도하신게 무엇인지 드디어 깨달은것같습니다🥲 
저도 이니셜라이저에대해서 아예 잘못 생각하고있었던것같구요...! 
또 과제 진행중에 프로퍼티 감시자는 언제 써야할지 감이 안왔는데 코멘트주신거보고 생각이 짧았다고 느꼈어요😭 이럴때쓰는거구나...!
그럼 확인해주시고 코멘트 부탁드립니다!

2022-11-07 06:03 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
`revenue` 와 `pickUpTable` 은 선언부에 이미 이렇게 초기화가 되어있어서 굳이 initializer 안에서 한번 더 초기화 해줄 필요는 없을 것 같아요 🧐

2022-11-07 06:04 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    var menu: Dictionary<Coffee, Int> = [:]
거대한 코드량이 단 한줄로 줄었군요 👍

2022-11-07 06:05 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +misterLee.orderCoffee(_: .caramelMacchiato, at: yagombucks)
이 부분은 사용할 때 파라미터 명을 생략하고 
```swift
missKim.orderCoffee(.vanillaLatte, at: yagombucks)
```
이렇게 사용 가능하지 않을까요 ?

2022-11-07 06:09 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
`Property Observer` 를 잘 활용 해주셨군요 👍

2022-11-07 06:11 UTC, wongbingg commented
수정 요청사항이 잘 반영되었네요 ☺️ 이번스텝도 고생하셨습니다
몇개의 코멘트 남겨두었으니 확인해보시고 다음 프로젝트에 적용 해주셔도 좋을 것 같아요 🧐
다음 프로젝트도 열심히 달려봅시다 !! 💪

2022-11-07 06:12 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
50번 줄의 개행은 의도 하신걸까요 !? 👀

2022-11-07 06:12 UTC, merged