Week3 [STEP 2] 500beckwon
yagom-academy/swift-starter-week3 pull request #157
Opened 2022-11-04 08:33 UTC by 500beckwon

@llingo 

STEP 2를 완료하여 PR을 보내드립니다

 ## 고민했던 점
 ### 에외처리
 - 열거형 Coffee 안에 Int로 가격을 설정할까 싶었지만 카페마다 가격이 다를 수 있기에 새로운 CoffeeShop이 초기화 될 때마다 메뉴 유동성이 있도록 초기화 때 메뉴를 임의로 정할 수 있도록 유지하였습니다
 - 구매를 할 때 카페에 해당 커피가 없을 걸 확인하는 예외처리 함수를 추가하였습니다

 ## 조언을 얻고 싶은 부분
 ### class 안의 함수에서 struct를 paramter로 받을 때
- 본디 CoffeeShop은 struct로 제작되었는데 Person의 make 함수에서 parameter로 받아서 조작할려니 'class Cannot use mutating member on immutable value: '' is a 'let' constant' 라는 컴파일 에러가 떠서 사용이 되지 않았습니다 구글링을 해보니 
함수가 반환하는 값은 불변 값이기 때문에 값을 변경하는 함수는 호출 할 수 없다라는 글을 읽게 되어서 class 로 변경하여 작업하였는데 맞는 방법일까요?

2022-11-05 02:10 UTC, llingo requested changes
안녕하세요 @500beckwon 님!
벌써 3주차의 마지막 스탭이군요 🎉

이번 Step의 중점사항은 다음과 같습니다.
- [x] 인스턴스 사이의 소통을 통해 특정한 결과 (`pickUpTable`) 가 발생한다는 것 이해하기
- [ ] `Property Observer` 를 이해하고, 활용하기

pickUpTable에 커피가 올려지면 출력되는 문구를 직접 make 메서드에서 해주셨는데요! **Property Observer**를 활용하셔서 pickUpTable가 변경되면 관측하고 있다가 문구를 출력해주는 방식으로 변경해보시는 것을 추천합니다! 😄

예외처리도 꼼꼼하게 하신 점도 좋습니다 👍 

---

**Q1. 본디 CoffeeShop은 struct로 제작되었는데 Person의 make 함수에서 parameter로 받아서 조작할려니 'class Cannot use mutating member on immutable value: '' is a 'let' constant' 라는 컴파일 에러가 떠서 사용이 되지 않았습니다 구글링을 해보니 함수가 반환하는 값은 불변 값이기 때문에 값을 변경하는 함수는 호출 할 수 없다라는 글을 읽게 되어서 class 로 변경하여 작업하였는데 맞는 방법일까요?**

A. 함수가 반환하는 값이 불변하기 때문에 1) mutable한 변수에 값을 저장 후 변경하는 방법과 2) 클래스 인스턴스를 사용하는 방법이 있을 것 같습니다. mutable한 변수에 저장하는 경우에는 값을 복사하여 새로운 인스턴스를 생성하는 것이므로 클래스를 사용하신 점 좋습니다 👍

2022-11-05 02:10 UTC, seu0313 commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    init(menu: [Coffee : Int], barista: Person, pickUpTable: [Coffee] = [Coffee](), totalSales: Int = 0) {
[Coffee : Int]보단 `[Coffee: Int]`이 더 좋을 것 같아요 :)

2022-11-05 02:10 UTC, seu0313 commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    }
pickUpTable에 커피가 올려지면 문구가 출력될 수 있도록 
PropertyObserver를 통해 값의 변화를 감지하는 방식으로 수정해볼까요?

2022-11-05 02:10 UTC, seu0313 commented on CodeStarterCamp_Week3/Step1/Person.swift
>          }
커피숍에 메뉴가 없어서 구매를 실패하는 경우에 대한
예외처리를 해주셨군요 👏

2022-11-05 02:10 UTC, llingo commented on CodeStarterCamp_Week3/main.swift
> +missKim.order(coffee: .cafeMocha, coffeeShop: yagombucks)
커피를 주문하는 고객과 바리스타가 동일한 인물인가요? 😅

2022-11-06 18:14 UTC, llingo approved these changes
안녕하세요 @500beckwon 님! 
3주차 미션동안 수고하셨습니다 👍 

이번 Step의 중점사항은 다음과 같으며 모두 잘 수행해주셨습니다
- [x] 인스턴스 사이의 소통을 통해 특정한 결과 (`pickUpTable`) 가 발생한다는 것 이해하기
- [x] `Property Observer` 를 이해하고, 활용하기

다음 주차 미션도 화이팅입니다! 🎉

2022-11-06 18:14 UTC, llingo commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    }
Property Observer를 잘 활용해주셨군요 👍

2022-11-06 18:14 UTC, merged

2022-11-16 12:49 UTC, ElonPark commented on CodeStarterCamp_Week3/Step1/CoffeeShop.swift
> +    func make(_ coffee: Coffee, from name: String) {
이렇게 네이밍 하는게 더 적절할거 같아요
```swift
func makeCoffie(_ coffee: Coffee, withCustomerName name: String)
```