Week3 [STEP1] 졔
yagom-academy/swift-starter-week3 pull request #159
Opened 2022-11-04 15:08 UTC by yijiye

@wongbingg 
3주차 미션 1 PR 입니다! 
질문하기 전에 최대한 생각을 많이 해보려고 이번주에는 웡빙을 많이 찾지 않으려 노력했습니다 :grimacing:

## 고민이 되는 부분
1. 전반적으로 person, coffeeshop, coffee종류를 만든 타입들이 각자인 느낌이 들었어요.
그래서 이런 저런 시도를 많이 했는데 할수록 더 복잡해져서 우선 미션의 내용을 채우는 위주로 작성해보았습니다.

2. Pickuptable ?
coffee를 담을 수 있는 배열 이라고 하길래 array 컬렉션을 사용하라는 뜻인가? 해서 [String]() 타입으로 넣었습니다.
그런데 제대로 문제를 이해한건지 잘 모르겠습니다.

3. 주문한 커피랑 pickuptable에 준비된 커피가 제가 따로 이름을 부여하지 않아도 같은 커피이도록 하고싶은데 이 부분은 조금 더 고민해볼게요 💪

2022-11-06 07:24 UTC, wongbingg commented
안녕하세요 졔 님 Week3 STEP1 고생하셨습니다 ☺️

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] Person 타입과 CoffeeShop 타입에 요구된 프로퍼티와 메서드가 작성되었는지

### ✅ 고민했던 점

1. 각각의 타입은 독립적인 것이 당연한 것 같아요. 연관시켜야할 부분만 연결되는 것이 맞는 것 같습니다.
2. PickUpTable 에는 Coffee 를 담는 배열이라고 요구사항에 나와있네요! 그럼 어떤 타입이 들어와야 할까요? 
3. 객체간 연결을 시키는 부분은 다음스텝에서 진행 하실거에요 👍

2022-11-06 07:34 UTC, wongbingg requested changes

2022-11-06 07:34 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
```suggestion
    func buy(_ coffee: Coffee) {
        print("\(coffee.rawValue) 주세요.")
    }
```

이렇게 하면 네이밍에 중복되는 단어사용을 피할 수 있을 것 같아요 . 또한 함수명과 소괄호 사이에 공백은 이 부분에만 들어갔네요! 다른곳과 같도록 통일시켜 주는 것이 좋습니다

2022-11-06 07:34 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
initializer의 역할은 무엇일까요?
현재 이미 초기화가 되어있어 initializer에 넣어주지 않아도 되는 파라미터가 있습니다. 한번 찾아볼까요?

2022-11-06 07:34 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +}
열거형 타입을 잘 선언 해주셨네요 👍

2022-11-06 07:34 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
요구사항에 나와있는 기능들을 잘 작성 해주셨네요 👍

2022-11-06 13:09 UTC, yijiye commented on CodeStarterCamp_Week3/main.swift
> +    }
프로퍼티 기본값을 지정하기 어려운 경우에 이니셜라이즈를 사용해서 초기값을 전달하는 역할을 합니다. 따라서 pickUpTable은 이니셜라이즈에 넣지 않아도 되는 것 같습니다!!

2022-11-06 13:11 UTC, yijiye commented on CodeStarterCamp_Week3/main.swift
> +    }
앗 이부분 공백은 수정하였습니다. 그런데 중복되는 단어는 위와 같이 buy(_ coffee) 로 표현하는 건가요..? 네이밍 규칙중 하나인가요???

2022-11-06 13:14 UTC, yijiye commented
❓ pickUpTable 의 배열
: 커피를 담는 배열이라고 하였으니 Array<String> 값으로 지정해주었는데요...! 그래서 주문한 커피를 append 하는 식으로 작성을 했습니다

2022-11-07 02:04 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
아니요! 정해진 규칙은 아닙니다. 가독성 측면에서 반복되는 단어 사용이 보기 좋지 않기 때문에 제가 자주 사용하는 방법이에요.
제가 드리는 코멘트는 정답이니 이렇게 바꿔야 한다! 라고 말씀드리는 것이 아닌, 다른방향을 제안 드리는 것이고 졔 님이 판단 후, 졔 님의 스타일대로 코드에 적용해주셔도 좋을 것 같아요 ☺️
파라미터 네임에 `_` 는 함수 사용(호출) 시, 파라미터명을 생략 해주는 기능을 합니다. 이 부분도 알아보시면 좋을 것 같아요 🧐

2022-11-07 02:11 UTC, wongbingg requested changes

2022-11-07 02:11 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
이니셜라이저에서 값을 받아와줄 필요가 없으니 파라미터로도 받을 필요가 없지 않을까요 ? 🧐
33번 줄의 `pickUpTable: [String] = [String]()` 이 부분은 어떤 의미로 작성 해주신걸까요? 🧐

2022-11-07 02:11 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    }
파라미터 명은 소문자 카멜케이스를 이용합니다 🧐

2022-11-07 02:13 UTC, wongbingg requested changes

2022-11-07 02:13 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable = [String]()
`pickUpTable` 은 커피를 담는 배열 이어야 할텐데, 타입을 봐선 문자열을 담는 배열인 것 같아요 🧐
커피를 담는 배열이라는 의미를 나타낼 수 있도록 타입을 수정 해볼까요 ?

2022-11-07 09:33 UTC, yijiye commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable = [String]()
커피를 담은 배열이므로 열거형으로 만들어준 [Coffee]() 로 해줘야 하는 걸로 이해를 했습니다.
그리고 pickUpTable에 주문이 들어온 커피를 또 다시 할당 해주는 구문을 추가해야 하는건가요..?

2022-11-07 09:34 UTC, yijiye commented on CodeStarterCamp_Week3/main.swift
> +    }
init을 입력하니 자동완성으로 만들어주길래 저 pickUpTable이 있어야 하는 건가? 생각했었는데 웡빙 말대로 필요없는 부분인 것 같아요!

2022-11-07 09:34 UTC, yijiye commented on CodeStarterCamp_Week3/main.swift
> +    }
넵! 수정했습니다

2022-11-07 09:51 UTC, wongbingg commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable = [String]()
제조가 완료된 커피를 pickUpTable 배열에 추가해주면 될 것 같아요 ☺️ 이 부분은 step2에서 수행해주셔도 될 것 같아요

2022-11-07 09:53 UTC, wongbingg commented
수정사항에 잘 반영되었네요 👏
이번 스텝 머지 하겠습니다 👍
다음 스텝도 화이팅입니다! 💪

2022-11-07 09:53 UTC, merged