Week3 [Step2] 송중
yagom-academy/swift-starter-week3 pull request #162
Opened 2022-11-07 09:15 UTC by kimseongj

@llingo 
안녕하세요 링고! step2를 해왔답니다. 

## 조언이 필요한 점
### 요구사항에 나온 메서드 파라미터 이외에, 추가적인 파라미터를 삽입해도 될까요?
요구사항에는 missKim이 주문을 하는 메서드인 *order(_ coffee: Coffee)*가 있는데, 이 부분에 추가적으로 *coffeeShop: CoffeeShop*이라는 파라미터를 넣었습니다. 
결과적으로는 원하는 기능을 작동시켰지만.. 어떻게 더 요구사항과 가깝게 코딩을 할 수 있었을까요..?

2022-11-07 15:19 UTC, llingo requested changes
안녕하세요 @kimseongj 님!
벌써 3주차의 마지막 스탭이군요 🎉

이번 Step의 중점사항은 다음과 같습니다.
- [x] 인스턴스 사이의 소통을 통해 특정한 결과 (`pickUpTable`) 가 발생한다는 것 이해하기
- [ ] `Property Observer` 를 이해하고, 활용하기

pickUpTable에 커피가 올려지면 출력되는 문구를 직접 order 메서드에서 해주셨는데요! **Property Observer**를 활용하셔서 pickUpTable가 변경되면 관측하고 있다가 문구를 출력해주는 방식으로 변경해보시는 것을 추천합니다! 😄

---

**Q1. 요구사항에 나온 메서드 파라미터 이외에, 추가적인 파라미터를 삽입해도 될까요?**
A. 네! 인스턴스 사이의 소통을 통해 특정한 결과 (`pickUpTable`) 가 발생한다는 것 이해 하는 목표 내에서 구현은 자유롭습니다 :)

2022-11-07 15:19 UTC, seu0313 commented on CodeStarterCamp_Week3/Step1.swift
> +//}
코드를 작성하면서 기능을 추가할 때 기존 코드를 주석 처리하는 것보다 새로운 Branch를 생성하고 기존 코드의 기능을 개선하는 방식으로 하는 것이 좋아보입니다! 😄

2022-11-07 15:19 UTC, llingo commented on CodeStarterCamp_Week3/Step2.swift
> +    var pickUpTable = [Coffee]()
pickUpTable에 커피가 올려지면 문구가 출력될 수 있도록
PropertyObserver를 통해 값의 변화를 감지하는 방식으로 수정해볼까요?

2022-11-07 15:19 UTC, llingo commented on CodeStarterCamp_Week3/Step2.swift
> +            print("\(name)님이 주문하신 \(coffee)(이/가) 준비되었습니다. 픽업대에서 가져가주세요")
pickUpTable에 커피가 올려지면 해당 문구가 출력될 수 있도록 Property Observer를 사용해서 수정해볼까요?
해당 문구는 주문한 커피가 준비되었다는 것이므로 Person이 알려줘야하는 것이 아닌 CoffeeShop이 알려줘야하는 것이 좋을 것 같아요 :)

2022-11-08 01:34 UTC, kimseongj commented on CodeStarterCamp_Week3/Step1.swift
> +//}
헉! 무슨 말인지 잘 이해가 안가요 ㅠㅠ 새로운 branch가 깃에서의 branch를 말하는 걸까요??

2022-11-08 01:51 UTC, kimseongj commented on CodeStarterCamp_Week3/Step2.swift
> +            print("\(name)님이 주문하신 \(coffee)(이/가) 준비되었습니다. 픽업대에서 가져가주세요")
네넵! 그게 더 자연스러운거 같아요! 근데 한가지 문제가 생겼습니다..
struct CoffeeShop 내에서 pickUpTable를 선언한 것이 아닌 make 메서드 내에서 pickUpTable을 선언해야 올바르게 작동합니다. 
그 이유는 make 메서드에서 받아오는 파라미터값들이 프린트에 필요한 요소값들이기 때문입니다. 
이렇게 된다면 함수 호출이 끝나고 pickUpTable이 사라지는거 아닌가요?!

2022-11-08 01:51 UTC, kimseongj commented on CodeStarterCamp_Week3/Step2.swift
> +            print("\(name)님이 주문하신 \(coffee)(이/가) 준비되었습니다. 픽업대에서 가져가주세요")
이 문제를 풀려면 struct 대신 class를 사용해서 상속을 받아오는게 좋을까요?

2022-11-08 05:02 UTC, llingo commented on CodeStarterCamp_Week3/Step1.swift
> +//}
네! 깃에서의 Branch를 의미합니다
예를 들어, 현재는 `kimsj` 브랜치에서 모든 작업을 하고 계시지만 아래와 같이 STEP별 브랜치를 나눠서 진행할 수 있을 것 같습니다!
![스크린샷 2022-11-08 오후 2 00 09](https://user-images.githubusercontent.com/94151993/200479072-6f2646e2-d28c-4dd4-8f4b-009e32951ff1.png)

2022-11-08 05:12 UTC, llingo commented on CodeStarterCamp_Week3/Step2.swift
> +            print("\(name)님이 주문하신 \(coffee)(이/가) 준비되었습니다. 픽업대에서 가져가주세요")
**Q1. pickUpTable를 선언한 것이 아닌 make 메서드 내에서 pickUpTable을 선언해야 올바르게 작동합니다.**
A. pickUpTable은 make 메서드 내부가 아닌 프로퍼티로 구현하는 것이 좋을 것 같아요
어떻게 해야 pickUpTable의 didSet이 불릴때 make 메서드에서 받아오는 파라미터값들을 사용할 수 있을까요? 🤔

**Q2. struct 대신 class를 사용해서 상속을 받아오는게 좋을까요?**
상속은 사용하지 않아도 가능할 것 같아요!

2022-11-08 09:47 UTC, closed without merging