Week3 [STEP2] 졔
yagom-academy/swift-starter-week3 pull request #164
Opened 2022-11-08 15:01 UTC by yijiye

@wongbingg 
이번 미션도 힘겹게 왔습니다 😢 

## 고민했던 부분

#### 1. 두개의 서로 다른 class를 연결시키는 것

7일날 같이 회의실에서 만나서 해결했던 부분을 정리해봤습니다.

✏️ 메서드에서 다른 메서드를 불러올때 class 이름을 넣어주고 그 아래로 클래스의 프로퍼티의 값을 할당해 주는 방법으로 해결

```swift
func order(_ coffee: Coffee, at coffeeshop: Coffeeshop) {
        coffeeshop.customer = name
        coffeeshop.pickUpTable.append(coffee)
```
coffeeshop: Coffeeshop 클래스를 넣어준 것 처럼요
* 프로퍼티를 불러올땐 '.프로퍼티이름' => ex) coffeeshop.customer
* 값을 할당해 줄땐 '=' => ex) coffeeshop.customer = name

✏️ 코드를 한눈에 보기 쉽게 하기 위해 **전달인자레이블** 의 활용

**missKim.order(.americano, at: yagomBucks)**

missKim 이란 Person 클래스를 호출할때에 전달인자레이블가 오게되니 문장처럼 쉽게 파악 가능 👍 

#### 2. 프로퍼티 옵저버(감시자)

커피를 주문했을 때 커피의 배열을 가진 pickUpTable에 넣어주었고 이때 원하는 내용이 print 되도록 입력해주었습니다.
처음에 customer 라고 작성했을 때 class Coffeeshop 에는 customer 프로퍼티가 없었고 여기서 좀 많이 헷갈렸던 것 같아요.
그래서 웡빙이 준 힌트를 듣고 아래와 같이 해결하였습니다.

---

* customer 의 프로퍼티는 가지지만, 초기값이 꼭 필요 없는 경우에 사용하는 옵셔널 이용

```swift
class Coffeeshop {

    var customer: String?
    var pickUpTable = [Coffee]() {
        
        didSet {
            if let name = customer {
                print("\(name)님이 주문하신 \(coffee.rawValue)(이/가) 준비되었습니다. 픽업대에서 가져가주세요.")
            }
        }
    }
```
옵셔널 바인딩으로 안전하게 추출해주기 위해 didSet 구문 안에 옵셔널 바인딩으로 해제해주었습니다.
이제 옵셔널 바인딩은 지난번보다 조금은 더 이해한거 같아요!

## 도움이 필요한 부분

#### 1. class Coffeeshop 의 메서드?

두개의 클래스를 연결시켜 주면서 Person 클래스에서 주로 coffeeshop의 프로퍼티들을 불러와서 문제해결을 하였는데요
코드를 보면서 든 생각은 
' 그럼 Coffeeshop의 메서드가 굳이 왜 있지? ' 하는 생각이였습니다.

```swift
 init(barista: Person, coffee: Coffee) {
        self.barista = barista
        self.coffee = coffee
    }
    
    func make(_ coffee: Coffee, from name: String) {
        
    }
```
제 코드를 보시면 이런식으로 make 메서드가 있는데 이 메서드는 사실 없어도 되는 부분인 거 같았어요
(주석으로 바꿔서 실행해도 코드가 실행이 되더라구요!)

문제에 나와 있는 내용은 
make(_ coffee: Coffee, from name: String) 가 호출되면 커피를 추출합니다.
추출된 커피는 pickUpTable 에 올려집니다.

이렇게 나와 있는데, 그렇다면 제가 만든 코드에서 pickUpTable 부분을 make 메서드에다가 할당을 했었어야 했을까요?

#### 2. 매출액과 가지고 있는 돈

계산식을 넣어서 커피를 구매하면 가지고있는 돈(moneyOnHand) 에서 빠지고, 매출액(turnover) 에서 더해지도록 했습니다.
그런데 바뀌는 부분은 어디서 표시를 해야하는지 잘 모르겠어서 print 구문에 넣었는데 이렇게 표현하면 되는게 맞나요?

2022-11-08 23:32 UTC, wongbingg commented
안녕하세요 졔 님 ☺️ step2 고생하셨습니다

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] 요구된 문구가 출력되는지
- [ ] 객체간 소통이 잘 이루어졌는지 
- [x] pickUpTable을 잘 활용했는지


### ✅ 도움이 필요한 부분

#### 1. class Coffeeshop 의 메서드?

기능분리가 되어있지 않은 것 같아요. 이 부분은 코멘트를 남겨두겠습니다.

#### 2. 매출액과 가지고 있는 돈

실제로 moneyOnHand 값이 변화하지 않고 있어요! 이 부분도 코멘트로 남겨두겠습니다.

2022-11-08 23:51 UTC, wongbingg requested changes

2022-11-08 23:51 UTC, wongbingg commented on step2/main.swift
> +    }
Person 타입에 order 메서드에는 실제 세상에서 내가 커피를 주문할 때라고 생각해보시면 쉬울 것 같아요.

현재 order 메서드 안에서 수행되고 있어서 어색한 부분이 두군데 있습니다. 어느 부분일까요 ? 이 부분들은 커피숍에서 해야할 것 같은 기능들 입니다.

2022-11-08 23:51 UTC, wongbingg commented on step2/main.swift
> +missKim.order(.americano, at: yagomBucks)
`missKim` 이 돈 5000 원을 가지고, 아메카노를 여러번 시키면 여러번 주문이 다 가능한 상태입니다. 
즉, 미스김의 돈이 차감되지 않고 있어요 어떻게 해결해봐야 할까요?

2022-11-08 23:51 UTC, wongbingg commented on step2/main.swift
> +    }
커피숍에서 커피를 만들고나서 커피숍의 프로퍼티들에 어떠한 영향을 미치게 될지 상상 해봅시다.
`turnover` 는 어떻게 되고, `pickUpTable`은 어떤 변화가 있을까요 ?

2022-11-08 23:51 UTC, wongbingg commented on step2/main.swift
> +missKim.order(.americano, at: yagomBucks)
여러번의 주문 후, yagomBucks 의 매출인 `turnover` 를 출력해봐도 0원이 나오네요. 커피값을 어떻게 적용해주어야 할까요?

2022-11-08 23:51 UTC, wongbingg commented on step2/main.swift
> +missKim.order(.americano, at: yagomBucks)
잔액이 부족한데도 커피가 pickUpTable에 올라가고 있습니다. 코드실행 순서를 어떻게 해야할까요 ?

2022-11-09 10:29 UTC, yijiye commented on step2/main.swift
> +    }
coffeeshop.customer = name
coffeeshop.pickUpTable.append(coffee)
이 두가지를 coffeeshop의 메서드로 이동시켰습니다!

2022-11-09 10:32 UTC, yijiye commented on step2/main.swift
> +    }
turnover 프로퍼티는 커피가격만큼 증가해야 하는데 이부분은 Person 타입의 메서드에서 계산되도록 넣었습니다.

2022-11-09 12:28 UTC, wongbingg commented on step2/main.swift
> +            }
잘 수정 되었네요 👍 이제 커피의 가격만큼 Person 수중의 돈에서 차감되네요
또한 CoffeeShop의 turnover 가 커피값만큼 올라갔는데요, 이 turnover 프로퍼티는 CoffeeShop 내의 프로퍼티니까 커피숍 내에서 처리 해주어도 좋을 것 같아요 🧐 참고만 해주세요 !

2022-11-09 12:30 UTC, wongbingg commented on step2/main.swift
> +            }
```suggestion
            if let name = customer, let orderedCoffee = orderedCoffee {
                print("\(name)님이 주문하신 \(orderedCoffee.rawValue)(이/가) 준비되었습니다. 픽업대에서 가져가주세요.")
            }
```

if let 바인딩이 연달아 있다면, 이런식으로도 작성을 합니다 ☺️

2022-11-09 12:33 UTC, wongbingg commented
수정사항이 잘 반영 되었네요 👍 이번 프로젝트도 고생 많으셨습니다
마지막 코멘트 남겨두었으니 확인하고 넘어 가셔도 좋을 것 같아요 !
이번 스텝 머지 하겠습니다 👏 다음 프로젝트도 화이팅 입니다 ! 💪

2022-11-09 12:33 UTC, merged