Week3 [STEP2] JM.Y
yagom-academy/swift-starter-week3 pull request #17
Opened 2021-12-27 16:59 UTC by JungmoYu

@Neph3779 안녕하세요 네프님!

Step2 진행하여 PR 발행합니다.

변경한 내용
1. `enum의 associated value`대신 `enum내에 computed property`를 사용해 보았습니다.
2. Barista라는 클래스를 만들고 Person을 상속받으면 어떨까 하여 Person을 'struct -> class'로 변경하였습니다.

궁금한 내용
구현 시 고민했던 몇가지 점들을 댓글로 남기겠습니다.

오늘도 감사합니다!

2021-12-27 17:15 UTC, JungmoYu reviewed
@Neph3779 님!

코멘트들로 질문을 좀 남겨보았습니다.
뭔가 객체를 이해함이 쉽지만은 않은 것 같습니다.

그리고 제가 짠 코드지만 뭔가 간결하지 못한 이 느낌이 참 찜찜한데, 혹시 네프님이라면 제가 작성한 코드 중에 어떤 부분을 좀 더 간결하게 바꿔보려 하실지 여쭤볼 수 있을까요?

감사합니다!

2021-12-27 17:15 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +    }
이 부분은 열거형의 연관값 보다는 하나의 변수로 지정하여, 어떤 메뉴가 들어오느냐에 따라 다른 값을 가지도록 만들어보았습니다.

열거형에서 연산프로퍼티가 이럴 때 상당히 유용할 것 이라는 생각이 들었습니다.

2021-12-27 17:15 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +}
Person 클래스 내에서 CoffeeShop 클래스의 메써드를 호출하는 방식을 사용했습니다.
여기서 isOrderCompleted 상수를 선언하고 사용한 이유는, 밑에 메써드에서 질문드리겠습니다.

2021-12-27 17:15 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +    }
클래스로 바뀌었기 때문에 생성자를 만들었습니다.

2021-12-27 17:15 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>  }
상속의 개념을 배운김에 `Barista`라는 클래스를 만들고 `Person`클래스를 상속받도록 만들어봤는데.
막상 만들고 나니, makeCoffee내부에서 특별히 어떤 일을 하지는 않고, 호출 되는 즉시 만들어졌다는 의미를 반환하였습니다.

2021-12-27 17:15 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>      }
연관값을 가지는 열거형이 아닌, 열거형의 각 case와 연산프로퍼티만을 갖게 만들었기 때문에, `Coffee`라는 열거형타입의 array만으로 원하는 생성자를 구현할 수 있었습니다.

2021-12-27 17:15 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +            self.money = isOrderCompleted ? (self.money - coffee.price) : self.money
이 부분의 경우,  혹여나 음료를 주문한 것이 주문취소(재고부족, 바리스타부재등의 이유로) 된다면 잔액을 깎으면 안되기에 이런 구문을 만들어봤고, 또한 if문 안에 또다른 if문이 존재하는것이 싫어서 `3항 연산자`를 사용해봤습니다.

2021-12-27 17:15 UTC, JungmoYu commented on CodeStarterCamp_Week3/main.swift
> +missKim.buyCoffee(at: yagomBucks, coffee: .cappuccino)
생각했던 여러 상황들을 출력해보고싶어서 위와 같이 메인문을 구성했습니다.

1. 돈이 부족해서 커피를 살 수 없는 상황
2. 바리스타가 없어서 커피 주문을 완료할 수 없는 상황
3. 정상적인 주문이 가능한 상황
입니다.

2021-12-28 00:25 UTC, Neph3779 requested changes
안녕하세요 정모님! Step2 진행하시느라 고생 많으셨어요!
조금만 더 고쳐봐도 좋을 것 같아서 수정요청 드릴게요!
그럼 화이팅~!

2021-12-28 00:25 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +            self.money = isOrderCompleted ? (self.money - coffee.price) : self.money
음.. 저라면 guard문을 통해 잔액 부족을 체크한 뒤
삼항연산자 대신 if else문을 통해  작업했을 것 같습니다
그리고  order 메서드의 결과값을 isOrderCompleted를 저장하는 부분이 조금 어색해보여요~

2021-12-28 00:25 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>  }
필요하지 않은 코드가 작성되는 것보다는 빈 블락으로 두는것도 좋아보여요!

2021-12-28 00:25 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>  }
여기서 flag 변수를 작성해야할 이유를 잘 모르겠어요

2021-12-28 00:25 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>  }
성공 여부를 이곳에서 반환할 이유가 있을까요?
DB에 잘 저장되었는지에 대한 여부는 DBMS에서 처리할 문제라 생각합니다!
이번 스텝에서는 저장의 성공 실패 여부를 다루지 않으므로 조금 오버엔지니어링이 아닌가 생각이 됩니당

2021-12-28 00:25 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +    }
```suggestion
    var price: UInt {
          switch self {
          case .americano: return 4500
          case .cafeLatte: return 5500
          case .cappuccino: return 6000
          case .hotChocolate: return 5000
          }
    }
```

swift에서는 get만 존재할때는 get 키워드를 생략하는것을 권장합니다!

2021-12-28 00:25 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>      }
커피샵 instance를 만드는 시점에 꼭 menu가 필요할까요?
이 부분은 개인 판단이겠지만 꼭 class의 custom init이 필요한 것은 아닌 것을 알아두시면 좋을 것 같아요!

2021-12-28 00:25 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>      var menu: [Coffee]
(추가과제) 이 변수들은 어떻게 해야 외부에서 마구 변경되지 않도록 보호할 수 있을까요?

2021-12-28 00:25 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +        }
didSet구문을 잘 사용해주셨네요!

2021-12-28 15:35 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>      }
제가 생성자를 만든 이유는, 카페마다 메뉴가 각기 다를 수 있을 것으로 생각했기에 따로 기본값으로 초기화 하지 않고, custom intializer를 만들었습니다.
제 의도가 나쁘지는 않은 의도였을까요?

말씀해주신 대로 class에서 꼭 custom initializer가 필요한 것은 아니라는 사실은 명심하겠습니다!

2021-12-28 15:36 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>      var menu: [Coffee]
점근제어로서 보호할 수 있을 같습니다.
다른 타입에서도 접근할수 없도록 `private`키워드를 사용하면 좋을 것 같습니다!

반영하도록 하겠습니다

2021-12-28 15:37 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +        }
사실 위에서 `isSucceed` 라는 변수를 선언한 이유가 이 `didSet`을 사용해보고싶었기 때문입니다!!
이와같이 프로퍼티 감시자를 만들어두엇다면, 뭔가 변경할 값이 필요한데, 그 대상으로 isSucceed를 만들었습니다.

저도 사실 이 부분이 가장 마음에 들지 않는데, 한번 수정해보도록 하겠습니다!

2021-12-28 16:19 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>  }
제가 여기서 반환한 이유는, 만약 `barista`가 `nil`이여서 커피를 만들지 못하는 경우에, `Person`클래스에서 `money`에 변화를 주지 않기 위함이었습니다!

제가 지금 코드를 좀 바꿔보려고 이것 저것 해보고있는데...
`order`라는 함수에서 return으로 음료 제조 성공 여부를 받지 않고서는 어떻게 `Person`클래스의 `buyCoffee` 메서드에서 이 사실을 알고 `money`프로퍼티를 처리할지 감이 오지 않습니다.

제 생각에는 커피숍에서 Customer의 money프로퍼티를 건드리는것이 어색할 것 같다는 생각이 들어서요!

혹시 제가 간과하고있는 개념이 있다던가, 생각해 볼 만한 것이 있을까요?

2021-12-28 16:30 UTC, JungmoYu commented
@Neph3779  안녕하세요 네프님!

피드백 내용 반영하여 반영하여 CR처리 하였습니다.
하지만, 피드백 내용을 100% 반영하지 못하고, 제가 생각한대로 구현하는데 혹시 다른방법은 없을까 하여 피드백 내용에 코멘트 남겨보았습니다!

감사합니다.

2021-12-28 16:33 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>  }
전 오히려 order전에 바리스타의 유무를 확인할 것 같아요
order이 들어갔으면 반드시 성공하도록 (현재는 바리스타만 있으면 반드시 주문에 성공하니) 만들었을 것 같습니다.

2021-12-28 16:33 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>      }
그렇다면 default를 빈 배열로 주어서 원하는 경우에만 초기화를 할 수 있도록 하는건 어떨까요?

2021-12-28 16:45 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>  }
그냥 바로 true를 리턴하는 함수로 만들었습니다.
사실 이 부분도 반환을 void로 처리할 수도 있지만, 이렇게 구현하니 `CoffeShop`클래스의 `order`메서드에서 `isSucceed = true`라는 값을 직접적으로 할당해줘야하는것 같아서.. 이부분보다는 이렇게 반환하는 것이 낫지 않나라고 생각했습니다.

이 모든것이 `Person클래스에서 money프로퍼티`를 변경하고자함에서 비롯된것인데... 그 부분을 수정하는게 좋을지, 한다면 어떻게 수정하면 좋을지 잘 모르겠습니다 ㅜㅜ

2021-12-28 16:45 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>  }
제가 guard 문을 사용해본 적이 없어서 한 번 사용해 봤습니다.
제 생각에 guard를 사용하면, return으로 바로 함수를 탈출할 수 있기에, 쓸데 없이 실행되는 부분이 줄어들 것으로 생각되어 어쩌면 더 좋을 수도 있겠구나....라는 생각을 해 봤는데 맞을까요?

추가적으로 여기서 `resultOfOrder`같은 변수에 `order`메서드 값을 반환받아서 할당하는것이 어색하다고 피드백 주셨었는데, 제가 여기서 이용한 이유는, 다른 댓글에서도 달았지만, **Person 클래스 내부에서만 money를 변경하고싶은 마음** 때문이었는데...

혹시 이렇게 하지 않는다면 어떤식으로 처리할 수 있을지에 대한 방법을 문의드립니다 ㅜㅡㅜ

2021-12-28 16:45 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +                print("\(nameOfCustomer) 님의 커피가 준비되었습니다. 픽업대에서 가져가주세요.")
`didSet`안에서 처리해도 될 사항들을 `didSet`안으로 옮겨주었습니다.
(커피가 만들어져야만, 매출도 오를테니..)

다만 `isSucceed`라는 변수를 없앤다면 `didSet`이 아닌 직접 함수 내부에서 사용해줘야할 것 같습니다!

2021-12-28 16:45 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>          return isSucceed
이 부분에서 또한, `if let -> guard let`구문을 활용해보았습니다.

그렇기 때문에 `barista`라는 새로 할당한 상수를 `guard`구문 밖에서도 사용할 수 있어서 좋은 것 같습니다.

네프님은 `if-let과 guard-let` 구문의 사용을 구분짓는 어떤 기준을 갖고 계신가요?
아울러 위에서 사용했던 `if문과 guard문(옵셔널 바인딩이 아닌)` 의 사용 기준도 갖고 계실지요!?

2021-12-28 16:45 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +        case .hotChocolate: return 5000
말씀 해 주신 피드백 반영하였습니다.
이런 코드컨벤션을 익히는것이 중요하다고 생각됩니다.
감사합니다!

2021-12-29 13:28 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>      }
아 맞습니다 그게 훨씬 좋을 것 같습니다!
제가 지정을 해주기보다는요!

감사합니다!

2021-12-30 08:42 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>          return isSucceed
if let 은 한정된 블록에서 사용할 수 있는 옵셔널 해제 방법인게 특징이고 return 등의 작업이 필요하지 않으므로
옵셔널은 해제 해주어야 하는데 return을 하기는 싫을 때 주로 사용합니다.
이 부분은 사실 compactMap 등의 다른 메서드로 대체할 수도 있어서 규칙이 정해져있다기 보단 유동적으로 하는 것 같아요

2021-12-30 08:51 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>  }
resultOfOrder
주문의 결과
이 변수가 왜 Bool값인지 잘 이해가 가지 않아요..
주문의 결과가 참/거짓 으로 나올 수 있는 것인가요?
변수 네이밍이 조금 아쉽습니다

2021-12-30 08:55 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>  }
guard문 내에서만 꼭 return을 쓸 수 있는 것은 아닙니다
guard문의 빠른 탈출이란 return을 만나서 탈출하는 것이 아닌 
guard문 진입시에 조건들을 비교할때 처음으로 만나는 변수가 nil이라면 뒷부분은 보지 않고 else문으로 넘어가기 때문이에요!
return을 통해 필요없는 밑줄의 코드가 실행되지 않도록 한 것은 좋지만 조금? 포인트가 다른 이야기인 것 같아서 말씀드려요!

2021-12-31 14:51 UTC, JungmoYu reviewed
@Neph3779  안녕하세요!

오늘 피드백 받은 내용을 기반으로  do-catch 등 에러처리를 공부해볼 겸 Step2에 반영해보았습니다.
감사합니다!

2021-12-31 14:51 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>  }
오늘 피드백 받은 내용기반으로 `do-catch / throws(throw)`를 통한 에러처리를 활용해봤습니다.

여기서 궁금한것이 `catch`문은 마치 `switch`처럼 `default`같은 부분이 하나 존재해야 하는 것 같더라구요.
제가 이해한 것이 맞을까요? 위 부분에서 마지막 `catch`를 지우면 에러가 발생하더라구요!

2021-12-31 14:51 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +    }
`makeCoffee` 메서드를 반환값 없는 형태로 바꿨습니다.

2021-12-31 14:51 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +    private var menu: [Coffee] = []
default로 아무것도 메뉴가 없는 상태로 초기화시키는것으로 반영하였습니다.

2021-12-31 14:51 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>          }
`isBaristaExist`메서드를 추가해보았습니다.

이 경우 Boolean으로 처리하여 `order메서드`에서 받아서 에러를 던지기 위함으로 처리해 보았습니다.

2021-12-31 14:51 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>  }
이곳에서 `isBaristaExist` 메서드를 활용하여 먼저 바리스타가 있는지/없는지를 체크하여 에러를 던지기로 했고(그를 위해 메서드 선언부에 throws 적용), 메서드 반환값을 Void처리하였습니다.

다만,  `if let`구문을 활용한 부분에 있어서, 사실상 위에서 guard처리 하였기 때문에(바리스타 유무) `barista!.makeCoffee(coffee: coffee)` 를 해도 된다고 생각하는데(이 부분은 맞는 것인지 피드백 부탁드려요 ㅜㅜ) 아직 '!'는 사용하지 말자고 야곰께서 하셨기에.. 그냥 if-let을 한 번 더 사용하였습니다!

2021-12-31 14:51 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +}
Error를 정의하기위한 Enum입니다.

2022-01-01 01:43 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>  }
네 맞습니다! catch CoffeeShopError.noBaristarError는
정말 저 error를 catch 한 경우에만 실행되는 block이에요
error는 다양하게 올 수 있으니 반드시 디폴트 캐치도 필요하답니다

2022-01-01 01:43 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +    }
훨씬 이해하기 좋아진 것 같아요!

2022-01-01 01:44 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>          }
좋습니다! 근데 이런 부분은 메서드가 아닌 연산 프로퍼티로도 해결해볼 수 있지 않을까요?

2022-01-01 01:45 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>  }
음.. 로직이 완벽하다 하더라도 라인이 떨어져있는 (순서에 영향을 받는) 코드에서는 강제 언래핑을 지양하는게 좋아요
전 그냥 이대로 두는게 더 낫다고 봅니다!
코드 depth가 너무 깊어져서 가독성이 떨어지는 상황이 아니니 괜찮다 생각해요!

2022-01-01 01:46 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +}
Error protocol에는 또 다른게 뭐가 있을까요? 한번 공부해보시는것도 나쁘지 않을 것 같아요!

2022-01-01 01:51 UTC, Neph3779 approved these changes
안녕하세요 정모님!
수정사항을 너무 잘 반영해주셨네요!
이번 스텝에서 여러 값진 경험들을 해보신 것 같아요 ㅎㅎ
여기서 머지해도 될 것 같습니다! 그럼 다음 스텝도 화이팅!!

2022-01-01 01:51 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +        } catch CoffeeShopError.noBaristaError { return }
바리스타가 없을때 이용자에게 이 사실을 알려주면 좋지 않을까요?

2022-01-01 01:51 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +    private var menu: [Coffee] = []
좋습니다! init에 default parameter 값을 지정해주는 방법도 있었겠네요!

2022-01-01 01:51 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>      }
```suggestion
    init(menu: [Coffee] = [], sales: Int = 0) {
        self.menu = menu
        self.sales = sales
    }
```

이런식으로 수정도 가능했을 것 같아요!

2022-01-01 01:51 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
>      }
```suggestion
    func isBaristaExist(barista: Barista?) -> Bool {
        guard barista != nil {
            return false
        }
        return true
    }
```

swift lint에서 권장하는 형식입니다!

2022-01-01 01:51 UTC, merged

2022-01-01 03:54 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>  }
nil이라면 바로  else로 넘어가는 것 또한 ealry exit이라는것 참고하겠습니다!

2022-01-01 03:59 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>  }
그러면, 어떤식으로든 제가 정의해준 에러 말고 default error가 존재한다는것인데, 항상 마지막에 catch 문을 하나 더 만들어줘야하는 것일까요?

```
enum myError: Error {
    case typeA
    case typeB
    case typeC
}

enum myAnotherError: Error {
    case type1
    case type2
    case type3
}

```
이렇게 2개의 열거형집단에 대해 3개씩의 에러를 정의했다 할 때
catch를 사용하는 부분에서는 myError, myAnotherError 두 타입의 에러가 모두 올 수 있고, 뿐더러 이 외의 어떠한 에러도 올 수 있게 되는것 일 테니, 제가 실제로 사용할 때는(설계할 때 myError만 오는것으로 예측했다고 하더라도)
```
catch {myError.TypeA}
catch {myError.TypeB}
catch {myError.TypeC}
catch {//예상치 못한 에러 또는 myAnotherError 도 올 수 있으니까!}
```

이렇게 만들어 주는 것이 맞는것이겠죠?

2022-01-01 04:14 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>          }
네 이 함수 자체를 없애고 그냥 새로운 변수하나를 만들고, `barista변수(Barista? 타입)`을 만들고, `getter`를 사용하여 아래와 같이 만들 수도 있을 것 같습니다.
그런데, 당연히 메서드를 만드는 것 보단 연산프로퍼티를 사용하는것이 좋은걸까요? 아니면 그냥 취향일까요!?
그리고, 연산프로퍼티의 경우 `class의 property`에서 (내부 메서드의 변수가 아닌) 사용하는경우가 많다고 하셨기에, 아래 코드처럼 만들어보았습니다!

```Swift
class CoffeeShop {
    ...
    var isBaristaExist: Bool{
        get {
            guard let _ = self.barista else {
                return false
            }
            return true
        }
    }
    ...
    func order(coffee: Coffee, nameOfCustomer: String) throws {
        guard isBaristaExist else {
            print("현재 카페에 바리스타가 없어서 커피를 만들 수 없습니다!")
            throw CoffeeShopError.noBaristaError
        }
    ....
}
```

2022-01-01 04:16 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +        } catch CoffeeShopError.noBaristaError { return }
엇 이 부분은, `CoffeeShop` Class내부에서 고객에게 바리스타가 없어서 커피를 만들 수 없다고 출력하는 부분으로 생각하여 설계한 것 입니다! 

저도 네프님 말씀처럼 바리스타가 없다면 이용자에게 알려줘야한다고 생각하고, 이 부분을 Person 클래스가 아닌, 커피숍이 해 줘야 의미에 맞다고 생각했습니다!

2022-01-01 04:17 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>      }
생성자 자체에서 초깃값을 주는 방븝은 생각해 보지 못한 것 같습니다.
감사합니다!

2022-01-01 04:19 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
>      }
앗 이 코멘트를 늦게 확인했네요!
감사합니다! 

코멘트 내용대로 아까 연산프로퍼티로 바꿨던 부분을 아래와 같이 수정해도 되겠네요!

```Swift
var isBaristaExist: Bool{
        get {
            guard barista != nil else {
                return false
            }
            return true
        }
    }
```

2022-01-01 04:20 UTC, JungmoYu commented
@Neph3779  감사합니다!
피드백들 잘 확인했고 앞으로 코딩하는데 참고하도록 하겠습니다!