Week3 [STEP2] Owen
yagom-academy/swift-starter-week3 pull request #174
Opened 2022-11-16 12:36 UTC by Duckduck1596

@llingo 

## 3주차 두번째 스텝입니다

# 고민한 점

한 번에 여러잔 시키면 어떻게 더할 것인가 
-> for-in문으로 menu dictionary의 숫자를  옵셔널 바인딩으로 풀어 반복했습니다.

2022-11-16 17:38 UTC, llingo requested changes
안녕하세요 @Duckduck1596 님!
벌써 3주차의 마지막 스탭이군요 🎉

이번 Step의 중점사항은 다음과 같습니다.
- [x] 인스턴스 사이의 소통을 통해 특정한 결과 (`pickUpTable`) 가 발생한다는 것 이해하기
- [ ] `Property Observer` 를 이해하고, 활용하기

pickUpTable에 커피가 올려지면 출력되는 문구를 직접 make 메서드에서 해주셨는데요! **Property Observer**를 활용하셔서 pickUpTable가 변경되면 관측하고 있다가 문구를 출력해주는 방식으로 변경해볼까요?

남겨드린 코멘트에 대해 확인하시고 디스코드로 DM 주시면 빠르게 Merge 해드리겠습니다 :)

2022-11-16 17:38 UTC, llingo commented on CodeStarterCamp_Week3/main.swift
> +        print("\(name) 님이 주문하신 \(pickUpTable.joined(separator: ", "))(이/가) 준비되었습니다, 픽업대에서 가져가주세요")
pickUpTable에 커피가 준비되면 해당 문구가 출력되도록 `Property Observer`를 활용할 수 있을 것 같습니다.

2022-11-16 17:38 UTC, llingo commented on CodeStarterCamp_Week3/main.swift
> +print("\(missKim.name)님 작액은 \(missKim.money)원 입니다")
오타가 있습니다!

2022-11-16 17:38 UTC, llingo commented on CodeStarterCamp_Week3/main.swift
> +    mutating func order(coffees: [Coffee]) {
```swift
mutating func orderCoffees(_ coffees: [Coffee]) { ... }
```
는 어떠신가요?

2022-11-16 17:38 UTC, llingo commented on CodeStarterCamp_Week3/main.swift
> +                totalPrice += price
if let 을 통한 옵셔널 바인딩을 하셨군요 좋습니다 👍

2022-11-16 17:38 UTC, llingo commented on CodeStarterCamp_Week3/main.swift
> +        for coffees in coffee {
for-in 은 여러 개를 담는 개념에서 하나씩 순회하는 것이지만 현재 네이밍은 반대의 의미로 작성된 것 같아요

2022-11-16 17:38 UTC, llingo commented on CodeStarterCamp_Week3/main.swift
> +    mutating func make(coffee: [Coffee], from name: String){
중괄호 앞에 한칸을 띄워주는 게 좋을 것 같아요.
```swift
mutating func make(coffee: [Coffee], from name: String) {
                                                       ⬆️
```

추가적으로 make 라는 메서드 명보다는 좀더 정보를 담았으면 좋겠습니다.
```swift
mutating func makeCoffees(_ coffees: [Coffee], forCustomerName name: String) { ... }
```

2022-11-16 17:38 UTC, llingo commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: [String] = []
Property Observer를 활용해볼까요!

2022-11-17 13:00 UTC, Duckduck1596 commented
@llingo  수정 완료 했습니당!!😀

2022-11-18 05:40 UTC, llingo approved these changes
@Duckduck1596 님!

스타터 캠프 5주동안 수고하셨습니다!! 🎉🎉🎉

2022-11-18 05:40 UTC, merged