Week3 [Step1] Zion
yagom-academy/swift-starter-week3 pull request #177
Opened 2023-03-06 06:56 UTC by LeeZion94

@jsa0224 

Step 1: 타입과 인스턴스의 관계

## 고민했던 점
### Coffee를 CoffeeShop에서 주문하는 방식
- Step1에 주어진 조건을 우선적으로 만족하도록 구현. 구체적은 설계는 명세되어 있지 않으므로 구현하지 않음.

2023-03-06 12:18 UTC, jsa0224 requested changes
안녕하세요, 시온님(@LeeZion94)~😊

벌써 3주차네요! 시간이 엄청 빠르게 지나가는 느낌이네요!
이번 코드도 너무 잘 구현해주셨네요! 
피드백은 아래 코멘트로 남겨두었습니다~

2023-03-06 12:18 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    }
```suggestion
    func purchaseCoffee() {}
```
- 메서드에 기능이 아직 없다면 이렇게 개행 없이 쓰는 것도 좋을 거 같습니다!

2023-03-06 12:18 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +//    }
주석은 지워주세요!

2023-03-06 12:18 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    var salesMoney: Int
판매금액이라는 뜻으로 보여, 카페의 매출에 대한 의미로는 해당 네이밍이 모호해보입니다!

2023-03-07 01:43 UTC, LeeZion94 commented on CodeStarterCamp_Week3/main.swift
> +    }
넵 ! 수정해두겠습니다 솜.

2023-03-07 01:44 UTC, LeeZion94 commented on CodeStarterCamp_Week3/main.swift
> +//    }
넵!

2023-03-07 01:54 UTC, LeeZion94 commented on CodeStarterCamp_Week3/main.swift
> +    var salesMoney: Int
음... 고민해보고 좀더 명확한 네이밍으로 적용하겠습니다!

2023-03-07 02:20 UTC, jsa0224 commented
수고하셨습니다, 시온님(@LeeZion94)!
다음 스탭 진행하시면 됩니다👍 화이팅이에요!!

2023-03-07 02:20 UTC, merged