Week3 [STEP1] gaemee
yagom-academy/swift-starter-week3 pull request #193
Opened 2023-03-09 08:31 UTC by increw

@jsa0224 
솜, 3주차 step1 입니다. 이번주에 할 일이 많아서 지금 올립니다...

### 고민했던 점
- 클래스와 구조체를 언제 사용할지에 대해서는 조금은 알지만 막상 나중에 어려운 것이 나온다면 많이 고민할거 같습니다.
- 클래스를 사용하려던 중 초기화를 위해 코드를 호출 중 필요하지 않은 것까지 해야해서 굳이 할 필요가 없는 부분도 있기에 구조체를 사용하였습니다.
- 이번 Step1을 하면서 내용을 해석하는 데에 시간이 좀 걸린거 같습니다.

### 해결하지 못한 점
- 딱히 없었다고는 생각하나 솜이 보시면서 문제가 있다면 코밋으로 알려주시면 정말 감사하겠습니다.

### 조언을 받고 싶은 점
- 항상 고민했던 점이 조언을 받고 싶은 점이라고 생각합니다. 클래스와 구조체를 이번주에 오면서 배우게 되면서 언제 사용하는지에 대해 살짝만 알고 따로 검색을 하였는데 정확히 언제에 사용해야 할지 확신이 서지 않습니다....

2023-03-10 02:57 UTC, jsa0224 commented
안녕하세요, 개미(@increw)님~🐜
3주차 프로젝트 PR이 안 올라오셔서 어려운 부분이 많으신가? 걱정이 되었는데, 바쁘셨군요!!
그럼에도 꾸준히 프로젝트 진행하시는 모습 멋있습니다👍

---

## 조언을 얻고자 하신 부분

> - 클래스와 구조체를 언제 사용할지에 대해서는 조금은 알지만 막상 나중에 어려운 것이 나온다면 많이 고민할거 같습니다.

> - 클래스를 사용하려던 중 초기화를 위해 코드를 호출 중 필요하지 않은 것까지 해야해서 굳이 할 필요가 없는 부분도 있기에 구조체를 사용하였습니다.

구조체와 클래스를 언제 사용해야할지 혼동이 오시는 군요! 
저도 아직까지 어떤 타입으로 구현해야 하는지 고민하고 있어 공감이 되네요…!

[Structures and Classes](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/classesandstructures#Comparing-Structures-and-Classes)와 [Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes) 문서를 읽어보시면 전보다 개념들이 명확해지실 거라고 생각이 듭니다!
두 번째 문서의 경우, 메모리 관련 이야기도 나오고, 조금 어려운 문서라서 참고용으로만 읽어주셨으면 좋겠습니다!

개미님이 생각하는 구조체와 클래스의 차이점도 궁금하고, 언급하신 `클래스를 사용하려던 중 초기화를 위해 코드를 호출 중 필요하지 않은 것까지 해야해서 굳이 할 필요가 없는 부분`이 무엇인지도 궁금하네요!

> - 이번 Step1을 하면서 내용을 해석하는 데에 시간이 좀 걸린거 같습니다.

그래서 Step 2까지 다 하신 거 같아요…🤣
각 스탭마다 todolist라는 구현해야할 부분이 존재하니, 수정해서 올리시면 다시 리뷰해드리겠습니다!

2023-03-10 03:33 UTC, increw commented
@jsa0224 
말씀해주신 부분은 수장하였습니다.문서 정보 감사드립니다. 제가 알고 있는 차이점은 구조체는 값을 복사하여 전달하며, 클래스는 주소를 전달하는 것으로 알고 있고 클래스는 상속이 가능하다라고 알고 있습니다. 그리고 호출이 필요하지 않다는 부분은 제가 혼동이 와서 헷갈렸던 것 같습니다.

2023-03-11 00:51 UTC, jsa0224 requested changes

2023-03-11 00:51 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> -//
- `Foundation`을 `import`하지 않은 이유가 있으신가요?
- 이 부분은 다시 복구해주세요!

2023-03-11 00:51 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +class Person {
`class`로 구현하신 이유가 있으실까요?

2023-03-11 00:51 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    case americano, capuccino, latte, espresso, mocha
`capuccino`에 오타가 존재하네요!

2023-03-11 00:51 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +struct CoffeeShop {
여기는 `struct`로 구현하신 이유가 있으신가요?

2023-03-11 00:51 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func takeOrder(orderCoffee: Coffee, customer: Person) {
메서드와 매개변수 명에서 `order`라는 네이밍이 겹치네요!

2023-03-11 00:51 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func makeCoffee(cutomerCoffee: Coffee) {
여기도 `coffee`라는 네이밍이 겹칩니다!

2023-03-11 00:51 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(coffeeShopName: "yagombucks", barista: missKim)
인스턴스를 생성해주셨군요👍
그런데 `var`로 설정해주신 이유가 있으신가요?

2023-03-11 02:34 UTC, increw commented on CodeStarterCamp_Week3/main.swift
> +    mutating func takeOrder(orderCoffee: Coffee, customer: Person) {
확인했습니다.

2023-03-11 02:34 UTC, increw commented on CodeStarterCamp_Week3/main.swift
> +    mutating func makeCoffee(cutomerCoffee: Coffee) {
넵, 바꿔보겠습니다.

2023-03-11 02:34 UTC, increw commented on CodeStarterCamp_Week3/main.swift
> -//
아뇨, 어쩌다보니 지워진 것 같습니다.

2023-03-11 02:53 UTC, increw commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(coffeeShopName: "yagombucks", barista: missKim)
이름과 카드의 잔액의 값이 바뀔 수 있으며, 카페의 바리스타가 바뀔 수 있다고 생각하여 변수로 선언해줬습니다.

2023-03-11 02:53 UTC, increw commented on CodeStarterCamp_Week3/main.swift
> +    case americano, capuccino, latte, espresso, mocha
확인헀습니다

2023-03-11 03:01 UTC, increw commented on CodeStarterCamp_Week3/main.swift
> +class Person {
공식문서에 하나라도 해당하면 구조체를 사용하는 것을 권장한다고 하길래 확인해보았더니, 연관된 간단한 값이기에 구조체로 바꾸었고 다른 타입에 상속받거나 상속할 필요가 없기에 구조체로 바꾸었습니다.

2023-03-11 03:12 UTC, increw commented on CodeStarterCamp_Week3/main.swift
> +struct CoffeeShop {
처음에는 클래스로 구현을 하려고 하였으나 CoffeeShop의 인스턴스에 기본 값을 주었습니다. 하지만 yagombuck를 선언하면서 이미 기본 값을 준 매개변수에 또 값을 넣어주어야 해서 구조체를 선정하게 되었습니다.

설명이 잘 된건지 잘 모르겠네요...  알고는 있지만 표현하기 어려웠습니다...

2023-03-11 03:15 UTC, increw commented
@jsa0224 
솜, 수정하였습니다. 또 문제가 있다면 답변 주시면 감사하겠습니다.

2023-03-13 02:37 UTC, jsa0224 requested changes

2023-03-13 02:37 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func takeOrder(likeCoffee: Coffee, customer: inout Person) {
프로젝트 요구사항을 다시 읽어보시고, 메서드명을 지어볼까요!

2023-03-13 02:37 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func makeCoffee(cutomerOrder: Coffee) {
이 부분도 프로젝트 요구사항을 다시 읽어보시고, 메서드명을 지어보죠!

2023-03-13 02:37 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(coffeeShopName: "yagombucks", barista: misterLee)
남겨주신 답변을 잘 보았습니다!
그러나 여전히 의문이 생기는 부분이네요...🧐
말씀해주신 부분은 `객체`의 `프로퍼티`가 변할 가능성이지, `객체` 자체가 변할 가능성은 아닌 거 같아요.
`객체`가 변할 가능성이 있을까요?

2023-03-13 03:25 UTC, increw commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(coffeeShopName: "yagombucks", barista: misterLee)
앞서 제가 말씀을 드릴려고 했던 부분은 프로퍼티인데 잘 못 전달이 된거 같습니다.

2023-03-13 05:47 UTC, jsa0224 commented
수고 많으셨습니다, 개미님(@increw)!
다음 스탭 진행하시면 될 거 같아요, 화이팅입니다!

2023-03-13 05:47 UTC, merged