Week3 [Step2] 마이노
yagom-academy/swift-starter-week3 pull request #2
Opened 2021-12-21 05:50 UTC by Mino777

안녕하세요 네프! @Neph3779
Step2 PR 입니다!

### 고민한 부분
- struct와 class의 사용
  - Person을 struct로 진행할 경우엔, 값을 복사하여 사용하기 때문에,
CoffeShop에서 Person의 buy 메서드를 호출하더라도 Person 원본의 money 속성 값은 변하지 않음.
  - 따라서 원본이 공유될 필요가 있기 때문에(참조 될 필요가 있기 때문에), **Person**의 경우 참조 타입인 **class**를 사용하였습니다.
  - **CoffeShop**의 경우에는 원본이 공유될 필요가 없기 때문에(참조 될 필요가 없기 때문에) 값 타입인 **struct**로 진행했습니다.
  - 드디어 상속외에 뭔가 좀 유의미한 차이를 알게 된 것 같습니다! 하지만 여전히 뭔가 확실하게 딱 구분지어서 사용할 정도의 단계는 아닌 것 같습니다😭
  - 혹시 네프가 봤을 때 네프였다면 해당 미션에서 이러한 이유로 이걸 사용했을 것 같다 정도의 의견을 여쭤봐도 될까요? 궁금합니닷

감사합니다!!

2021-12-21 22:55 UTC, Neph3779 requested changes
안녕하세요 마이노님!
여러가지 고민을 해보신게 보이네요!
PR 메세지로 질문해주신 것은
comment의 wwdc영상이  아마 해결해줄 것 같습니다 😄

저는 공유되어야하는 값들이 있다면 주저하지  않고 class를 택하는 편인데요
특히 타입 안에 또다른 타입의 instance가 들어가야 하는 경우에는 더더욱 그렇습니다

struct는 그 struct 자체로만 쓰이는 경우에 주로 사용해요!

이해가 가지 않는 부분은 dm으로 언제든 질문주세요~

2021-12-21 22:55 UTC, Neph3779 commented on CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
> +    var customer: Person?
struct내부에 class와 같은 참조 자료형이 있으면 성능적으로 좋지 못하답니다
아직은 좀 버거운 난이도의 영상일지 모르겠지만
https://developer.apple.com/videos/play/wwdc2016/416/
이 wwdc 영상을 꼭 한 번 천천히 보시면 도움이 될거에요~

2021-12-21 22:55 UTC, Neph3779 commented on CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
> +        }
guard와 if문의 차이는 뭘까요?
둘은 성능차이가 날까요?

2021-12-21 22:55 UTC, Neph3779 commented on CodeStarterCamp_Week3/main.swift
> +
상수로 분리하셨군요! 좋습니다!

2021-12-21 22:55 UTC, Neph3779 commented on CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
> +        print("\(name) 님의 커피가 준비되었습니다. 픽업대에서 가져가주세요.")
이 print문을 함수에 넣는것도 좋지만
pickUpTable에 어떤 값이 추가되면 자동으로 나오도록 하는 것은 어떨까요?
어떻게 하면 좋을지 생각해볼까요?

2021-12-21 22:55 UTC, Neph3779 commented on CodeStarterCamp_Week3/main.swift
> +print("잔액이 부족할 때 /매장/ 보유 금액: \(yagombucks.sales)")
이 코드들은 조금 정리할 필요가 있어보여요
테스트용 문장들이더라도 좀 더 깔끔한것도 좋을 것 같습니다!

2021-12-21 22:55 UTC, Neph3779 commented on CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
>      private(set) var menu: [Coffee:Int]
```suggestion
    private(set) var menu: [Coffee: Int]
```

2021-12-23 11:14 UTC, Mino777 commented on CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
> +    var customer: Person?
struct안에 레퍼런스가 있는 경우, 레퍼런스 수에 비례하여 레퍼런스 카운팅 오버헤드를 지불하게되고 
둘 이상의 레퍼런스가 있는 경우 class보다 레퍼런스 카운팅 오버헤드가 더 많이 유지되기 때문에 성능적으로 좋지 못하다.
정도라고 이해했는데 맞을까요?! 확실히 메모리쪽 이야기는 계속해서 생각날때마다 반복해서 봐야 확실히 이해될 것 같습니다😭

앞으로 공식문서 말고도 WWDC 영상들도 천천히 한번 쭉 봐야겠네요.. 
뭔가 지금까지 안풀리던것들이 WWDC 영상들에 녹여져있는 것 같아요
네프덕분에 요즘 공부하는게 너무 재밌습니다 감사합니다!

2021-12-23 11:16 UTC, Mino777 commented on CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
> +        }
- guard
	- Early Exit!
	- if 코드보다 훨씬 간결하고 읽기 좋게 구성 가능
	- 예외사항만을 처리하는 경우에는 guard구문이 훨씬 간편
	- 해당 상수를 메서드 내에 지역 상수처럼 자유롭게 사용이 가능
	- return,break,continue,throw등의 제어문 전환 명령어를 쓸 수 없는 상황이라면 사용 불가
- if
	- if let으로 옵셔널 바인딩 된 상수는 해당 scope 안에서만 사용 가능
정도로 정리해보았습니다!

if문이 데이터가 많은 배열을 옵셔널 바인딩 할시에 아주 쪼오금 더 빠르다는 자료를 찾긴 했는데
뭔가 유의미한 차이는 아닌 것 같습니다!
guard문 짱짱!
네프는 어떤걸 좋아하시나요?!

2021-12-23 11:18 UTC, Mino777 commented on CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
> +        print("\(name) 님의 커피가 준비되었습니다. 픽업대에서 가져가주세요.")
프로퍼티 옵저버인 didSet을 활용해보았습니다! 감사합니다!

2021-12-23 11:18 UTC, Mino777 commented on CodeStarterCamp_Week3/main.swift
> +print("잔액이 부족할 때 /매장/ 보유 금액: \(yagombucks.sales)")
앗 제가 지운다는걸 깜밖했네요😭
수정했습니다!

2021-12-23 11:20 UTC, Mino777 commented
@Neph3779
제가 일이있어서 피드백 반영이 늦어졌네용😭
피드백 반영 해보았습니다!
감사합니다!

2021-12-23 12:13 UTC, Neph3779 commented on CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
> +        }
guard문과 if문의 성능적 차이에 대해서 면접 질문이 들어온 경우가 있다고 하더라고요 ㅎㅎㅎ..
정답은 "별 차이 없다" 였다는..
그냥 한번쯤 알아봐도 좋을 주제인 것 같아 질문드렸습니다! 😁
early exit에 대해서는 조금 더 자세히 알아봐도 좋을 것 같아요!

2021-12-23 12:19 UTC, Neph3779 approved these changes
안녕하세요 마이노님! 드린 피드백 잘 반영해주셨네요!
이번 스텝은 여기서 머지해도 될 것 같습니다~! 😁
추가로 드린 피드백은 다음에 반영해주시면 될 것 같아요
그럼 다음 스텝도 화이팅입니다!! 💪💪💪

2021-12-23 12:19 UTC, Neph3779 commented on CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
> +
잘해주셨습니다! 👍👍

2021-12-23 12:19 UTC, Neph3779 commented on CodeStarterCamp_Week3/CoffeeShop/CoffeeShop.swift
>  }
큰 것은 아니지만
order 메서드와 네이밍을 조금 통일하는 것도 좋아보여요!
한쪽에는 Coffee가 붙고 한쪽은 안붙는게 조금은 어색해보이네요 😅
제가 보기엔 Coffee가 붙어도, 안붙어도 이상할 것이 없는 상황이라 이 둘 중의 선택은 마이노님이 해주시면 될 것 같습니다!

2021-12-23 12:19 UTC, merged