Week3 [STEP1] yyss99
yagom-academy/swift-starter-week3 pull request #201
Opened 2023-03-11 06:44 UTC by yy-ss99

@jsa0224
솜! 이제 봄인가봐요!!! 날씨가 너무 좋아서 놀러가고싶어요🌻

 ## 고민했던 점
  - 나름 enum을 사용하면 코드가 더욱 읽기 쉽고, 오타나 잘못된 입력으로 인한 에러가 발생하는 것을 방지할 수 있다고 했는데 어떤식으로 그게 가능한지 이해가 잘 가지 않아요
  - 그냥 buyCoffee함수나 giveCoffee 매개변수로 yagobucks.menu를 가져와도 될거 같은데? 하는 생각이 들어요. 구체적으로 어떤 걸 방지 할 수 있는건가요
  - 아니면 이런식으로 열거형을 사용하는게 아닌가요??😭

2023-03-12 06:06 UTC, yy-ss99 commented
Coffee enum을 더 활용하는 쪽으로 코드를 수정해 봤습니다!!

2023-03-13 03:16 UTC, jsa0224 requested changes
안녕하세요 와이님(@yy-ss99)~😊
그러게요! 벌써 봄이네요~🌸 카페에서 봄기운을 느끼면서 코딩을 해보는 것도 좋을 거 같네요!
근데 어젯밤은 넘 추워서… 이불 꼭꼭 덮고 잤어요🥶 아직 꽃샘추위 시즌인가봐요…ㄷㄷ

---

## 조언 받고 싶으신 부분

- enum을 사용하면 코드가 더욱 읽기 쉽고, 오타나 잘못된 입력으로 인한 에러가 발생하는 것을 방지할 수 있다고 했는데 어떤식으로 그게 가능한지 이해가 잘 가지 않아요
- 그냥 buyCoffee함수나 giveCoffee 매개변수로 yagobucks.menu를 가져와도 될거 같은데? 하는 생각이 들어요. 구체적으로 어떤 걸 방지 할 수 있는건가요
- 아니면 이런식으로 열거형을 사용하는게 아닌가요??😭

‘`오타나 잘못된 입력으로 인한 에러가 발생하는 것을 방지할 수 있다`’부분은 저도 이해가 잘 되지 않네요… 어디서 참고하신 문서일까요? `Enum`은 공통된 성질을 묶어서 타입으로 만들 때 자주 사용되는 개념이에요! 

아마도 저 문장은 열거형의 case는 `.케이스` 이렇게 접근할 수 있어서 잘못된 입력을 방지할 수 있다는 의미일지 모르겠네요!

이 부분은 나중에 디코로 이야기 나눠봐도 좋을 거 같네요!

아래 코멘트에 피드백 남겼습니다!

2023-03-13 03:16 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    let name: String
이름은 변경 가능성이 없을까요?

2023-03-13 03:16 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    }
Struct에서 초기화를 해주셨네요! 이유가 있으실까요?

2023-03-13 03:16 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    let menu: [Coffee: Int]
메뉴도 바뀔 가능성이 없을까요?

2023-03-13 03:16 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func buyCoffee(Coffee: Coffee) {
메서드와 파라미터 네이밍에서 `coffee`가 중복되네요!

2023-03-13 03:16 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func giveCoffee(orderedCoffee: Coffee) {
여기도 `coffee`가 중복!
그리고 `give`라는 네이밍은 대가 없는 선물을 주는 느낌이에요~
다른 네이밍으로 지어볼까요!

2023-03-13 03:16 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(barister: misterLee, income: 0, menu: [.americano : 2000, .latte: 2500, .iceTea: 3000])
해당 인스턴스들은 변경될 가능성이 있나요??

2023-03-13 03:16 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +yagombucks.giveCoffee(orderedCoffee: .latte)
오... 객체간의 소통은 Step 2 부분입니다! 삭제해주세용!

2023-03-13 12:27 UTC, yy-ss99 commented on CodeStarterCamp_Week3/main.swift
> +    let name: String
보통 이름은 바꾸는 경우는 없으므로 변경 가능성이 없다고 생각해서 let으로 했습니다. 변수로 만드는게 나았을까요??

2023-03-13 12:27 UTC, yy-ss99 commented on CodeStarterCamp_Week3/main.swift
> +    }
어떤 변수가 있는지 보기 쉽지 않을까 생각했었는데 생각해보니 굳이 넣을 필요 없는 부분인거 같아서 수정했습니다!!

2023-03-13 12:27 UTC, yy-ss99 commented on CodeStarterCamp_Week3/main.swift
> +    let menu: [Coffee: Int]
메뉴는 바뀔 가능성이 많은 거 같아요!!

2023-03-13 12:27 UTC, yy-ss99 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func buyCoffee(Coffee: Coffee) {
수정 해봤습니다!

2023-03-13 12:27 UTC, yy-ss99 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func giveCoffee(orderedCoffee: Coffee) {
넵넵 ! 수정해봤습니다!

2023-03-13 12:27 UTC, yy-ss99 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(barister: misterLee, income: 0, menu: [.americano : 2000, .latte: 2500, .iceTea: 3000])
커피를 판매해서 income과 money가 변하기 때문에 var로 했습니다!!

2023-03-13 12:28 UTC, yy-ss99 commented on CodeStarterCamp_Week3/main.swift
> +yagombucks.giveCoffee(orderedCoffee: .latte)
@jsa0224  넵!

2023-03-14 05:37 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    let name: String
개명의 여지도 있을 거라 생각해서 드린 말씀입니다!
한 번 생각해보시고, 와이님의 의견대로 구현해주시면 됩니다!

2023-03-14 05:37 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    }
그쵸, 구조체에는 `맴버와이즈 이니셜라이저`가 존재하니까요👍

2023-03-14 05:45 UTC, jsa0224 requested changes

2023-03-14 05:45 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func buyCoffee(myMemu: Coffee) {
```suggestion
    mutating func buyCoffee(from menu: Coffee) {
```

여기는 `from`이라는 전달인자 레이블이 적절해보이네요!

2023-03-14 05:45 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    var barister: Person
요기! 바리스타에 오타가 존재합니다!

2023-03-16 06:37 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func buyCoffee(from memu: Coffee) {
memu 에 오타가 존재하네요! 그리고 커피의 의미를 메뉴라는 단어로 지칭되는 게 애매해보여요.
메뉴는 포괄적인 의미가 강해서요!
```suggestion
    mutating func buyCoffee(_ coffee: Coffee) {
```

이렇게 전달인자 레이블로 언더바를 활용하시면, 해당 메서드를 호출할 때 중복되는 단어가 보이지 않기 때문에, 많이 활용합니다.
해당 부분은 좀 더 공부하시는 게 좋을 거 같아요~

2023-03-18 05:10 UTC, yy-ss99 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func buyCoffee(from memu: Coffee) {
@jsa0224 변수이름이나 전달인자 레이블 공부좀 더해봐야겟네요!! 수정했습니다

2023-03-18 10:44 UTC, jsa0224 commented
수고 많으셨습니다, 와이님(@yy-ss99)!
다음 스탭 진행하시면 됩니다~

2023-03-18 10:45 UTC, merged