Week3 [STEP 1] appledayz
yagom-academy/swift-starter-week3 pull request #203
Opened 2023-03-13 06:53 UTC by Appledayz

som~ @jsa0224

# 👨‍🔬 Step 1: 타입과 인스턴스의 관계

하다보니 STEP2까지 포함하게 되는거 같아서 미리 해봤습니다.
주문에 실패하는 경우까지 포함해보려다가 너무 범위가 넓어지는 것 같아서 멈췄습니다. 코드가 조금 남아 있어요. 나중에 에러처리에 대해 배워서 쓰는게 낫지 않을까 합니다.

## 1. 고민한 점

enum, struct, class 를 배우기는 했지만, 직접 써보려고 하니 감이 잘 안잡혔습니다. 계속 하다보니 조금 감이 잡히는거 같아요.

실제 서비스를 생각하다보니 쓸데없이 복잡하게 만들게 되길래 간소화해서 줄였습니다. 돈에 대해서도 보수적으로 접근하려다보니 결제를 중재하는 신뢰할 수 있는 중간자의 필요성이라던가, 지갑이라던가. 최소한 coffeeShop 메서드에서 주문하는 Person을 받지 않도록 해봤습니다. 어차피 하나의 앱에서 처리하는 상관없을 거 같긴해요.

커피가 주문하자 마자 나오는게 별로같아서 delay를 줘봤습니다. 잘 쓴건진 모르겠지만 동작합니다!

2023-03-14 02:38 UTC, jsa0224 requested changes
안녕하세요, 애플데이즈님(@Appledayz)~🍎
3주차 프로젝트 어려우셨을텐데, 잘 구현해주셨네요!

전보다 네이밍이 정말 좋아지셨어요!!
Step 1과 Step 2 구현 부분을 헷갈려하시는 분들이 많더라고요! 
이 부분은 제가 코멘트로 남겼습니다!

---

## 고민 하신 부분

> enum, struct, class 를 배우기는 했지만, 직접 써보려고 하니 감이 잘 안잡혔습니다. 계속 하다보니 조금 감이 잡히는거 같아요.
실제 서비스를 생각하다보니 쓸데없이 복잡하게 만들게 되길래 간소화해서 줄였습니다. 돈에 대해서도 보수적으로 접근하려다보니 결제를 중재하는 신뢰할 수 있는 중간자의 필요성이라던가, 지갑이라던가. 최소한 coffeeShop 메서드에서 주문하는 Person을 받지 않도록 해봤습니다. 어차피 하나의 앱에서 처리하는 상관없을 거 같긴해요.

정말 현실반영을 하려면 끝이 없을 거 같네요! 
저도 이 프로젝트 해보면서, 편리하게 썼던 주문 앱들이 대단하게 보이더라고요!

Step 2는 객체간의 소통이 중심 키워드이니, coffeeShop 메서드에서 주문하는 Person을 파라미터로 받아보는 것도 저는 좋을 거 같아요~

> 커피가 주문하자 마자 나오는게 별로같아서 delay를 줘봤습니다. 잘 쓴건진 모르겠지만 동작합니다!

잘 쓴 건지는 모르겠다는 의미가 개념을 잘 모르고 쓰신 거 같아 조금 걱정이 되네요🥲
이 부분도 아래 코멘트 확인해주세요!

2023-03-14 02:38 UTC, jsa0224 commented on CodeStarterCamp_Week3/step1.swift
> +class Person {
`class`로 하신 이유가 있으신가요? (Just 궁금해서 물어보는 겁니다)

2023-03-14 02:38 UTC, jsa0224 commented on CodeStarterCamp_Week3/step1.swift
> +        }
`order`이라는 기능과 다르게 주문을 받고 있는 기능처럼 보여요!
`CoffeeShop`에 있어야 할 기능 같은데요?

2023-03-14 02:38 UTC, jsa0224 commented on CodeStarterCamp_Week3/step1.swift
> +let group = DispatchGroup()
요 객체는 왜 따로 빼서 구현하셨나요?

2023-03-14 02:38 UTC, jsa0224 commented on CodeStarterCamp_Week3/step1.swift
> +    }
기능분리 좋습니다👍

2023-03-14 02:38 UTC, jsa0224 commented on CodeStarterCamp_Week3/step1.swift
> +        }
- `DispatchQueue`는 무슨 역할을 하나요? (`DispatchQueue`에 대한 정확한 개념을 설명해주세요!)
- 새로운 개념을 사용하시는 것 또한 좋지만, `구현을 위한 구현`보다는 `공부를 위한 구현`을 하셨으면 좋겠네요!

2023-03-14 02:38 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +group.wait()
이 부분은 Step 2 내용이니 지워주세요!

2023-03-14 06:13 UTC, Appledayz commented on CodeStarterCamp_Week3/step1.swift
> +class Person {
처음에 struct로 할지 class로 할지 고민했는데요. 언제 써야하는지 감이 잘 안잡혔어요. 그래서 두가지를 언제 사용하면 좋을지 고민해 봤습니다. 아래 이유로 class가 더 적합하다고 생각했습니다.
1. Person과 coffeeShop은 이후에 복잡성이나 확장성을 고려했을 때 상속 및 다형성이 가능한 class가 더 적합하다고 생각했습니다.
2. struct는 할당, 전달 하는 경우 값으로써 복사가 되는 점이 인스턴스를 사용할 때 부적합하다고 생각했습니다. 만약 missKim을 만들고 전달하는 경우 전달받은 쪽에서는 해당 인스턴스의 값을 조작할 수 없으며 복사된 인스턴스를 조작하게됩니다. 단순히 값을 전달 받기만 하지 않고 변경까지 해야한다면 struct보다 인스턴스 공유가 가능한 class가 더 나은 것 같습니다.

2023-03-14 06:21 UTC, Appledayz commented on CodeStarterCamp_Week3/step1.swift
> +let group = DispatchGroup()
단순히 main.swift에서 쓰려고 전역으로 선언했습니다.
주문하는 함수를 main에서 호출하는데 주문들이 끝나는 시점에 wait() 할 수 있도록 하려고 했습니다.

2023-03-14 06:41 UTC, Appledayz commented on CodeStarterCamp_Week3/step1.swift
> +        }
저도 이부분을 어떻게 해야할지 고민했는데요. CoffeeShop이 Person을 가져가서 Person 인스턴스를 조작하는게 맞는가? 란 의문이 들었어요. 둘을 따로 떼어놓고 각자 의지를 가진다면 맘대로 조작하게 해서는 안되는거 같고, 어차피 같은 하나의 프로그램 안에 구현하는거고 하나의 앱(자체 결제 시스템에 충전된 상태)이라면 상관 없는 것 같았어요.
CoffeeShop으로 단순히 Person을 전달해서 조작, 변경하면 되는걸까요? Person property에 직접 접근하지 않고 메서드를 선언하는게 좋을까요?

2023-03-14 06:41 UTC, Appledayz commented on CodeStarterCamp_Week3/main.swift
> +group.wait()
뉍

2023-03-16 07:12 UTC, Appledayz commented on CodeStarterCamp_Week3/step1.swift
> +        }
`DispatchQueue`는 멀티코어 환경에서 동시성을 관리하는 `GCD(Grand Central Dispatch)`의 핵심 클래스로 작업항목의 실행을 관리합니다. Queue에 작업항목을 추가하면 시스템에서 관리하는 스레드 풀에서 해당 작업을 처리합니다. `DispatchQueue`는 기본적으로 세가지 큐가 있습니다.
- `main`: 기본적으로 직렬(Serial)큐 입니다. 즉, FIFO(First In First Out) 입니다.
- `global`: 동시(Concurrent)로 동작하는 큐입니다. 작업 중요도에 따라 순서가 달라집니다.
- `custom`: 개발자가 직접 생성하는 큐로 default는 직렬큐 입니다.

2023-03-16 07:30 UTC, jsa0224 commented on CodeStarterCamp_Week3/step1.swift
> +        }
오, 그렇다면 2가지 질문을 추가로 남기겠습니다.

- 픽업테이블로 추가되는 메서드가 비동기로 호출되고 있는데, 그렇게 구현하신 이유가 있으실까요?
- 해당 프로그래밍을 동시성 프로그래밍으로 구현할 필요가 있을까요?

2023-03-16 10:56 UTC, Appledayz commented on CodeStarterCamp_Week3/step1.swift
> +        }
PR comment에 썼던 것처럼 그저 실제로는 주문보다 커피만들기가 훨씬 느려서 커피 만드는 동안 주문을 받을 수 있기 때문에 같은 느낌이 들게 사용해 봤습니다. 굳이 사용하지 않아도 되긴 하지요.
혼자 간단한 문제를 복잡하게 만드는게 특기인거 같아요. 계속 코드 쓰고 지우고 시험해보고 하면서 배웁니다.

저번에 class 상속받은 변수 오버라이딩 하면서 get { return self.weight }인가 했더니  멈춰버리더라구요 ㅋㅋ

2023-03-17 01:38 UTC, jsa0224 commented on CodeStarterCamp_Week3/step1.swift
> +        }
음... 애플데이즈님이 하시는 말씀이 크게 와닿지는 않는 거 같아요.

카페 직원이 2명인 경우, 2명이 각각의 일을 처리하기 위해 프로그래밍적으로 스레드가 2개 필요해서 동시성 프로그래밍을 적용할 수 있겠지만, 현재 프로젝트에서는 카페 직원이 바리스타 1명인 걸로 알고 있습니다.
그리고 단순히 픽업 테이블에 올리는 시간을 실제 만드는 시간처럼 늦추기 위해 `asyncAfter`를 사용하신 거 같고요.

`global()`로 구현하신 걸로 보아 스레드를 2개 쓰신다는 건데, 이번 프로젝트에서는 오버엔지니어링으로 보여요.
전혀 스레드를 2개 이상 쓸 필요가 없어보이기 때문이죠.

동시성 프로그래밍의 개념을 다시 숙지하셨으면 좋겠어요. 현재 프로젝트에서는 불필요해보입니다!

2023-03-17 05:18 UTC, Appledayz commented on CodeStarterCamp_Week3/step1.swift
> +        }
넵 지우고 올리겠습니다. 미션 요구사항에 맞춰서 구현하라는 말씀이신거죠?

2023-03-17 11:29 UTC, jsa0224 commented on CodeStarterCamp_Week3/step1.swift
> +        }
네네! 미션 요구사항에 없는 부분도 물론 구현하셔도 되지만, 이번 동시성 프로그래밍은 적절하지 않다고 생각되서 말씀드린 겁니다 ㅎㅎ

2023-03-17 11:37 UTC, jsa0224 commented
애플데이즈님(@Appledayz)! 수고 많으셨습니다!
다음 스탭 진행하시면 됩니다~!

2023-03-17 11:37 UTC, merged