Week3 [STEP2] redmango1446
yagom-academy/swift-starter-week3 pull request #214
Opened 2023-03-15 14:55 UTC by redmango1446

@jsa0224 

#고민했던 점
자꾸 Person의 order메소드에서 에러가 난다. 번역기 돌려보니 
"변경할 수 없는 값에 변경 멤버를 사용할 수 없음: 'CoffeeShop'은 'let' 상수입니다."
(Cannot use mutating member on immutable value: 'coffeeShop' is a 'let' constant)
찾아보니 CoffeeShop의 make 메소드 앞에 mutating을 붙인게 원인이 된듯한데 
이걸 떼면 make메소드 내부에서 프로퍼티 값 변경이 안된다. 왜냐? 이건 구조체라 값 타입이니까.

그래서 아예 CoffeeShop의 타입을 class로 바꿔주었다.

변경할수없는 값에 변경멤버를 못쓴다고해서 안쓰려고 했더니 그건 그것대로 안된다고해서 
이번엔 CoffeeShop가 let이 아니게 만들어버린것이다!
(이렇게 해석되는게 맞...나? 맞는것같긴한데...)

#해결되지 않은 점
변경할 수 없는 값(immutable value)이라는게 이해는 커녕 정확히 어딜 말하는지도 모르겠다

#step1에서 구조체를 사용한 이유!
"일반적으로 추론이 쉽기때문에 구조체 사용을 권장"
이외에도 
###애플 문서 - 구조체를 사용하는게 좋은 경우
- 연관된 간단한 값의 집합을 캡슐화하는 것만이 목적일 경우
- 캡슐화한 값을 참조하는 것보다 복사하는 것이 합당할때
- 구조체에 저장된 프로퍼티가 값 타입이며, 참조하는 것보다 복사하는것이 합당할때
- 다른 타입으로부터 상속받거나, 자신을 상속할 필요가 없을때
등이 있는데 2번째는 잘 모르겠고 1,3,4번이 해당되는것 같다

2023-03-16 07:04 UTC, jsa0224 requested changes
안녕하세요, 레드망고님(@**redmango1446**)~🥭
Step 2도 잘 구현해주셨네요! 

제 덕분에 오류문도 해결하시고 좋네요🤣👍
구조체랑 클래스의 차이는 앞으로도 많이 나올 키워드입니다!
미리 탄탄하게 개념에 대해 공부해두시는 게 좋습니다!

피드백은 아래 코멘트에 남겨두었습니다!

2023-03-16 07:04 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func order(_ coffee: Coffee, of coffeeShop: CoffeeShop, by name: String) {
`name`은 프로퍼티를 사용하시면 될 거 같은데, 매개변수로 활용하신 이유가 있으신가요?

2023-03-16 07:04 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
공백!

2023-03-16 07:04 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +            print("\(self.name): \(name)님이 주문하신 \(coffee.rawValue)(이/가) 준비되었습니다. 픽업대에서 가져가 주세요.")
이 부분은 `pickUpTable`로 프로퍼티 감시자로 활용해서 구현해도 괜찮을 거 같네요!

2023-03-16 07:04 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +
여기도 공백!

2023-03-16 13:16 UTC, redmango1446 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func order(_ coffee: Coffee, of coffeeShop: CoffeeShop, by name: String) {
그러게요..? 활용한 이유는 일단 과제에 써있는 메소드 예시?는 저렇게 매개변수를 받아오길래 그대로 옮겨썼는데.... 이제보니 코드상으론 필요없어보이네요! 누가 주문했는지 명시적으로 표시하기 위해서일까요? 으으으음 일단 지우고 프로퍼티를 활용하는 식으로 수정해볼게요!

2023-03-17 01:48 UTC, jsa0224 commented
수고하셨습니다, 레드망고님(@redmango1446)~
프로퍼티 감시자 활용 잘하셨네요!!
다음 스탭 진행하시면 됩니다!

2023-03-17 01:48 UTC, merged