Week3 [Step 1] knumber2
yagom-academy/swift-starter-week3 pull request #246
Opened 2023-08-01 10:14 UTC by cognd98

@Rhode-park 

### 고민했던 점

- Person, CoffeeShop타입 모두 이후 상속받을 가능성을 고려하여 class타입을 사용하였습니다.
- money, sales프로퍼티 모두 초기값을 설정할 필요가 없다고 생각해 옵셔널을 사용하였습니다.

2023-08-04 09:39 UTC, Rhode-park requested changes
PR잘 받았습니다!
type에 대해 많이 공부해보신게 느껴집니다.

각각의 프로퍼티나 타입의 존재의미에 대해서 생각해보시고 코드를 짜면 더 좋을 것 같습니다.
모든 프로퍼티나 타입은 그 쓸모가 있기 마련입니다.
그러니 단순히 '요구사항에서 이걸 만들라고 했으니까~'라고 코드를 짜기 보다는
'요구사항에서 이걸 만들라고 했는데, 왜 이걸 만들라고 했을까? 어디에서 쓰기 위함일까?'
라는 식으로 생각을 조금만 더 해보시면 좋을 것 같습니다!
이러한 생각은 추후에 프로젝트를 만들 때에도 도움이 됩니다.
각각의 기능이 뭘 위한건지, 각각의 요소들이 왜 필요한지 주체적으로 생각을 해보는 연습을 해보셨으면 좋겠습니다.

이번 프로젝트도 화이팅입니다!!!!
리뷰 반영해주시면 merge해드리겠습니다!!

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +enum Coffee {
enum을 잘 정의해주셨습니다. LGTM!
열거형은 주로 어떨 때 사용하게 될까요? 답변 부탁드립니다!

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    case 카푸치노
각각의 case는 영어로 작성하는게 좋을 것 같습니다.

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    var money: Int?
`money`를  Int`?`로 타입 명시 해주신 이유는 무엇인가요?
왜 옵셔널이어야만 하나요?

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    }
앞서 `Coffee`라는 enum을 정의했습니다.
타입을 정의하는 이유는 그것을 사용하기 위해서겠지요?
그것을 사용해서 메서드를 정의해보면 어떨까요?
매개변수를 통해 어떤 커피를 구매하는지 나타내면 좋을 것 같습니다.

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    var sales: Int?
마찬가지입니다.
`sales`를  Int`?`로 타입 명시 해주신 이유는 무엇인가요?
왜 옵셔널이어야만 하나요?

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    var menu: [String : Int] = [:]
`menu`는 무엇을 나타내는 프로퍼티인가요?
커피종류, 가격을 나타내는 프로퍼티네요?
커피 종류는 앞서 enum을 통해 정의하지 않았나요?
그러면 String대신에 뭐가 들어가면 좋을까요?

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    var menu: [String : Int] = [:]
`menu`가 빈 딕셔너리입니다.
커피종류와 가격을 알 수 있도록 해주어야하지 않을까요?

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    }
이니셜라이저를 통해 초기값을 전달받고자하고 있군요. 멋집니다! LGTM👍🏻

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    init(barist: Person) {
`barist`는 오타인가요?

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    }
앞서 `barista`라는 프로퍼티를 만들어주셨습니다.
왜 `barista`라는 프로퍼티를 만들었을까요?
만든 프로퍼티는 사용해주어야하지 않을까요?
누가 커피를 만드는지 받아오고 append한 후에 그 정보를 출력해봄은 어떨까요?

2023-08-04 09:39 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(barist: misterLee)
type annotation을 사용해주고 계십니다.
type inference와 비교했을 때, type annotation은 어떤 장점을 가지고 있을까요? 답변 부탁드립니다

2023-08-04 14:23 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    var money: Int?
초기값을 설정할 필요가 없다고 하셨는데, 그 이유가 궁금합니다. 옵셔널로 타입을 지정해놓았을 때는 어떠한 장점이 있으며 어떠한 단점이 있을까요? 어떠한 상황들이 예상되는지 설명 부탁드립니다.

2023-08-04 14:24 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    var sales: Int?
초기값을 설정할 필요가 없다고 하셨는데, 그 이유가 궁금합니다. 옵셔널로 타입을 지정해놓았을 때는 어떠한 장점이 있으며 어떠한 단점이 있을까요? 어떠한 상황들이 예상되는지 설명 부탁드립니다.

2023-08-06 07:28 UTC, cognd98 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(barist: misterLee)
type annotation은 초기값이 없어도 사용할 수 있습니다.

2023-08-06 07:33 UTC, cognd98 commented on CodeStarterCamp_Week3/main.swift
> +    var money: Int?
돈을 가지고 있지 않을 수도 있다고 생각했기 때문입니다. 옵셔널로 지정한다면 초기값을 지정해주지 않아도 되며 즉 이니셜라이저를 하지 않아도 됩니다.

2023-08-06 07:37 UTC, cognd98 commented on CodeStarterCamp_Week3/main.swift
> +enum Coffee {
허용 가능한 값을 제한하고 싶을 때 사용합니다.

2023-08-06 07:42 UTC, cognd98 commented on CodeStarterCamp_Week3/main.swift
> +    var sales: Int?
매출이 있을 수도 없을 수도 있다고 생각했기 때문에 굳이 초기값을 설정해 주지 않아도 된다고 생각했기 때문입니다. 옵셔널을 사용하면 이너셜라이저를 하지 않아도 됩니다.

2023-08-06 07:55 UTC, cognd98 commented on CodeStarterCamp_Week3/main.swift
> +    init(barist: Person) {
네 수정하겠습니다!

2023-08-07 04:11 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    var money: Int?
돈을 가지고 있지 않은 상황이라면 돈이 0원인 상황이라고 보는게 현실적이지 않을까요?

2023-08-07 04:12 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    var sales: Int?
마찬가지로 매출이 없을 수도 있는 상황이라면 매출이 0원인게 현실적인 상황 아닐까요?

2023-08-07 04:13 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(barist: misterLee)
지금은 초기값이 있는데도 type annotation을 사용하고 계시네요? 그러면 knumber2님의 컨벤션은 모든곳에서 type annotation을 하는 것이다라고 알고 있으면 될까요?

2023-08-07 04:21 UTC, cognd98 commented on CodeStarterCamp_Week3/main.swift
> +    var money: Int?
네 0으로 보는 것이 현실적일 거 같아 초기값을 0으로 설정하였습니다.

2023-08-07 04:22 UTC, cognd98 commented on CodeStarterCamp_Week3/main.swift
> +    var sales: Int?
넵 매출 초기값을 설정하는 것이 현실적인 상황이라고 생각하고 수정하였습니다.

2023-08-07 04:37 UTC, Rhode-park commented
수고하셨습니다!

이제부터는 `import Foundation`의 기능을 생각해보면 좋을 것 같습니다.
다음 step하면서 숙제로 `import Foundation`이 어떤 역할을 하는지 알려주시면 감사하겠습니다.

또한, 이 프로젝트를 좀 더 다채롭게 하기 위하여 각각의 메서드마다 문구를 출력해줘도 좋을 것 같습니다.
이를테면 다음과 같이요:

`Person` class에 `name`이라는 프로퍼티 추가 후 메서드에 프린트문 추가
```swift
class Person {
    var name: String
    var money: Int = 0
    
    init(name: String, money: Int) {
        self.name = name
        self.money = money
    }
    
    func order(_ coffee: Coffee, coffeeShop: CoffeeShop) {
        print("\(name)이/가 \(coffeeShop.name)에서 \(String(describing: coffee))을/를 주문했습니다.")
        coffeeShop.make(coffee, barista: misterLee)
    }
}
````

`CoffeeShop` class에 name이라는 프로퍼티 추가 후 메서드에 프린트문 추가
```swift
class CoffeeShop {
    var name: String
    var sales: Int = 0
    var menu: [Coffee : Int] = [.americano : 3000, .latte : 4000, .cappuccino : 5000]
    var pickUpTable: [Coffee] = []
    var barista: Person
    
    init(name: String, barista: Person) {
        self.name = name
        self.barista = barista
    }
    
    func make(_ coffee: Coffee, barista: Person) {
        pickUpTable.append(coffee)
        print("pickUpTable에 \(coffee)이/가 추가되었습니다.")
    }
}

```

프로퍼티 생성 및 order메서드 호출
```swift
var misterLee: Person = Person(name: "misterLee", money: 0)
var missKim: Person = Person(name: "missKim", money: 10000)
var yagombucks: CoffeeShop = CoffeeShop(name: "yagombucks", barista: misterLee)

missKim.order(.americano, coffeeShop: yagombucks)
```
결과물
```text
missKim이/가 yagombucks에서 americano을/를 주문했습니다.
pickUpTable에 americano이/가 추가되었습니다.
```

아무튼 수고가 많으셨습니다. merge해드리겠습니다. 다음 step에서 뵈어요!

2023-08-07 04:37 UTC, merged