Week3 [STEP 1] paul
yagom-academy/swift-starter-week3 pull request #248
Opened 2023-08-02 08:44 UTC by suhjuho

@Tediousday93 
week3 step1 PR입니다!

## 고민했던 점
- Coffee 타입(열거형)을 만들어 원시값으로 문자열로 이름을 넣었습니다.
- Person 타입에 buyCoffee 메서드로 커피를 구매하고 커피 금액만큼 asset 프로퍼티의 값을 차감했습니다.(가진 돈과 음료 값은 비교하지 않았습니다.)
- CoffeShop 타입에서는 init시에 메뉴판에 음료와 가격이 있는 딕셔너리 타입 값을 넣었습니다.
- 주문을 받는 getOrder 메서드에서는 여러 메뉴를 주문받게 배열을 파라미터로 받았습니다.
- 커피를 만드는 함수 makeCoffee는 pickUpTable(배열)에 음료를 추가하고, 매출액에 음료가격을 더하게 했습니다.

---

## 조언을 얻고 싶은 부분
- 메뉴판에 커피 종류와 가격을 정해놓을 수 있는데  Coffee 타입(열거형)이 있어야 하는 이유가 궁금합니다.

2023-08-02 15:21 UTC, Tediousday93 requested changes
안녕하세요 폴님 👋
벌써 4주차군요!! 마지막까지 힘내서 달려봅시다. 💪
이번 스텝도 잘 수행해주셨네요!
고생하셨습니다👍

아래 코드에서도 코멘트를 확인해주시고, 수정이 완료되시면 디스코드로 머지 의사를 알려주세요 ☺️

</br>

---

### 수행한 점

* [ ] 정확한 브랜치에 PR 보내기
* [x] PR의 제목/내용을 양식에 맞게 보내기
* [x] 학습 도우미 태그하기

---

- [x] 요구조건에 맞게 타입 정의하기
- [x] 정의한 타입의 인스턴스 생성하기
- [x] 생성한 인스턴스의 프로퍼티 / 메서드 활용하기

---

</br>

### ✅ 고민했던 점
* Coffee 타입을 원시값이 있는 enum으로 잘 만들어주셨습니다 👍
* Person 타입의 요구되는 기능을 잘 만들어주셨습니다 👍
* CoffeeShop init 내부, 딕셔너리를 직접 생성하는 부분에서 개선할 점이 보입니다(코드 코멘트 확인해주세요 🙏)
* CoffeeShop 타입의 요구되는 기능을 잘 만들어주셨습니다 👍
* `getOrder` 보다는 실제로 활용되는 영문 `takeOrder`로 수정해보면 어떨까요?!

</br>

### ✅ 조언을 얻고 싶은 부분
* Coffee 열거형을 사용하지 않고 String 타입으로 사용하게 된다면, 휴먼에러가 발생할 가능성이 있습니다. 직접 문자열을 "americano"로 적어 전달하다 보면 오타가 생길 수도 있겠죠?! 또한 커피의 이름이 아닌 아무 의미없는 문자열("라면")이 들어가는 상황이 발생할 수도 있습니다. 이를 예방하기 위해 Coffee 타입으로 해당 자리에는 Coffee 타입만 사용할 수 있음을 나타내주는 용도라고 생각합니다.

정의해주신 CoffeeShop 타입의 프로퍼티 `menus`는 현재 타입이 `[String: Int]`로 설정되어있어 Coffee 열거형을 활용하지 못하고 있는 것 같습니다.

아래 코멘트를 확인해주시고 리팩토링 해봅시다 ☺️

</br>

### ✅ 추가 학습내용
이번에 클래스(class)와 구조체(struct)에 대해 학습하셨을 텐데요! 한 번에 와닿지 않는 내용이지만 매우 중요합니다. 🤔

클래스와 구조체에 대한 내용은 [애플 공식문서 - Structures and Classes](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/classesandstructures/)에서 자세히 알아볼 수 있으니 기회가 되신다면 학습해보시는 것을 추천드립니다 👍

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +    var asset: Int = 0
이니셜라이저에서 초기화를 해주고 있는데 기본값으로 0을 할당해주신 이유가 있을까요?!
기본값이 있는 프로퍼티의 경우 이니셜라이저 파라미터에 포함시키지 않을 수도 있습니다. 👀
(asset과 init 사이에 개행이 필요해보이네요!)

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +        }
여러개의 메뉴를 주문할 경우를 고려해서 작성해주셨네요 👍
전달인자 레이블을 활용하면 메서드를 호출할 때 좀 더 이해하기 쉬울 것 같습니다.
menu를 보통 복수형으로 쓰던가요...?! 💭

```suggestion
    func buyCoffee(menu: [Coffee], at coffeeShop: CoffeeShop) {
        coffeeShop.getOrder(menu: menu)
        for coffee in menu {
            if let price = coffeeShop.menu[coffee.rawValue] {
                self.asset -= price
            }
        }
```

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +}
CoffeeShop 타입도 요구조건에 맞게 잘 만들어주셨습니다! 👍
barista의 타입을 옵셔널 타입으로 설정하신 이유가 있을까요?

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +    }
init 위 아래 개행이 필요해 보입니다 👀
이니셜라이저에서 menus를 초기화해주고 있네요!

이렇게 고정적으로 할당해주게 되면 초기 메뉴를 임의로 설정할 수 없을 것 같아요. (처음 생성된 모든 CoffeeShop의 메뉴가 같게되겠죠?!)
어떻게 하면 CoffeeShop의 인스턴스를 만들 때 menu를 선택적으로 할당해줄 수 있을까요?

💡 hint
* 딕셔너리의 key type에 `Coffee` enum을 활용해보시면 좋겠습니다. 🤔
* 이니셜라이저 파라미터의 활용

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +    var pickUpTable: Array<String> = []
배열의 타입은 `[String]` 이렇게 간략히 나타낼 수도 있습니다 💭

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +
여기는 폴님이 의도하신 개행일까요?
CoffeeShop과는 다른 컨벤션으로 보이네요.
이런 세세한 개행 컨벤션도 맞춰주시면 좋겠습니다 😊

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +    func getOrder(menus: [Coffee]) {
get 보다는 take가 조금 더 어울리지 않을까요? 🤔

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +}
열거형의 원시값을 활용해주셨네요 👏
원시값을 직접 할당하지 않고 String 타입이라는 것만을 알려준다면 원시값이 어떻게 작동하는지 확인해볼까요?
```suggestion
enum Coffee: String {
    case americano 
    case latte 
    case iceTea
}
```

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +}
CoffeeShop의 menu 딕셔너리에 커피의 price를 수월하게 전달할 방법으로 연산 프로퍼티를 활용할 수 있습니다!
가능하시다면 enum 내부에 `price` 연산 프로퍼티를 만들어볼까요?

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +misterLee.buyCoffee(coffeeShop: yagombucks, menus: [Coffee.americano, Coffee.iceTea])
정의한 타입들의 인스턴스를 잘 만들어주셨네요! 👍
스텝 요구조건에 잘 맞게 작성해주셨습니다 👏👏👏

(Person type 이니셜라이저 가장 뒤쪽 괄호 앞 공백이 들어가있습니다..! 👀)

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +dump(yagombucks.pickUpTable)
`dump` 함수를 활용해주셨네요!
보통 print 함수와 같이 소개되는 것으로 알고 있는데요, 커피 주문 / 제작 메서드에 따로 print되는 내용이 없어 확인용으로 작성하신 것 같네요.

다음 스텝 넘어가셨을 때 불필요하다면 삭제해주세요 ~ ☺️

2023-08-02 15:21 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +    var menus: Dictionary<String, Int> = [:]
딕셔너리의 타입은 [String: Int] 로 간략히 나타낼 수도 있습니다 💭

2023-08-07 03:42 UTC, suhjuho commented on CodeStarterCamp_Week3/Step1.swift
> +}
기본값으로 어떤 값을 할당할지 애매해서 옵셔널로 설정했습니다.

2023-08-07 03:45 UTC, suhjuho commented on CodeStarterCamp_Week3/Step1.swift
> +}
타입만 알려준다면 문자열인 경우 case 이름과 동일한 원시값이 자동으로 만들어집니다. 제가 쓴 코드의 경우에는 굳이 문자열을 따로 쓰지 않아도 되겠네요!

2023-08-07 07:57 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +}
CoffeeShop에 barista 프로퍼티는 꼭 필요할까요? 없어도 될까요?
이 부분을 생각해서 결정해주시면 좋을 것 같습니다 ㅎㅎ

만약 CoffeeShop 내부 메서드에서 barista가 하는 일이 매우 중요한 것이 있다면 꼭 필요하겠죠?!
요즘엔 무인 카페도 있으니 옵셔널이 될 수도 있겠네요..! 🤣

2023-08-07 07:59 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +}
참고로 원시값의 타입이 Int인 경우에 원시값을 할당하지 않는다면
제일 위쪽 case의 원시값이 0부터 시작해서 1씩 증가하게 됩니다~!

2023-08-07 08:07 UTC, Tediousday93 reviewed
요구사항이 잘 반영되었군요~! 👍👍👍
고생 많으셨습니다.

다음 스텝도 화이팅입니다!

2023-08-07 08:07 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Step1.swift
> +    }
price 함수를 만들어주셨군요..! 좋습니다 👍
연산프로퍼티로 더 간단하게 나타낼 수 있답니다~ 👀
```suggestion
    var price: Int {
        switch self {
        case .americano:
            return 4000
        case .latte:
            return 4500
        case .iceTea:
            return 4500
        }
    }
```

이러면 호출할 때 괄호를 넣지 않아도 되겠죠?!
```swift
let americanoPrice = CoffeeShop.americano.price
```

2023-08-07 08:07 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +misterLee.buyCoffee(menu: [Coffee.americano, Coffee.latte], at: yagombucks)
열거형은 타입추론을 사용해도 좋다고 생각합니다 ㅎㅎ
위 13번 줄 key에는 잘 사용해주셨군요..!

```suggestion
misterLee.buyCoffee(menu: [.americano, .latte], at: yagombucks)
```

2023-08-07 08:09 UTC, merged