Week3 [STEP 1] Manito
yagom-academy/swift-starter-week3 pull request #249
Opened 2023-08-03 10:17 UTC by ParkSY0919

@Rhode-park 3주차 Step1 PR 드립니다!

## 조언을 얻고 싶은 부분: 
- Coffe를 열거형으로 표현할 때에 CoffeShop이라는 Class 안에 중첩하여 표현하는 것과, 독립적으로 바깥에 빼두고 enum 처리하는 것 중 어떤 것이 더 나을까요?

2023-08-04 11:05 UTC, Rhode-park requested changes
PR 잘 받았습니다!
여러가지 상상력이 돋보이는 논리적인 프로젝트였습니다.
너무 멋집니다!

### Coffe를 열거형으로 표현할 때에 CoffeShop이라는 Class 안에 중첩하여 표현하는 것과, 독립적으로 바깥에 빼두고 enum 처리하는 것 중 어떤 것이 더 나을까요?
어떤 상황을 반영하고 싶냐에 따라 달라질 것 같습니다. Coffee가 커피숍 안에 속해있는 정보라면 중첩하여 표현하는 것이 좋을 것 같고, 그게 아니라 독립적으로 존재하는 정보라면 독립적으로 처리하는게 좋을 것 같습니다.
그런데, 커피의 종류는 커피숍과는 별개로 존재하는 종류들이 아닐까 생각합니다.

덧붙여, 이니셜라이저에 대해서 조금 더 공부해보시면 좋을 것 같습니다.

더불어 각각의 프로퍼티나 타입의 존재의미에 대해서 생각해보시고 코드를 짜면 더 좋을 것 같습니다.
모든 프로퍼티나 타입은 그 쓸모가 있기 마련입니다.
그러니 단순히 '요구사항에서 이걸 만들라고 했으니까~'라고 코드를 짜기 보다는
'요구사항에서 이걸 만들라고 했는데, 왜 이걸 만들라고 했을까? 어디에서 쓰기 위함일까?'
라는 식으로 생각을 조금만 더 해보시면 좋을 것 같습니다!

또한, 코드가 현실을 반영하도록 코드를 짜면 더 좋을 것 같습니다.
현실적으로 누가 어떤 정보를 알고 있는 것이 좋은지에 대해서 고민해보시고 리뷰에 반영해보시길 바랍니다!

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    }
이니셜라이저를 잘 사용해주고 계십니다. LGTM! 멋집니다!

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    }
메서드는 동사로 시작하는 것이 좋습니다.
~ing 형태는 동명사로서 명상상당어구입니다.

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    var typeOfBeans: String // 원두종류
당도와 원두종류는 커피숍보다는 커피가 가져야 할 정보같습니다!

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    var menu: Dictionary<Coffee, Int>
[Dictionary Type Shorthand Syntax](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/collectiontypes#Dictionary-Type-Shorthand-Syntax)를 한 번 살펴볼까요?
> Although the two forms are functionally identical, the shorthand form is preferred and is used throughout this guide when referring to the type of a dictionary.

라고 나와있네요!

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +        self.pickUpTable = []
이니셜라이저에서 무조건적으로 빈배열을 할당해주고 있습니다. 무조건적으로 빈배열을 할당해주는 상황이라면, 프로퍼티 기본값을 지정해주는 방법도 있었을텐데, 이렇게 초기값을 설정해주신 이유가 있을까요?

[Default Property Values](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/initialization#Default-Property-Values) 참고해보시면 좋을 것 같습니다!

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    }
우와 고객이 가진 돈에 따라서 커피를 주문하고 매출을 올리는 코드를 짜주셨군요. 멋집니다!
그런데말이지요, 고객의 돈을 커피숍에서 알 수 있을까요?
차라리 `buyingCoffee(from coffeeShop: CoffeeShop, typeOfCoffee: CoffeeShop.Coffee )`쪽에서 price를 알게 하고, money가 price 이상일 때 `coffeeShop.orderCoffee(from: self, typeOfCoffee: typeOfCoffee)`를 호출하는게 합리적으로 보입니다.

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +let yagombucksMenu: [CoffeeShop.Coffee: Int] = [.iceAmericano: 4000, .caffeMocha: 7000, .brewCoffee: 8000]
`yagombucksMenu`가 커피숍 밖에 있는 이유는 무엇일까요? 단순 질문입니다. 이유를 듣고 싶습니다!

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +misterLee.buyingCoffee(from: yagombucks, typeOfCoffee: .caffeMocha)
`misterLee`는 바리스타네요. 손님인 `missKim`이 주문을 할 수 있도록 해볼까요?

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    func buyingCoffee(from coffeeShop: CoffeeShop, typeOfCoffee: CoffeeShop.Coffee ) {
`CoffeeShop.Coffee`뒤에 공백 지워주시면 좋을 것 같습니다.

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +                makeCoffee(cofee: typeOfCoffee)
`cofee`는 오타겠지요?

2023-08-04 11:05 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    }
우리는 바리스타를 고용했습니다. 바리스타가 커피를 만들게 할 수 있을까요?

2023-08-05 07:41 UTC, ParkSY0919 commented on CodeStarterCamp_Week3/main.swift
> +    }
주의하겠습니다!

2023-08-05 07:42 UTC, ParkSY0919 commented on CodeStarterCamp_Week3/main.swift
> +    var typeOfBeans: String // 원두종류
커피숍에서 사용한다고 생각하여 이렇게 표시하였었나 봐요! 주의하겠습니다!

2023-08-05 07:43 UTC, ParkSY0919 commented on CodeStarterCamp_Week3/main.swift
> +    var menu: Dictionary<Coffee, Int>
축약형으로 다시 습관을 들이겠습니다!

2023-08-06 04:54 UTC, ParkSY0919 commented on CodeStarterCamp_Week3/main.swift
> +                makeCoffee(cofee: typeOfCoffee)
넵! 수정하였습니다!

2023-08-08 00:24 UTC, ParkSY0919 commented on CodeStarterCamp_Week3/main.swift
> +let yagombucksMenu: [CoffeeShop.Coffee: Int] = [.iceAmericano: 4000, .caffeMocha: 7000, .brewCoffee: 8000]
상수로 yagombucks의 Menu를 한 번에 집어 넣고자 하였는데 야곰님의 세션을 돌이켜보니 밖에서 설정하는 것을 지양하라고 하셨던게 다시금 떠올랐습니다.
추후 CoffeeShop 안에서 설정할 수 있도록 하겠습니다.

2023-08-09 00:33 UTC, ParkSY0919 commented on CodeStarterCamp_Week3/main.swift
> +    }
적용하여보겠습니다!

2023-08-09 00:39 UTC, ParkSY0919 commented on CodeStarterCamp_Week3/main.swift
> +        self.pickUpTable = []
주문이후 만들어진 음료만을 해당 배열에 담아야 하는데 기본 값이 지정되어있다면 pickUPTable로써의 의미가 퇴색된다고 생각했습니다.

2023-08-09 00:40 UTC, ParkSY0919 commented on CodeStarterCamp_Week3/main.swift
> +let yagombucksMenu: [CoffeeShop.Coffee: Int] = [.iceAmericano: 4000, .caffeMocha: 7000, .brewCoffee: 8000]
시간이 없어 이는 적용하지 못하고 commit 드렸어요.. 죄송합니다 ㅠㅠ

2023-08-09 05:08 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    }
이런식으로 적용해봤다면 좋을 것 같습니다:
```swift
func purchaseCoffee(from coffeeShop: CoffeeShop, typeOfCoffee: CoffeeShop.Coffee) {
    if let price = coffeeShop.menu[typeOfCoffee] {
        if money >= price {
            money -= price
            coffeeShop.orderCoffee(from: self, typeOfCoffee: typeOfCoffee)
        } else {
            let shortage = price - money
            print("잔액이 \(shortage)원만큼 부족합니다.")
        }
    }
}
```

불필요한 코드 제거하고, 네이밍 적절하게 바꾼 후 보여드립니다.
돈이 부족한 것에 대해서도 표시하라고 되어있네요.

2023-08-10 09:38 UTC, Rhode-park commented
리뷰 반영해주신 것 멋집니다!
그러나, 몇 가지 아쉬운 점이 있어서 한 번 더 말씀드립니다..


1️⃣ CoffeeShop의 프로퍼티
아직도 커피숍이 당도와 원두종류를 알고 있네요?
```swift
class CoffeeShop {
    var sugarContent: Int // 당도
    var typeOfBeans: String // 원두종류
```
이 부분 빠지면 좋을 것 같습니다

2️⃣ `self`의 활용
`self`는 어떨 때 사용할까요?
여기에서 `self`가 붙어야 할 상황은 어느상황들인가요?
```swift
func purchaseCoffee(from coffeeShop: CoffeeShop, typeOfCoffee: CoffeeShop.Coffee) {
    let strTypeOfCoffee = typeOfCoffee
    if let typeOfCoffee = coffeeShop.menu[typeOfCoffee] {
        if self.money >= typeOfCoffee {
            self.money -= typeOfCoffee
            coffeeShop.orderCoffee(from: self, typeOfCoffee: strTypeOfCoffee)
        } else {
            let shortage = typeOfCoffee - self.money
                        print("잔액이 \(shortage)원만큼 부족합니다.")
        }
    }
}
```
`self`를 모두 붙이는 것이 Manito님의 컨벤션이라면 괜찮지만, `orderCoffee`쪽에서는 또 `self`들이 없습니다.
통일을 해주었으면 좋겠는데, `self`를 꼭 명시해줘야하는 상황이 아니라면 빼는 쪽으로 가는게 좋을 것 같습니다.

3️⃣ `money`차감 중복
`purchaseCoffee(from coffeeShop: CoffeeShop, typeOfCoffee: CoffeeShop.Coffee)`에서 이미 `money`를 차감해주고 있습니다.
그런데, `orderCoffee(from customer: Person, typeOfCoffee: Coffee)`쪽에서 한 번 더 차감해주고 있네요?
`missKim`이 10000원을 가지고 있다고 할 때, 카페모카를 주문한다면 `missKim`의 잔액은 얼마가 될까요?
일반적으로는 10000에서 7000원을 제한 3000원이 남아야겠죠?
그런데, print해보면 다음과 같이 나오네요?
```text
caffeMocha 결제가 완료되었습니다.
-4000
```
`orderCoffee(from customer: Person, typeOfCoffee: Coffee)`쪽에서 커피값을 차감해주는 코드는 빼줘야하지 않을까요?


이 부분 반영해주신 후에 DM주시면 바로 머지해드리겠습니다!!

2023-09-06 03:50 UTC, closed without merging