Week3 [STEP 2] knumber2
yagom-academy/swift-starter-week3 pull request #250
Opened 2023-08-07 05:31 UTC by cognd98

@Rhode-park 

### 고민했던 점

- 옵셔널을 안전하게 추출하기 위해 guard let 구문을 사용하였습니다.

2023-08-08 06:20 UTC, Rhode-park requested changes
PR 잘 받았습니다!
어느새 WEEK3 STEP2이군요.
많은 부분을 멋지게 해내주셨습니다.
코드는 실생활을 반영하는게 좋습니다.
각각의 프로퍼티나 매개변수들이 어디에 위치해야할지 조금 더 고민해보셨으면 좋겠습니다.
더불어 enum에 대해서 조금 더 공부해보셔도 좋을 것 같습니다.
조금만 더 화이팅해봅시다!

2023-08-08 06:20 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
>  enum Coffee {
혹시 rawValue에서 들어보셨을까요?
현재 다음과 같이 결과가 출력됩니다:
```text
missKim 님이 주문하신 americano(이/가) 준비되었습니다. 픽업대에서 가져가 주세요.
````
rawValue라는 것을 사용해보면 다음과 같이 출력할 수도 있을 것 같습니다:
```text
missKim 님이 주문하신 카푸치노(이/가) 준비되었습니다. 픽업대에서 가져가주세요.
```

rawValue에 대해서 공부해보시고 다음에 대한 답을 댓글로 설명해주시길 바랍니다.
* rawValue는 어떤 친구인가요?
* rawValue로는 무엇무엇이 올 수 있나요?
* rawValue의 기본값에 대해서 아시나요?

2023-08-08 06:20 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    }
`money`를 외부에서 주입받고 있군요. 멋집니다! LGTM!

2023-08-08 06:20 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +    func order(_ coffee: Coffee, coffeeShop: CoffeeShop, name: String) {
`name`을 매개변수로 외부에서 받아오는 것은 적절하지 않아보입니다.
현실적으로 `Person`이 `money`를 갖고 있는 것처럼 `name`을 가지고 있고, 이니셜라이저를 통해 주입받는게 더 실생활에 맞는 코드인 것 같습니다.

2023-08-08 06:20 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +        guard let price = coffeeShop.menu[coffee] else { return print("상품이 존재하지 않습니다.") }
일반적으로는 다음과 같이 작성하는 것 같습니다:
```suggestion
        guard let price = coffeeShop.menu[coffee] else {
            print("상품이 존재하지 않습니다.")
            return
        }
```
* print문보다 return이 아래에 위치할 수 있게
* 두 단어 이상일 때는 개행을 하게

이렇게 작성하는게 일반적으로 보입니다.

2023-08-08 06:20 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +            coffeeShop.sales += price
`coffeeShop`의 `sales`를 `Person`이 알아야할까요?
이 메서드에서 매출을 올려주는 것은 적절하지 않아보입니다.
그러면, 어디에서 매출을 올려주어야할까요?

2023-08-08 06:20 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
>      }
메서드 내에서 `barista`를 사용하는 부분이 없습니다.
그렇다면 왜 매개변수로 받아오시는 것입니까?

2023-08-09 04:17 UTC, cognd98 commented on CodeStarterCamp_Week3/main.swift
>  enum Coffee {
rawValue는 케이스별로 고유한 값을 지정해주고 싶을 때 사용합니다.
rawValue에는 Int, String 등이 올 수 있습니다.
Int의 경우 기본값은 첫번째 케이스부터 0, 1, 2...이며, String의 경우 케이스 이름이 문자열이 기본값이 됩니다.

2023-08-09 04:18 UTC, cognd98 commented on CodeStarterCamp_Week3/main.swift
> +    func order(_ coffee: Coffee, coffeeShop: CoffeeShop, name: String) {
수정하겠습니다.

2023-08-09 04:56 UTC, Rhode-park commented on CodeStarterCamp_Week3/main.swift
> +            coffeeShop.sales += price
`sales`에 대한 코드는 `make(_ coffee: Coffee, name: String)`쪽에 들어가는게 좋지 않을까요?
가령 이런 식으로요:
`order`메서드에서는 `sales`에 대한 내용을 빼고
```swift
func order(_ coffee: Coffee, coffeeShop: CoffeeShop) {
    guard let price = coffeeShop.menu[coffee] else {
        print("상품이 존재하지 않습니다.")
        return
    }
    if money >= price {
        coffeeShop.make(coffee, name: name)
        money = money - price
    }else {
        print("\(price - money)원만큼 잔액이 부족합니다.")
    }
}
```

`make`메서드에서 `sales`를 다루주고
```swift
func make(_ coffee: Coffee, name: String) {
    guard let price = menu[coffee] else {
        return
    }
    sales += price
    pickUpTable.append(coffee)
    print("\(name) 님이 주문하신 \(coffee.rawValue)(이/가) 준비되었습니다. 픽업대에서 가져가 주세요.")
}
```

guard let 구문이 두 번 들어가더라도, 이런 방향성이 좀 더 적합하지 않을까 싶습니다.

2023-08-09 05:13 UTC, cognd98 commented on CodeStarterCamp_Week3/main.swift
> +            coffeeShop.sales += price
넵 수정하였습니다.

2023-08-09 05:49 UTC, Rhode-park commented
수고하셨습니다!!! 다음 STEP에서 뵙겠습니다!

2023-08-09 05:50 UTC, merged