Week3 [STEP 1] 아담
yagom-academy/swift-starter-week3 pull request #253
Opened 2023-08-07 17:51 UTC by yawoong2

@Tediousday93 
안녕하세요 로웬!
요구사항을 잘 이해했는지 모르겠지만, 얼렁뚱땅 작성하였습니다! 🙌

 ## 고민했던 점
 ### 요구사항에 있는 문장을 그대로 받아들이기
 - 최대한 요구사항에 있는 문장의 내용에 벗어나지 않으려 했습니다.

 ---

 ## 조언을 얻고 싶은 부분
 ### 클래스와 구조체
 - 클래스와 구조체의 차이에 대해서는 LMS에서의 설명을 통해 학습했지만, 막상 둘 중 하나를 선택하여 선언할 때에 망설여졌습니다.
 - 상황에따라 클래스를 선언하기도, 구조체를 선언하기도 하는데 로웬의 경우에는 주로 어떤 기준을 먼저 고려하시나요?
 ```

2023-08-07 23:36 UTC, Tediousday93 requested changes
안녕하세요 아담님 👋
벌써 4주차군요!! 마지막까지 힘내서 달려봅시다!!
이번 스텝 학습 내용이 어렵더라도 최대한 이해해보려고 노력해주시면 좋겠습니다. 💪💪💪

이번엔 수정해야할 부분이 꽤나 있네요..🤔
시간이 너무 오래걸리시거나 어려운 부분은 언제든 DM으로 질문해주세요!

아래 코드에서도 코멘트를 확인해주시고, 수정이 완료되시면 디스코드로 머지 의사를 알려주세요 ☺️

PR 제목 수정 부탁드립니다! **Week3**

</br>

---

### 수행한 점

* [x] 정확한 브랜치에 PR 보내기
* [ ] PR의 제목/내용을 양식에 맞게 보내기
* [x] 학습 도우미 태그하기

---

- [ ] 요구조건에 맞게 타입 정의 / 생성하기
- [x] 정의한 타입의 인스턴스 생성하기
- [x] 생성한 인스턴스의 프로퍼티 / 메서드 활용하기

---

</br>

### ✅ 고민했던 점
* Coffee 타입을 원시값이 있는 enum으로 잘 만들어주셨습니다만 활용하지 않으셔서 아쉽네요 🥲
* Coffee 열거형 활용 조건을 놓치신 것 같습니다.
* CoffeeShop 타입의 요구 사항을 잘 지켜주셨습니다 👍

</br>

### ✅ 조언을 얻고 싶은 부분
클래스와 구조체의 가장 큰 차이점은 "참조 타입(reference type)"과 "값 타입(value type)"이라는 점이죠!

아직은 어떤 상황에 선택해야할지 감이 잘 오지 않을 수 있습니다🤔
결정 방법에 대한 내용이 애플 공식문서에 있어 링크 남겨드립니다.
여유있을 때 참고해보세요!
[Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)

저는 위 글의 내용 중 **Use Classes When You Need to Control Identity**를 중요한 기준으로 생각하고 있답니다 👀

</br>

### ✅ 추가 학습내용
이번에 클래스(class)와 구조체(struct)에 대해 학습하셨을 텐데요! 한 번에 와닿지 않는 내용이지만 중요하답니다. 🤔

클래스와 구조체에 대한 내용은 [애플 공식문서 - Structures and Classes](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/classesandstructures/)에서 자세히 알아볼 수 있으니 기회가 되신다면 학습해보시는 것을 추천드립니다 👍

2023-08-07 23:36 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +}
Person 타입을 잘 만들어 주셨습니다 👍
내부 기능은 구현해주지 않으셨는데, 현재 스텝에서는 기능이 필요하진 않네요!
그래도 money를 커피값 만큼 차감하는 기능은 넣어볼까요? 😁

2023-08-07 23:36 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +    }
열거형의 원시값을 잘 활용해주셨습니다 👍

* 원시값을 타입만 알려주고 아무것도 작성하지 않으면 어떻게 동작하는지 알고 계실까요? 👀
* 무슨 이유로 중첩 타입으로 정의해주셨을까요?
* 이번 스텝에서 원시값을 어떻게 활용해볼 수 있을까요?

코멘트에 답변 남겨주세요!

2023-08-07 23:36 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +    var menu: [String: Int] = [:]
현재 메뉴에 아무것도 할당되어있지 않네요 🥲
메뉴의 key에는 `Coffee` 타입을 활용해보시면 좋겠습니다!

💡 menu에 key-value 쌍을 할당하는 메서드를 정의하셔도 좋고, class 이니셜라이저를 정의해보셔도 좋습니다

2023-08-07 23:36 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +    var barista: Person?
옵셔널 타입으로 정의하신 이유가 있을까요?!

2023-08-07 23:36 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: [String] = []
Coffee를 담을 수 있어야한다는 조건에 맞게 타입을 수정해봅시다 👏

2023-08-07 23:36 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +    func getOrder(orderedCoffee: String) {
주문을 받는다는 의미는 일상에서도 활용하는 `takeOrder`가 어떨까요?!

파라미터의 이름도 Coffee의 이름이라는 것을 잘 나타내주면 좋겠습니다.
또한, 해당 타입에도 Coffee 타입을 활용해보면 좋겠죠? 💭

2023-08-07 23:36 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +yagombucks.barista = misterLee
요구조건에 맞게 인스턴스를 잘 생성해주셨습니다 👍
하지만 missKim이 빠져있군요..

2023-08-07 23:36 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +    func brewCoffee(to orderedCoffee: String) -> String {
이 부분에도 Coffee 열거형 타입을 활용하면 좋겠네요 !!

일반적으로 더 친숙한 단어를 네이밍에 사용하면 좋다고 합니다. (brew 부분인데 굳이 바꾸지 않으셔도 괜찮습니다)
또한 최대한 간결하게 이름을 정해야 좋습니다. ☺️
전달인자 레이블을 활용하는 것도 좋지만, 중복된 의미를 갖는 단어를 사용한 네이밍을 피하기 위해 
이렇게 바꿔볼 수 있을 것 같아요 🤔
```suggestion
    func brew(coffee: Coffee) -> String {
```

2023-08-10 14:01 UTC, yawoong2 commented on CodeStarterCamp_Week3/main.swift
> +}
money를 커피값 만큼 차감하는 기능을 코드 수정하면서 추가했습니다!

2023-08-10 14:08 UTC, yawoong2 commented on CodeStarterCamp_Week3/main.swift
> +    var menu: [String: Int] = [:]
Class 이니셜라이저를 통해 정의했습니다..!

2023-08-10 14:10 UTC, yawoong2 commented on CodeStarterCamp_Week3/main.swift
> +    var barista: Person?
class 이니셜라이저를 통해서 커피숍 인스턴스를 선언하면서 바리스타를 지정할 수 있다는 것을 숙지하지 못하고, 바리스타는 초기값이 지정되지 않아서 없을 수도 있다는 생각에 옵셔널 타입으로 정의하였습니다.
 하지만, 위 방법이 알맞은 것인지는 모르겠습니다.🥲

 현재는 이니셜라이저를 통해 바리스타 초기값을 지정하였습니다.

2023-08-10 14:12 UTC, yawoong2 commented on CodeStarterCamp_Week3/main.swift
> +    func brewCoffee(to orderedCoffee: String) -> String {
하나의 문장처럼 보이도록 한다는 것이 생각보다 어렵네요..😇
알려주셔서 감사합니다!

2023-08-10 14:21 UTC, yawoong2 commented on CodeStarterCamp_Week3/main.swift
> +    }
- 타입만 알려주게 된다면, 내부에 원시값은 존재하지 않습니다. 열거형 Coffee에 대한 선택지만 제공할 뿐, 값을 포함하는 것은 들어있지 않습니다.
- 세로로 case를 각각 선언하거나, 한줄로 선언해도 기능엔 차이가 없다고 생각했습니다!
- 원시값에 가격에 대한 원시값을 정해줄 수 있습니다!

2023-08-11 03:11 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +    func buyCoffee(coffeeShop: CoffeeShop, nameOfCoffee: Coffee) {
요 메서드에선 전달인자 레이블을 사용해봐도 좋을 것 같아요!
메서드 네이밍이 참 어렵죠 ..? ㅎㅎ  👀
```suggestion
    func buy(coffee: Coffee, at coffeeShop: CoffeeShop) {
```

2023-08-11 03:11 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
>      }
커피를 만들면 pickUpTable에 잘 할당해주셨네요 👍

2023-08-11 03:11 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucksMenu: [Coffee: Int] = [.americano: Coffee.americano.price, .espresso: Coffee.espresso.price, .cafeLatte: Coffee.cafeLatte.price, .vanilaLatte: Coffee.vanilaLatte.price]
한 줄에 코드가 너무 길 경우에는 줄바꿈해주는 컨벤션도 있답니다 !
```suggestion
var yagombucksMenu: [Coffee: Int] = [
    .americano: Coffee.americano.price, 
    .espresso: Coffee.espresso.price, 
    .cafeLatte: Coffee.cafeLatte.price, 
    .vanilaLatte: Coffee.vanilaLatte.price
]
```

2023-08-11 03:11 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +    }
연산 프로퍼티 활용 👍
익숙해지시면 편리하게 사용하실 수 있을거에요!!

2023-08-11 03:11 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +            print("돈이 부족하여 구입할 수 없습니다.")
돈이 부족할 경우까지 잘 처리해주셨네요 👏

2023-08-11 03:11 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +    }
String 타입의 열거형에 원시값을 할당하지 않게 되면 case의 이름이 그대로 나오게 됩니다!
Int일 경우 가장 위의 case를 0으로 시작하여 1씩 증가하는 원시값을 갖게 됩니다.

직접 실험해보시면 좋겠네요 👍

2023-08-11 03:13 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +    var barista: Person?
옵셔널 타입인 이유를 생각해주시면 좋겠습니다~~
옵셔널 타입은 초기값을 지정해주지 않고 (var일 경우) 나중에 프로퍼티에 접근해서 할당해도 괜찮습니다!

barista가 coffeeshop에 반드시 필요한지 아니면 없어도 괜찮은지에 따라 결정해주시면 좋을 것 같아요. 👀

2023-08-11 03:26 UTC, Tediousday93 reviewed
요구사항이 잘 반영되었네요 👍
다음 스텝 내용과 비슷하게 메서드를 작성해주셔서 좋습니다 ㅎㅎ

5주간 고생많으셨습니다!
앞으로도 원하시는 일 모두 성취하시길 바랍니다 🙏

2023-08-11 03:26 UTC, merged