Week3 [STEP 2] QL
yagom-academy/swift-starter-week3 pull request #257
Opened 2023-08-31 13:10 UTC by slowkuma

@Tediousday93
Round 3 의 Step 1 진행 결과 입니다.

## 고민했던 점
### Step 2 조건에 따라 기존 구현을 변경 할것인가? 
- 주어진 조건에 따라 기존 구현을 변경을 해야 할지 상속으로 구현 할지 생각을 좀 하였는데,
  이전에 진행된 내용을 남기기 위해서 상속으로 진행 하였습니다. 때문에 Class 이름이 조건과 어긋 나게 되었습니다.
  Class 이름까지 조건을 만족해야 한다고 말씀 해 주시면 이전 내용을 변경 하도록 하겠습니다.

---

## 해결이 되지 않은 점
- 없습니다.

---

## 조언을 얻고 싶은 부분
- 없습니다.

2023-09-01 11:47 UTC, Tediousday93 requested changes
안녕하세요 QL님 ☺️
step2 고생하셨습니다!

CoffeeShop 메서드에 예외처리를 정말 잘 해주셨습니다 👍
Result 타입을 활용하지 않았을 때는 어떻게 Error 프로토콜을 채택한 열거형을 활용하는지 간단히 알아보셔도 좋겠습니다. 💭
(아마도 다음 주에 학습자료로 제공되는 내용일 겁니다 👀)

---

### 수행 내용

* [x] 정확한 브랜치에 PR 보내기
* [x] PR의 제목/내용을 양식에 맞게 보내기
* [x] 학습 도우미 태그하기

---

- [x] 요구된 타입의 인스턴스를 생성하기
- [x] 요구된 문구 출력하기
- [x] 객체 간 소통하기(missKim 돈 차감, yagombucks 매출 증가)

---

### ✅ 고민했던 점

미션이 step별로 진행되긴 하지만 남겨주신 커밋을 통해 이전 내용을 알 수 있으므로 프로젝트 파일을 step 별로 나눠주실 필요는 없을 듯 합니다 😙

상속을 통해 만들어주신 메서드는 기존 타입의 메서드를 수정 또는 추가 해주시면 좋겠네요!

2023-09-01 11:47 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Round3Step1/CoffeeShop.swift
> +    }
매출액을 증가시키는 기능을 분리해주셨군요 👍

2023-09-01 11:47 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Round3Step2/CoffeeShopStep2.swift
> +    }
요 부분에서 item을 가져오지 못했을 때 -1을 반환하는 의미를 직관적으로 알기 어려운 것 같습니다.
`Error`를 활용하면 잘 해결되겠네요!

Error 프로토콜을 채택한 열거형의 case는 `throws` 키워드가 있는 함수 / 메서드에서 반환값 대신 오류를 던져줄 수 있습니다.
던져진 오류를 처리하는 방법에는 do - catch문, Result타입 활용이 있습니다.
관련 내용은 차주 학습자료를 통해 학습하시면 좋겠습니다 👍 

```suggestion
    func getPrice(of coffee: Coffee) throws -> Int {
        guard let item = getMenuItem(of: coffee) else {
            throw OrderError.isNotInMenu
        }

        return item.price
    }
```

2023-09-01 11:47 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Round3Step2/CoffeeShopStep2.swift
> +        _ = saleMenuItem(of: item)
saleMenuItem 메서드에 `@discardableResult` attribute를 붙여주는 것도 좋겠네요!

이번 스텝에서는 pickUpNumber를 활용할 기능이 없지만,
주문한 사람이 pickUpTable에서 번호표에 맞는 커피를 가져가도록 하는 기능이 추가된다면 쓸모가 있을 거라고 생각합니다. 💭

2023-09-01 11:47 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Round3Step2/PersonStep2.swift
> +}
요구사항에 맞는 order 메서드를 잘 작성해주셨네요 👍

예외처리도 잘 해주셨습니다 👏👏👏

2023-09-04 10:39 UTC, slowkuma commented on CodeStarterCamp_Week3/Round3Step2/CoffeeShopStep2.swift
> +        _ = saleMenuItem(of: item)
적용 하였습니다.

2023-09-04 11:02 UTC, slowkuma commented on CodeStarterCamp_Week3/Round3Step2/CoffeeShopStep2.swift
> +    }
아직 누적 시간이 부족하여 다음 과정이 열리지 않아서 어떤 내용인지 확인 하지는 못하였습니다.
일단은 제가 아는 방법으로 구현 하였습니다.
말씀 대로 다음 프로젝트에서 지적 하실부분을 말씀 해 주시면 되겠습니다.

---

throws 로 Error 를 반환 한다고 선언 하면
catch 쪽에서 해당 프로젝트 또는 모듈에서 사용 가능한 모든 Error 가 대상이 되어서
부분적으로만 처리를 하고 싶을때에는 약간은 귀찮은 부분이 생겨 나서 조금은 머뭇 거리게 됩니다.
물론 발생할 수 있는 모든 Error 가 나오게 됨으로 종류별로 각각 후처리가 필요한 경우에는 사용 합니다.

저는 method 에서 Error 를 단한가지만 발생 하는것이 아니거나
명시적으로 후처리가 필요한경우 가능한 Result 로 처리 하고 있긴 합니다.

이 경우 반환 하는 내용은 음수 로는 "없다" 를 뜻하고
0 을 포함한 양수 는 "있다" 라는 내용으로서 예외 처리는 1개의 경우라 이렇게 표현 하였습니다.

만약 음수값에 대한 처리가 알아보기 어렵다면 Error 보다는 아래처럼 optional 로 바꾸어도 될꺼라 생각 합니다.
```swift
func getPrice(of coffee: Coffee) -> Int? {
  // 해당하는 메뉴가 없으면 nil
  // 있다면 가격 반환
}
```

2023-09-04 11:03 UTC, slowkuma commented
@Tediousday93
지적 해 주신 내용을 적용하였으니 확인 부탁 드립니다.

2023-09-04 12:45 UTC, Tediousday93 commented on CodeStarterCamp_Week3/Round3Step2/CoffeeShopStep2.swift
> +    }
메뉴가 없을 때 nil을 반환해주는 편이 더 좋긴 하겠네요!! 👍

2023-09-04 13:04 UTC, slowkuma commented
@Tediousday93
CoffeeShop.getPrice(of:) 를 optional 로 변경 하였습니다.
확인 부탁 드립니다.

2023-09-04 13:05 UTC, slowkuma commented on CodeStarterCamp_Week3/Round3Step2/CoffeeShopStep2.swift
> +    }
적용 하였습니다.

2023-09-04 13:32 UTC, Tediousday93 commented
고생하셨습니다 👍
오류처리에 집중하다보니 PropertyObserver에 대한 내용이 빠져버렸네요..

요구조건 중, 
* pickUpTable에 커피가 올려지면 다음과 같은 문구가 출력됩니다.

이를 만족하기 위해 함수의 반환값을 활용하는 방법도 있지만
pickUpTable 자체에 didSet 프로퍼티 감시자를 활용하여 해결할 수도 있습니다!
따로 String을 반환하지 않더라도 didSet에서 손님의 이름과 어떤 커피가 올려졌는지만 알 수 있다면 쉽게 출력이 가능하겠죠?!
```swift
var customer: Person?
var pickUpTable = [Coffee]() {
    didSet {
        guard let customerName = customer?.name,
              let coffee = pickUpTable.last
        else { return }
        var message = "\(customerName)님이 주문하신 \(coffee) (이/가) 준비되었습니다. 픽업대에서 가져가주세요."
        print(message)
        customer = nil
        pickUpTable.removeAll()
    }
}
```

print 함수를 마지막에 한 번만 호출하려는 흐름을 유지하고 계시기 때문에 약간은 흐름이 달라서 적용해달라 말씀드리기가 어렵네요 ㅎㅎ
추후 프로퍼티 감시자를 활용해보실 기회가 있다면 좋겠습니다 💭

머지하도록 하겠습니다 !

2023-09-04 13:34 UTC, merged