Week 3 [STEP 1] Grumpy
yagom-academy/swift-starter-week3 pull request #26
Opened 2021-12-30 16:51 UTC by sewoongpark

@joey-ful 
반갑습니다 Joey! 연말 잘 보내고 계신가요~ 조금 늦었지만 Week 3 미션 PR합니다💪

고민했던 점
* 메뉴판의 구현
카페마다 메뉴에 따른 가격이 다르기 때문에 이들을 CoffeeShop에서 매개변수로 Coffee를 전달받아 가격을 알려주는 함수를 새로 만들었습니다. 메뉴명도 각각 다르게 설정하고 싶은데 입력할 값이 너무 많아질 것 같네요

확실히 난이도가 점점 올라가는 것 같네요. 지금까지 학습한 내용을 복합적으로 사용해야 하는 것도 느껴지네요.
피드백 기다릴게요! 감사합니다~

2021-12-31 02:17 UTC, joey-ful requested changes
@sewoongpark 

요구사항대로 잘 구현하셨습니다 👍
많이 고민하신 흔적이 보이는 코드였어요!!
구매 메서드, pickUpTable, customer를 받는 점, 가격을 어디에 정의할지를 염두에 두신 부분과 커피 이름이 달라질 수 있다는 점 등등
프로그램이 어느 방향으로 확장될지 모르기 때문에 grumpy님처럼 다양한 경우를 고려하시는 점이 정말정말 좋다고 생각합니다! 👍 👍 👍
코드가 에러때문에 빌드되지 않아 수정 요청드렸어요!

2021-12-31 02:17 UTC, joey-ful commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +    }
가격과 마찬가지로 커피 이름이 커피숍마다 다르다면 이렇게 하시는 것이 좋아보입니다!

2021-12-31 02:17 UTC, joey-ful commented on CodeStarterCamp_Week3/Stuff/Coffee.swift
> +}
커피 열거형 좋습니다 👍

2021-12-31 02:17 UTC, joey-ful commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(revenue: 0, barista: misterLee)
요구사항대로 잘 구현하셨습니다 👍

2021-12-31 10:39 UTC, sewoongpark commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +    var barista: Person
> 매출액은 커피숍을 생성할 때 입력하는건가보군요. 0이 아닌 값으로 시작할 수도 있는걸까요

이 부분은 생각을 못했었네요..ㅎㅎㅎ 일 매출액이라 생각하고 인스턴스 생성 시 0으로 초기화하도록 변경하였습니다!

2021-12-31 10:42 UTC, sewoongpark commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +        }
> 메뉴판을 프로퍼티가 아닌 메서드로 구현하신 이유가 궁금합니다

이 방법도 고민했던 내용인데, 구조체 생성 시 프로퍼티 초기화를 하기 위해 너무 많은 값이 필요한 것 같아 메서드로 구현했습니다ㅋㅋ 만약 yagombucks 뿐만 아니라 여러 카페 인스턴스가 존재한다면 카페마다 다른 메뉴판을 제공한다는 점에서 볼 때 딕셔너리 프로퍼티로 변경하는 것이 좋을 지도 모르겠네요!

> return을 함수명에 잘 사용하지 않는다고 들었는데 관련 컨벤션을 못 찾겠네요 🤔 혹시 return을 써도 된다 쓰면 안된다 등의 관련 내용을 찾으면 공유하겠습니다

좋은 지적 감사합니다. 함수명에 속성을 가져오는 경우 흔히 사용하는 동사는 return이 아니라 get인데, 알려주신 대로 단순히 어떤 속성이나 값을 리턴하는 경우 get을 사용하지 않고 명사형으로 이름을 짓는다고 하는군요🤭 
각각 ```coffeeName``` ```coffeePrice``` 로 변경했습니다~

2021-12-31 10:44 UTC, sewoongpark commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +        self.pickUpTable.updateValue(coffee.name, forKey: customer.name)
헉 😱
졸린 상태였는지 미완성 코드를... 이 부분은 enum 타입에서 name을 갖도록 코드를 짰다가 커피 가격과 이름을 CoffeeShop의 메서드로 변경하면서 빠졌어야 하는 코드인데 미처 확인하지 못했네요 ㅠㅠㅠ 수정하겠습니다!

2021-12-31 10:48 UTC, sewoongpark commented on CodeStarterCamp_Week3/Person/Person.swift
> +    }
> 그리고 20번줄처럼 money 프로퍼티 앞에 self가 없어도 Swift가 프로퍼티를 잘 인식하는 것을 확인하실 수 있어요! self를 꼭 붙여야 하는 상황도 존재하는데 지금처럼 필요없다면 보통 사용하지 않는 것으로 알고 있습니다! 참고하실만한 컨벤션을 첨부드려볼게요 raywenderlich style guide
self를 사용하시더라도 일관적으로 모든 곳에 사용하시는 것이 좋을 것 같습니다 😁

이 부분은 아직 익숙하지 않은 부분이라 많이 헷갈리네요.. 
항상 함수 안에서 새로운 변수에 선언하거나, 매개 변수로 전달받지 않았다면 인스턴스의 프로퍼티에 접근할 때 ```self```를 꼭 붙여서 사용했는데.... 링크해주신 문서 읽어보겠습니다! 감사해요!

2021-12-31 10:49 UTC, sewoongpark commented
@joey-ful 

실수로 미완성인 코드를 PR 했네요 죄송해요 ㅠㅠㅠ 피드백 꼼꼼히 읽어보고 소스코드 조금 수정해서 다시 올립니다!

2022-01-02 03:51 UTC, joey-ful approved these changes
@sewoongpark 

수고 많으셨습니다! 👍 👍 👍 👍
잘 작동하네요!
다음 스텝에서 봬요! 😁

2022-01-02 03:51 UTC, joey-ful commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +        pickUpTable.updateValue(_: productName, forKey: customer.name)
커피 이름을 productName 변수에 담아주셨군요! 👍
이걸 18번 줄에서도 활용할 수 있을 것 같아요!

2022-01-02 03:52 UTC, merged