Week3 [STEP 2] Say
yagom-academy/swift-starter-week3 pull request #269
Opened 2023-09-12 08:48 UTC by SAY-Hong

@Tediousday93 
안녕하세요 로웬🫠 step2 PR입니다!

step1에 작성했던 코드를 수정해야되니까
파일로 step1, step2 나눠서 각각 저장했습니다 \^0^/ (Xcode에서 step1의 흔적을 지우고 싶지 않았어요ㅎㅎ...)
(🧐혹시 상속을 사용해서 클래스를 새롭게 만들었어야했을까요??)

## 코드 작성 시 고민했었던 부분
딕셔너리의 값이 필요할 때 등.. 옵셔널을 써야하는 부분 때문에 살짝 당황하긴 했지만 안전하게 추출하도록 작성했습니다.

2023-09-12 11:53 UTC, Tediousday93 requested changes
안녕하세요 세이님 ☺️
step2 고생하셨습니다!

따로 파일만 분리해서 수정하셔도 좋습니다. (상속은 기능적으로 꼭 필요할 때 써주시는게 좋습니다.💭)
어차피 레포지토리에 커밋 이력이 남기 때문에 이전 버전으로 돌아가서 확인할 수 있거든요!

현재 프로젝트를 보니 target membership 설정으로 step1 파일을 컴파일/빌드 시 포함시키지 않도록 해주셔서 지금도 나쁘진 않은 것 같습니다.

다만 유의하실 점은 PR에서 보면 같은 코드가 2번 나오는 것처럼 보일 수 있다는 점입니다. 유의해주세요!

---

### 수행 내용

* [x] 정확한 브랜치에 PR 보내기
* [x] PR의 제목/내용을 양식에 맞게 보내기
* [x] 학습 도우미 태그하기

---

- [x] 요구된 타입의 인스턴스를 생성하기
- [x] 요구된 문구 출력하기
- [ ] 객체 간 소통하기(missKim 돈 차감, yagombucks 매출 증가)

---

### ✅ 고민했던 점
* 옵셔널바인딩 잘 해주셨습니다 👍
* 요구사항 중 person 인스턴스의 money 차감이 빠진 것 같아요 👀

2023-09-12 11:53 UTC, Tediousday93 commented on CodeStarterCamp_Week3/main.swift
> +missKim.order(_ : .cafeLatte, of: yagombuks, by: missKim.name)
order 메서드를 정의할 때, 파라미터에 wildcard를 사용하셨다면 앞을 아예 생략할 수 있습니다!
네이밍 잘해주셨네요 👍
```suggestion
missKim.order(.americano, of: yagombuks, by: missKim.name)
Coda.order(.cappuccino, of: yagombuks, by: Coda.name)
missKim.order(.cafeLatte, of: yagombuks, by: missKim.name)
```

2023-09-12 11:53 UTC, Tediousday93 commented on CodeStarterCamp_Week3/step2.swift
> +                coffeeShop.sales += price
이렇게 보면 주문한 사람이 커피숍의 매출을 올려주고 있는 것처럼 보이네요.
커피숍에서 커피를 만들 때 같이 sales가 올라가도록 수정해봅시다 👍

여기에서 person의 money를 감소시켜주면 좋겠네요.

2023-09-12 11:53 UTC, Tediousday93 commented on CodeStarterCamp_Week3/step2.swift
> +            }
요구사항에 맞게 잘 구현해주셨네요 👍

2023-09-12 11:53 UTC, Tediousday93 commented on CodeStarterCamp_Week3/step2.swift
> +            else {
if-else 문 컨벤션은 보통 이렇습니다 👀
```suggestion
            if money < price {
                print("잔액이 \(price - money)원 만큼 부족합니다. ")
            } else {
```

2023-09-12 11:53 UTC, Tediousday93 commented on CodeStarterCamp_Week3/step2.swift
> +    func order(_ coffee: Coffee, of coffeeShop: CoffeeShop, by name: String) {
name 을 파라미터로 받을 필요가 있을까요? 💭

메서드를 호출하는 인스턴스의 프로퍼티로 name이 있으니 내부에서
`self.name`으로 접근하여 전달해줄 수 있습니다.

2023-09-12 11:53 UTC, Tediousday93 commented on CodeStarterCamp_Week3/step2.swift
> +    }
사용되지 않는 메서드는 지워도 될 것 같아요 🤔
만약 사용하신면 여기에서 sales를 증가시켜주고, 이후에 make 메서드를 호출해도 좋습니다.

2023-09-12 11:53 UTC, Tediousday93 commented on CodeStarterCamp_Week3/step2.swift
> +    }
프로퍼티 옵저버에 대해 학습하셨던 내용을 활용해볼 수 있겠네요!

make는 커피를 만들어서 pickUpTable에 전달만 하고 프로퍼티 옵저버를 통해 pickUpTable이 변경되었을 때 알아서 print문이 호출되도록 수정해볼까요?

2023-09-12 11:53 UTC, Tediousday93 commented on CodeStarterCamp_Week3/step2.swift
> +    var pickUpTable: [String]
pickUpTable에서 프로퍼티 옵저버를 활용해봅시다!
name을 출력하기 위해서 배열의 element를 튜플(tuple) 타입으로 설정해줄 수도 있습니다. 👍
(Coffee 타입 활용해주세요💭)

2023-09-12 11:53 UTC, Tediousday93 commented on CodeStarterCamp_Week3/step2.swift
> +    init(sales: Int, barista: Person, menu: [Coffee: Int], pickUpTable: [String]) {
pickUpTable의 경우 초기값을 빈 배열로 할당해두셔도 좋을 것 같습니다. 🤔
(주문이 없는데도 커피가 올려져있을 경우가 없다면말이죠 💭)
```suggestion
    var pickUpTable: [Coffee] = []
    
    init(sales: Int, barista: Person, menu: [Coffee: Int]) {
```

2023-09-14 02:40 UTC, SAY-Hong commented
@Tediousday93 
안녕하세요 로웬! PR 보낼 수 있는 마지막 날이네요🫢
지금 다른 부트캠프를 시작한게 있어서 ROUND4의 PR 피드백을 받을 수 없는게 슬프네요🥺

##고민한 점
일단, pickUpTable을 그냥 make함수 안에 집어넣었습니다.
어차피 픽업대에 올라올 수 있는 음료는 주문을 받아서 만든 메뉴만 올라갈 수 있으니까,  make 함수 안에 집어넣기는 했는데 확신이 없네요..

수정 사항 알려주시면 또 수정하겠습니다🤓

2023-09-14 07:36 UTC, Tediousday93 requested changes
마지막 PR이 되겠군요 🥲
미션 요구사항에 맞지 않는 부분이 있기 때문에
pickUpTable 부분 코멘트 확인하셔서 수정해주시면 머지하도록 하겠습니다!

2023-09-14 07:36 UTC, Tediousday93 commented on CodeStarterCamp_Week3/step2.swift
> +            }
didSet을 잘 활용해주셨네요!
하지만 pickUpTable을 CoffeeShop이 프로퍼티로 갖게 하라는 요구사항이 지켜지지 않게 되었어요. 🥲

프로퍼티로 선언했을 때 손님의 이름을 받기 어렵다고 느끼셨다면 pickUpTable의 타입을 아래와 같이 튜플을 활용해 전달해줄 수 있습니다.💭
또는 방금 주문한 손님의 이름을 프로퍼티로 추가해서 해결할 수도 있겠네요. 🤔

```suggestion
var pickUpTable: [(menu: Coffee, name: String)] = [] {
    didSet {
        let order = pickUpTable.removeFirst()
        print("\(order.name)님이 주문하신 \(order.menu.rawValue)(이/가) 준비되었습니다. 픽업대에서 가져가주세요.")
    }
}
```

2023-09-14 07:36 UTC, Tediousday93 commented on CodeStarterCamp_Week3/step2.swift
> +                money = price - money
손님이 결제를 하게 되었군요 👍
struct 여도 괜찮을 것 같은데 mutating 키워드 때문에 class로 바꾸신건가요? ㅎㅎ

2023-09-14 08:51 UTC, SAY-Hong commented on CodeStarterCamp_Week3/step2.swift
> +                money = price - money
mutating 키워드를 까먹고 있었네요..! 괜히 class로 바꾼..😂

2023-09-14 08:53 UTC, SAY-Hong commented
@Tediousday93 수정 완료했습니다✍️

2023-09-14 09:00 UTC, Tediousday93 commented
마지막까지 열심히 진행해주셨어요 👍
함께 학습한 5주가 유익한 시간이 되셨다면 좋겠네요 😊
앞으로도 좋은 일만 있으시길 빕니다 🙏

고생 많으셨습니다!

2023-09-14 09:00 UTC, merged