Week3 [STEP 1] 김마루
yagom-academy/swift-starter-week3 pull request #275
Opened 2023-10-22 08:55 UTC by marukim365

안녕하세요, 두두!(@FirstDo )
김마루 입니다.

Week3 STEP 1 - 타입과 인스턴스의 관계
완료하여 PR 보냅니다!

🤔 어려웠던 점
----------
1. 언제 Struct와 Class를 사용해야 할지 아직 잘 모르겠습니다.
둘의 차이점이 값 타입과 참조 타입, 상속 가능 여부, deinit 가능 여부... 등이 있다고 공부는 했는데,
실제 코드에서 어떤 타입을 사용하는게 적절한 것인지 아직 감이 잘 안옵니다.

2. 각 타입 안에서 메소드를 만들었는데(Pesron이 커피를 구매하거나, CoffeShop에서 주문을 받고 커피를 만들거나 등)
제가 요구사항에 맞게 메소드를 만든 것인지 모르겠습니다...
그냥 Print 함수만 넣어봤는데...😅

이상입니다.

확실히 Week3에서 타입에 대한 개념이 들어가니까... 
뭔가 새로운 기능이 많아지고, 복잡하고 어려워지는 느낌이네요! 😂

그리고 commit을 작게작게 하려고 했으나.. 뭔가 타입들이 서로 연관이 되다 보니까
한 번에 코드를 다 작성하게 되었습니다. 참고 바랍니다!

PR 확인 부탁 드립니다!
감사합니다 :)

2023-10-22 09:55 UTC, FirstDo requested changes
안녕하세요 @marukim365 마루님!
오랜만의 PR이라 반가웠습니다 ㅎㅎ

## 🤔 어려웠던 점

1. 언제 Struct와 Class를 사용해야 할지 아직 잘 모르겠습니다.
둘의 차이점이 값 타입과 참조 타입, 상속 가능 여부, deinit 가능 여부... 등이 있다고 공부는 했는데,
실제 코드에서 어떤 타입을 사용하는게 적절한 것인지 아직 감이 잘 안옵니다.

여러가지 차이가 있지만, 이번스텝에서는 값 타입인지, 참조 타입인지가 가장 중요할 것 같습니다
객체가 복사가 되어도 괜찮은지, 아니면 동일성을 유지해야 되는지를 잘 생각해보시면 될것같아요.
구조체도 `inout paramter` 사용하면 값을 바꿀 순 있긴 합니다

우선 구조체로 만들고 필요하다면 클래스로 바꾸는것도 좋은 방법입니다 (반대는 x)

2. 각 타입 안에서 메소드를 만들었는데(Pesron이 커피를 구매하거나, CoffeShop에서 주문을 받고 커피를 만들거나 등)
제가 요구사항에 맞게 메소드를 만든 것인지 모르겠습니다...
그냥 Print 함수만 넣어봤는데...😅

잘 만드셨고 다음 스텝이 기대됩니다!!

3. 그리고 commit을 작게작게 하려고 했으나.. 뭔가 타입들이 서로 연관이 되다 보니까
한 번에 코드를 다 작성하게 되었습니다. 참고 바랍니다!

그래서 가장 작은 타입부터 만드는게 중요합니다
우선 Coffee 를 만들고, 
Person을 만들고
근데 Person이 CoffeeShop 객체를 필요로 한다면, 그냥 틀만 만들어 놓고 끊어서 진행하는게 좋습니다

```swift
class CoffeeShop {
 // empty
}
```

2023-10-22 09:55 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +}
`Person` 타입을 구조체로 잘 만들어 주셨습니다!

2023-10-22 09:55 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +}
원시값(RawValue)를 사용해서 커피 이름을 정의하신건 좋습니다!
이런 방식의 문제는 `coffee.rawValue` 라는 뜻이 명확하지 않다는 것입니다

그래서 저는 아래 방식을 더 선호합니다.
추후 또다른 특성이 추가되더라도, 연산 프로퍼티 하나만 추가해 주면 되니까요

```swift
enum Coffee {
    case iceAmericano 
    case hotAmericano
    case cafeLatte
    case coldBrew
    case appleJuice
    case bananaJuice

    var name: String {
      switch self {
      case iceAmericano: return "Ice Americano"
      case hotAmericano: return "Hot Americano"
      case cafeLatte: return "Cafe Latte"
      case coldBrew: return "Cold Brew"
      case appleJuice: return "Apple Juice"
      case bananaJuice: return "Banana Juice"
      }
    }
}
```

2023-10-22 09:55 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +var yagombucksMenu: [Coffee: Int] = [.iceAmericano: 4500, .hotAmericano: 4200, .cafeLatte: 4600, .coldBrew: 4500, .appleJuice: 4000, .bananaJuice: 4000]
[Coffee: Int] 타입으로 메뉴판을 만든건 좋은것 같습니다!

생각하기 나름이긴 하지만, `가격` 또한 커피의 특성이라고 생각하면 `Coffee` 자체가 들고 있는것도 나쁘지 않을것 같네요

2023-10-22 09:55 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +class CoffeShop {
CoffeeShop 오타난것 같아요!
그리고 Person은 구조체, CoffeeShop은 클래스로 만든 이유가 있을까요?
본인만의 이유만 있으면 됩니다

2023-10-22 09:55 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +    lazy var pickUpTable: [String] = []
lazy var를 사용하신 이유가 궁금합니다.
그리고 puckUpTable의 타입은 커피를 담을 수 있어야 할것 같네요

2023-10-22 09:55 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +let missKim: Person = .init(name: "Kim", age: 28, money: 10000)
이 친구들도 다 start 매서드 안에서 만드는게 좋을것 같습니다
전역변수는 최대한 지양하는쪽으로요!

2023-10-24 07:12 UTC, marukim365 commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +}
좋은 방식
알려주셔서 감사합니다 :)

2023-10-24 07:14 UTC, marukim365 commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +var yagombucksMenu: [Coffee: Int] = [.iceAmericano: 4500, .hotAmericano: 4200, .cafeLatte: 4600, .coldBrew: 4500, .appleJuice: 4000, .bananaJuice: 4000]
이것도 위의 피드백처럼
`Coffee` 타입 안에 `price` 라는 변수를 만들어 `switch` 구문을 사용하는 방식 말씀하시는거죠!?

2023-10-24 07:17 UTC, marukim365 commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +class CoffeShop {
사실 이유는 없었습니다..ㅎㅎ
Person을 구조체로 만들어봤으니 CoffeeShop은 클래스로 만들어 봤던 것입니다..!

2023-10-24 07:22 UTC, marukim365 commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +    lazy var pickUpTable: [String] = []
먼저, 아직 pickUpTable이 무슨 기능을 하는 것인지 파악을 하지 못했습니다!
커피 제조가 완료되면 pickUpTable 에서 고객에게 완료가 되었다고 알람을 보내주는 기능이 맞을까요?

일단 저는 위에 처럼 pickUpTable 기능을 생각하고 있어서
makeCoffee 함수가 완료되고 나면 pickUpTable의 `지연 저장 프로퍼티`가 호출되면서 초기화되는...
그런 식으로 생각을 했어서 `lazy var`를 사용했었습니다!(물론 아직 코드에서 기능이 구현이 되지는 않았습니다만..!)

2023-10-24 07:23 UTC, marukim365 commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +let missKim: Person = .init(name: "Kim", age: 28, money: 10000)
아하!
사실 저번에도 전역변수는 최대한 지양하자고 피드백 주셨었는데, 저 전역변수들을 어떻게 할 지 고민하고 있었거든요!

start 함수에 넣어버리면 되는군요 👍

2023-10-24 09:06 UTC, FirstDo approved these changes

2023-10-24 09:06 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +//    var menu: [Coffee: Int]
menu는 있어야 할것 같네요.
기존에는 [Coffee: Int] 타입이었다면, 이제는 [Coffee] 타입으로 충분할 것 같습니다

2023-10-24 09:06 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP1_makeType.swift
> +    lazy var pickUpTable: [Coffee] = []
lazy var 지연초기화는 이럴때 사용하는것이 아니라

1. 해당 프로퍼티 초기화 과정에서 self or 다른프로퍼티에 접근해야할때

2. 해당 프로퍼티가 객체 초기화 시점에 초기화될 필요가 없을때 사용합니다
(프로퍼티가 너무 크다던가, 사용하지 않을수도 있다던가)

pickUpTable은 조제가 끝난 커피를 담는 완료된 주문 대기열 인것 같네요..!

2023-10-24 09:06 UTC, merged