Week3 [STEP 1] lucie
yagom-academy/swift-starter-week3 pull request #276
Opened 2023-10-24 06:37 UTC by lucidly-lucie

안녕하세요 @FirstDo ~! 3주차 첫번째 과제 제출합니다.

## 고민했던 점
- Person 생성 이후 money를 기본값으로 설정했다가, init를 사용하여 기본값이 없도록 구성하였습니다. 요구사항에는 없지만 buyCoffee 함수에서 받는 order 내용을 변수로 저장할까 고민하다가 아직까지는 특별한 사용 용도는 없는 것 같아 배제하였습니다.
- CoffeeShop을 생성하며, receivedOrer과 makeCoffee 함수 사이의 동작에 대해 고민하였습니다. receivedOrder에서 받은 주문을 makeCoffee로 넘겨줘야 할 것 같아 초반에는 아래와 같은 형태였습니다.
~~~
    mutating func receivedOrder(order: String) {
        makeCoffee(order: order)
        print("\(order) 메뉴의 주문이 들어왔습니다.")
    }
    mutating func makeCoffee(order: String) {
        pickupTable = [order]
        print("\(order) 메뉴의 제작이 완료되었습니다.")
    }
~~~
- 하지만 이런 형태는 receivedOrder 내에서 makeCoffee를 실행하는 결과가 되는 것 같아서 바람직하지 않을 것 같고 추후에 별도에 함수가 추가 요구사항으로 있을 것 같아 삭제하였습니다. (원래 의도는 주문한 메뉴값을 전달하는것이었습니다...!)

## 해결이 되지 않은 부분
- 저는 다 작성한 것 같은데... 분명 뭔가 해결이 덜 된 부분이 있겠지요?... 😅

## 조언을 얻고 싶은 점
- 늘 강의를 볼 떄는 알겠는데, 과제를 하다 보면 여전히 어렵습니다... 코드의 실행 순서나 데이터의 전달 구조등을 생각하는게 어려운 것 같아요.
- 코드를 작성할 때도 하나씩 작성하는게 아니라, 수정하다 보면 앞서 작성한 코드가 잘못돼서 또 건들여보고... 계속 사방팔방으로 계속 수정하게 됩니다ㅜㅜ

2023-10-24 23:42 UTC, FirstDo requested changes
안녕하세요 luice님! 
3주차 STEP1 잘 수행해 주셨습니다!

요구사항에 맞게 잘 수정해주셨어요!
코맨트 몇개 남겼으니 확인 부탁드립니다 :)

## 질문에 대한 답변

> 하지만 이런 형태는 receivedOrder 내에서 makeCoffee를 실행하는 결과가 되는 것 같아서 바람직하지 않을 것 같고 추후에 별도에 함수가 추가 요구사항으로 있을 것 같아 삭제하였습니다. (원래 의도는 주문한 메뉴값을 전달하는것이었습니다...!)

실제 객체간의 상호작용은 다음 스텝에서 구현하실텐데요, 
receivedOrder 매서드 내부에서 makeCoffee 함수를 실행하는게 왜 바람직하지 않다고 생각하셨을까요?
저는 문제없다고 생각했는데 어떤부분이 걸리셨는지 luice님의 생각이 궁금합니다!

> 늘 강의를 볼 떄는 알겠는데, 과제를 하다 보면 여전히 어렵습니다... 코드의 실행 순서나 데이터의 전달 구조등을 생각하는게 어려운 것 같아요.
코드를 작성할 때도 하나씩 작성하는게 아니라, 수정하다 보면 앞서 작성한 코드가 잘못돼서 또 건들여보고... 계속 사방팔방으로 계속 수정하게 됩니다ㅜㅜ

그냥.. 많이 해보는 방법밖에 없는것 같습니다..!!!

2023-10-24 23:42 UTC, FirstDo commented on CodeStarterCamp_Week3/main.swift
> +}
구조체 안에 열거형을 만들 필요가 없을것 같네요!

```swift
enum Coffee {
  case 아메리카노
  case 카페라떼
  case 돌체라떼
  case 아포카토
}
```

추가적으로 Coffee가 가져야할 속성도 한번 생각해보시면 좋을것 같아요
(이름이나 가격? 기타 등등?)

2023-10-24 23:42 UTC, FirstDo commented on CodeStarterCamp_Week3/main.swift
> +    func buyCoffee(order: [String]) {
[String] 형이 아니라, Coffee 혹은 [Coffee] 타입이어야 할 것 같습니다

2023-10-24 23:42 UTC, FirstDo commented on CodeStarterCamp_Week3/main.swift
> +    let menu: [String: Int] = ["아메리카노": 2500, "카페라떼": 4000]
Coffee 타입을 사용해서 메뉴판 역시 [Coffee: Int] or [Coffee] 타입으로 바꿀 수 있을거 같아요

2023-10-24 23:42 UTC, FirstDo commented on CodeStarterCamp_Week3/main.swift
> +    }
다음스텝에서 진행하실꺼라서 고치지는 않으셔도 되지만

pickupTable = [order] 이런식으로 작성하면
기존 pickupTable에 있던 커피들은 다 날라가겠죠?

2023-10-24 23:42 UTC, FirstDo commented on CodeStarterCamp_Week3/main.swift
> +    mutating func receivedOrder(order: String) {
receive 자체가 받다라는 뜻이니까 `receiveOrder`가 더 맞을것 같습니다

2023-10-25 03:23 UTC, lucidly-lucie commented on CodeStarterCamp_Week3/main.swift
> +    }
맞습니다! ㅎㅎㅎㅎㅎ 원래 append를 사용해서 붙여보려다가, 그러면 pickup테이블이 계속 채워지기만 하는게 어색하다고 생각해서 그냥 주문 받은것을 픽업테이블에 내놓는다고 생각했습니다. 다음 스텝의 요구사항을 구현하며 변경하겠습니다~

2023-10-25 04:29 UTC, FirstDo approved these changes

2023-10-25 04:29 UTC, FirstDo commented on CodeStarterCamp_Week3/main.swift
> +    let menu: [Coffee: Int] = [Coffee.아메리카노: 2500, Coffee.카페라떼: 4000]
컴파일러가 타입 추론을 해주기때문에 이런식으로도 작성할 수 있습니다

```swift
let menu: [Coffee: Int] = [.아메리카노: 2500, .카페라떼: 4000]
```

2023-10-25 04:29 UTC, FirstDo commented on CodeStarterCamp_Week3/main.swift
>      }
처음에 시도했던대로 tuple 형식으로 매개변수를 가지는걸 연관값이라고 하는데요!
그 방식을 의도했던건아니고 이런식을 생각했었습니다

```swift
enum Coffee {
    case iceAmericano
    case hotAmericano
    case cafeLatte
    case coldBrew

    var name: String {
        switch self {
        case .iceAmericano: return "Ice Americano"
        case .hotAmericano: return "Hot Americano"
        case .cafeLatte: return "Cafe Latte"
        case .coldBrew: return "Cold Brew"
        }
    }

    var price: Int {
        switch self {
        case .iceAmericano: return 4500
        case .hotAmericano: return 4200
        case .cafeLatte: return 4600
        case .coldBrew: return 4500
        }
    }
}
```

2023-10-26 04:47 UTC, merged