Week3 [STEP 2] Grumpy
yagom-academy/swift-starter-week3 pull request #28
Opened 2022-01-02 17:51 UTC by sewoongpark

@joey-ful
안녕하세요~!🙋🏻‍♂️
 
3주차 2번째 미션 PR입니다 :)

고민했던 점
1. 본문 내용의 이해
> missKim 은 yagombucks 의 order(coffee: Coffee) 메서드를 호출해 커피를 주문합니다.
주문과 동시에 missKim의 돈은 커피의 가격만큼 줄어들고, yagombucks 의 매출액은 커피 가격만큼 증가합니다.

처음엔 이 부분이 잘 이해가 되지 않았습니다.. ```missKim```이 ```yagombucks```의 메서드를 호출한다면 ```missKim``` 인스턴스가 ```yagombucks```를 프로퍼티로 갖고 있어야 하는지, 또한 동시에 ```missKim```의 돈과 ```yagombucks```의 매출액을 조정하려면 어떻게 해야 하는지가 또 고민점이었습니다.
저는 조건문을 사용해서 커피의 구매 가능 여부를 ```Bool``` 타입으로 리턴하고, ```true```를 받으면 주문이 실행된 상황으로 간주하여 바로 ```yagombucks```의 ```order```메서드가 실행되도록 구현했습니다! 

2. 프로퍼티 옵저버
> 추출된 커피는 pickUpTable 에 올려집니다.
__pickUpTable에 커피가 올려지면__ 다음과 같은 문구가 출력됩니다.

```order``` 내부에서 바로 출력을 하면 쉽지만, 굳이 ```pickUpTable``` 에 커피를 올린다고 명시한 이유가 있을 것이라 생각했습니다.
그런 관점으로 접근하다 보니, __Property Observers__ 라는 것이 있더군요🤓
* willSet : 값이 저장되기 직전에 호출됩니다. 새로운 프로퍼티의 값이 newValue 로 제공됩니다.
* didSet : 새로운 값이 저장된 직후에 호출됩니다. 이전 프로퍼티의 값이 oldValue 로 제공됩니다.
```pickUpTable```에 새로운 값이 저장될 때 실행되어야 하므로 ```didSet```을 사용했습니다. 

다만 처음 설계 의도와는 다르게, 주문자의 이름을 key값으로 해서 coffee를 올리고 내리는 방법을 생각했는데 손님이 오면 주문 받고 바로 커피를 만들어서 내주는 선입선출 방식의 커피숍이 되었네요 ㅋㅋ

2022-01-03 10:54 UTC, joey-ful requested changes
@sewoongpark 

grumpy님 안녕하세요!
코드에 역시 많이 고민하신 흔적이 보입니다! 지난번 피드백에 달아주신 커멘트들도 잘 읽어보았습니다 👍
이번에도 고민거리와 해결방안을 적어주셔서 좋았어요 👍
Person타입이 구매를 하면 CoffeeShop 타입이 주문을 받는 부분은 커멘트에 남겨드린대로
타입끼리 서로 소통하는 방식으로 구현되면 좋을 것 같습니다!
그리고 프로퍼티 옵저버는 정말 잘 활용하셨습니다 👏🏻 
다만 pickUpTable은 주문자의 이름과 커피를 저장해두는 방식이 Step2에서는 사용이 되지 않아 딕셔너리가 아닌 다른 타입을 적용해보시는 것도 좋을 것 같아요

요구사항대로 잘 동작하고 지금 코드도 정말 잘 짜주셨지만
`missKim 은 yagombucks 의 order(coffee: Coffee) 메서드를 호출해 커피를 주문합니다.` 부분에 좀 더 맞춰서 구현이 되면 좋을 것 같아 수정 요청을 해봅니다!

2022-01-03 10:54 UTC, joey-ful commented on CodeStarterCamp_Week3/Person/Person.swift
> +            return true
> 처음엔 이 부분이 잘 이해가 되지 않았습니다.. missKim이 yagombucks의 메서드를 호출한다면 missKim 인스턴스가 yagombucks를 프로퍼티로 갖고 있어야 하는지, 또한 동시에 missKim의 돈과 yagombucks의 매출액을 조정하려면 어떻게 해야 하는지가 또 고민점이었습니다.
저는 조건문을 사용해서 커피의 구매 가능 여부를 Bool 타입으로 리턴하고, true를 받으면 주문이 실행된 상황으로 간주하여 바로 yagombucks의 order메서드가 실행되도록 구현했습니다!

고민거리를 상세하게 공유해주시고 그에 대한 해결책도 잘 설명해주셔서 감사합니다! 🤩
말씀하신대로 두 타입의 돈을 수정해야하는데 조건문으로 그 부분을 잘 해결하신 것 같아요 👍
- 다만 `purchase(stuff:price:)`를 호출할 때마다 조건문을 작성해야한다면 번거롭고 헷갈린다는 단점이 있을 것 같습니다
  - 코드가 많아지고 복잡해진다면 `purchase(stuff:price:)`가 false일 때 `order(coffee:)`를 해버리거나 아니면 아예 `order(coffee:)`를 잊고 안 해버리는 등의 실수가 발생할 리스크가 존재할 것 같아요 🤔  
- 제가 생각했을 땐 고객이 커피숍을 알고 커피숍도 고객을 아는 것이 자연스러워보입니다! 프로퍼티가 아닌 매개변수로 서로를 아는 방법도 있으니 이 부분을 참고해서 missKim이 yagombucks에서 커피를 주문하는 로직을 수정해보시면 어떨까 싶어요

2022-01-03 10:54 UTC, joey-ful commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +    }
didSet을 활용해 pickUpTable 에 커피가 올라갈 때 특정 동작을 하고 있네요 👏🏻
커피를 여러 잔 저장해두는 것을 고려하셔서 딕셔너리로 pickUpTable을 구현하신 것이 정말 좋다고 생각해요 👍
- 하지만 지금 로직에서는 pickUpTable이 딕셔너리일 필요가 없어보이네요
- else 부분은 없어도 똑같을 것 같은데 어떻게 생각하시나요

2022-01-03 10:54 UTC, joey-ful commented on CodeStarterCamp_Week3/Person/Person.swift
> +    mutating func purchase(stuff: String, price: Int) -> Bool {
문자열로 구매품목을 받고 있기 때문에 커피 외의 것도 구매할 수 있어 좋다고 생각해요
하지만 String이라면 정말 그야말로 아무거나 전달받을 수 있어서 무엇을 살 수 있는지 제한하는 것도 나쁘지 않은 것 같아요 🤔
지금은 구매할 수 있는 것이 커피밖에 없으니 커피 타입을 구매할 수 있도록 해보는 것을 어떨까요?

2022-01-03 10:54 UTC, joey-ful commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +    }
커피숍에 주문을 하면 고객이 있는지 확인 후 주문을 진행하고 있네요
주문을 받기 전에 고객을 미리 아는 것보다 주문 받을 때 고객을 안다면 어떨까요?

2022-01-03 16:39 UTC, sewoongpark commented
@joey-ful 

고민하고 있던 부분을 짚어 설명해 주셔서 감사합니다! 피드백 주신 소스 수정했어요!

Person의 purchase 메서드 내부에서 CoffeeShop의 order 메서드 호출을 시도하자 
'Swift Cannot use mutating member on immutable value' 에러가 발생했고 다음과 같은 이유로 CoffeeShop을 클래스로 변경했습니다 ㅎㅎ

>"Swift의 구조체는 값 타입이고, 클래스는 참조 타입입니다. 
구조체는 값 타입이며 값 타입은 값의 복사가 이뤄집니다. 위와 같이 변수에 할당하게 되면 값의 복사가 일어나고 복사된 값에서 함수의 결과값을 가져오는 것이기 때문에 원본 인스턴스에는 반영되지 않습니다. 
클래스는 참조 타입이기 때문에 함수에서 반환되어도 원본 인스턴스의 참조가 반환됩니다. 따라서 order() 메서드를 호출하면 원본 인스턴스에 접근하여 수행됩니다."

--> 만약 컴파일 에러로 잡아내지 못했어도 복사된 값에서 함수를 부르기 때문에 복사되기 전인 원본에는 반영이 되지 않아 yagombucks의 매출액을 출력하려 해도 변동이 없었을 것. 그에 반해 클래스는 원본 인스턴스의 참조를 반환하기 때문에 직접 메소드를 호출하는 것과 같다.

상속의 여부에 따라 구조체와 클래스를 선택하는 것이 아니라 용도에 따라 취사선택할 수 있어야 한다는 게 굉장히 어렵네요.
값 타입과 참조 타입의 차이를 직접 느껴보니 더 와닿는 것 같습니다.
왜 더 수정을 요청하셨는지 알 것 같네요! 고맙습니다😀
Thanks to: 
[Swift Cannot use mutating member on immutable value 에러가 무엇일까](https://zdodev.github.io/swift/trouble%20shooting/Swift-Cannot-use-mutating-member-on-immutable-value-에러가-무엇일까/)
[Swift - 언제 class 대신 struct 를 사용하는가](http://seorenn.blogspot.com/2016/04/swift-class-struct.html)

또한 함께 링크해 주신 [Bool 변수 이름 제대로 짓기 위한 최소한의 영어 문법](https://soojin.ro/blog/naming-boolean-variables) 흥미롭게 읽었습니다 ㅎㅎ 저의 경우에는 __조동사+동사원형__에 해당하는 케이스였네요!

2022-01-04 05:57 UTC, joey-ful approved these changes
@sewoongpark 

grumpy님 고생 많으셨습니다!
이번 미셤의 중점사항 중 하나였던 인스턴스 사이의 소통을 잘 파악하신 것 같아요 👍
수정하셨으면 하는 사항들이 조금 있긴해서 커멘트 남겨드렸어요
하지만 요구사항대로 잘 동작하고 핵심 경험들과 관련된 내용들은 다 잘 구현하셔서 머지는 승인합니다
(프로퍼티 옵저버, 인스턴스 간의 소통, 안전한 옵셔널 바인딩, 타입의 구현과 사용 등등 +⍺로 값타입과 참조타입의 차이까지 🤩  )
피드백 한 번 확인해 주시고 다음 단계 넘어갈 때 말씀해 주시면 머지할게요!

2022-01-04 05:57 UTC, joey-ful commented on CodeStarterCamp_Week3/Person/Person.swift
> +            shop.customer = Self.init(name: name, age: age, gender: gender, money: money)
여기는 새로운 인스턴스 대신 self 를 넣어도 될 것 같아요!

2022-01-04 05:57 UTC, joey-ful commented on CodeStarterCamp_Week3/Person/Person.swift
> +            shop.order(coffee: stuff)
- shop의 고객을 지정하는 행위와 shop의 `order(coffee:)`함수를 호출하는 행위는 아마 매번 함께 이루어질 것 같아요
따라서 `order(coffee:)`에서 고객을 매개변수로 전달받는 편이 더 유용할 것 같습니다
- 또, 외부에서 어떤 인스턴스의 프로퍼티를 마음대로 수정하게 하는 것보다는 메서드를 통해 변경하도록 하는 것이 조금 더 안전하다고 생각합니다! 메서드에 전달할 수 있다면 바로 customer 프로퍼티를 바꾸기보다 매개변수로 전달하는 것이 좋지 않나 생각합니다

2022-01-04 05:57 UTC, joey-ful commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +    }
pickUpTable의 보다 목적에 맞는 형태로 잘 바꿔주셨습니다!
근데 요구사항에 따르면 pickUpTable은 고객이름이 아닌 커피를 기억하는 것이 적절할 것 같아요
지금은 고객을 customer와 pickUpTable 두 곳에 저장하고 있네요

2022-01-04 05:57 UTC, joey-ful commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +        self.pickUpTable = ""
pickUpTable에는 커피가 있을 수도 있고 없을 수도 있을 것 같아요
빈 문자열도 좋지만, 커피가 없다는 것을 의도적으로 나타내려면 옵셔널로 두는 방법도 있을 것 같습니다

2022-01-04 05:57 UTC, joey-ful commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +        }
옵셔널의 내용물을 안전하게 추출하고 있네요 👍
옵셔널 체이닝의 활용도 좋습니다

2022-01-04 05:57 UTC, joey-ful commented on CodeStarterCamp_Week3/Person/Person.swift
> +    mutating func purchase(shop: CoffeeShop, stuff: Coffee) {
구매할 물건의 타입이 커피라면 `stuff` 보다는 `coffee`, 혹은 `_` 등으로 받으면 어떨까요 🤔
함수명과 argument label 을 활용해 한 문장처럼 읽히면 더 좋을 것 같아요!

2022-01-04 05:57 UTC, joey-ful commented on CodeStarterCamp_Week3/main.swift
> +missKim.purchase(shop: yagombucks, stuff: hotChoco)
이제 Person타입이 구매를 하면 알아서 CoffeeShop 타입이 주문을 받고 있네요! 👏🏻
메서드가 메서드를 호출하며 인스턴스끼리의 소통을 구현해 주셨어요

남겨주신 글을 보니 값타입과 참조타입까지 잘 파악하셨고 그에 따라 적절한 타입을 선택해 주셨습니다 👍 👍 👍
어려운 개념인데 금새 공부해서 적용하신 점이 대단합니다! 정말 고생 많으셨습니다!
어려운만큼 정말 중요한 개념이라 자주 나올텐데 제대로 이해하신 것 같아요
- 커피의 종류는 미리 변수로 선언하지 않고 함수 호출부에서 **바로 선택해도** 괜찮을 것 같아요
  ```swift
  missKim.purchase(shop: yagombucks, stuff: .hotChocolate)
  ```

2022-01-04 06:35 UTC, sewoongpark commented on CodeStarterCamp_Week3/Shop/CoffeeShop.swift
> +    }
맞습니다! 이 부분은 CoffeeShop이 customer를 가지게 되었기 때문에 Coffee를 담는 것이 맞다고 생각됩니다. pickUpTable이라는 이름에도 더 걸맞는 것 같아요.

2022-01-04 06:40 UTC, sewoongpark commented on CodeStarterCamp_Week3/Person/Person.swift
> +    mutating func purchase(shop: CoffeeShop, stuff: Coffee) {
물론 확장을 염두해 두고 범용적으로 물건을 구입한다는 개념으로 stuff를 사용하긴 했지만, CoffeeShop에서 Coffee를 구매하는 상황으로 한정지었기 때문에 저 역시 coffee가 더 어울린다고 생각합니다!!! 
마지막 문장도 정말 멋진 말씀이네요👍

2022-01-04 06:41 UTC, sewoongpark commented on CodeStarterCamp_Week3/main.swift
> +missKim.purchase(shop: yagombucks, stuff: hotChoco)
와 이렇게 사용할 수 있다는 건 몰랐어요ㅋㅋㅋ 아직 enum타입의 쓰임이 어렵긴 하네요..😅

2022-01-04 06:43 UTC, sewoongpark commented
@joey-ful 

멋진 피드백 감사합니다! 다음 미션도 잘 부탁드려요!

2022-01-05 04:31 UTC, merged