Week3 [STEP 2] 김마루
yagom-academy/swift-starter-week3 pull request #280
Opened 2023-10-26 02:54 UTC by marukim365

안녕하세요, 두두!(@FirstDo  )
김마루 입니다.

Week3 STEP 2 - 인스턴스는 서로 소통한다
완료하여 PR 보냅니다!

🤔 어려웠던 점
-----------
1. `order(_ coffee: Coffee, of coffeeShop: CoffeeShop, by name: String)` 메서드에 너무 많은 기능이 담겨있는 것 같습니다.
기능을 분리해보고 싶었으나, 도저히 방법이 생각이 안나서 ㅠㅠ 메서드에 많은 기능이 추가되어 버렸습니다.

2. 커피값을 지불하는 과정에서 구매자는 금액이 줄어들고, 커피숍은 매출이 늘어나는 과정을 잘 구현한 것인가 의문이 듭니다.
(제가 너무 단순하게 구현한 것은 아닌지...😅)

이상입니다.

PR 확인 부탁 드립니다!
감사합니다 :)

2023-10-26 04:41 UTC, FirstDo requested changes
구현을 너무 깔끔하게 해주셔서..!
코맨트를 드릴말씀이 딱히 없습니다

코맨트에도 적었지만, Person의 order 함수에서 모든걸 컨트롤하면서, 수행하는게 아닌,
CoffeeShop 객체에게 그냥 주문을 받으라고 시키세요!
나머지 일은 CoffeeShop 객체가 다 처리하는 방식으로 수정해주시면 
좀더 OOP적인 프로그램에 가까울것 같네요 :)

2023-10-26 04:41 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP2_instance.swift
> +    let yagombucksMenu: [Coffee: Int] = [.iceAmericano: Coffee.iceAmericano.price, .hotAmericano: Coffee.hotAmericano.price, .cafeLatte: Coffee.cafeLatte.price, .coldBrew: Coffee.coldBrew.price, .app
제생각엔 menu 타입이 [Coffee: Int] 일 필요가 없을거같아요
[Coffee] 로만 메뉴를 구성해도 어차피 이름, 가격을 모두 알 수 있습니다

2023-10-26 04:41 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP2_instance.swift
> +    }
아래와 같은 함수 호출은 어색합니다
by name이라는 매개변수는 어차피 호출하는 객체의 프로퍼티 인데, 매개변수로 받을 필요가 있을까요?
그리고 지금 실제로 사용하고 있지 않은 값인것 같네요..!
```swift
missKim.order(.bananaJuice, of: yagombucks, by: missKim.name)
```

다시보니까 해당 매서드가 요구사항이었군요..!
하지만 매개변수를 사용하지 않는다면 필요는 없을것 같네요

2023-10-26 04:41 UTC, FirstDo commented on CodeStarterCamp_Week3/STEP2_instance.swift
> +    }
제생각에는 여기도 더 단순하게 쓸 수 있을것 같습니다

Person이라는 객체에서 아래와 같은 내용을 알 필요가 있을까요?
```swift
coffeeShop.calculateSales(coffee)
coffeeShop.make(coffee, from: coffeeShop.barista.name)
coffeeShop.announceMenu(by: self, coffee: coffee)
```

Person객체가 주문을하면, CoffeeShop 객체는 주문을 받기만 하면 됩니다.
누가, 어떤 커피를 주문했는지만 알면, 나머지는 모두 CoffeeShop 객체가 내부적으로 처리할 수 있습니다

```swift
coffeeShop.make(_ coffee: Coffee, from name: String)
```

나머지 돈계산이나, 커피 만드는거나, pickupTable에 넣는 행동은 모두 CoffeeShop 객체에서 수행하는게 맞는것 같아요

`payMoney(coffee)`
이 매소드 역시 order에서 호출되는게 좋을지, CoffeeShop의 돈계산에서 호출되는게 더 적절할지 한번 생각해보시면 더 좋을것 같습니다 (정답은 없는것 같네요..!)

2023-10-26 06:11 UTC, marukim365 commented on CodeStarterCamp_Week3/STEP2_instance.swift
> +    }
피드백 주신대로
각 타입의 역할에 맞게 메서드 구성해주는 것이 훨씬 좋아보이네요!!

2023-10-27 03:04 UTC, marukim365 commented on CodeStarterCamp_Week3/STEP2_instance.swift
> +    let yagombucksMenu: [Coffee: Int] = [.iceAmericano: Coffee.iceAmericano.price, .hotAmericano: Coffee.hotAmericano.price, .cafeLatte: Coffee.cafeLatte.price, .coldBrew: Coffee.coldBrew.price, .app
a2c0f45541496e6eb61c89e30a1d79e4ae7d222c

수정 했습니다~

2023-11-23 00:11 UTC, closed without merging