[Round3/Stpe1]-Crois_Person타입 생성과 호출
yagom-academy/swift-starter-week3 pull request #332
Opened 2024-07-25 08:18 UTC by Crois0509

Step 1 미션 과제 달성을 위한 Person 타입 생성

2024-07-26 06:50 UTC, jaemuYeo requested changes
Round3/Step1 너무 잘 구현해주셨군요!!
출력되는 주문/제작/정산 등의 표시가 너무 멋졌습니다 👍
코멘트 남겨두었으니 확인해주세요 :)
다량의 커피 주문은 추후에 스텝2까지 완료 후 리팩토링을 통해 진행해보면 어떨까요~?
시도해본다면 buyCoffee메서드의 Coffee타입을 [Coffee] 형태의 배열로 받아볼 수 있을 것 같습니다.

제가 이전에 커밋 컨벤션에 대해서도 한 번 언급한 적이 있어요~
대표적인 [카르마 컨벤션](https://karma-runner.github.io/latest/dev/git-commit-msg.html)을 참고하여 앞으로 진행해보면 좋을 것 같습니다!
구글에다가 카르마 커밋 컨벤션 치면 많은 블로그 내용도 있어요 :)

대표적으로 잘 못된 예시를 하나만 꼽자면
`커피숍 및 커피 타입 생성` 입니다.

일단 커피숍과 커피 타입은 각각의 타입이므로 따로따로 커밋되는 것이 좋을 것 같고,
커피숍과 커피가 한글로 표기되었다는 것이 치명적인 문제라고 생각해요.

타입명, 메서드 명은 항상 구현된 그대로를 넣어주는게 좋습니다!
엄청 귀찮은 작업이긴하지만 지금부터 익숙해지셔야해요 ㅠㅠ
화이팅! 💪

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +class CoffeeShop {
CoffeeShop 타입은 왜 클래스로 정의하였나요~?

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +        didSet {
프로퍼티 옵저버를 활용해보셨군요!! 👏👍

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    init(name: String, barista: String, sales: Int) {
이니셜라이저의 위치는 보통 프로퍼티 매서드 보다 최 상단에 위치합니다!

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Coffee.swift
> +    var discription: Int {
크~~ 👍 연산 프로퍼티 활용 너무 좋습니다!!

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +class Person {
Person타입은 왜 클래스 타입으로 정의하였나요??

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +    var gender: String
정해져 있는 값은 열거형등의 타입으로 만들어도 좋아요~
gender의 경우 남,여 두 가지 뿐이기때문에 그렇게해봐도 좋을 것 같습니다 :)

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +            print(" ")
빈 문자열 또는 의미가 부여되지 않은 숫자 등을 매직 넘버라고 칭하기도 합니다.
이러한 빈 문자열 또한 상수에 담아 사용한다면 의미를 부여해주고 가독성을 높일 수 있어요!
매직 넘버에 대해 찾아보아도 좋을 것 같아요 :)

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +        for calculate in of.pickUpTable {
for문 위아래로 개행이 있다면 가독성이 좋아질 것 같습니다!

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +        if let order = pickUpTable.last {
if문 위에 개행이 되면 좋을 것 같아요!

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +    func buyCoffee(from: CoffeeShop, to: Coffee) {
파라미터 네임도 함께 사용하면 좋을 것 같아요.
내부 구현에서 보면 \(to) 또는 from.을 통해 매개변수를 활용하고 있는데
사용하는 부분에서 to가 뭔지 from이 뭔지 명확하지가 않은 것 같습니다!
\(coffee)를 주문합니다. coffeeShop.makeCoffee 형태로 시도해봐도 좋을 것 같아요!

buyAllMenu에서 처럼요!

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +
이 곳에 개행은 왜 이루어졌나요?

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +            missKim.buyCoffee(from: CoffeShop, to: coffee)
missKim은 외부에서 선언된 Persom의 인스턴스인데 이 곳에 다시 불러온 이유는 무엇인가요?

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    func todaysCalculate(_ of: CoffeeShop) {
인자레이블과 파라미터 네임 모두 있으면 좋을 것 같습니다!

2024-07-26 06:50 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +            calculateCoffee.insert(contentsOf: "\(calculate), ", at: calculateCoffee.endIndex)
해당 부분은 추후에 map을 활용해보면 좋을 것 같아요!

2024-07-26 06:59 UTC, Crois0509 commented on CodeStarterCamp_Week3/CoffeShop.swift
> +class CoffeeShop {
CoffeeShop의 타입은 원래 Struct로 진행하고 있었으나,
CoffeeShop의 매출(sales)에 대해 고객이 커피를 구매하면 그에 맞춰 커피가격만큼 매출이 증가하는 코드를 작성하고자 했습니다.
이 과정에서 CoffeeShop 내부에서 sales 값에 변동을 주기 위해 mutating을 활용했었는데,
이렇게 할 경우 CoffeeShop의 프로퍼티인 sales 자체의 값은 변하지 않아
sales의 값을 보기 위해 호출하여도 늘 0이라는 값을 출력했습니다.
이를 해결하고자 참조타입인 Class로 바꾸어보니 mutating을 사용하지 않고도 내부에서 값에 변화를 줄 수 있고,
호출을 할 때도 sales의 값이 판매한 커피의 금액만큼 값이 오른 채 잘 호출되었기에
Class로 정의하게 되었습니다.

2024-07-26 07:01 UTC, Crois0509 commented on CodeStarterCamp_Week3/Person.swift
> +class Person {
Person 타입 역시, CoffeeShop과 마찬가지로
지니고 있는 돈, money의 값에 변동을 주고 외부에서 이를 호출할 때
Struct 보다 Class 타입이 더욱 유용하다고 생각하여 Class 타입으로 정의했습니다.

2024-07-26 07:23 UTC, Crois0509 commented on CodeStarterCamp_Week3/Person.swift
> +    // Person타입이 가지는 성별의 종류
Person타입에서 지정할 수 있는 gender 프로퍼티를
male, female, other 의 세가지로 선택지를 제한했습니다.

2024-07-26 07:34 UTC, Crois0509 commented on CodeStarterCamp_Week3/Person.swift
> +            person.buyCoffee(from: CoffeShop, to: coffee)
Person, CoffeeShop, Coffee, main 으로 파일을 나누며 기존 코드를 백업해두고
해당 코드를 복사해서 붙여넣는 과정에서
기존에는 main에서 호출하던 코드를 Person 타입의 메소드로 사용하려다가
놓친 부분입니다.
함수 내에서 missKim을 호출하는 것이 아닌 person이라는 매개변수를 추가하여
person을 호출하는 것으로 수정하였습니다.

2024-07-26 07:58 UTC, Crois0509 commented on CodeStarterCamp_Week3/MagicNumber.swift
> +}
매직넘버라는 것을 찾아보니 코드의 가독성을 높이기 위해서 상수나 변수 등의 선언없이 사용되는 숫자, 문자 등을 일컫는 코드라고 이해했습니다.
또, 이를 상수화 해줌으로써 코드의 가독성을 높이는 것이 좋고,
이를 enum 타입으로 생성하여 언제든 필요한 경우 호출할 수 있도록 하면 좋을 것 같아
만들어 보았습니다.
enum 타입으로 한 이유는, 이번 코드에서는 blankPage라는 하나의 매직넘버만이 필요했지만,
후에 여러 종류의 매직코드가 생성되거나 필요해지는 경우
다양한 경우에 적용시킬 수 있도록 많은 case를 만들 수 있는 enum 타입이 유리해 보였기 때문입니다.

2024-07-26 08:10 UTC, Crois0509 commented
@jaemuYeo 
안녕하세요 잼킹님!
남겨주신 코멘트 피드백 확인하여 코드를 수정하고
재요청 드립니다.
카르마 컨벤션에 대해 알려주셔서 확인해 보았는데,
코드만 열심히 하고 commit에 대해서는 신경을 못 쓴 것 같다고 생각하게 되었습니다...

실무에 가면 당연히 많은 작업자들과 협력을 하게 될텐데
그 때 commit 을 잘 하지 못하면 다른 작업자들에게 폐가 되겠죠...
지금부터 연습이라고 생각하고 시도하는 노력을 해보려고 합니다!

## 고민했던 점
### commit을 나누는 기준?
- 카르마 컨벤션을 찾아보니 commit 에 대한 다양한 내용과 다양한 컨벤션이 나왔습니다.
- 이 중 가장 대중적이라고 생각하는 <type>:  <subject> 형식을 참고하여 commit을 진행해 보았습니다.
- 실제로는 <body>나 <footer> 등의 내용도 있는 듯 하지만, 선택사항이고 지금은 굳이 필요 없을 것 같아 생략했습니다.
- 코드를 수정하며 어느 타이밍에 commit을 작성하는게 좋을까? 고민을 했습니다.
- 일단은 하나의 작업을 마칠 때마다 commit을 진행해 보았는데, 이게 정답인지 모르겠네요
- 코드를 수정하다보니 다른 수정할 부분도 보여서 수정하려고 했지만, 그랬다가는 commit이 꼬이게 될 것 같아 하던 수정을 먼저 다 마무리 한 후에 commit을 하고, 이후에 다시 다른 부분을 수정하는 방식으로 진행했는데 이게 맞을까요??

## 조언을 얻고싶은 부분
### Class와 Struct
- 저는 이번 코드를 작성하며 Struct 타입을 한번도 사용하지 않았습니다.
- 이유로는 값을 복사하는 특성의 Struct로는 원하는 코드를 구현하기 어렵다고 생각했기 때문에 값을 참조하는 타입의 Class를 선택했습니다.
- 다만, 이 부분은 제가 잘 모르기 때문에 혹시 Struct를 쓰더라도 내부 프로퍼티의 값을 변경, 참조할 수 있는 방법이 있는지 알고싶습니다.

## 해결이 되지 않은 부분
### map 메소드?
- 피드백으로 추후 map을 활용해 보시면 좋을 것 같다고 하셔서 map에 대한 정보를 찾아보았습니다.
- 다만 아직은 map에 대한 이해와 숙련도가 부족하여... 좀 더 공부를 해봐야할 것 같습니다.

2024-07-27 06:19 UTC, Crois0509 commented on CodeStarterCamp_Week3/CoffeShop.swift
> +            \(calculateCoffee.joined(separator: ", "))
지난 피드백들의 내용을 기억하여
map 메소드와 seperator를 활용하여 todaysCalculate 메소드의 구현을 새롭고 깔끔하게 바꿔보았습니다.

2024-07-30 05:52 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    init(name: String, barista: String, sales: Int) {
@Crois0509 

에고 제가 잘못 전달했네요!
프로퍼티 아래 메서드 위에 위치합니다 🙏

2024-07-30 06:18 UTC, jaemuYeo reviewed
스텝1 고생하셨습니다!
현재 빌드가 되지않는 에러가 발생하여 다음 스텝에서 수정해주시면 좋을 것 같아요~

### 구조체와 클래스
참조를 위해서는 클래스를 사용하는 것이 맞으나 
구조체의 경우도 프로퍼티가 참조가 되는 경우가 있을 수 있습니다.
예를 들어 프로퍼티의 타입이 참조타입(클래스)인 경우이죠.

```swift
class Person {

}

struct Student {
   var person = Person() // 해당 프로퍼티는 참조 발생가능성 있음. Person 타입이 클래스이기에
}
```

구조체와 클래스, 고차함수에 대한 부분은 피드백 세션 4주차를 참고해주시면 좋을 것 같아요!
더 궁금한 내용이 있다면 언제든 질문해주세요 :)

2024-07-30 06:18 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +    }
프로퍼티와 init 사이에 개행이 필요해보입니다!

2024-07-30 06:18 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +    enum Gender {
외부에 타입을 생성하지 않고 Person타입 내부에 타입을 선언한 이유가 궁금합니다 :)

2024-07-30 06:18 UTC, jaemuYeo commented on CodeStarterCamp_Week3/MagicNumber.swift
> +            " "
return 키워드가 없어 앱이 실행되지 않아요 🤔

2024-07-30 06:18 UTC, jaemuYeo commented on CodeStarterCamp_Week3/MagicNumber.swift
> +enum MagicNumber: String {
해당 방법도 좋은 방법입니다!
또는 
```swift
enum MaginNumber: String {
   let blankingPage = " "
}
```
이런 방법도 있어요. 아니면 Swift의 Extension에 대해서 알아보아도 좋을 것 같습니다!

2024-07-30 06:19 UTC, merged

2024-07-30 06:29 UTC, Crois0509 commented on CodeStarterCamp_Week3/Person.swift
> +    enum Gender {
gender 타입은 Person타입에서만 쓰일 고유한 값이라고 생각하여 내부에 생성해 보았습니다.