[Round3/Step2]-Crois
yagom-academy/swift-starter-week3 pull request #333
Opened 2024-07-30 06:39 UTC by Crois0509

2024-07-30 07:15 UTC, Crois0509 commented
@jaemuYeo 
안녕하세요 잼킹님!
Round3 Step2 제출합니다!!
이전 스텝에서 다양한 기능을 넣어봤었는데,
우연히도 스텝2에서 같은 과제를 내었더라구요
그래서 특별히 크게 수정할 필요가 없어
네이밍 등만 스텝2에 맞도록 수정해 보았습니다.
물론 지난 마지막 피드백 내용을 확인하고 그에 맞도록 수정도 진행했구요!! 

이대로 제출하는건 재미가 없어서 스스로 생각해서
Person타입에 work라는 메소드를 추가해 보았습니다.
일을 한 시간만큼 money가 증가하도록 간단히 작성해 보았어요!

2024-07-31 07:20 UTC, jaemuYeo requested changes
스텝2도 빠르게 진행해주셨군요!! 
말씀하신대로 크게 바뀐 부분이 없어 추가로 학습해보면 좋을 것 같은 내용위주로
코멘트 남겨두었습니다 :)

확인 후 재요청 주시면 merge 진행하겠습니다!

2024-07-31 07:20 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +            if let order = pickUpTable.last {
if-let과 guard-let의 차이점은 무엇인가요?
현재 else가 없기에 guard문을 활용해보아도 좋을 것 같아요.
guard문의 가장 큰 장점은 `early exit` 라는 것인데요. 어떤 이점이 있은지 조사해보면 좋을 것 같습니다.

2024-07-31 07:20 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +
todaysCalculate의 네이밍을 수정해보면 좋을 것 같아요.
동사로 시작하면 좋을 것 같습니다!
매개변수 또한 타입은 CoffeeShop인데 네이밍은 매출이군요!
매출을계산하다(커피샵) 형태로 하면 좋을 것 같아요.

2024-07-31 07:20 UTC, jaemuYeo commented on CodeStarterCamp_Week3/MagicNumber.swift
> +    case blankPage = " "
이건 제가 지난번에 제시했던 내용인데요~
꼭 이대로 하라! 라는 것은 아니고 전달해주고싶어서 공유해요 :)
[kodecco style guide](https://github.com/kodecocodes/swift-style-guide?tab=readme-ov-file#constants)

```swift
enum MaginNumber: String {
   static let blankPage = " "
}
```

2024-07-31 07:56 UTC, Crois0509 commented
@jaemuYeo 
안녕하세요 잼킹님! 피드백 감사합니다!
말씀하신 내용을 확인하여 아래의 내용을 수정했습니다!

## 수정한 내용
- 기존의 코드를 아래와 같이 수정했습니다.
```swift
if pickUpTable.count != 0 {
if let order = pickUpTable.last {
print("현재 주문목록: \(order)")
print("\(name) 님이 주문하신 \(coffee)(이/가) 준비되었습니다. 픽업대에서 가져가주세요.")
print(MagicNumber.blankPage.rawValue)
}
}
// if가 두번 사용되어 가독성을 해치고, else 가 없어 의미없는 코드가 되어버리거나 error가 발생할 가능성이 있음

// 때문에 아래와 같이 수정함
guard let order = pickUpTable.last else {
return print("아직 주문이 들어오지 않았습니다.")
}
print("현재 주문목록: \(order)")
print("\(name) 님이 주문하신 \(coffee)(이/가) 준비되었습니다. 픽업대에서 가져가주세요.")
print(MagicNumber.blankPage.rawValue)
}
// guard-let 사용으로 가독성을 높이고 쓸데없는 코드의 사용을 줄이며, else를 통해 돌발상황에 대처하는 코드를 생성
```
- 다음으로는 todaysCalculate의 메소드 이름과 매개변수 명을 수정했습니다.

## 조언을 얻고싶은 부분
- 피드백을 주신 부분 중 매직넘버에서 쓰신 static let 이란 부분에 대해 조언을 구하고 싶습니다
- 제가 알기로 static은 타입 메소드를 만들어주는 코드인 걸로 알고 있습니다
- 타입 메소드와 인스턴트 메소드의 차이를 정확히 이해하지 못하겠는데 어떻게 이해하면 좋을까요?

2024-08-01 03:25 UTC, jaemuYeo reviewed
Round3 고생많으셨습니다!!
막판 스퍼트 내보아요 💪

## 타입 메서드와 인스턴스 메서드

### 타입 메서드/프로퍼트
타입메서드 또는 프로퍼티는 말그대로 타입자체의 메서드를 의미합니다.
```swift
class Person {
   static let age: Int = 30 
}

// 사용시 타입 자체에서 접근가능
Person.age
```

### 인스턴스 메서드/프로퍼트
인스턴스 메서드도 말 그대로 인스턴스 생성시 사용가능한 메서드입니다.
```swift
class Person {
   var age: Int = 20
}

// 사용시 인스턴스 생성 후 접근 가능
let jamking: Person = Person(age: 20)
jamking.age = 30
```

2024-08-01 03:25 UTC, merged