[Round3] step1 - GOO
yagom-academy/swift-starter-week3 pull request #337
Opened 2024-08-28 12:25 UTC by Goohyun3436

@jaemuYeo 
안녕하세요. 잼킹. Round3의 첫 PR 입니다!
이번 PR도 잘 부탁드립니다!!

<br />

## Person 타입 - Structure
- Person의 타입은 구조체로 정의하였습니다.
- Person 타입은 확장성이 크므로, 상속을 할 수 있는 Class로 정의하는 것이 맞지만, 구조체를 경험해보고 싶어서 구조체로 선택하였습니다.
- Property
  - `name`: 사람의 이름(필수)
  - `money`: 가지고 있는 돈(선택)
- Initializer
  - 카페 사장의 경우 money를 사용하는 기능이 없으므로 Person 구조체의 initializer 를 2개 정의하여,
  - money를 직접 초기화해주거나, 또는 구조체 내에서 초기화될 수 있도록 하였습니다. 
- Method
  - `buyCoffee`: 커피를 구매하는 메서드, 자신의 속성을 변경하는 함수로 mutating 키워드를 붙였습니다.
  - `totalAmount`: 총 지불할 가격을 반환하는 메서드입니다. 가게에 없는 메뉴를 주문 시에는 nil을 반환합니다.
  - `remainMoney`: 커피를 산 후 남은 돈을 반환하는 메서드입니다. 지불할 돈이 부족할 시에는 nil을 반환합니다.
  - `printOrderList`: 주문한 커피의 목록을 출력하는 메서드입니다.
```swift
struct Person {
    var name: String
    var money: Int

    init(name: String, money: Int) {}
    init(name: String) {}

    mutating func buyCoffee(items: [Coffee], shop: CoffeeShop) {}
    func calculateTotalAmount(_ items: [Coffee], at shop: CoffeeShop) -> Int? {}
    func checkBuyAvailability(_ totalAmount: Int) -> Int? {}
    func printOrderList(_ items: [Coffee]) {}
}
```

## CoffeeShop 타입 - Class
- CoffeeShop의 타입은 클래스로 정의하였습니다.
- 다양한 종류의 CoffeeShop이라도 공통된 속성과 메서드들이 존재하므로 클래스로 정의하였습니다.
- Property
  - `revenue`: 총 매출액
  - `menu`: 메뉴판(커피 종류, 가격)
  - `barista`: 바리스타(Person 타입)
  - `pickUpTable`: 주문이 접수된 Coffee 를 담은 배열
- Initializer
  - 카페의 메뉴와 바리스타를 초기화 매개변수로 전달하여 속성들을 사용자 정의로 초기화 해줍니다.
- Method
  - `order`: 주문을 받는 메서드
  - `makeCoffee`: 주문 목록에 따른 픽업 테이블과 총 금액을 반환하는 메서드, 가게에 없는 메뉴를 주문 시에는 nil을 반환합니다.
  - `printPickUpTable`: 최종 픽업 테이블을 출력하는 메서드입니다.
  - `printRevenue`: 최종 총매출액을 출력하는 메서드입니다.
```swift
class CoffeeShop {
    var revenue: Int
    var menu: [Coffee: Int]
    var barista: Person
    var pickUpTable: [Coffee]

    init(menu: [Coffee: Int], barista: Person) {}

    func order(items: [Coffee]) {}
    func makeCoffee(_ items: [Coffee]) -> ([Coffee], Int)? {}
    func printPickUpTable() {}
    func printRevenue() {}
}
```

## Coffee 타입 - Enumeration
- Coffee의 타입은 열거형으로 정의하였습니다.
- String 타입을 가지는 열거형으로 정의하여 `printOrderList`, `printPickUpTable` 에서 주문 목록을 출력할 때 String으로 활용할 수 있도록 하였습니다.
```swift
enum Coffee: String {
    case iceAmericano
    case hotAmericano
    case iceChoco
    case hotChoco
    case milkTea
}
```

2024-08-29 08:24 UTC, jaemuYeo requested changes
Round3도 완벽하게 수행해주셨군요!
왜 클래스로 선언했나요? 왜 구조체로 선언했나요?가 제 단골 질문인데
PR내용에 잘 남겨주어서 쉽게 납득할 수 있었습니다 👏
그 외 내용 잘 이해하였습니다 :)
무엇보다 커밋을 적절하게 잘 남겨주신게 인상깊었습니다 😀

## 옵셔널 바인딩
guard let 활용은 적절한 것 같아요!
옵셔널 바인딩 이후 코드의 로직이 계속 흘러가지 않는 경우라면
지금과 같이 예외처리를 해주고 바로 함수를 종료하는게 좋을 것 같아요 👍

## 결과물
print 결과물에 구매 -> 주문 접수 -> 총 매출로 결과가 나오는데
음료 제조 후 반환까지 해주면 자연스러울 것 같아요!

## 파일 분리
현재 step1이라는 파일 안에 모든 타입이 선언되어있어요!
타입별로 또는 관련된 타입끼리 파일을 분리하여 작성하시면 좋을 것 같습니다 :)

2024-08-29 08:24 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    init(name: String) {
money 변수에 기본값을 주어 두개의 이니셜라이저를 생성한 것이 좋네요! 👍👏

2024-08-29 08:24 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +enum Coffee: String {
추후에 rawValue도 경험해보세요!
또는 연산 프로퍼티와 switch-case 활용도 경험해보면 좋을 것 같아요!

2024-08-29 08:24 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +        var totalAmount: Int = 0
변수와 for문 사이 개행이 되면 좋겠어요 :)

2024-08-29 08:24 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +        let remainMoney: Int = self.money - totalAmount
여기도 개행이 필요할 것 같아요!

2024-08-29 08:24 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +        self.revenue = 0
위의 변수에 0을 초기값으로 주지않고 init에 설정한 이유는 무엇인가요~?

2024-08-29 08:24 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    func makeOrders(with items: [Coffee]) -> ([Coffee], Int)? {
파라미터의 타입은 Coffee또는 음료인데 item으로 표현한 이유가 궁금해요!

2024-08-29 08:24 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +        var totalAmount: Int = 0
이 곳에도 개행을 통해 변수와 다음 로직을 구분해주세요!

2024-08-29 08:24 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    var pickUpTable: [Coffee] = []
변수의 네이밍과 타입이 매칭이 잘 되지않는 것 같아요!

2024-08-29 08:24 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +        if remainMoney >= 0 {
guard문을 활용해볼 수 있을 것 같아요!

2024-09-02 10:42 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/step1.swift
> +        var totalAmount: Int = 0
잼킹의 리뷰와 [Swift Style Guide](https://google.github.io/swift/) 를 참고하여 수정하였습니다!

2024-09-02 10:42 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/step1.swift
> +        let remainMoney: Int = self.money - totalAmount
넵! 수정하였습니다.

2024-09-02 10:42 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/step1.swift
> +        self.revenue = 0
총매출액 프로퍼티를 사용자 정의로 초기화를 해야할지 고민하다가 실수로 남겨두었습니다.

- 해당 코드는 제거하였습니다.

2024-09-02 10:47 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/step1.swift
> +    func makeOrders(with items: [Coffee]) -> ([Coffee], Int)? {
커피 외의 품목이 메뉴에 추가되었을 때 `makeOrders` 메서드를 재사용하기 위해 좀더 넓은 의미의 파라미터로 표현하였습니다. 하지만 아직은 다른 종류의 품목이 없으므로 coffees 로 수정하였습니다.

- items -> coffees 로 수정하였습니다.

2024-09-02 10:47 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/step1.swift
> +        var totalAmount: Int = 0
수정하였습니다.

2024-09-02 11:05 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/step1.swift
> +        if remainMoney >= 0 {
`remainMoney` 변수가 0보다 같거나 큰지에 조건 검사에 guard문을 활용하여 아래와 같이 수정하였습니다.

```swift
let remainMoney: Int = self.money - totalAmount

guard remainMoney >= 0 else {
        return nil
 }

return remainMoney
```

2024-09-02 11:06 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/step1.swift
> +    var pickUpTable: [Coffee] = []
```swift
var revenue: Int  // 총 매출액 -> 수익의 의미
var menu: [Coffee: Int]  // 메뉴판(커피 종류, 가격) -> 메뉴판은 한개이므로 단수
var barista: Person  // 바리스타(Person 타입) -> 한명이므로 단수
var pickUpTable: [Coffee] = []  // 주문이 접수된 Coffee 를 담은 배열 -> 커피는 여러개지만 테이블은 한 개이므로 단수
```

@jaemuYeo 
매칭이 안 되는 부분이 어떤 부분인지 잘 모르겠습니다..! 🤔 제가 어떤 부분을 놓친 건지 좀더 자세히 짚어주실 수 있을까요?
제가 의도한 바는 위와 같습니다!

2024-09-02 11:07 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/step1.swift
> +enum Coffee: String {
넵 step2 과정에서 연산 프로퍼티와 switch-case 를 활용해볼수 있을 것 같아서, step2 과제에 적용해보도록 하겠습니다!

2024-09-03 05:59 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    var pickUpTable: [Coffee] = []
해당 부분은 개인적인 의견이었는데 요구사항에서는 pickUptable이 Coffee 배열을 담을 수 있게해달라고 되어있네요!
pickUpTable이라고하면 단순히 테이블을 의미하는데 그것이 커피를 담고있다는게 어색하게 느껴졌어요 ㅎㅎ
coffeePickUpTable 또는 drinkPickUpTable 처럼 명확하게 하면 어떨까 싶었습니다!

2024-09-03 06:00 UTC, jaemuYeo reviewed
Step1 고생많으셨습니다!
이번 스텝에서 했던 내용에 이어서 Step2도 잘 수행해주세요 💪

2024-09-03 06:00 UTC, merged

2024-09-03 06:07 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/step1.swift
> +    var pickUpTable: [Coffee] = []
아하! 이렇게 또 영어의 장벽을 느낍니다..
step2에서 좀 더 명확한 표현으로 수정하겠습니다. 감사합니다.