[Round3] Step1 - Elin
yagom-academy/swift-starter-week3 pull request #338
Opened 2024-08-31 08:48 UTC by Elin113

@jaemuYeo 안녕하세요 잼킹! Round3 Step1 PR을 보냅니다.
제시문을 너무 어렵게 생각한 건지 제일 시간이 많이 걸린 과제였습니다.. 올리는 와중에도 자신이 없네요ㅠㅠ
이번에도 잘 부탁드립니다!

### 고민했던 점
`CoffeeShop.getOrder` 에서 주문을 여러 잔 받고 계산하는 기능을 구현하고 싶었는데.. `menu` 프로퍼티에 대한 의문점이 해결이 되지 않아 결국 한 잔만 받는 기능으로 만들었습니다. 최대한 카페에서 계산하는 과정들을 구현하고 싶었어서 추가하다보니 수정 사항도 많아졌고, 프로퍼티가 제시되었던 것보다 너무 많아진 느낌이네요....

 - Class와 Struct 사이에서 어떤 타입으로 할지 고민했습니다. Swift 공식 문서 상의 결정 방법을 참고하여 처음엔 Struct로 결정했었습니다. 아직 해당 타입을 복잡하게 다른 곳에서 호출해서 쓸 일이 없고, 값이 변할 일이 없다고 생각했기 때문입니다.
   -> `Person.buyCoffee` 메소드에서 `person.money` 값이 변경되는데, 이를 CoffeeShop struct 에서 호출하다보니 Person이 let 상수라서 값을 변경할 수 없다는 오류가 발생했습니다. 값 타입 / 참조 타입의 차이에서 오는 것으로 생각하여 Class로 타입을 바꾸어 주었더니 오류가 발생하지 않았습니다.

 - `standBy`와 `pickUpTable` 배열에 `order` 값 할당 시 오류가 발생했습니다.
   -> `standBy[customerNumber] = order`로 하면 `standBy[0] = order`로 할당이 될 것이라 생각했는데, 애초에 `standBy`가 빈 배열이었기 때문에 할당이 안되었습니다. 위치에 값 할당이 아닌 `.insert` 메소드로 배열에 삽입하여 오류를 해결했습니다.
   -> `.append`가 아닌 `.insert`를 사용한 이유는 배열에 순서대로 할당한다기 보다는 `customerNumber`의 위치에 값을 할당하고 싶었기 때문에 원하는 위치에 값을 넣을 수 있는 `.insert` 메소드를 사용하였습니다.

- 과제에서 시키지 않은 기능을 마음대로 너무 많이 만들었나..싶습니다.....

###해결되지 않은 부분
 - 열거형 `Coffee` 의 존재 이유를 모르겠습니다. 제시문에서 열거형으로 선언하래서 하긴 했는데.. `menu` 딕셔너리의 키 값에 원시 값으로 넣긴 했지만 열거형이 없었다면 그냥 `yagombucksMenu` 선언 시 `["아메리카노": 1500]` 형식으로 하면 되지 않나요..?? 열거형을 어떻게 써먹어야할지 모르겠습니다ㅠㅠ
 - 연관된 값(Associated Value)를 써볼까 했지만
   `enum Coffee {
                case americano(String, Int) }
      var americano = Coffee.americano("아메리카노", 1500)`
     위처럼 사용했을 때 다른 메소드에서 가격을 불러올 방법을 모르겠어서 사용하지 않았습니다.

2024-09-02 15:06 UTC, jaemuYeo requested changes
Round3 스텝1도 잘 수행해주셨군요!
아무래도 타입 설계가 처음이다보니 손도 많이가고 어려운 부분이 많았죠??
그래도 너무너무 잘 해주셨어요 👍

코멘트 몇 가지 남겨두었으니 확인해주세요 :)

## 파일 분리
현재 선언한 모든 타입이 step1이라는 하나의 파일에 담겨있습니다!
타입별로 또는 관련 타입끼리 묶어 파일을 분리해보는 것도 좋을 것 같아요 😀

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +            return }
중괄호가 개행되지 않았네요! 컨벤션 이슈 👀

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    case vanilaLatte = "바닐라라떼"
해결하지 못한 부분에 대해 아래와 같이 사용해도 좋지만
이 곳에 연산프로퍼티를 활용하여 사용도 가능합니다!

```swift
enum Coffee: String {
    case americano = "아메리카노"
    case cafeMocha = "카페모카"
    case cafeLatte = "카페라떼"
    case vanilaLatte = "바닐라라떼"
    
    var price: Int {
        switch self {
        case .americano:
            return 1500
        case .cafeMocha:
            return 4000
        case .cafeLatte:
            return 4000
        case .vanilaLatte:
            return 4500
        }
    }
}
```

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +var yagombucksMenu: [String: Int] = [Coffee.americano.rawValue: 1500,
딕셔너리의 key 타입이 Coffee라면 배열안에 타입.케이스.rawValue 까지 작성할 필요없이 
.americano  .cafeMocha 와 같이 사용할 수 있을 것 같아요!

이 것을 포함한 전역변수(타입들의 인스턴스)들은 main 파일에 위치해있으면 보기편할 것 같아요!

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +            return self.enoughMoney = false }
끝에 중괄호 개행해주셔요!

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    func buyCoffee(priceCoffee: Int) {
네이밍에 Coffee가 명시되어있기에 매개변수명은 price로 간단히 해주셔도 좋습니다 :)

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    var menu = [String: Int]()
menu의 키값이 Coffee 타입이면 더 적절할 것 같아요 :)

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    var onHand: [String] = []
오호 손님입장에서 커피를 가지고 있는 것을 구현하신분은 처음인 것 같아요!
좋은 시도입니다 👍

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    var number: Int?
Number만으로는 어떤 것을 뜻하는지 잘 모르겠어요 🤔
대기 순번을 뜻하나요??

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    init(name: String, money: Int) {
이니셜라이저 잘 해주었군요! 👍
이니셜라이저도 여러개 만들 수 있어요~
Person 타입의 인스턴스 타입마다 초기화가 다를 수 있기에 거기에 따른 init을 설계해주는 것도 좋습니다 :)

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    func getCoffee(receive: String) {
receive 라는 매개변수명이 동사로 되어있는데 조금 더 한 문장처럼 읽히게 바꿔보는건 어떨까요~?

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    func makeCoffee(customerNumber: Int) {
함수의 네이밍은 `커피를 만들다`인데 매개변수명에 `고개 번호`가 있어
어떤 기능을 하는 함수인지 모호한 것 같습니다!
고객 번호를 다른 곳에서 주입받거나 인자 레이블을 통해 전치사로 조금 더 자연스럽게 만들어보는 것도 좋을 것 같아요 🙌

2024-09-02 15:06 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    func giveCoffee(customer: Person, customerNumber: Int) {
이 곳에도 위에와 같이 인자 레이블을 활용해보세요 💪

2024-09-03 12:10 UTC, Elin113 commented on CodeStarterCamp_Week3/step1.swift
> +            return }
수정했습니다!

2024-09-03 12:17 UTC, Elin113 commented on CodeStarterCamp_Week3/step1.swift
> +    case vanilaLatte = "바닐라라떼"
오 이런 방법이 있군요!!!! 수정하였습니다. 감사합니다!

2024-09-03 12:56 UTC, Elin113 commented on CodeStarterCamp_Week3/step1.swift
> +var yagombucksMenu: [String: Int] = [Coffee.americano.rawValue: 1500,
넵 딕셔너리 타입 수정했습니다!

2024-09-03 13:00 UTC, Elin113 commented on CodeStarterCamp_Week3/step1.swift
> +    func buyCoffee(priceCoffee: Int) {
넵 수정햇습니다!

2024-09-03 13:00 UTC, Elin113 commented on CodeStarterCamp_Week3/step1.swift
> +    var onHand: [String] = []
오 감사합니당!!

2024-09-03 13:02 UTC, Elin113 commented on CodeStarterCamp_Week3/step1.swift
> +    var number: Int?
넵 대기 순번입니다! waitingNumber로 변경하였습니당

2024-09-03 13:08 UTC, Elin113 commented on CodeStarterCamp_Week3/step1.swift
> +    func getCoffee(receive: String) {
메소드의 Coffee들을 없애고 buy, get만 남겼습니다. 그리고 receive를 coffee로 변경하여 한 문장처럼 읽힐 수 있도록 변경하였습니다!
```swift
func get(coffee: String) {
... }
```

2024-09-03 13:10 UTC, Elin113 commented on CodeStarterCamp_Week3/step1.swift
> +    func makeCoffee(customerNumber: Int) {
인자 레이블에 of를 추가하였습니다! `make Coffee (of customerNumber: Int)`으로 고객 번호 n번의 주문을 만든다는 의미로 작성하였습니다.

2024-09-03 13:13 UTC, Elin113 commented on CodeStarterCamp_Week3/step1.swift
> +    func giveCoffee(customer: Person, customerNumber: Int) {
customerNumber에 인자 레이블 to를 추가하고 두 매개변수의 위치를 바꾸어 주었습니다.
`func giveCoffee(to customerNumber: Int, customer: Person)` 
n번 손님에게 커피를 준다는 의미로 작성하였습니다.

2024-09-03 13:23 UTC, devBambu commented
@jaemuYeo 안녕하세요 잼킹! 이번에도 피드백 감사드립니다.

- 파일 분리 완료
- 열거형 Coffee 연산 프로퍼티 추가 및 menu 딕셔너리 키 타입 변경 완료
- 딕셔너리 키 타입 변경에 따른 `CoffeeShop.getOrder` 메소드 옵셔널 바인딩 추가
- 곳곳의 인자 레이블 추가 및 매개변수 명, 메소드 명 변경. 그에 따른 코드 수정

이제 처음보단 클래스와 구조체에 대해 쪼끔은 어떻게 쓰는 건지 알 것 같습니다..!!
복잡하긴 하지만 재미있네요ㅎㅎㅎ

2024-09-04 03:13 UTC, jaemuYeo requested changes
리뷰 반영하시느라 고생많으셨습니다!
몇 가지 코멘트 남겨두었으니 확인 부탁해요 :)

프로젝트 요구사항과 맞지 않는 부분이 있어 해당 사항만 수정해볼까요~?
단 건드리면 꽤 많은 코드를 수정해야할 거예요 ㅠㅠ
빠르게 수정 후 다음 스텝으로 넘어가요!! 💪

2024-09-04 03:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1-CoffeeShop.swift
> +var yagombucksMenu: [Coffee: Int] = [Coffee.americano: Coffee.americano.price,
Coffee.americano로 하셔도 좋지만 간결하게 .americano로도 표현할 수 있답니다 🙌

2024-09-04 03:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1-CoffeeShop.swift
> +    var pickUpTable: [String] = []
프로젝트 요구 사항에서 pickUpTable의 타입은 [Coffee] 입니다!

2024-09-04 03:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1-CoffeeShop.swift
> +    func getOrder(of customer: Person, order: String) {
order 매개변수가 커피타입이면 조금 더 적절할 것 같아요!
현재 함수 네이밍과 매개변수만으로는 어떤 것을 get order하는지 파악하기가 힘든 것 같습니다 🤔
order라는 단어 또한 겹치고있어 함수명을 변경해보아도 좋을 것 같아요!

2024-09-05 13:09 UTC, devBambu commented on CodeStarterCamp_Week3/step1-CoffeeShop.swift
> +    func getOrder(of customer: Person, order: String) {
입력받을 때 커피 이름으로 입력받는 게 값을 입력하는 입장에서 더 쉽지 않을까 싶어서 String으로 설정했었습니다. Coffee로 고치려면....너무 많은 부분을 고쳐야할 것 같은데 시간이 없어서 우선 그대로 두었습니다ㅠㅠ
매개변수 order는 좀더 명확히 하기 위해 coffeeOrder로 이름을 변경해 주었습니다.

2024-09-05 13:15 UTC, Elin113 commented
@jaemuYeo 안녕하세요 잼킹! 피드백 반영하여 수정하였습니다.

pickUpTable을 Coffee타입으로 바꾸면서 오류가 많이 나서 어려웠습니다.
옵셔널 값으로 변경하여 해결은 하였는데 .insert나 .remove 메소드를 사용할 때에도 ?를 같이 써줘야한다는 것을 몰랐어서 해결하는 데 시간이 걸렸네요.

getOrder의 order를 Coffee타입으로 받았으면 좀더 수월했을 것 같긴 한데 이미 타입 변경한 후에 피드백을 보기도 했고... 다시 다 변경하기엔 시간이 없어 우선 그대로 두게 되었습니다.
제일 처음 코드를 짤 때 입력할 때는 "아메리카노"와 같이 메뉴 이름으로 입력하는 게 함수를 사용하거나 이해하는 데 있어 더 쉽지 않을까 하고 String타입으로 설정해두었는데 너무 사람의 입장에서 생각했나 봅니다.
Step2에서 가능하다면 변경해볼 수 있도록 하겠습니다!

2024-09-06 08:03 UTC, jaemuYeo reviewed
지금도 충분히 훌륭한 코드가 된 것 같아요!! 👏
옵셔널 타입으로 설계한 경우 바인딩 처리가 번거롭긴하지만
안전하게 데이터를 처리할 수 있다는 장점이 너무크기에 적절하게 사용하시면 좋습니다!
5주간 리뷰받으며 학습하시느라 너무너무 고생많으셨습니다 🙏

2024-09-06 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/main.swift
> +yagombucks.getOrder(of: missKim, order: "아메리카노")
두번째 매개변수명이 수정되었는데 호출부에서 변경되지 않아 컴파일 에러를 발생시키고 있네요!

2024-09-06 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1-CoffeeShop.swift
> +var yagombucksMenu: [Coffee: Int] = [.americano: Coffee.americano.price,
.구문을 활용하여 사용하는 것이 열거형 case의 장점중 하나입니다!
다만 현재 가격을 확인하기위해서는 매번 Coffee타입을 들여다보아야하는 번거로움이 있는데요!
또는 만약 카페가 여러개 생기고 메뉴는 동일하지만 가격을 수정해야하는 경우 수정도 많이 어려울 것 같아요.
이전에 방법에 대해 소개해주었는데 직접적으로 값을 넣어도 괜찮을 것 같습니다 :)

2024-09-06 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1-CoffeeShop.swift
> +    var pickUpTable: [Coffee]? = []
오우! Coffee타입으로 리팩토링하셨군요! 생각보다 고칠 부분이 많았죠? 😭
픽업테이블이 비어있을 수도 있으니 옵셔널타입으로 해주신 것도 너무 좋아요 👍

2024-09-06 08:03 UTC, merged