[Round3] step2 - GOO
yagom-academy/swift-starter-week3 pull request #340
Opened 2024-09-03 14:41 UTC by Goohyun3436

@jaemuYeo
안녕하세요. 잼킹. 항상 자세한 리뷰 남겨주셔서 감사합니다!
이번 PR도 잘 부탁드립니다!

<br />

## 고민했던 점
### Coffee 열거형의 가격(연산 프로퍼티)을 변경하고 싶다면,,
- 이전에는 커피샵의 메뉴를 `menu: [Coffee, Int]` 딕셔너리 프로퍼티를 사용하여 사용자 정의로 초기화하였습니다.
- 즉, 인스턴트마다 다른 메뉴와 가격을 지정할 수 있었습니다.
- 이번 과제에서는 Coffee 열거형에서 연산 프로퍼티를 활용하여 가격을 정의하였습니다.
- 그러다보니, 모든 커피샵이 고정된 커피 종류와 가격을 갖습니다.
- 다음과 같은 경우에는 별도의 메뉴 딕셔너리를 작성하는 방식으로 접근해야하나요?
  - iceAmericano의 가격을 3000원으로 바꾸고 싶을 때
  - 메뉴를 추가하거나 삭제하고 싶을 때
- 더 좋은 방법이 있을까요?
```swift
enum Coffee: String {
    case iceAmericano = "아이스아메리카노"
    case hotAmericano = "뜨거운아메리카노"
    case iceChoco = "아이스초코"
    case hotChoco = "핫초코"
    case milkTea = "밀크티"
    
    var price: Int {
        switch self {
        case .iceAmericano:
            return 2000
        case .hotAmericano:
            return 1500
        case .iceChoco:
            return 4500
        case .hotChoco:
            return 4000
        case .milkTea:
            return 5000
        }
    }
}
```
<br />

## Person 구조체
- 프로퍼티 감시자를 사용하여 `money` 값이 변경될 때 마다 `money`를 출력하도록 하였습니다.
- Person 구조체 인스턴스의 `buyCoffee` 메서드를 호출 시에 CoffeeShop 클래스 인스턴스의 `order` 메서드를 호출하도록 하여, 인스턴스 간의 상호작용을 구현하였습니다.
- 주문 후에 바로 Person 구조체 인스턴스의 money 프로퍼티를 업데이트 해주었습니다.
```swift
struct Person {
    ...
    var money: Int = 0 {
        didSet {
            printMoney()
        }
    }
    ...
    
    mutating func buyCoffee(_ coffees: [Coffee], shop: CoffeeShop) {
        ...
        shop.order(coffees, by: self)
        self.money = remainMoney
    }
}
```

## CoffeeShop 클래스
- `buyer`(구매자) 프로퍼티는 초기값을 할당하지 않아도 된다고 판단하여, 암시적 추출 옵셔널로 정의하였습니다.
- `buyer` 프로퍼티는 `printPickUpTable()` 메서드에서 구매자를 부를 때 사용됩니다.
- 프로퍼티 감시자를 사용하여 `pickUpTable` 값이 변경될 때 마다 `pickUpTable`을 출력하도록 하였습니다.
- 프로퍼티 감시자를 사용하여 `revenue` 값이 변경될 때 마다 `revenue`를 출력하도록 하였습니다.
```swift
class CoffeeShop {
    ...
    var buyer: Person!
    var pickUpTable: [Coffee] = [] {
        didSet {
            printPickUpTable()
        }
    }
    var revenue: Int = 0 {
        didSet {
            printRevenue()
        }
    }

    func order(_ coffees: [Coffee], by buyer: Person) {
        guard let (pickUpTable, totalAmount): ([Coffee], Int) = makeOrders(with: coffees) else {
            return
        }
        
        self.buyer = buyer
        self.pickUpTable = pickUpTable
        self.revenue += totalAmount
    }
}
```

2024-09-04 09:13 UTC, jaemuYeo requested changes
스텝2의 목적인 프로퍼티 옵저버를 적절하게 잘 사용해주셨군요!!
몇 가지 코멘트 남겨두었습니다 😀
확인 후 큰 이슈가 없다면 Merge 진행하겠습니다!

2024-09-04 09:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/main.swift
>  missKim.buyCoffee(orderList, shop: yagombucks)
앗 orderList 변수를 넣는 것보다 매개변수 안에 [.커피1, .커피2] 처럼 넣는 것이 자연스러워보여요!
Person마다 다르게 음료를 주문할테니까요! ㅎㅎ

2024-09-04 09:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/person.swift
> +        print("잔액이 \(self.money)원 남았습니다.")
이 곳에도 `~~의` 잔액이 ㅇㅇ원 남았습니다 처럼 이름을 명시해주면 좋을 것 같아요 :)

2024-09-04 09:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/person.swift
> +        didSet {
프로퍼티 옵저버를 잘 활용해주셨군요! 👍

2024-09-04 09:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/coffee.swift
> +            case .iceAmericano:
일반적인 컨벤션은 case를 들여쓰기하지 않아요!
```swift
    var price: Int {
        switch self {
        case .iceAmericano:
            return 2000
        case .hotAmericano:
            return 1500
        case .iceChoco:
            return 4500
        case .hotChoco:
            return 4000
        case .milkTea:
            return 5000
        }
    }
```

2024-09-04 09:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/coffee.swift
> +    var price: Int {
연산프로퍼티를 활용한 가격 표시 좋습니다 👏

2024-09-04 09:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/person.swift
>      mutating func buyCoffee(_ coffees: [Coffee], shop: CoffeeShop) {
첫 번째 매개변수가 복수형으로 되어있는데 하나만 주문할 경우는 어떻게 될까요?
단수형과 복수형 중 어떤 표현이 적절할까요?

2024-09-04 09:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/person.swift
> +        guard remainMoney >= 0 else {
guard문 활용이 적절하군요 👍

2024-09-04 09:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/person.swift
>      func calculateTotalAmount(items: [Coffee], at shop: CoffeeShop) -> Int? {
이 곳의 첫 번째 매개변수명은 왜 다른 곳의 Coffee타입들의 명들과 다르게 items인가요?🤔

2024-09-04 09:13 UTC, jaemuYeo commented on CodeStarterCamp_Week3/person.swift
> +        let remainMoney: Int = calculateRemainMoney(with: totalAmount)
remainMoney 의 네이밍의 번역이 조금은 부자연스럽게 느껴집니다!
남은 돈을 의미하려면 remainingMoney가 조금 더 적절하지 않을까 생각해요 :)

2024-09-05 02:37 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/main.swift
>  missKim.buyCoffee(orderList, shop: yagombucks)
예외 처리를 체크하실 때 편하도록 경우별 변수를 따로 빼두었습니다.

- `orderList` 변수를 제거하고 매개변수에 Array를 바로 전달하도록 수정하였습니다.

2024-09-05 02:41 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/person.swift
> +        print("잔액이 \(self.money)원 남았습니다.")
- Person 구조체의 printMoney 메서드에 이름도 같이 출력하도록 수정하였습니다.

2024-09-05 02:43 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/person.swift
> +        didSet {
이전에는 buyCoffee 메서드에서 printMoney 메서드를 호출하였는데, 프로퍼티 옵저버를 활용하니 buyCoffee 메서드의 목적이 뚜렷해지는 것 같습니다!

2024-09-05 02:47 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/coffee.swift
> +            case .iceAmericano:
xcode에서 `ctrl+i` 단축어로 코드 자동 정렬을 했는데, 자동으로 들여 써진 것 같습니다.
 
- switch-case 문의 들여쓰기를 제거하였습니다.

2024-09-05 02:49 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/coffee.swift
> +    var price: Int {
Coffee 열거형을 재사용할 때에 가격을 변경하지 못하는 부분이 조금 아쉬웠습니다.
(위의 `고민했던 점` 에 자세한 설명을 적어뒀습니다.)

2024-09-05 02:49 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/person.swift
> +        guard remainMoney >= 0 else {
guard 문을 애용하게 될 것 같습니다 ㅎㅎ

2024-09-05 02:55 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/person.swift
>      mutating func buyCoffee(_ coffees: [Coffee], shop: CoffeeShop) {
coffees 매개변수는 Array 컬렉션 타입으로 정의하였습니다.
배열의 요소가 1개일 수는 있지만, 배열 자체는 여러 개의 요소를 포함할 수 있다는 의미를 갖고 있기 때문에,
복수형을 사용하는 것이 좀 더 일관성이 있어, 복수형 표현이 적절하다고 생각합니다.
또, 다른 누군가가 제 코드를 봤을 때, 가독성이나 유지보수 측면에서도 coffees(복수형) 표현이 좀 더 적절할 것 같습니다!

2024-09-05 03:04 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/person.swift
>      func calculateTotalAmount(items: [Coffee], at shop: CoffeeShop) -> Int? {
`calculateTotalAmount` 메서드는 커피 외에도 여러 품목들을 구매할 때에 재사용할 수 있다고 판단하여 items 파라미터를 사용했습니다.
이번 과제에서는 커피만 다루기 때문에 해당 부분은 coffees 로 표현하는게 더 적절한 것 같습니다.

- 매개변수명을 items -> coffees 수정하였습니다.

2024-09-05 03:09 UTC, Goohyun3436 commented on CodeStarterCamp_Week3/person.swift
> +        let remainMoney: Int = calculateRemainMoney(with: totalAmount)
앗! 감사합니다. 혼자서 코드를 짜다 보니 놓쳤던 부분입니다!!

- 남은 돈을 의미하는 변수명 remainMoney -> remainingMoney 으로 수정하였습니다.

2024-09-05 03:11 UTC, Goohyun3436 commented
@jaemuYeo 
안녕하세요. 잼킹. GOO 입니다.
이번 PR도 꼼꼼하게 확인해주셔서 감사합니다.

남겨주신 코멘트를 확인 후 코드에 반영하였습니다. 감사합니다!!

2024-09-05 10:10 UTC, jaemuYeo commented on CodeStarterCamp_Week3/coffee.swift
> +            case .iceAmericano:
XCode를 너무 믿으면 안돼요 ㅎㅎㅎㅎㅎㅎ

2024-09-05 10:11 UTC, jaemuYeo commented on CodeStarterCamp_Week3/coffee.swift
> +    var price: Int {
아! 제가 놓친 부분이 있었네요 확인해보겠습니다 :)

2024-09-05 10:27 UTC, jaemuYeo reviewed
열거형의 가격을 변경하고 싶을때의 부분에 대해서만 얘기하고 Merge진행하겠습니다!
Round3도 너무너무 고생많으셨어요!

일단 열거형또한 `값타입`이기에 컴파일 시점에 값이 고정되므로 rawValue값들을
런타임 시점에 변경하는 것은 어렵습니다.
다만 커피숍 객체마다 다른 가격을 주고싶다면 현재의 방법과는 다르게 접근해야할 것 같아요.
구조체를 통해 커피숍 객체를 만들고 메뉴는 메뉴대로 가격은 프로퍼티로 따로 빼는 것이 좋을 것 같습니다!

2024-09-05 10:27 UTC, merged