[Round3]Step 1 - sy
yagom-academy/swift-starter-week3 pull request #343
Opened 2024-10-02 13:52 UTC by jeseoyoung

### main.swift
- Person의 인스턴스인 misterLee, missKim 추가
- CoffeeShop의 인스턴스인 yagombucks 추가 및 바리스타 할당

### step1.swift
- Person struct 정의
- Coffee enum 정의
- CoffeeShop struct 정의(pickUpTable은 비어있을 수도 있기 때문에 옵셔널로 지정해봤습니다!)

@jaemuYeo 감사합니다🙂

2024-10-04 06:12 UTC, jaemuYeo requested changes
Round3 입성 축하합니다 🥳
코멘트 확인해주세요 :) 제가 남겨놓은 질문에 대해서는 답변 남겨주세요!

## 파일 분리
현재 step1이라는 파일에 모든 타입이 선언되어있군요!
이제는 파일 분리도 조금씩 신경써주면 좋습니다.
타입별로 파일을 분리하여 작성해보면 좋을 것 같아요 :)
분리 시 커밋도 신경써주세요!

2024-10-04 06:12 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    var sales: Int = 1000000
매출의 기본값이 설정되어있는 것은 시재인가요~?

2024-10-04 06:12 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +struct Person {
Person 타입을 구조체로 선언한 이유가 궁금합니다!
또한 이니셜라이저를 설정하지 않은 이유도요 🤔

2024-10-04 06:12 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    var appearance: String
오우 appearance를 프로퍼티로 설계하신 분은 처음 보네요!! ㅎㅎ 👍

2024-10-04 06:12 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    var budget: Int = 100000
예산에 초기값을 준 이유는 무엇인가요?
인스턴스로 생성한 사람마다 가지고 있는 돈은 다를텐데요!

2024-10-04 06:12 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    mutating func buyCoffee() {
mutating 키워드는 왜 붙여야했나요??

2024-10-04 06:12 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +        self.budget = self.budget - 5000
5000은 무엇을 의미하나요?

2024-10-04 06:12 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    var menu: Dictionary<Coffee, Int> = [
메뉴라는 것은 CoffeeShop의 인스턴스마다 다를 수 있으니 이 곳에는 타입만 지정해주고
인스턴스 생성시 구성해주는 것은 어떻게 생각하시나요??

2024-10-04 06:12 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    mutating func getOrder(is order: Coffee) {
get Order is order를 번역하면 주문은 주문이다로 되는데요!
takeOrder(to coffee) 또는 takeOrder(for coffee) 등으로 조금 더 자연스러운 문장으로 표현해볼 수 있을 것 같아요 :)

2024-10-04 06:12 UTC, jaemuYeo commented on CodeStarterCamp_Week3/step1.swift
> +    mutating func makeCoffee(is order: Coffee) {
해당 함수도 조금 더 자연스럽게 문장을 만들어보면 좋을 것 같아요!

2024-10-04 14:17 UTC, jeseoyoung commented
### Main.swift (질문 하나 포함)
- Person의 예산 기본값을 삭제함으로써 인스턴스 생성 시 입력하도록 변경.
- CoffeeShop의 메뉴, 예산 기본값을 삭제함으로써 인스턴스 생성 시 입력하도록 변경.
- Person이 buyCoffee()를 할 경우에 **&yagombucks**에서 구매하라고 코드를 추천받았는데, 왜 &를 사용해야 하는지 알 수 있을까요?

### Coffee.swift, CoffeeShop.swift, Person.swift
- 파일을 분리하였습니다.

### CoffeeShop.swift
- 구조체에서 클래스로 타입을 변경하였습니다.(클래스와 구조체를 하나씩 구현해보고 싶어서 이외의 특별한 이유는 없습니다🤔)
- 이니셜라이저를 추가하였습니다.
- 메뉴를 인스턴스 생성 시 추가하도록 변경하였습니다.
- 함수들의 문장을 자연스럽게 변경하였습니다.
- if let문을 guard let으로 변경하였습니다.(마찬가지로 연습해보고 싶어서 바꿔보았습니다.)

### Person.swift
- 이니셜라이저를 추가하였습니다.
- 예산의 기본값을 제외하였습니다.
- 커피 구매 시 예산을 적절하게 감소하도록 수정하였습니다.

2024-10-05 14:24 UTC, jeseoyoung commented
그리고 분리 시 커밋을 신경써달라고 하셨는데 이번 커밋에서 잘못된 점이 있을까요?

2024-10-07 07:51 UTC, jaemuYeo reviewed
수정하시느라 고생많으셨습니다!
지난 제가 남긴 코멘트의 질문에 아직 답변을 받지 못했어요 😭
틀려서 드린 질문이아니라 수정만 하는 것이 아닌 이유에 대해 답글로 남겨주시면
많이 도움 될 것 같아요 🙏

### Person이 buyCoffee()를 할 경우에 &yagombucks에서..
&를 붙여아하는 이유는 buyCoffee함수의 첫 번째 파라미터에 inout키워드를 사용해서 입니다!
inout파라미터에 대해 조사해보시면 좋을 것 같아요.
inout 파라미터를 사용한 이유도 궁금합니다!

기능적으로 큰 문제는 없어 이번 스텝은 Merge 하겠습니다 👏
단 다음 스텝으로 넘어가기 전 제가 이전에 남겨둔 질문과 inout 파라미터에 대해
학습 후 넘어가시면 좋을 것 같아요 😀

2024-10-07 07:51 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    init(interior: String, sales: Int, menu: Dictionary<Coffee, Int>, pickUpTable: [Coffee?] = [Coffee?](), barista: Person) {
위의 변수에서 값을 초기화 한 경우에는 꼭 init하지 않아도 돼요!
init은 인스턴스를 만드는 입맛에 따라 다양한 방식으로 초기화할 수 있게
여러개 생성도 가능하답니다 🙌

2024-10-07 07:51 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +class CoffeeShop {
이전에는 구조체였는데 클래스로 변경한 이유는 무엇때문인가요~?

2024-10-07 07:51 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    func takeOrder(for order: Coffee) {
for order보다는 for coffee가 더 자연스러운 문장 같아요 :) (커피 주문을 받다)

2024-10-07 07:51 UTC, merged

2024-10-07 15:46 UTC, jeseoyoung reviewed
죄송합니다! 제 코멘트들이 Pending 상태인 것을 지금 확인했네요😭😭

2024-10-07 15:46 UTC, jeseoyoung commented on CodeStarterCamp_Week3/step1.swift
> +    var sales: Int = 1000000
아닙니다! 매출 역시 커피샵마다 다르므로 지워야 할 것 같습니다

2024-10-07 15:46 UTC, jeseoyoung commented on CodeStarterCamp_Week3/step1.swift
> +    var budget: Int = 100000
"커피를 사면 budget에서 무조건 차감해야 하니까"라는 생각을 하고 적당한 값을 넣어줬던 것 같네요😞 해당 값은 지우도록 하겠습니다!

2024-10-07 15:46 UTC, jeseoyoung commented on CodeStarterCamp_Week3/step1.swift
> +    mutating func buyCoffee() {
해당 구조체 내 예산(budget 프로퍼티)을 차감하기 위해서 mutating이 필요한 것 같아 붙였습니다

2024-10-07 15:46 UTC, jeseoyoung commented on CodeStarterCamp_Week3/step1.swift
> +        self.budget = self.budget - 5000
아무 의미 없습니다 수정하는 것을 깜빡했습니다...😣😣

2024-10-07 15:46 UTC, jeseoyoung commented on CodeStarterCamp_Week3/step1.swift
> +struct Person {
구조체로 선언한 이유는 Choosing Between Structures and Classes(https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes) 에서 클래스를 사용해야 하는 경우에 속하지 않는다고 생각해서입니다!
이니셜라이저는 깜빡했습니다...ㅎㅎ 그거와는 별개로 이니셜라이저의 필요성이 아직 잘 이해가 안되는 것 같네요😭

2024-10-07 15:46 UTC, jeseoyoung commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +class CoffeeShop {
두 타입 모두 만드는 연습을 해보고 싶어서 바꿔봤습니다🤔🤔

2024-10-07 15:46 UTC, jeseoyoung commented on CodeStarterCamp_Week3/step1.swift
> +    var menu: Dictionary<Coffee, Int> = [
여기에 댓글 남기는 걸 깜빡했네요😣 실제로 커피샵마다 가격이 다르니 좋은 아이디어라고 생각했습니다 ㅎㅎ

2024-10-07 16:02 UTC, jeseoyoung commented
> &를 붙여아하는 이유는 buyCoffee함수의 첫 번째 파라미터에 inout키워드를 사용해서 입니다! inout파라미터에 대해 조사해보시면 좋을 것 같아요. inout 파라미터를 사용한 이유도 궁금합니다!

제가 이해한 게 맞다면, inout 파라미터는 C언어의 포인터 파라미터와 비슷한 개념인 것 같네요...🤔
챗GPT가 inout을 추천해줘서 작성해봤습니다!

피드백 감사합니다🙂🙂