[Round3] Step1 - tomchoi95
yagom-academy/swift-starter-week3 pull request #344
Opened 2024-10-04 09:08 UTC by tomchoi95

@jaemuYeo

감사합니다.

2024-10-07 08:03 UTC, jaemuYeo requested changes
Round3 입성을 축하합니다 🥳
타입 설계하는 것이 생각보다 어렵죠? ㅎㅎ
코드에 라인별 코멘트 남겨드렸습니다!!

### 파일 분리
현재 Person, CoffeeShop, Coffee 총 세개의 타입이 선언되었는데
cafe라는 파일 하나에 모두 구현되어있네요!
타입별로 분리하여 작성해보는 것도 좋을 것 같아요 :)

2024-10-07 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/cafe.swift
> +struct Person {
Person 타입은 왜 구조체로 선언하셨나요~? 🤔

2024-10-07 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/cafe.swift
> +    var money: Int = 0
money를 초기값 0으로 준 이유가 궁금해요!

2024-10-07 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/cafe.swift
> +    func buyCoffee() {
buyCoffee의 기능이 조금 더 구체적이였으면 좋겠어요!
Coffee관련된 것들은 CoffeeShop타입, Coffee타입과 소통해야한답니다 💪

2024-10-07 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/cafe.swift
> +enum Coffee :String {
콜론 띄어쓰기가 잘 못되었어요! ㅎㅎ

2024-10-07 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/cafe.swift
> +struct CoffeeShop {
해당 타입이 구조체인 이유도 궁금합니다!

2024-10-07 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/cafe.swift
> +    let menu: [Coffee:Int] = [.americano:3000,.cafeLatte:3500,.cappuccino:3500,.espresso:3000,.latteMacchiato:3500]
이렇게 CoffeeShop 타입에 메뉴와 가격을 책정해버리면
만약 야곰벅스뿐만아니라 야곰다방, 이디야 ... 등등 카페가 생길때마다 타입을 새로 만들어줘야하는데요!
인스턴스 생성시 메뉴와 가격을 지정해주려면 어떻게 해야할까요?

### 컨벤션은 아래와 같습니다!
띄어쓰기 참고해주세요.

```swift
let menu: [Coffee: Int] = [.americano: 3000, .cafeLatte:3500, .cappuccino:  3500, .espresso:3000, .latteMacchiato: 3500]
```

2024-10-07 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/cafe.swift
> +    mutating func makeCoffee() {
mutating키워드는 어떤 경우에 사용해야했나요?

2024-10-07 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/cafe.swift
> +    var pickUpTable: [(String,String)] = []
튜플의 컨벤션도 띄어쓰기가 있습니다!
pickUpTable과 orderList를 튜플로 지정한 이유도 궁금해요!

2024-10-07 08:03 UTC, jaemuYeo commented on CodeStarterCamp_Week3/cafe.swift
> +    case americano = "아메리카노"
케이스별로 rawValue를 지정해주었군요!! 👏

2024-10-07 09:56 UTC, tomchoi95 commented on CodeStarterCamp_Week3/cafe.swift
> +struct Person {
스위프트 문서에서 default로 structure를 채택하라고 나와서 그렇게 해보았습니다.
하지만 나중에 Person type을 상속하는 Barista라는 타입을 새로 만드려 한다면 class로 하는것이 좋다고 생각 하였고 수정 진행 해 보겠습니다!

2024-10-07 09:59 UTC, tomchoi95 commented on CodeStarterCamp_Week3/cafe.swift
> +    var money: Int = 0
사실 큰 생각 없이 property로 돈을 갖는다라고 써 있어서 만든 것인데 이 property를 이용하여 커피를 사고 마시고 하는 것을 구현한다면 init을 활용하여 초깃값을 넣어주는 것이 좋을 것 같네요!

2024-10-07 10:01 UTC, tomchoi95 commented on CodeStarterCamp_Week3/cafe.swift
> +    func buyCoffee() {
money property와 연계하고, CoffeeShop타입, Coffee타입과 소통해야할 수 있게 구현해 보겠습니다!

2024-10-07 10:04 UTC, tomchoi95 commented on CodeStarterCamp_Week3/cafe.swift
> +    mutating func makeCoffee() {
structure에서 method를 이용하여 property를 수정할 때 사용해야 했습니다!

2024-10-07 10:09 UTC, tomchoi95 commented on CodeStarterCamp_Week3/cafe.swift
> +    var pickUpTable: [(String,String)] = []
띄어쓰기 수정 하겠습니다.
튜플로 지정한 이유는 바리스타가 "\(name)님 주문하신 \(coffee) 나왔습니다"를 구현하고 싶어서 이름과 커피가 한 쌍이 되도록 하고싶었습니다.

2024-10-07 10:13 UTC, tomchoi95 commented on CodeStarterCamp_Week3/cafe.swift
> +struct CoffeeShop {
사실 위와 같은 이유로 큰 의미는 없었지만, 상속하지 않을 의도라면 구조체로 이용해도 될 거라고 생각합니다.
하지만 여기서 이견이 있다면 들어보고 싶습니다!

2024-10-10 03:51 UTC, tomchoi95 commented on CodeStarterCamp_Week3/cafe.swift
> +struct Person {
다시 해보니 인스턴스끼리 상호작용이 힘드네요 class로 수정 해 보았습니다.

2024-10-10 03:54 UTC, tomchoi95 commented on CodeStarterCamp_Week3/cafe.swift
> +struct CoffeeShop {
다시 해보니 인스턴스끼리 상호작용이 힘드네요 class로 수정 해 보았습니다.

2024-10-10 04:02 UTC, tomchoi95 commented
@ jaemuYeo

person 객체에서 주문하는 메서드 추가 하였습니다.

2024-10-10 08:16 UTC, jaemuYeo reviewed
Step1 고생많으셨습니다!!
제가 월요일 저녁 급히 지방에 내려갈 일이 있어서 리뷰가 많이 늦어졌네요 ㅠㅠ
미리 양해구했어야했는데 죄송해요 🙏
이번 스텝은 merge 진행하겠습니다!
다음 스텝에서 만나요!

2024-10-10 08:16 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +    func placeOrder (_ coffee: Coffee, at cafe: CoffeeShop) {
앗 함수명과 매개변수 사이 띄어쓰기가 되었어요ㅎㅎ
함수명은 꼭 place를 붙이지 않아도 order만으로 충분할 것 같습니다!

2024-10-10 08:16 UTC, jaemuYeo commented on CodeStarterCamp_Week3/main.swift
> +var starbucks: CoffeeShop = CoffeeShop(menu: [.americano: 1000, .latteMacchiato: 1500, .cappuccino: 2000], barista: tom)
인스턴스 생성시 줄길이가 길어지거나 컬렉션에 여러 값을 넣어야할때 개행을 적적히 해주면 좋습니다!
```swift
// 예시일뿐 컨벤션은 팀마다 다를 수 있습니다!
var starbucks: CoffeeShop = CoffeeShop(
    menu: [
    .americano: 1000,
    .latteMacchiato: 1500,
    .cappuccino: 2000
], barista: tom)
```

2024-10-10 08:16 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    var orderList: [(Coffee, String)] = []
이전에 튜플에 대해 여쭤보았던 이유는 한 가지는 coffee 종류중 하나가 들어올 것이다라는 것이 예상이되는데
String에는 Person.name이 들어올 것이 예상되지 않아 여쭤보았어요! ㅎㅎ 👍

2024-10-10 08:16 UTC, merged