[Round3] Step2 - tomchoi95
yagom-academy/swift-starter-week3 pull request #346
Opened 2024-10-10 13:30 UTC by tomchoi95

@jaemuYeo

2024-10-11 07:27 UTC, jaemuYeo requested changes
Step2도 고생많으셨습니다!!
이번 스텝은 지난 스텝에서 조금만 변형하면 되는 것이라 라인리뷰가 아닌 코멘트로 대체하겠습니다 :)

## 열거형 연산프로퍼티 활용
현재 Coffee타입에 rawValue로 String타입을 주어 전달하고있는데
만약 여러가지 설정이 필요하다면 아래와 같은 방식도 추천드립니다!
```swift
enum Coffee {
    case americano
    case cafeLatte
    case cappuccino
    case espresso
    case latte
    case macchiato
    case latteEspresso
    case latteMacchiato
    case water
    case milk
    
    var name: String {
        switch self {
        case .americano:
            return "아메리카노"
        case .cafeLatte:
            return "카페라떼"
        case .cappuccino:
            return "카푸치노"
        case .espresso:
            return "에스프레소"
        case .latte:
            return "라떼"
        case .macchiato:
            return "마끼야또"
        case .latteEspresso:
            return "라떼에스프레소"
        case .latteMacchiato:
            return "라떼마끼야또"
        case .water:
            return "물"
        case .milk:
            return "우유"
        }
    }
    
    var price: Int {
        switch self {
        case .americano:
            return 1000
        case .cafeLatte:
            return 1500
        case .cappuccino:
            return 2000
        case .espresso:
            return 3000
        case .latte:
            return 4000
        case .macchiato:
            return 5000
        case .latteEspresso:
            return 6000
        case .latteMacchiato:
            return 7000
        case .water:
            return 500
        case .milk:
            return 1000
        }
    }
    
    var englishName: String {
        switch self {
        case .americano:
            return "americano"
            // 이하 생략
        }
    }
}
```
이렇게 사용하면 사용하는 곳에서 .rawValue가 아닌 .name / .price 등으로 사용가능합니다!

## 요구사항 불충족
프로젝트를 진행할때 요구사항과 일치하는 것이 아주 중요한 부분입니다.
현재 Todo의 요구사항 중 order메서드는 `by name: String` 파라미터가 생략되었고
make메서드 또한 일치하지 않습니다.
조건에 맞게 수정 후 재요청 부탁드립니다!! 💪

## 커밋 메시지
이번 스텝2를 수행하며 이것저것 수정된 사항이 많은데
하나의 커밋으로 마무리된 것이 아쉽게 느껴졌습니다!

2024-10-16 11:35 UTC, tomchoi95 commented
@jaemuYeo

열거형에 변수 프로퍼티 생성
- 위의 예시처럼 rawValue보다 switch case로 만드는 것이 이점이 매우 많은 것 같아 수정.

조건을 만족하기 위해 Person class의 order 메서드 수정
- by name: String 파라미터 추가.

메서드 통합 수정 및 삭제
- Person.order()가 조건에 맞추어 CoffeShop.make()를 호출하기 위해 CoffeShop의 메서드를 통합 및 수정

2024-10-18 07:38 UTC, jaemuYeo reviewed
tomchoi님 5주간 학습하며 프로젝트 진행하시느라 고생많으셨습니다!!
이번 스텝에서 매개변수를 수정하며 손볼 곳이 많았을텐데 잘 수행해주신 것 같아요 👍
커밋 메시지에는 `카르마 커밋 컨벤션`을 적용해보면 좋겠어요!

앞으로도 멋진 개발자가 될 수있길 항상 응원하며
저희 야곰아카데미가 조금이나마 도움의 발판이 되었길 바랍니다.

감사합니다!

2024-10-18 07:38 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Coffee.swift
> +    var name: String {
지난번 전달해드렸던 방법에 대해 시도해보셨군요!!
사용하지 않는 것들은 당장에 작성해두지 않아도 좋아요 :)

2024-10-18 07:38 UTC, merged