Week3 [Step1] JeeeeSang
yagom-academy/swift-starter-week3 pull request #40
Opened 2022-02-24 06:10 UTC by JeeeeSangRyul

열거형의 타입을 클래스 안에 저장 프로퍼티로 할다하여 활용하는 방법에 대해 고민이 해봤습니다.
감사합니다~ 좋은하루되세요~

@Monsteel

2022-02-25 04:05 UTC, Monsteel requested changes
안녕하세요 상률님 ~
Week3, Step1 진행하시느라 수고 많으셨습니다.

코드에 대한 코멘트를 몇개 남겨보았습니다. 확인 부탁드리구요!

Step1에서는 해당하지 않는 내용들(다음 Step에서 구현해야 하는 것들)이 포함되어 있는것 같습니다.
이번 PR에서는 Step1에 해당하는 코드만 남겨두고, 나머지 코드는 제거 부탁드립니다 🙏

2022-02-25 04:05 UTC, Monsteel commented on CodeStarterCamp_Week3/Step1.swift
> +    case Americano = 4500
enum의 rawValue 개념을 활용하여, 가격을 가질 수 있도록 해주셨네요!
하지만 `rawvlaue == 가격` 라는 것을 항상 보장할 순 없습니다.

Coffe의 가격을 조금 더 명확하게 표현할 수 있는 방법은 없을까요?


> hint keyword :` var price` / `switch`

2022-02-25 11:05 UTC, JeeeeSangRyul commented on CodeStarterCamp_Week3/Step1.swift
> +    case Americano = 4500
rawvalue를 없애주고 열거형안에 함수를 설정하여 보다 명확하게 표현해주었습니다. 함수는 Int로 반환하게 하여 나중에
얼마를 팔았는지도 알수있습니다.

2022-02-28 06:44 UTC, Monsteel approved these changes
수고많으셨습니다~ ☀️

> Step1에서는 해당하지 않는 내용들(다음 Step에서 구현해야 하는 것들)이 포함되어 있는것 같습니다.
이번 PR에서는 Step1에 해당하는 코드만 남겨두고, 나머지 코드는 제거 부탁드립니다 🙏

에 대한 부분은 제가 오해한 부분이 있었습니다😓  양해부탁드립니다 🙏

2022-02-28 06:45 UTC, merged