3 yeeton
yagom-academy/swift-starter-week3 pull request #41
Opened 2022-02-24 07:05 UTC by yeeton37

@YebinKim 
안녕하세요 비비!!

Week3-Step 1 과제 제출합니다.

이번 과제는 클래스, 인스턴스 ,구조체 등등 개념 이해하는 데 많은 시간을 쏟았습니다. (매우 헷갈렸어요..)

제가 코드를 작성하면서 가장 고민했던 점 두가지는

1. CoffeeShop 타입의 인스턴스로 yagombucks 을 생성해봅시다. 라는 조건의 과제가 있었는데,
```
var yagombucks: CoffeeShop = CoffeeShop(menu: [.coldBrew : 4500], sales: "$300", pickUpTable: 1, barista: misterLee)
```
저는 이렇게 구현을 해주었습니다.
menu: [.coldBrew : 4500] 이렇게 쓴 이유는 enum 으로 선언했던 Coffee의 coldBrew를 가져왔기 때문입니다. 
위에서 menu를 딕셔너리 타입으로 선언해준 이유는 커피 이름과 가격을 저장하도록 하기 위함이었는데요,
위의 코드에서 인스턴스 yagombucks에서 menu를 선언할 때 딕셔너리의 키값만 써주면 자동으로 value인 가격 4500이 출력되도록 하고 싶었는데, 저 부분은 타입에 맞추어 [String : Int] 의 값을 선언해주는 부분이었기 떄문에 아예 잘못된 생각이었을까요?

그 방법을 찾지 못해서 [.coldBrew : 4500]를 똑같이 써주게 돼었습니다.. 저 부분은 저렇게 써주는 것이 맞는건지 궁금합니다.ㅜㅜ

2. 두 번째 고민했던 점은, 
```
var yagombucks: CoffeeShop = CoffeeShop(menu: [.coldBrew : 4500], sales: "$300", pickUpTable: 1, barista: misterLee)
```
에서 barista에 misterLee 라고만 써주니까 오류가 났었습니다. 
그 이유는 제가 스스로 찾아보았는데, 윗부분에서 선언해줄 때 barista: String 이라고 선언을 해주었더라구요
저는 misterLee 라는 인스턴스 "자체"를 할당해주고 싶었던 것이지, 문자열로 misterLee를 할당해주고 싶었던 것이 아니었기 때문에
고민을 해보다가 barista의 타입을 Person으로 선언해주었습니다. 이렇게 하니까 오류가 나지 않더라구요!! (유레카)

제가 쓴 두 방법이 맞는지 의문이 듭니다. 뭔가 코드에서 효율성이 떨어지는 것 같기도 하구요.. 
더 좋은 코드를 쓰고 싶으나 머리가 여기까지만 돌아가네요 히히 

잘 부탁드려요 비비~

2022-02-25 16:59 UTC, yeeton37 reviewed
비비 안녕하세요><
리뷰 기다리는동안 코드를 다시 분석해보았는데요,,!! 제가 비효율적으로 작성한 코드가 많더라구요..ㅜㅜ 
두번 보니까 왜 이제서야 보이는건지,, 제가 바꿔본 것들 아래에 작성해보았습니다.

1. 열거형 Coffee 타입 내부의 커피 이름을 대문자->소문자로 변경해주었습니다.
2. Person 클래스 내에서 name 상수를 선언해주었습니다.
3. CoffeeShop 클래스 내에서 sales의 초기값을 0으로 설정해주었고, pickUpTable이 없는 경우도 있을 것 같아서 옵셔널 선언해주었습니다. 또, 커피샵에 고객도 변수로 추가해줬고 고객이 없는 경우를 대비해서 옵셔널 설정해주었습니다!
4. CoffeeShop 클래스 내부 함수 makeCoffee 의 내부 구문을 너무 비효율적으로 써서 아예 바꿔주었습니다. (if문을 안써도 되는데 굳이 써줬었음..)
5. 인스턴스 yagombucks에 CoffeeShop을 선언해줄 때 sales와 barista만 입력받을 수 있도록 설정을 바꿔보았습니다. ㅎㅎ

번거롭게 해서 죄송해용 비비 ㅠㅠ

2022-02-27 13:03 UTC, YebinKim requested changes
예톤님 안녕하세요 😆
Week3 프로젝트에 오신 것을 환영해요! 🥳🎉

이번 프로젝트에서는 처음으로 타입을 직접 정의해보고 그 안에 필요한 프로퍼티를 넣기 위해 많은 고민을 하셨을 거 같은데요 🤯
앞으로 개발을 하면서 타입에 대한 정의와 활용은 계속 안고 나갈 과제이니..!! 첫 단계부터 차근차근 경험해보아요! 🙌

첫 코멘트에서 적어주신 질문은 모두 잘 해결해서 적용하신 것으로 보이는데요.
**수정을 진행한 커밋([1ea2168](https://github.com/yagom-academy/swift-starter-week3/pull/41/commits/1ea2168d4d5b0c521b4cdbf78ac37392b58b8ec3))이 DOCS: 메세지로 작성된 이유**는 무엇일까요?

그리고 수정 커밋 또한 수정 기능별로, 수정 종류(컨벤션 수정, 기능 수정 등 구분)별로 나눠줄 수 있으면 히스토리 관리에 더 효율적일 거 같아요 😄


---

현재 `CoffeeShop` 은 `커피를 만들어낼 수 있는` 동작을 할 수 있는 메서드가 보이지 않는데요 🤔
이 부분과 확인이 필요해 Request Changes 로 요청 드렸어요~

그리고 가독성과 프로퍼티의 사용 및 메서드 선언과 관련한 코멘트가 있으니 확인 부탁드려요!
코멘트 내용 또는 학습 내용과 관련해 질문이 있다면 언제나 질문 환영입니다 ᕕ( ᐛ )ᕗ


---

< 그 외 코멘트 >
1. 코드 블럭을 표현할 때 언어의 종류를 작성해줄 수도 있습니다!
* 언어 적용 전
```
enum Coffee {
    case americano
    case latte
    case cappuccino
    case coldBrew
}
 ```

* 언어 적용 후
```Swift
enum Coffee {
    case americano
    case latte
    case cappuccino
    case coldBrew
}
 ```

2. 이번 스텝에서는 프로젝트 파일이 누락되지 않았네요! 😆👏

2022-02-28 07:30 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +    var feeling: String = ""
아무 생각 없이 초기화를 해주었네요. ㅠㅠ 아래에서 필수로 feeling의 값을 입력해주지 않아도 되도록 하려고 기본값을 입력해주었는데 기본값을 입력해주지 않는 편이 나았을까요..?!

2022-02-28 07:34 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +    func buyThings(coffee: Coffee) {
조건에서 물건을 구매할 수 있도록 메서드를 작성해보라는 게 있어서 물건을 things로 표현해주었습니다. 그런데 커피만 입력받을 수 있도록 설정해놓는 건 좀 모순이네요..ㅎㅎ
```swift
func buying(_ coffee: Coffee) {
        print("안녕하세요. \(coffee) 한 잔 주시겠어요?")
    }
```
이렇게 표현해주면 괜찮을까요??

2022-02-28 07:35 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +    init(name: String, money: Int) {
넵 개행을 통일해서 다시 작성해보겠습니다!!

2022-02-28 07:37 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +    var menu : [Coffee :Int] = [.americano : 1500, .latte : 3000, .cappuccino : 3500, .coldBrew : 4000]
넵 공식문서 참고해서 띄어쓰기 스타일 통일해서 다시 작성해보겠습니다 
일관되게 코드를 작성하는게 참 어렵네요.ㅠㅠ

2022-02-28 07:38 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +    init(sales: Int,barista: Person, pickUpTable: String) {
넵 고쳐보겠습니다 ! ㅎㅎ

2022-02-28 07:41 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +yagombucks.barista = misterLee
앗 그러네요 제가 중복으로 할당을 해준 것 같아요!
바로 윗줄인 
```swift
var yagombucks: CoffeeShop = CoffeeShop(sales: 300000, barista: misterLee)
```
에서 이미 할당을 해주었으니 아래꺼는 지워도 될 것 같습니다!

2022-02-28 07:43 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(sales: 300000, barista: misterLee)
misterLee의 자산과 missKim의 자산, yagombucks의 매출액이나 바리스타 등등 모두 변할 수 있다고 생각하여 var로 표현해주었는데, 혹시 제가 잘못 생각한걸까요?

2022-02-28 07:44 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +    var sales: Int = 0
CoffeeShop의 매출액을 sales로 표현해주었습니다
매출액이 처음엔 0이었을테니 0으로 초기화해주었습니다!(확신이 안서네요,..ㅠㅠ)

2022-02-28 07:45 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +    init(sales: Int,barista: Person) {
week3-step2를 보니 CoffeeShop의 매출액과 바리스타의 값을 이용하는 부분이 나와서 추후에 필요한 두개의 매개변수만 입력할 수 있도록  초기화해주었습니다!

2022-03-01 06:30 UTC, YebinKim commented on CodeStarterCamp_Week3/main.swift
> +    var feeling: String = ""
필수값이 아니라고 생각하신다면 기본값을 가져도 괜찮을 거 같아요~
어떤 의도를 가지고 작성하셨는지 궁금해서 여쭤보았습니다 ㅎㅎ

2022-03-01 06:36 UTC, YebinKim commented on CodeStarterCamp_Week3/main.swift
> +    func buyThings(coffee: Coffee) {
`buying(:)` 메서드는 매서드의 이름에서도 전달인자에서도 무엇을 사는지가 드러나지 않아서 모호하게 느껴져요 🤔
Swift API Design Guidelines 의 [Compensate for weak type information to clarify a parameter’s role](https://www.swift.org/documentation/api-design-guidelines/#promote-clear-usage) 항목을 참고해서 작성해볼 수 있을까요?

2022-03-01 06:38 UTC, YebinKim commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(sales: 300000, barista: misterLee)
`misterLee`의 자산과 `missKim`의 자산, `yagombucks`의 매출액이나 바리스타 등등 모두 변할 수 있다는 생각에 동의해요~!

그렇다면 클래스의 인스턴스를 let으로 선언했을 때와 var로 선언했을 때, **각 인스턴스 내부의 프로퍼티**와 **인스턴스**를 변경하는 것이 어떻게 다른지 생각해볼 수 있을까요?

2022-03-01 06:39 UTC, YebinKim commented on CodeStarterCamp_Week3/main.swift
> +    var sales: Int = 0
어떤 역할을 할지 궁금해서 질문드렸어요~!
0으로 초기화가 필요한 값이라면 초기화를 해두는 것이 좋다고 생각합니다 😄👍

2022-03-01 07:10 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +    func buyThings(coffee: Coffee) {
넵 참고해서 작성해보겠습니다~~!!

2022-03-01 07:23 UTC, yeeton37 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(sales: 300000, barista: misterLee)
오... 처음 생각해보았어요 이 개념에 대해서ㅠㅠ 어렵네요.

제가 찾아본 결과 

위에서 Person 클래스를 선언할 때,  money는 var로 선언해주었고, name은 let으로 선언해주었는데 
아래에서 인스턴스 mistetLee를 let으로 선언해주면, money는 값이 변경 가능하고 name은 상수형 인스턴스 프로퍼티이기 때문에 변경 불가한 것이되겠네요..!

클래스는 인스턴스가 상수형으로 선언되어 있더라도 인스턴스 프로퍼티가 변수형으로 선언되어 있으면 값을 변경할 수 있네요. 당연히 상수형으로 선언된 프로퍼티는 변경할 수 없구요!
제가 찾아본 것이 맞을까요??ㅎㅎ

2022-03-01 07:30 UTC, yeeton37 reviewed
안녕하세요 비비! 

무수히 많은 코드 수정을 하여 다시 commit 보냅니다..ㅎㅎ..

1. 
DOCS: 메세지로 작성한 이유는 제가 커밋 메세지 규칙을 보고 문서 수정이라고 되어있길래 코드 수정으로 잘못 읽어서.... 사용했습니다.ㅜㅜ

다시 찾아보니 feat, fix, refactor 등을 적절히 활용하면 될 것 같습니다 ㅎㅎ

2. 
CoffeeShop 메서드에서 커피를 만들 수 있는 동작을 추가했습니다 (조건을 깜빡했습니다..ㅠ)

주문을 받는 order함수도 수정해주었습니다. 다음부터 조건을 꼼꼼히 보겠습니다!

3. 
개행과 띄어쓰기 통일되게 수정해주었습니다.

4. 
5. 기본값과 변수 선언부도 코멘트에 따라 바꿔주었습니다.

많은 변경이 있었네요 꼼꼼 피드백 항상 감사해요 😘

2022-03-01 11:20 UTC, YebinKim commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks: CoffeeShop = CoffeeShop(sales: 300000, barista: misterLee)
맞아요 클래스는 인스턴스가 상수형으로 선언되어 있더라도 인스턴스 프로퍼티가 변수형으로 선언되어 있으면 값을 변경할 수 있어요~
let으로 선언했을 때와 var로 선언했을 때의 차이를 잘 찾아보셨군요! 😆👏

2022-03-01 21:15 UTC, YebinKim commented on CodeStarterCamp_Week3/main.swift
> +    init(sales: Int,barista: Person) {
인스턴스를 생성할 때 매개변수가 다를 수 있다는 점을 고려하셨군요! 👍
이 필요성에 따라서라면 [매개변수 기본값](https://docs.swift.org/swift-book/LanguageGuide/Functions.html#ID169)을 이용해 간결하게 표현해볼 수 있을 거 같아요 😊
또한, `CoffeeShop` 내부의 `pickUpTable` 프로퍼티는 `String?` 타입이고 현재 생성자를 통해 넘겨주는 값은 `String` 타입이기 때문에 이 부분 확인이 필요해보입니다.

2022-03-01 21:27 UTC, YebinKim approved these changes
예톤님 안녕하세요~
Step1 수정 진행까지 고생 많으셨습니다 😆🙌

드렸던 질문들에 관해서는 모두 의문이 해결되었어요!
추가로 [생성자의 활용과 관련한 코멘트](https://github.com/yagom-academy/swift-starter-week3/pull/41#discussion_r817145828)가 있으니 이 부분 확인한 후 머지 진행해도 좋을 거 같습니다 😄

확인 후 머지의사 알려주시면 바로 머지 또는 수정 확인 진행하도록 할게요~!

2022-03-02 03:16 UTC, yeeton37 commented
생성자 부분에서 ?을 빼먹었네요....! 수정해서 다음 스텝때 반영하도록 하겠습니다 ㅎㅎ
머지 부탁드려요 감사해요😚😚

2022-03-02 14:53 UTC, YebinKim commented
넵! 머지 진행하겠습니다~
다음 스텝 진행도 화이팅이에요 😄💪

2022-03-02 14:53 UTC, merged