Week3 [STEP 1] lia388
yagom-academy/swift-starter-week3 pull request #42
Opened 2022-02-24 09:08 UTC by lia388

@TTOzzi 

또치님~! 안녕하세요😄 벌써 목요일이네요,,! 시간이 정말 빨리 지나갑니다!
step1 작성 완료해서 pr합니다! 

이번 과제의 경우 미션에서 주어진 오더보다, 뭔가 제가 결정해야 하는 것들이 많아서 고민이 됐었습니다.
그래서 질문 드릴건,
1. 저는 `coffeeShop` 구조체에 `barista`를 미리 변수로 생성해두었는데, 혹시 구조체에 미리 생성해두지 않고 이후에 새롭게 변수로 추가할 수 있는 방법은 없을까요? `How to add a var in structure`로 구글링 했었는데 딱히 유의미한 자료를 못 찾았습니다,,

2. `mutating func makeCoffee(person: String, coffee: Coffee) {` 에서 `person`을 `String`으로 정했는데, 처음에 작성할 때`person: Person`으로 받으니까
```swift
yagombucks.makeCoffee(person: missKim, coffee: Coffee.americano) 
// Person(name: "missKim", money: 100000)님 주문하신 americano 나왔습니다
```
이렇게 되더라구요ㅠ 그래서 일단 String으로 "misskim"을 받아서 `missKim님 주문하신 americano 나왔습니다`로 출력하게 만들었는데,
혹시 Person에서 이름만 뽑아내는 방법이 없을까요? _약간 Dict에서 menu[coffee]로 가격에 해당하는 값을 뽑는 것처럼요,,_

제가 정확히 설명한건지 모르겠지만,, 혹시 이해가 안되시면 말씀해주세요ㅠㅠ
항상 감사합니당😌

2022-02-24 18:51 UTC, TTOzzi requested changes
안녕하세요 리아님!! 🙇‍♂️
이번 스텝은 추상적인 부분이 많아서 어렵네요 😖
PR 메세지에서 기나긴 고민의 흔적이 보이네요.. 고생하셨습니다! 

### 질문

> 1. 저는 `coffeeShop` 구조체에 `barista`를 미리 변수로 생성해두었는데, 혹시 구조체에 미리 생성해두지 않고 이후에 새롭게 변수로 추가할 수 있는 방법은 없을까요? `How to add a var in structure`로 구글링 했었는데 딱히 유의미한 자료를 못 찾았습니다,,

음! 제가 이해한 게 맞다면..? 두 가지 방법이 있을 것 같아요!
`barista`를 **Optional**로 선언해두고, 지금처럼 `CoffeShop` 인스턴스를 생성한 후 `barista` 프로퍼티에 `misterLee` 를 할당해주거나, `barista` 를 선언만 해두고 **initializer** 를 활용해 생성 시점에 `misterLee` 를 넣어줄 수도 있을 것 같아요 :slightly_smiling_face:

> **😳 우왁! 해결했습니다! 프로퍼티 다시 공부하면서 깨달았습니다!!**
>
> ```
>     mutating func makeCoffee(person: Person, coffee: Coffee) {
>         let finishCoffee = pickUpTable == "on"
>         if finishCoffee {
>             print("\(person.name)님 주문하신 \(coffee) 나왔습니다")
>         } else {
>             print("잠시만 기다려주세요")
>         }
>     }
> }
> yagombucks.makeCoffee(person: missKim, coffee: Coffee.americano)
> ```
>
> print에 `person.name`하니까 제가 원하는 값이 나오네요..! 복잡하게 해드려 죄송합니당!!
> 수정한 코드는 코멘트 주신 내용 수정할 때 반영해서 다시 커밋하겠습니다!

ㅋㅋ 깨달음을 얻으셨군요!! 🥳
제가 리뷰할 때 보게 되는 Changes에서의 코드는 이 변경사항이 반영되기 전일 거라 요런 건 (시간 여유가 되시면!)바로바로 커밋해주시는 게 좋습니다 :bow:

자세한 내용은 코멘트로 남겨둘게요!!

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    case fruitSmoothie
`fruitSmoothie` 도 커피..죠? 🧐

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    var name: String
현재 로직에서 사람의 이름이 변경되는 경우가 있을까요? 👀 
변경되는 경우가 없다면, 상수로 선언하여 변경될 일이 없음을 표현해주는 게 좋습니다 🙂

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    mutating func buySomething(somethingPrice: Int) {
something 이라는 단어가 불필요하게 중복되는 것 같아요 🤔

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +        if self.money >= somethingPrice {
오- 예외처리 좋습니다 👍 
추가 코멘트 살짝 드리자면
```suggestion
        let hasEnoughMoney = self.money >= somethingPrice
        if hasEnoughMoney {
```
요렇게 표현해줄 수도 있을 것 같아요 (이건 조건이 간단해서 취향의 영역일 것 같습니다 😁)

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +            print("\(self.name)이 구매를 완료했습니다. 잔액은 \(minus)원 입니다")
잔액을 나타내기엔 `minus` 보단 다른 단어를 사용하는 것이 더 명확할 것 같아요 🤔 
그리고 지금은 물건을 구매하더라도, `Person` 이 갖고있는 `money` 값은 그대로일 것 같은데, `money` 를 업데이트하도록 수정해볼 수 있을까요?!

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    var menu: [Coffee: Int]
요기도 메뉴는 처음 생성 이후로 변경될 일이 없어보이니, 상수로 선언해주면 좋을 것 같아요!

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    var barista = Person(name: "", money: 0)
기본값을 할당해주셨군요! 여기 할당된 이름도 없고 돈도 없는 사람은 의미 있는 값 일까요? 🥲
관련해서 남겨주신 질문에 따로 답변 드렸으니 변경해보아요 🚀

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: String
요구사항에 `커피를 올려둘 수 있는 pickUpTable을 가질 수 있도록 해봅시다.` 이라 되어있어 뭔가 커피를 잠깐 저장해둘 수 있는 형태여야 할 것 같아요 🤔

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    mutating func orderCoffee(coffee: Coffee) {
커피숍의 입장에서 이 메서드는 `커피를 주문하다`로 표현해야 할까요, `커피 주문을 받다`로 표현해야 할까요? 👀

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    mutating func makeCoffee(person: String, coffee: Coffee) {
한 줄 띄워줘야 할 것 같아요! +_+

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    mutating func makeCoffee(person: String, coffee: Coffee) {
한 문장처럼 읽히게 메서드 이름을 바꿔볼 수 있을까요?
그리고 `mutating` 은 어떤 경우에 사용하나요?
현재 코드에선 `mutating`이 필요 없는 메서드임에도 `mutating`으로 선언되어있는 메서드들이 있는 것 같아요 🤔

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +        let finishCoffee = pickUpTable == "on"
조건에 의미를 부여해주신 것 너무 좋습니다! 👏 
추가 코멘트 살짝 드리면 Bool 값은 일반적으로 `is-`, `has-` 의 형태로 선언합니다.
https://soojin.ro/blog/naming-boolean-variables 이 글을 읽어보시면 좋을 것 같아요!

2022-02-24 18:51 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +        let finishCoffee = pickUpTable == "on"
현재 로직에선 `pickUpTable`은 항상 `"on"` 일 것 같네요 🤔 
구체적인 로직은 다음 스텝에서 구현하게 되는 것 같으니, 차차 개선해보아요!

2022-02-25 02:39 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +    case fruitSmoothie
앗 죄송해염😅 그냥 카페를 생각하면서 메뉴를 적다보니 제일 좋아하는 걸 무의식 중에 적었네요,, 수정하겠습니닼ㅋㅋㅋ

2022-02-25 02:39 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +    var name: String
아! 넵넵! 변경 없는 것은! `let name: String` 으로!

2022-02-25 02:43 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func buySomething(somethingPrice: Int) {
아! 그렇군요! `mutating func buySomething(for price: Int)`로 수정하겠습니다! **price에 something을 buy했다**라는 의미로 읽히려면 for가 들어가는 게 좋을 것 같아요!

2022-02-25 02:43 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +        if self.money >= somethingPrice {
아하! if 뒤에는 아무래도 짧고 명확하게 들어가는 게 낫군요! 상수로 선언해서 수정하겠습니다!!

2022-02-25 02:51 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +            print("\(self.name)이 구매를 완료했습니다. 잔액은 \(minus)원 입니다")
남은 돈이라는 의미를 조금 더 담아서 moneyLeft로 수정하겠습니다! 다른 사람들도 봤을 때 이해하기 쉽도록!! 명심할게요!!
money도 업데이트 해보겠습니당!

2022-02-25 02:54 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: String
커피를.. 저장이요..? 저는 약간 커피가 나왔다는 걸 표현하는 매개체로 쓴다고 생각해서
`테이블 위에 올려져 있다 = 커피가 나왔다 = "On"` Off는 반대라고 생각했습니다!

`커피를 잠깐 저장해둔다`는 말이 무슨 말인지 모르겠습니다ㅠㅠㅠ

2022-02-25 05:30 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +        let finishCoffee = pickUpTable == "on"
오호! 넵넵 그러면 완성된 의미를 주기 위해 `isCompleted` 로 변경하겠습니다!

2022-02-25 05:55 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func makeCoffee(person: String, coffee: Coffee) {
구조체에서는 자신의 프로퍼티의 값을 변경하는 메서드 앞에는 muatating이라는 키워드를 붙여주어야 합니다! 
맞네요,, 그렇네요,, 무의식 중에 structure는 mutating을 써야 한다고 생각했습니다,,
제가 작성한 코드 중에서는 `takeOrder` 외에 현재 프로퍼티 값이 변하는 메서드가 없어서 다른 곳에 mutating은 빼겠습니다!

2022-02-25 11:15 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    case fruitSmoothie
앗 ㅋㅋ 요건 그냥 달았던 건데.. 수정하란 의미는 아니었어요! ㅋㅋ

2022-02-25 11:19 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: String
(사실 요건 다음 스텝을 살짝 보고 단 코멘트이긴 해요 😅)
바리스타가 커피를 만들고, 손님이 가져가기 전까지 커피를 잠깐 올려두는 곳이라 커피를 잠깐동안 할당해서 저장할 수 있는 느낌..? 이라 생각했어요.
지금 리아님께서 하신 구현도 좋다고 생각합니다! 다만 On, Off 를 표현하려는 것이었다면, Bool 타입이 더 좋을 것 같아요 👍

2022-02-25 11:29 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
>          }
물건을 사야하는데, 돈이 없는 등의 예외 상황에 대한 처리는 guard로 구현하면 더 이해하기 쉬워집니다.
아래의 존재하지 않는 메뉴를 주문했을 때도 마찬가지구요!
요건 다음 스텝에서 리아님께서 판단하시고 적용해보시는 걸로 하시죠!

2022-02-25 11:30 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    var barista: Person?
`var yagombucks = CoffeShop(sales: 200000, menu: [Coffee.espresso: 3800, Coffee.americano: 4100, Coffee.latte: 4500], pickUpTable: "on", barista: misterLee)
`
barista를 생성 시점에 생성자를 통해 전달해주고, 이후 변경되지 않는다면 let, non-optional 로 선언하는 게 더 좋을 것 같아요.

2022-02-25 11:33 UTC, TTOzzi approved these changes
고생하셨습니다아! 🙇🙇🙇
다음 스텝에서도 같은 코드로 이어서 작업할 것 같으니 남겨드린 코멘트는 다음 스텝에서 적용해보아요!

2022-02-25 11:33 UTC, merged