Week3 [STEP2] Kay Ahn
yagom-academy/swift-starter-week3 pull request #47
Opened 2022-02-28 10:54 UTC by cpp2swift

@1Consumption 
올라프님 안녕하세요~
이번 스텝 "인스턴스는 서로 소통한다" 를 구현했습니다.
이번 제 코드를 간략하게 설명드리면, 구조체를 이용해서 객체를 생성하고 객체가 어떤 행위를 할 수 있을때, 다음 동작을 실행하도록 했습니다.
저번에 말씀 해주신것 "구조안에서는 객체가 할 수 있는 기능을 구현하고 실제로 객체가 소통하는 과정은 그 밖에서 한다" 를 중점으로 구현했습니다.
이번에도 미흡한점 많이 조언 부탁 드립니다!
항상 감사합니다!

2022-02-28 13:59 UTC, 1Consumption requested changes
@cpp2swift 
안녕하세요 KayAhn님~ 고생 많으셨습니다.
이제 슬슬 코드가 복잡해지고 있네요!


Person과 CoffeShop의 관계를 정의하고 서로 소통하는 코드를 잘 짜주셨어요! 
그런데 각 객체 내부에서 여러가지 역할을 하는 메소드가 있어서 조금 아쉬웠습니다.
이 부분을 고쳐보려면 일단 메소드를 최소 단위로 만들어보고(최대한 내부에서는 사용하지 말고), 외부에서 조립을 하듯이 사용해보세요. 
> 💡 `구조안에서는 객체가 할 수 있는 기능을 구현하고 실제로 객체가 소통하는 과정은 그 밖에서 한다`

추가적으로 커밋을 잘 나눠 주셨는데, 아직 네이밍이 조금 아쉽습니다. 이 프로젝트를 처음 보는 사람이 봐도 제목을 보고 커밋의 내용을 유추할 수 있도록 커밋메세지를 적어볼까요?

나머지는 코멘트를 확인해주세요.

2022-02-28 13:59 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
> +    mutating func buyProduct(productName: Coffee) -> Bool {
buyProduct와 productName이 겹치네요.

2022-02-28 13:59 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
> +    }
buyProduct 메소드는 정확히 어떤걸 하는 메소드인가요?
커피를 살 수 있는지 없는지를 반환하는 메소드인가요? 커피를 구매하는 메소드인가요? 아니면 둘 다 하는 메소드인가요?
두개의 역할을 하고있다면 분리하는건 어떨까요?

추가적으로 bool을 반환하는 메소드는 `~ 인가?`, `~ 할 수 있는가?` 로 해석되는게 좋습니다.

2022-02-28 13:59 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
>      var money: Int
외부에서 알아야하는 정보인가요?

2022-02-28 13:59 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
>      var pickUpTable: [String: String]
외부에서 알아야하는 정보인가요?

2022-02-28 13:59 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
> +    mutating func takeOrder(coffee: Coffee) -> Bool {
여기도 한번에 어려개의 역할을 하는거 같아요.

2022-02-28 13:59 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
>          }
if let 대신 guard let을 사용해 뎊스를 하나 줄여보는건 어떨까요?

2022-02-28 13:59 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
> +    }
missKim은 커피를 샀는데 yagomBuck의 상태에 따라 커피가 만들어지지 않을수도 있는건가요?
이러면 missKim의 돈은 어떻게 되나요?

2022-02-28 13:59 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
> +    }
👍 한곳으로 모여있네요

2022-02-28 13:59 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
>      var pickUpTable: [String: String]
property observer를 통해 pickUpTable의 값이 바뀌면 완료 메세지를 보낼 수 있나요?

2022-03-03 05:42 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
>      var money: Int
https://github.com/yagom-academy/swift-starter-week3/pull/47/commits/4c33e1cb6d82053534a305260b37af88e2c8b56a

외부에서 알면 안되는 정보는 접근제어자로 처리했습니다!
하지만 name 같은 경우는 나중에 "xxx님 커피 나왔습니다 픽업테이블에서 가져가세요" 처럼 다른곳에서 쓰인다고 생각해 원형 그대로 두었습니다.

2022-03-03 05:44 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
> +    }
https://github.com/yagom-academy/swift-starter-week3/pull/47/commits/4ec1b39c56095029c2ecb1f425919cd84743f274

함수명을 반환형의 타입에 맞게 수정했습니다.  또, 커피를 살수있는지 없는지 여부만 확인하게끔 수정해 다음 함수에서 실제로 구매자의 돈이 줄어들게 구현했습니다.

2022-03-03 05:48 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
>      var pickUpTable: [String: String]
https://github.com/yagom-academy/swift-starter-week3/pull/47/commits/674cf409f566319196240f9b7629551ac00de605

이 부분도 Person의 money 프로퍼티처럼 외부에서는 몰라도 되는 부분이라 생각하여 접근제어자를 이용해 private으로 만들었습니다.
또, 픽업테이블 프로퍼티 경우에는 딕셔너리 컬렉션에서 배열 컬렉션으로 수정하고 배열 컬렉션이 변경이 될때 프로퍼티 옵저버를 통해 처리 해주었습니다.

2022-03-03 05:49 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
> +    mutating func takeOrder(coffee: Coffee) -> Bool {
https://github.com/yagom-academy/swift-starter-week3/pull/47/commits/cd823775cc080e1ae6a0be7a3bf8963d5d2e013e

takeOrder 함수를 반환형 타입에 맞게 canOrder로 변경하고 두가지 일을 수행하던 함수 내부를  '여부 판단' 한가지 일만 하도록 수정했습니다.

2022-03-03 05:51 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
> +    }
https://github.com/yagom-academy/swift-starter-week3/pull/47/commits/d67dbbcfae3f3f3e94f7efb2b9508b04fef79976

구매를 할 수 있는지 -> 오더를 받을수 있는지 ->영수증 출력 및 커피 제작 처럼 실제 사람이 커피숍에서 구매하는 프로세스를 생각하고 그에 맞게 수정했습니다.

2022-03-03 05:57 UTC, cpp2swift commented
@1Consumption 
올라프님. 이번 스텝은 오랜시간이 걸릴정도로 여러가지 부분을 공부하고 생각해보는 스텝이였습니다.
짧은 코드보다 "하나의 함수에는 하나의 기능"이라는 기초가 아직도 익숙치 않아 이번에도 하나의 함수에 여러 수행문장을 넣었고
또, 함수명을 반환타입에 맞지 않게 쓰고, 커피를 받지 못했음에도 구매자의 돈이 나가는 경우 등등. 신경을 써야 할 부분이 무엇인지 깨닫는 스텝이였습니다. 접근제어자를 사용하는 방법은 조금 더 공부를 해야겠지만 전체적인 그림을 그리게 해주셔서 감사합니다.
항상 좋은 코멘트와 더 성장할수있게 해주셔서 감사합니다!

2022-03-03 16:32 UTC, 1Consumption requested changes
코멘트 확인 부탁드리겠습니다!

2022-03-03 16:32 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
> +    mutating func canOrder(coffee: Coffee) -> Bool {
여기도 mutating이 필요한가요?

2022-03-03 16:32 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
> +        return orderAvailability
여기도 마찬가지로 if문 내부에서  Bool을 반환하네요.

2022-03-03 16:32 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
> +    }
if 문이 중첩되네요! 아래와 같이 바꿀 수 있습니다.
```suggestion
if missKim.canBuy(productName: Coffee.americano),
   yagomBucks.canOrder(coffee: .americano) {
        missKim.printPurchaseResult(buyAvailability: true, productName: .americano)
        yagomBucks.makeCoffee(person: missKim, coffee: .americano)
    }
```

2022-03-04 02:34 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
> +    mutating func canBuy(productName: Coffee) -> Bool {
수정하기 전 코드에 구조체의 프로퍼티를 건드리는 부분이 있었는데
수정 후 코드에는 필요가 없을것 같습니다.

2022-03-04 02:36 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
>          }
확실히 한줄에 모든게 표현되니 가독성이 훨씬 좋아졌습니다!

2022-03-04 02:53 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
> +        }
프로퍼티 옵저버로 willSet과 didSet을 제공하는데 willSet은 값이 저장되기 직전에 호출이 되고 새로운 값이 newValue로 호출 할수 있습니다. didSet은 새로운 갑싱 저장된 후 호출이 되는데 예전 값을 oldValue로 호출해 사용할 수 있는 차이점이 있습니다.

2022-03-04 02:53 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
> +    mutating func canOrder(coffee: Coffee) -> Bool {
여기도 마찬가지로 프로퍼티의 값을 바꾸는 부분이 없기 때문에 필요하지 않습니다!

2022-03-04 02:54 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
> +        return orderAvailability
지금 생각해보니 이 부분도 간략히 줄여서 가독성을 늘리는게 좋은것 같습니다!

2022-03-04 03:10 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
> +    }
새로운 방법을 알려주셔서 감사합니다!

2022-03-04 10:55 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
>          }
https://github.com/yagom-academy/swift-starter-week3/pull/47/commits/fa0aee23acb40716962475a574021daca71e48f7

mutating을 삭제하고 가독성이 높게 수정했습니다!

2022-03-04 10:56 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
> +        return orderAvailability
https://github.com/yagom-academy/swift-starter-week3/pull/47/commits/a9fceb50c2c57888e8e9a724704ef51730dbb42f

여기도 mutating을 삭제하고 nil인지만 확인한후 리턴하는 형식으로 수정했습니다!

2022-03-04 10:56 UTC, cpp2swift commented on CodeStarterCamp_Week3/main.swift
> +    }
https://github.com/yagom-academy/swift-starter-week3/pull/47/commits/1d16b51961f5300dbe6e4817de0c180b78d2caae

이부분은 차후에 중첩if문을 사용할 때 유용하게 사용하겠습니다!

2022-03-04 10:57 UTC, cpp2swift commented
@1Consumption 
올라프님이 코멘트 달아주신것을 고치고 나니 조금더 보기 편한 코드가 되었습니다.
감사합니다!

2022-03-04 12:12 UTC, 1Consumption approved these changes
고생하셨습니다! 다음 스텝을 진행해주세요.

2022-03-04 12:12 UTC, 1Consumption commented on CodeStarterCamp_Week3/main.swift
>      }
여기도 `menu[coffee] != nil` 로 바꿀수 있네요

2022-03-04 12:12 UTC, merged