Week3 [STEP 2] lia388
yagom-academy/swift-starter-week3 pull request #53
Opened 2022-03-02 11:59 UTC by lia388

@TTOzzi 

안녕하세요 또치님! 오랜만이에요😭
step2를 열심히 고민하다 step1의 구조체로 코드를 진행하기엔 어려움이 있어서, class도 공부할겸 바꿔봤습니다!
하나 바꾸니 저기가 오류나고, 또 하나 바꾸니 다른 오류가 나고ㅎㅎ 오래 걸렸습니다😅

이번 리뷰도 잘 부탁드립니다!😊

2022-03-03 12:12 UTC, TTOzzi requested changes
안녕하세요 리아님!! 리뷰가 조금 늦었네요..! 죄송합니다 🙇 

step2를 구조체로 진행할 때 어떤 부분이 문제가 있었나요?
클래스와 구조체의 차이를 명확하게 이해하고 구현하는 건 정말 중요한 부분이니 꼭 자세히 공부해보셨음 해요!
매번 새로운 객체를 구현할 때마다, 그 객체가 어떤 역할을 하며 어떤 방식으로 쓰일지를 생각해보고 클래스로 구현할지 구조체로 구현할지 선택해야하거든요 🙂 

자세한 피드백은 코멘트로 남겨두었습니다.
이해가 어려운 부분이 있다면 언제든지 말씀해주세요!
고생하셨습니다 🙇

2022-03-03 12:12 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +        sales += coffee.price
`CoffeeShop` 은 각 커피 별로 가격 정보를 `menu` dictionary에 저장해서 관리하고 있는데, 가격을 `coffee.price`를 통해 가져오고 있네요 🤔 
커피 가격을 올리고 싶어서 `menu` 의 값을 수정해도, 수정된 값이 반영되지 않을 것 같아요 😢 

추가로 `menu`에 없는 커피 주문이 들어왔을 때도, 지금은 주문을 받을 수 있는 상태인 것 같네요 🤔

2022-03-03 12:12 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(sales: 0, menu: [Coffee.espresso: Coffee.espresso.price, Coffee.americano: Coffee.americano.price, Coffee.latte: Coffee.latte.price], pickUpTable: false, barista: misterLe
요렇게 `menu`를 하나씩 타이핑해서 집어넣기보단 위에서 `enum Coffee` 에 채택해준 사용하신 `CaseIterable` 프로토콜이 제공해주는 것을 활용하면 메뉴판을 간단하게 만들어 볼 수 있을 것 같아요!
지금은 메뉴가 3개 뿐이라 괜찮아보일 수 있지만, 커피 종류가 수십개가 되어버린다면 메뉴 만들기가 힘들 것 같아요 🤔

2022-03-03 12:12 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +var missKim = Person(name: "missKim", money: 10000)
요기 두 변수는 변수로 선언할 필요가 있을까요?
아마 `Person`이 구조체였을 땐, 내부의 `money` 값을 변경해주기 위해 변수여야 했고, `Person`이 클래스가 된 지금은 상수여도 정상적으로 동작할 거예요.
어떤 차이가 있는 걸까요 🤔

2022-03-04 10:58 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +            self.money -= coffee.price
앗! 제가 도둑이었군요!!!
```
guard hasEnoughMoney else {
            print("잔액이 \(coffee.price-self.money)원만큼 부족합니다.")
```
이렇게 수정하겠습니다!

2022-03-04 11:46 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +var missKim = Person(name: "missKim", money: 10000)
구조체는 값타입, 클래스는 참조타입이기 때문입니다! 값타입은 값을 복사해서 전달하기 때문에 money 값 변동을 위해 변수여야 했고, 참조타입은 상수여도 변경 가능합니다!! 상수로 바꾸겠습니다ㅎㅎ

2022-03-04 12:26 UTC, lia388 commented on CodeStarterCamp_Week3/main.swift
> +enum Coffee: CaseIterable {
앗 enum 안의 case들을 순회할 수 있도록 만들려고 했는데, coffeeShop 클래스에서 init에 초기값을 설정하면서 빠진 것 같습니다! `allCases` 추가하겠습니다!

2022-03-04 15:05 UTC, lia388 commented
@TTOzzi 

또치님,, 말씀하신거 수정해보았습니다,, 후하!
`PropertyObserver`로 `makeCoffee` 함수 안에서 만들려고 노력했는데 너-무 안돼서 책도 보고 이렇게 저렇게 찾아보니
`pickUpTable` 변수를 설정할때 같이 만들어둬야 하더라구요..!
그래서 그렇게 만들고 makeCoffee 안에 `append`로 저장했습니다!

**저장**과 **저장 프로퍼티** 개념에 혼동이 생기면서 헤맸습니다ㅠㅠ
수정된 커밋 리뷰 부탁드립니다!!

2022-03-04 16:19 UTC, TTOzzi requested changes
> PropertyObserver로 makeCoffee 함수 안에서 만들려고 노력했는데 너-무 안돼서 책도 보고 이렇게 저렇게 찾아보니
pickUpTable 변수를 설정할때 같이 만들어둬야 하더라구요..!

헉 코드를 사용하는 단계에서부터 어려움을 겪고 계셨었군요.. 좀 더 자세히 설명드릴 걸 그랬네요 😢 


코멘트 여러 개 남겨드리긴 했는데, 커피숍에서의 커피 주문에 대한 예외처리만 짚고 넘어가면 될 것 같아요.
이번에도 이해가 어려운 부분이 있다면 바로바로 말씀해주세요~! 
고생하셨습니다!! 🙇

2022-03-04 16:19 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +        if Coffee.allCases.contains(coffee) {
음 인자로 들어오는 `Coffee` 타입은 항상 `Coffee.allCases`에 포함되어있지 않을까요? 👀 
커피 종류에 대한 예외처리는 여기보단, 커피숍에서 주문을 받을 때 주문받은 커피가 커피숍이 가진 메뉴판에 있는 커피인지 확인해야 할 것 같아요 🤔 
커피숍의 메뉴는 변경할 수 있도록 구현되어있어 모든 커피를 다 팔 수도 있지만, 아메리카노와 라떼만 팔 수도 있으니까요.

2022-03-04 16:19 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +        else {
```suggestion
        } else {
```
`if-else` 에서 `else`는 보통 요렇게 올려씁니다!

2022-03-04 16:19 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +var missKim = Person(name: "missKim", money: 10000)
여기 놓치신 것 같아요! +_+

2022-03-04 16:19 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    var customer: String = ""
값이 없을 땐, 의미없는 빈 문자열보단 optional을 활용해서 값이 없다는 것을 명확하게 표시해주면 더 좋을 것 같아요!

2022-03-04 16:19 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +    func takeOrder(coffee: Coffee, from person: Person) {
위에서 코멘트 드렸듯이 현재는 `menu`에 `Coffee.allCases`를 넣어주고 있어 문제가 없긴 하나, 두 종류의 커피만 팔도록 코드를 변경하는 경우까지 생각한다면 판매하는 커피인지 확인하는 방어 로직이 요기에 들어가야 할 것 같아요 🤔

2022-03-04 16:19 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +            print("\(customer)님의 커피가 준비되었습니다. 픽업대에서 가져가주세요.")
바로 `print`를 호출하기보단, 여기서 하는 동작이 어떤 행위인지 메서드를 만들어 의미를 부여해주면 더 좋을 것 같아요 🙂

2022-03-04 16:19 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(barista: misterLee)
요기도 변경되지 않는 값은 항상 `let`으로 선언해주는 게 좋습니다!

2022-03-05 17:04 UTC, lia388 commented
@TTOzzi 

또치님! 우선 먼저 수정해보라고 하셨던 것만 수정해서 커밋합니다ㅎㅎ

> coffeeShop 에선 판매중인 커피인지 여부를 지금은 단순 메뉴판에 있는지만으로 체크하지만, 나중에 뭔가 재고를 체크한다던지 하는 부가 로직이 추가될 수 있으니
coffeeShop의 메서드로 커피를 받아 판매중인 커피인지를 Bool 값으로 반환하는 메서드를 만들어 Person 에서 호출하면 더 유연한 코드가 될 것 같아요!

디스코드에서 말씀해주셨던 해당 내용은 이해가 어려운 부분이 있습니다ㅠㅠ

1. coffeeShop 클래스 안에 매서드(`checkCoffee`)를 만들어서 
2. 판매중인 커피인지 확인하고(`coffeeShop.menu.contains(coffee)`) 
3. 그 값을 `-> Bool` 로 반환한 후
4. Person에서는 어떻게 호출해야 할까요..?🥲

다른 수정 사항과 함께 알려주시면 다시 해보겠습니다!

2022-03-05 17:38 UTC, TTOzzi requested changes
코멘트 남겨주신 마지막 남은 부분만 수정하고 넘어가시죠! 🚀 
늦은 시간까지 고생하셨습니다 🙇🙇🙇

2022-03-05 17:38 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +        }
말씀해주신대로 `CoffeeShop`의 `checkCoffee`가 판매중인 커피인지 확인 후 `Bool` 값을 반환할테니
```suggestion
        guard coffeeShop.checkCoffee(coffee) else { return }
```
이런 형태가 되겠네요 🙂 
`print("죄송합니다. 주문하신 \(coffee)는 판매하지 않습니다.")` 와 같은 커피 판매에 대한 안내 문구도 커피숍의 메서드로 옮겨가면 더 좋을 것 같구요!

2022-03-05 17:38 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +            if let actual_customer = customer {
Swift api design guideline 에선 camel case 를 사용하길 권장하고 있습니다 🙂 
<img width="663" alt="스크린샷 2022-03-06 오전 2 30 30" src="https://user-images.githubusercontent.com/50410213/156893834-d78bcb5e-ead8-40f1-930a-a317db04d442.png">

2022-03-05 17:38 UTC, TTOzzi commented on CodeStarterCamp_Week3/main.swift
> +            }
조건을 만족하지 않았을 때 ealry return 해주는 로직은 if-else 보단 guard 로 표현해주면 더 가독성이 좋아질 것 같아요!

2022-03-06 07:29 UTC, lia388 commented
@TTOzzi 

또치님~! 수정했습니다!!! 

### 새벽의 저주
그리고 buy에서 호출을 어떻게 해야 하는지 여쭤봤던 게 말씀해주신대로 호출은 동일하게 했었는데ㅎㅎ 제가 checkCoffee에 쓸데없이 매개변수로 `in coffeeShop: CoffeeShop`을 넣어서 계속 함수 안에서 값이 돌고 있었던 거였어요ㅎㅎ후! 새벽이라 정신이 없었나봐요ㅎㅎ `checkCoffee(coffee: coffee)`만 넣으니까 잘 돌아가네요ㅎㅎ허허

### Bool 반환은 처음이라
`checkCoffee`의 Bool 타입 return을 `false, true`로 직접 입력하는 것이 맞나🤔 의문이 들었지만 return만 작성하니 계속 오류가 나서 우선 직접 다 입력했습니다! 다른 방법이 있다면 알려주세요ㅠㅠ

### if와 guard?
계속 `gurad`를 사용하는 게 낫다고 말씀을 해주셔서,, 혹시 if랑 guard를 사용하는 명확한 기준이 있을까요..?
저는 didSet에서 먼저 필요한 값이 도출되는게 맞다고 생각해서 (수정전)`actual_customer = customer`에 해당하는 값을 먼저 쓰려고 if let을 썼는데, 여기선 옳지 않으면 조기 종료된다는 return 값이 왜 먼저 표시되어야 하는걸까요??🥲 둘 다 사용은 가능한데 해석에 따라 어떤걸 써야하는지가 달라지는 것 같아 헷갈립니다ㅠㅠ

2022-03-06 09:56 UTC, TTOzzi approved these changes
우와 새벽에 더 하셨군여.. 고생하셨습니다 🙇 
열심히 하시는 모습 좋지만 지금도 충분히 잘 하고 계시니 너무 무리하진 마세요! ㅎㅎ

### Bool 반환은 처음이라

>  `checkCoffee`의 Bool 타입 return을 `false, true`로 직접 입력하는 것이 맞나🤔 의문이 들었지만 return만 작성하니 계속 오류가 나서 우선 직접 다 입력했습니다! 다른 방법이 있다면 알려주세요ㅠㅠ

반환값을 가지는 함수에서 `guard` 문을 사용하면 `else` 에서 값을 반환해줘야 해요!
조건에 따른 `Bool` 값의 반환이니 바로 조건(`menu.contains(coffee)`)를 반환해줄 수도 있지만, 지금은 메뉴가 없을 때 안내문구 출력도 해야하기에 잘 구현해 주셨습니다 :thumbsup:

### if와 guard?

```swift
if let actual_customer = customer {
    giveCoffee(to: actual_customer)
} else {
    return
}
```

작성해주셨던 코드처럼 어떤 조건을 만족하지 않았을 때, 스코프를 종료(`return`) 해줘야하는 코드가 있을 때가 `guard`를 사용하는 가장 대표적인 예시가 될 것 같구요.

다른 곳은 개인 취향에 따라 조금 의견이 갈릴 수 있긴 한데, 저는 메서드의 로직에서 예외사항에 대한 처리를 해야할 때 `guard`를 주로 사용하는 편이에요!
`if` 블럭과 `else` 블럭의 로직이 동등하다면 `if-else`를, `guard` 이후 로직이 의도한 동작이고 `else` 의 로직은 의도하지 않은 경우에 대한 예외처리라면 `guard` 를 사용합니다.

만약 지금 작성되어있는 `buy(coffee: Coffee, from coffeeShop: CoffeeShop)` 메서드에 `guard`를 사용하지 않았다면

```swift
func buy(coffee: Coffee, from coffeeShop: CoffeeShop) {
    if coffeeShop.checkCoffee(coffee: coffee) {
        let hasEnoughMoney = self.money >= coffee.price
        if hasEnoughMoney {
            self.money -= coffee.price
            coffeeShop.takeOrder(coffee: coffee, from: self)
        } else {
            print("잔액이 \(coffee.price-self.money)원만큼 부족합니다.")
        }
    }
}
```

요런 형태가 되는데, 개인적으론 코드의 들여쓰기도 깊어지고 `guard` 보다 가독성이 떨어진다고 생각해요 :thinking:

이건 제 주관이 담긴 의견이니 리아님께서 어떻게 작성하는 것이 코드 가독성이 더 좋을지 판단하셔서 작성하시면 될 것 같아요 :slightly_smiling_face:

그럼 머지하겠습니다!

2022-03-06 09:57 UTC, merged