Week3[STEP2] Dason3027
yagom-academy/swift-starter-week3 pull request #54
Opened 2022-03-02 13:21 UTC by Dason3027

@Journey36 글렌님 안녕하세요!  3주차 step2 작성해 봤습니다!

이번 스텝은 많이 어려웠던 것 같습니다...!  요구하는 결과 값들을 출력해 보았는데 어떤지 피드백 부탁드리겠습니다!

이 과제에 연산 프로퍼티(get, set)를 사용하여 매출액과 person.money를 계산이 가능한 코드가 있는것 같은데 
그렇게 코드 작성하는 것이 쉽지가 않았습니다. 
그리고 pickUpTable을 한번에 정의해서 사용하고 싶었는데 그 부분도 잘 이해가 가지않았습니다ㅜㅜ 
이번에는 class 상속을 사용해 Person의 하위 클래스로 coffeeShop을 상속 시켰지만 어디에 무엇이 맞는 상속인가
이 부분도 아직 부족한 것 같습니다. 지금 다시보니 상속을 잘못 한것 같기도하고,,, 하하;; 

글렌님 피드백 항상 감사합니다!!

2022-03-03 13:58 UTC, Journey36 requested changes
@Dason3027
안녕하세요, 대현님! 작성해주신 코드 잘 확인했습니다.
지금 제가 가장 먼저 드리고 싶은 피드백은, 무작정 코드를 작성하기 보다 키보드에서 손을 떼고, 설계하는 시간을 먼저 가지면 더 좋을 것 같다는 것입니다.

개발자는 문제를 해결하기 위해 설계를 하는 사람들입니다. 코드나 문법은 문제를 해결하기 위한 수단일 뿐이에요. 너무 바쁘게 가려하지 마시고, 우리 천천히 해봐요. 🙂 

물론 지금 코드 자체가 완전히 잘못됐다는 이야기는 아닙니다. 하지만, 그저 다른 객체의 프로퍼티나 메소드를 사용하기 위해, 요구사항만을 충족하기 위해 개념적으로 상하관계가 성립되지 않는 부분을 강제로 이어가려고 하는 모습이 보였기 때문에 조금 우려스럽네요.

우선적으로 궁금한 점을 코멘트로 남겨놨습니다. 확인부탁드려요.
너무 힘드시면 저에게 DM 주세요. 함께 고민해보는 시간을 가져봐도 좋을 것 같습니다.
그렇다고 자신감을 잃지 마세요. 지금도 충분히 잘 하고 계십니다. 이 고비만 넘기시면 한 단계 더욱 성장했다고 느끼실 수 있을 것 같아요. 화이팅입니다! 💪💪💪

2022-03-03 13:58 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        missLee.pickUpTable = "\(name)님의 커피가 준비되었습니다. 픽업대에서 가져가주세요."
프로퍼티 감시자(Property Observer)를 사용해서 값의 변화를 감지하여, 현재 픽업대에 준비된 음료가 출력되도록 해보는 건 어떨까요?

2022-03-03 13:58 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        }
`if` 의 조건이 아닌 나머지 조건은 `else` 문으로 처리하는 것이 더 깔끔할 것 같아요!
`if`와 `else if`의 조건들을 봤을 때 비는 구간이 없어보여요.

2022-03-03 13:58 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        if missMoney < coffeePrice {
`miss`만 커피를 사지는 않을 것 같아요. ㅎㅎ 네이밍을 조금 더 보편적으로 작성해보면 좋겠습니다.

2022-03-05 16:08 UTC, Dason3027 commented
@Journey36  글렌님 안녕하세요 step2 수정해 봤습니다!

글렌님의 피드백을 받고 수정해 봤지만 제가 아직 깔끔하게 코드 작성을 못했다는 느낌이 듭니다 ㅠ 그래서 그런지
pr보내는것이 약간 주춤해지는군요! 그래도 다시 보내고 피드백 받아서 고비를 넘어보겠습니다!!

이번에는 사람이 구매하는 것처럼 행동하도록 함수를 4가지로 만들어서 나누어 봤습니다. 
제가 처음 작성했던 코드는 하나의 함수 안에 끼워 맞추기 급급했습니다. 
이번에는 행동을 나누어서 작성 해 보고 저번과 다르게 좀 더 포괄적(?) 으로 구현이 되도록 코드 작성을 해 봤습니다!
(제 기준이지만요...하하)

글렌님 이번에도 좋은 피드백 부탁드립니다 감사합니다!

2022-03-07 14:27 UTC, Journey36 requested changes
@Dason3027 
안녕하세요, 대현님! 주말 잘 보내셨나요? 리뷰가 조금 늦어져서 죄송합니다. 😢
전체적으로 코드가 정말 좋아졌다는 것이 보이네요! 그리고 조금씩 감을 잡아가고 계신 듯 합니다!
궁금한 점을 코멘트로 남겼으니 확인 부탁드립니다.

2022-03-07 14:27 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        }
잔액을 체크하는 함수를 따로 분리해놓으신 부분, 좋은 것 같아요! 👍

2022-03-07 14:27 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        }
`Person` 타입에 있는 checkMoney를 활용하면 어떨까요? 🤔

2022-03-07 14:27 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        }
[공식 문서](https://docs.swift.org/swift-book/LanguageGuide/Properties.html#ID262)를 한 번 참고해볼까요?
함수 내부에 있는 로컬 변수는 함수가 종료되면 메모리에서 제거됩니다. 그럼 프로퍼티 감시자의 역할을 제대로 수행하지 못하지 않을까 생각이 드네요. 꼭 한 번 읽어봅시다! 🙂

그리고 `pickUpTable`에 커피가 없을 수도 있지 않을까요? ㅎㅎ

2022-03-07 14:27 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +}
해당 함수는 *실행의 묶음 역할*을 하는 함수인 것 같네요. 해당 함수 없이, 각 인스턴스 메소드에서 실행할 수 있지 않을까요?

2022-03-07 18:02 UTC, Dason3027 commented
@Journey36 글렌님 안녕하세요! 피드백 바탕으로 다시 수정 해 봤습니다!

그런데 말씀해 주신 Person타입에 checkMoney 를 활용해 coffeeShop takeOrder을 쓰는 방법을 
잘 모르겠습니다..ㅜㅜ  어떠한 방법으로 활용 할 수 있는지 부연설명 해 주실수 있으실까요?

2022-03-09 12:24 UTC, Journey36 reviewed
@Dason3027 
안녕하세요, 대현님!
피드백 드렸던 부분이 서로 소통이 안된 것 같아서 다시 코멘트로 남겨놨습니다. 🙂
혹시 이해가 안되시면 바로 DM으로 말씀해주세요. 마지막까지 화이팅입니다!

2022-03-09 12:24 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        }
👍
픽업대의 커피를 가져가서 비어있을 때의 로직을 `else`로 처리해줘도 좋겠네요!

2022-03-09 12:24 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        if coffee.rawValue <= person.money {
제가 설명이 부족했던 것 같습니다!
이 부분은 `checkMoney`라는 함수에서 이미 가진 돈을 체크하는 로직이 있는데, 재사용할 수 있지 않느냐 라는 의미로 말씀드린 겁니다! 사실상 하나의 함수에서 모두 구현할 수 있을 것 같아요. `checkMoney`에 모두 구현하든, `takeOrder`에 모두 구현하든지요!
아니면 `checkMoney` 함수를 없애도 되구요. 방법은 여러가지 일 것 같다고 생각합니다!

2022-03-09 12:24 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +yagomBucks.makeCoffee(coffee: .cappuccino, person: missKim)
제가 말씀드린 방법은 checkMoney를 `takeOrder`나 다른 함수에서 실행시키면 굳이 밖에서 따로 실행시키지 않고 자연스러운, 하나의 `주문`이라는 흐름으로 실행시킬 수 있지 않을까라는 뜻이었습니다! ㅎㅎ

2022-03-09 13:55 UTC, Dason3027 commented
@Journey36 글렌님 안녕하세요! 코멘트 주신부분에 대하여 생각해서 정리해 보았습니다.

말씀해주신 takeOrder 함수에 돈을체크하는 checkMoney함수를 넣어서 한번에 구현이 되는것을 확인했습니다!
추가로 Person이 주문하는 함수 orderCoffee 함수도 같이 넣어 커피를 주문 행위를 한번에 구현 해봤습니다!

그리고 픽업 테이블이 비어있을 때 else문으로 처리 해 보았습니다


감사합니다!!

2022-03-10 09:52 UTC, Journey36 reviewed
@Dason3027 
안녕하세요, 대현님! 
확실히 코드에 많은 변화가 생겼네요!
이번에는 딱히 피드백드릴 게 없을 것 같네요. 스텝 진행하시느라 고생하셨습니다!

2022-03-10 09:52 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +                print("커피를 올려주세요")
`didSet`에서는 `oldValue`를, `willSet`에서는 `newValue`를 사용할 수 있어요. ㅎㅎ 참고하세요!

2022-03-10 09:52 UTC, merged