[WEEK3] step2 yeeton
yagom-academy/swift-starter-week3 pull request #55
Opened 2022-03-03 07:02 UTC by yeeton37

@YebinKim 
안녕하세요 비비~ 
week3의 step2 과제 제출합니다!

1. week3의 step1 코드에서 잔액 확인하는 함수 hasAsset를 추가해주었습니다.
2. missKim이 커피를 주문하고, yagombucks에서 커피를 제조하고, 만약 missKim의 잔액이 커피 가격보다 부족하면 hasAsset이 false가 나오고, 잔액이 남으면 hasAsset이 true가 돼서 주문이 완료되도록 했습니다.

잘부탁드려요~~!!

2022-03-06 15:37 UTC, YebinKim requested changes
예톤님 안녕하세요~ 😄
Step2 진행까지 고생 많으셨어요!

커피를 결제하기 위한 hasAsset(_:_:) 메서드의 구현 이유와 사용 방법 확인했어요! (어떤 의도로 구현하고 사용했는지 알려주셔서 감사해요 😆)
메서드의 이름 및 **인스턴스 간의 소통 방식(프로그램의 동작 흐름)** 과 관련한 코멘트가 있으니 확인 부탁드립니다 😊

그리고 `step2 - order coffee.swift` 파일이 프로젝트 파일 참조에서 누락된 것으로 보여요! 👀
이 부분 확인 한 번 부탁드려요~
<img width="256" alt="file missing" src="https://user-images.githubusercontent.com/38066039/156929844-019ddd06-634e-44c8-a985-5dbf70948f8a.png">

파일 이름과 관련해서 하나 더 전달드리자면,
파일 이름에 공백이 있으면 파일 공유 시 공백이 다른 문자로 대체될 가능성이 있기 때문에 가능하면 공백 없이 작성하는 것을 추천드려요~



---

`pickUpTable` 프로퍼티의 사용 및 프로그램의 동작 흐름과 관련해 확인이 필요해 보여서 Request Changes 로 리뷰 의견 드렸어요.
혹시 이번 스텝 진행 및 학습 내용과 관련해 어려운 점이 있다면 언제든 DM 주세요 🙆🙌

2022-03-06 15:37 UTC, YebinKim commented on CodeStarterCamp_Week3/main.swift
> +//
복붙을 완료하여 불필요해진 코드는 삭제해도 괜찮지 않을까요?

2022-03-06 15:37 UTC, YebinKim commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +let yagombucks: CoffeeShop = CoffeeShop(sales: 300000, barista: misterLee, pickUpTable: "")
인스턴스 생성을 클래스 선언 및 함수 선언부 코드와 함께 둔 이유가 무엇일까요?

2022-03-06 15:37 UTC, YebinKim commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +    }
> 주문과 동시에 `missKim`의 돈은 커피의 가격만큼 줄어들고, `yagombucks`의 매출액은 커피 가격만큼 증가합니다.

요구사항과 달리 주문과 결제 과정이 분리되어 있는 것으로 보이네요 👀

일반적으로 카페에 갔을 때는 손님과 바리스타의 입장에서 아래의 동선이 자연스러울 것으로 생각하는데 예톤님의 생각은 어떠실까요?
1. 손님의 커피 주문 및 결제 (또는 주문과 결제 과정은 분리)
2. 바리스타의 커피 제조
3. 바리스타가 커피 제조 완료 시(pickUpTable에 올라왔다면) -> 손님이 픽업

< 현재 구현된 동선 >
1. 손님의 커피 주문
2. 바리스타의 커피 제조
3. 손님의 결제 및 픽업

2022-03-06 15:37 UTC, YebinKim commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +            print("잔액이 {\(menu)}원만큼 부족합니다.")
중괄호{} 는 함께 출력하지 않아도 괜찮을 거 같아요 😄

2022-03-06 15:37 UTC, YebinKim commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +    if let menu = yagombucks.menu[coffee] {
`menu` 상수는  잔액을 나타내기에는 적절하지 않은 네이밍으로 보이네요 🤔

2022-03-06 15:37 UTC, YebinKim commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +func hasAsset(_ customer: Person, _ coffee: Coffee) -> Bool {
hasAsset의 전달인자 2가지는 모두 이름이 생략된 것으로 보이네요 👀
어떤 값을 전달해야 하는지 알 수 있도록 함수 이름 문맥에 맞는 적절한 이름을 붙여보면 어떨까요?

2022-03-06 15:37 UTC, YebinKim commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +            yagombucks.pickUpTable = "\(customer.name) 님의 커피가 준비되었습니다. 픽업대에서 가져가주세요."
픽업 테이블에는 커피가 올려져야 하지 않을까요?

2022-03-06 16:09 UTC, yeeton37 commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +let yagombucks: CoffeeShop = CoffeeShop(sales: 300000, barista: misterLee, pickUpTable: "")
별다른 이유없이 붙여놓았는데 타입 생성 후 바로바로 인스턴스 호출 해놓는게 좋을까요?ㅎㅎ

2022-03-06 16:13 UTC, yeeton37 commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +    }
아 그러네요! 주문하고 바로 결제를 하도록 바꿔보겠습니다.

2022-03-06 16:15 UTC, yeeton37 commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +    if let menu = yagombucks.menu[coffee] {
아 그러네요 ㅠㅠ assetOfYagombucks로 고쳐보겠습니다!

2022-03-06 16:18 UTC, yeeton37 commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +func hasAsset(_ customer: Person, _ coffee: Coffee) -> Bool {
넵 적용해보겠습니다!
hasAsset(of customer: Person, for coffee: Coffee) 
고객의 자산이 있는가, 커피를 위한 자산이 있는가로 해석해서 이렇게 지어봤는데 괜찮을까요??

2022-03-06 16:18 UTC, yeeton37 commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +            yagombucks.pickUpTable = "\(customer.name) 님의 커피가 준비되었습니다. 픽업대에서 가져가주세요."
넵 수정해보겠습니다 ㅜㅜ  pickUpTable이 제일 막히네요

2022-03-07 10:08 UTC, yeeton37 reviewed
안녕하세요 비비! 코멘트에 따라서 고쳐보았습니다!
제가 수정을 다 해서 저장을 한 후에 commit을 나눠서 보내려니깐 수정부분이 수정된 것처럼 안보이네요. ㅜㅜ

수정한 부분은 
1. pickUpTable의 타입을 Coffee로 지정해주었고, 프로퍼티 옵저버의 하나인 willSet을 사용하여 pickUpTable에 값이 들어오면  들어온 값을 출력되도록 해주었습니다. 
2.  pickUp이라는 함수를 CoffeeShop 클래스 내부에 선언해주어서 pickUpTable의 값을 받아오도록 해주었습니다. 
3. main.swift에서 함수 구현 순서를 코멘트에 맞게 바꾸어보았습니다

이번에는 프로퍼티 옵저버 구현 함수 안에서 customer를 호출하는데서 애를 먹었네요. ㅜㅜ
감사합니다!!

2022-03-09 04:38 UTC, YebinKim commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +let yagombucks: CoffeeShop = CoffeeShop(sales: 300000, barista: misterLee, pickUpTable: "")
현재 파일이 함수의 구현부(`step2_ordercoffee.swift`)와 프로그램 로직(`main.swift`)으로 구분되어 있으니 인스턴스 생성은 프로그램 로직부에 넣어주는 게 보기 좋을 거 같아 물어봤어요! 😄

2022-03-09 04:39 UTC, YebinKim commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +func hasAsset(_ customer: Person, _ coffee: Coffee) -> Bool {
적절하다고 생각합니다! 👍

2022-03-09 05:13 UTC, YebinKim approved these changes
예톤님 안녕하세요~
Step2 수정까지 고생 많으셨어요!

commit 을 나눠서 보내는 방분은 DM 으로 전달드렸듯 git stage 를 찾아보시면 도움이 되실 거 같아요 ☺️

프로퍼티 감시자 willSet 을 사용하며, 옵셔널을 안전하게 사용하신 것 또한 확인했는데요 👍
didSet 이 아닌 willSet 이어야 할 이유가 궁금해서 라인별 코멘트를 남겨두었으니 확인 후 답글 부탁드려요~

또한, 인스턴스의 생성 위치와 관련한 코멘트에 [답글](https://github.com/yagom-academy/swift-starter-week3/pull/55#discussion_r822280183)을 남겨두었습니다.


---

이번 스텝에서 수행하고자 했던 커피 주문 및 매출액 변경, `pickUpTable` 의 사용은 충분히 진행될 거 같아 Approve 로 리뷰 의견 드렸어요~
라인별 코멘트 확인 후 머지 의사 남겨주시면 바로 머지 또는 추가 리뷰 진행해보도록 할게요 😄

2022-03-09 05:13 UTC, YebinKim commented on CodeStarterCamp_Week3/step2_ordercoffee.swift
> +    init(sales: Int, barista: Person, pickUpTable: Coffee) {
`pickUpTable` 생성자 매개변수의 타입과 프로퍼티의 타입이 여전히 일치하지 않고 있네요!
다시 한 번 리마인드 드립니다 😊

그리고 `pickUpTable` 매개변수의 기본값이 nil이 될 수 있다면 `init(sales:barista:)` 도 선언이 필요하지 않을 것으로 보이는데 🤔
이 부분도 한 번 생각해주세요~

2022-03-09 06:46 UTC, yeeton37 commented on CodeStarterCamp_Week3/step2_ordercoffee.swift
> +        willSet {
didSet을 사용하니까 제가 입력해준 값이 바로 출력되지 않고 이전에 저장돼있던 값이 출력되더라구요..! 저는 사용자가 값을 입력했을 때 바로 그 값이 출력되길 원했어서  고객이 커피를 가져가기 전에 알리는 것을 목적으로 willSet을 사용했습니다!

2022-03-09 06:47 UTC, yeeton37 commented on CodeStarterCamp_Week3/step2 - order coffee.swift
> +let yagombucks: CoffeeShop = CoffeeShop(sales: 300000, barista: misterLee, pickUpTable: "")
아 그렇군요!! 인스턴스 생성도 앞으로는 로직부에서 해주도록 하겠습니다. ㅎㅎ

2022-03-09 06:51 UTC, yeeton37 commented on CodeStarterCamp_Week3/step2_ordercoffee.swift
> +    init(sales: Int, barista: Person, pickUpTable: Coffee) {
앗!! Coffee? 로 옵셔널 타입인데 또 안써줬네요 ;; 
pickUpTable은 고객이 없을 경우에 nil이 될 수 있는 반면
매출액인 sales와 barista는 고객이 없어도 항상 존재하기 때문에 옵셔널 선언을 해주지 않았는데 혹시 잘못 생각한걸까요?ㅎㅎ

2022-03-09 07:54 UTC, YebinKim commented on CodeStarterCamp_Week3/step2_ordercoffee.swift
> +        willSet {
`didSet` 에서도 `oldValue` 가 아닌 `pickUpTable` 을 호출하면 새로 입력해준 값을 사용할 수 있어요~
`고객이 커피를 가져가기 전`이라는 것은 이미 `pickUpTable` 에 커피가 올라와 있는 상태라는 생각이 들어서 질문 드렸어요 😄
`didSet` 에서도 예톤님이 생각하신 동작을 수행할 수 있다면 `didSet` 으로 변경하는 게 좋을지 아니면 `willSet` 이 더 의도에 맞을지 한 번 생각해보시면 좋을 거 같아요!

2022-03-09 07:57 UTC, YebinKim commented on CodeStarterCamp_Week3/step2_ordercoffee.swift
> +    init(sales: Int, barista: Person, pickUpTable: Coffee) {
`init(sales:barista:pickUpTable:)` 생성자에서 `pickUpTable` 매개변수의 기본값을 세팅할 수 있다면 `init(sales:barista:)` 의 선언이 필요하지 않을 거 같다는 뜻이었어요!
매출액인 `sales`와 `barista`는 고객이 없어도 항상 존재한다는 것에는 공감합니다 😄

2022-03-09 09:32 UTC, yeeton37 reviewed
안녕하세요 비비!!
이번 코멘트는 머지 전에 수정해보는 게 좋을 것 같아서 다시 commit하여 보냅니다!

코멘트에 따라서 변경한 것은
1.  기존 step2_ordercoffee에서 main.swift로 인스턴스 선언 위치를 변경해주었습니다.
2. willSet 보다 didSet이 취지에 더 맞는 것 같아서 변경해주었습니다.
3. pickUpTable을 nil로 초기화해주어 아래 init 부분에서 pickUpTable을 뺀
```swift
init(sales: Int, barista: Person) {
         self.sales = sales
         self.barista = barista
     }
```
부분을 삭제해주었습니다!

감사합니다 만약 부족한 것이 다 해결되었다면 여기서 머지부탁드려요~~!!

2022-03-09 09:32 UTC, yeeton37 commented on CodeStarterCamp_Week3/step2_ordercoffee.swift
> +        willSet {
헉 pickUpTable을 호출해주면 새로 입력해준 값을 사용할 수 있군요...! ㅠㅠㅠ 
고객이 커피를 가져가기 전에 호출한다는 의미에서 willSet 을 써준 것이었는데, 생각해보니 그것도 이미 커피가 올라와있는 상태이기 때문에 테이블 입장에서 보면 didSet을 쓰는게 나을 것 같네요! 
```swift
 didSet {
             guard let pickuptable = pickUpTable, let name = self.customer?.name else { return }
             print("\(name)님의 \(pickuptable)가 준비되었습니다. 픽업대에서 가져가주세요.")
         }
```
이렇게 바꿔주었습니다!

2022-03-10 16:05 UTC, YebinKim approved these changes
예톤님 안녕하세요!
수정 진행까지 고생 많으셨어요 😆👏
요청 주신대로 바로 머지 진행할게요~

Week3 프로젝트 마무리까지 고생 많으셨습니다 😄👍

2022-03-10 16:05 UTC, merged