Week3 [Step1] SEO-YJ
yagom-academy/swift-starter-week3 pull request #65
Opened 2022-03-07 15:02 UTC by SEO-YJ

@hrjy6278 
지스님 안녕하세요!
PR이 많이 늦어졌습니다,,,

Week3-step1 과제를 수행하였습니다!

이번 과제로 '사람' 클래스, '카페' 클래스 타입과 프로퍼티, 메소드 등을 정의해보고 
각 인스턴스끼리 값을 주고 받는 과정을 진행해 보았습니다!

## Person 클래스
### * 사람을 클래스로 선언한 이유
1. 사람의 공통적인 속성을 프로퍼티, 동작을 메소드로 정의한 후에
직업(학생, 회사원, 군인, 개발자 등), 인종(황인, 흑인, 백인 등) 세부적인 그룹에 속한 사람들을 '상속'하여 만들기 위해
'클래스'로 정의해 보았습니다.

### * Person 클래스 내부의 PersonalInformation, PhysicalInformation 구조체
(1) 개인정보, 신체정보를 구조체로 선언한 이유
1. 각 그룹별로 연관된 프로퍼티를 모아서 하나의 데이터 타입으로 그룹화하여 표현하고 싶었습니다.
2. 위 그룹 타입은 상속할 필요가 없고, 상속받을 필요가 없기에 구조체로 타입을 지정하였습니다.

(2) 개인정보, 신체정보의 프로퍼티를 var(변수)로 선언한 이유
1. 사람의 특성 중 변경 가능한 모든 프로퍼티는 var로 선언하여 멤버의 값을 변경할 수 있도록 하였습니다.

(3) Person 클래스의 모든 프로퍼티를 생성자에 넣지 않은 이유
1. 사람의 필수정보들 위주로 생성자의 매개변수로 넣어보았습니다.

(4) 생성자가 2개 인 이유
1. 사람 중 직업, 학교, 직장이 없는 경우가 있을 수 있으므로,
이는 '옵셔널 타입'으로 구분하여 선언 후, 
위 프로퍼티가 필요한 경우와 필요하지 않은 경우로 구분하여 선언하였습니다.

(5) 생성자가 '옵셔널' 타입인 이유
1. '사람'의 특성에 맞지 않는 값이 생성자의 인자로 들어오는 경우,
nil 값을 반환하도록 하였습니다.
ex> 나이가 0보다 작거나, 130살 보다 많은 경우

## CoffeeShop 클래스
### Coffee 타입에 타입 프로퍼티 배열을 넣은 이유
1. case 값들을 반복문으로 사용하고 싶은 경우가 있었는데, 이를 고민하다가 
타입 프로퍼티로 case값을 배열 내에 넣고 사용해 보았습니다.

### 질문 1
혹시, 이렇게 case외에 다른 프로퍼티를 열거형에 넣어도 되는지 궁금합니다!

### decideCoffeePrice 메소드
'커피의 가격을 결정'하는 메소드 입니다.
이 메소드에서 Coffee 타입의 열거형의 배열 프로퍼티로 반복문을 돌려서,
사용자에게 가격을 입력받도록 구현해보았습니다.

### 질문 2
readLine() 에러 문제
 메뉴를 입력하는 부분에서
 한글을 쓰고 지운 후, 영어로 입력하면 'ㅇcaramelMacchiato', 'ㅍㅑvienna'와 같이 이상한 값이 출력된다.
입력 buffer에서 안 지워졌나??? 라고 생각하였었습니다,,
 
Test1: readLine메소드의 매개변수 strippingNewline: false로 변경
결과: 실패

지금까지의 추측으로는 Mac OS의 ‘한글 자소 분리 문제’ 때문이라고 보고는 있습니다.
NFDMac OS에서 한글을 저장하는 방식: NFD(Normalization Form Canonical Decomposition)

"한국어.txt"저장 -> "ㅎㅏㄴㄱㅜㄱㅇㅓ.txt"로 풀어서 유니코드로 저장

ex) 보통 mac -> window로 파일을 전송할 때,window에서 파일을 열어보면 한글 자소가 분리되어 있는걸 발견하였다고 합니다. 왜 이런 에러가 나는지 궁금합니다,,!

### storeMenu 메소드
'메뉴를 저장'하는 메소드 입니다.

### order 메소드
바리스타에게 손님이 '주문'하는 메소드 입니다.

### printMenu 메소드
'메뉴를 출력'하는 메소드입니다.

### decideCoffeeMenu 메소드
'손님이 커피 메뉴를 결정'하는 메소드 입니다.
여기서도 Coffee 타입의 타입 프로퍼티 배열로 반복문을 돌려서 사용하였습니다.

### calculateNowPrice 메소드
'현재까지의 가격 계산' 메소드 입니다.
여기서도 Coffee 타입의 타입 프로퍼티 배열로 반복문을 돌려서 사용하였습니다.

### calculateAllPricePay 메소드
'모든 가격 지불 계산' 메소드입니다.

### makeCoffee 메소드
'커피를 만드는' 메소드입니다.
여기서, 딕셔너리 컬렉션 타입의 key 값들과 for in 반복문을 이용해,
'pickUpTable의 재사용a을 위해
'pickUpTable'의 모든 멤버를 출력하며,
'pickUpTable의 모든 멤버 제거'를 진행해보았습니다!

### playCoffeeShopGame 메소드
'커피샵 게임 메소드' 입니다.
손님 인스턴스
바리스타 인스턴스
카페 인스턴스
3 인스턴스가 값을 주고 받으며, 카페의 주문, 계산 로직을 구현해보았습니다.

### 질문 3
게임이나 코딩 같은 것을 만들 때,
개발자 본인은 그 프로그램을 직접 작성하여 어떤 질문에, 어떠한 값을 넣을 지 잘 알고 있어 
타인이 이 게임을 해보았을 때, 어떠한 불편한 점, 이해하기 어려운 점, 에러 등이 있을지 인지하는 것이 중요하다고 배웠습니다.
혹시, 이 'CoffeeShopGame'은 많은 문제들이 있겠지만, 특히, 어떤 부분에서 부족한 지 알고 싶습니다!

지스님! 항상 좋은 피드백 감사합니다!!

2022-03-08 09:09 UTC, hrjy6278 requested changes
안녕하세요 유준님! 벌써 마지막주네요! 그간 정말 고생하셨습니다. 
제가 리뷰를 처음하는지라 많이 부족했습니다..ㅎㅎ 그래도 항상 쏙쏙 배우시는걸 보고 뿌듯했답니다.
정말 코딩잘하시는것 같아요 👍

이번 객체야 놀자 스텝을 몽땅해주셨네요 ㅎㅎ 좋습니다. 아무래도 기간이 기간인만큼 리뷰도 빡세게 해보겠습니다.

질문에 대한 제 생각을 좀 말씀드려볼게요!

>Coffee 타입에 타입 프로퍼티 배열을 넣은 이유
>case 값들을 반복문으로 사용하고 싶은 경우가 있었는데, 이를 고민하다가
>타입 프로퍼티로 case값을 배열 내에 넣고 사용해 보았습니다.
>질문 1
>혹시, 이렇게 case외에 다른 프로퍼티를 열거형에 넣어도 되는지 궁금합니다!

넵 저도 자주 사용합니다! 하지만 현재 배열을 추가하는 것이라면 제가 코멘트를 달아드렸으니 확인해주세요!


> 질문 2
> readLine() 에러 문제
> 메뉴를 입력하는 부분에서
> 한글을 쓰고 지운 후, 영어로 입력하면 'ㅇcaramelMacchiato', 'ㅍㅑvienna'와 같이 이상한 값이 출력된다.
> 입력 buffer에서 안 지워졌나??? 라고 생각하였었습니다,,
> 
> Test1: readLine메소드의 매개변수 strippingNewline: false로 변경
> 결과: 실패
> 
> 지금까지의 추측으로는 Mac OS의 ‘한글 자소 분리 문제’ 때문이라고 보고는 있습니다.
> NFDMac OS에서 한글을 저장하는 방식: NFD(Normalization Form Canonical Decomposition)
> 
> "한국어.txt"저장 -> "ㅎㅏㄴㄱㅜㄱㅇㅓ.txt"로 풀어서 유니코드로 저장
> 
> ex) 보통 mac -> window로 파일을 전송할 때,window에서 파일을 열어보면 한글 자소가 분리되어 있는걸 발견하였다고 합니다. 왜 이런 에러가 나는지 궁금합니다,,!
> 

이 부분은 저도 좀 검색해봤는데 시원한 답이 없네요.. 잘 모르겠습니다 ㅠㅠ 다만 redLine()은 iOS앱 개발에서는 쓰이지 않으니 안심하셔도 될 것 같습니다.

고생하셨습니다!

2022-03-08 09:09 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +}
만약에 이중 하나라도 기본값 없이 선언만 되어있다면 에러가 나려나요? 어떻게 생각하시나요?

2022-03-08 09:09 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +        static let coffeeList = [americano, caffeeLatte, caffeMocha, cappuccino, caramelMacchiato, espresso, hazlnutLatte, vienna]
`static` 프로퍼티를 선언하네요! 왜 그냥 `let`을 쓰지 않고 `static`을 써주셨나요?

2022-03-08 09:09 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +    var cafeName: String
`cafeName`이 바뀔 수 있나요?

2022-03-09 09:30 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +}
- 클래스 안에 구조체의 인스턴스가 있는 경우

일반적으로 선언된 구조체 vs 타입 내부의 타입으로 선언된 중첩된 타입

일반적으로 선언된 구조체: 구조체의 ‘인스턴스'를 초기화하여 구조체의 프로퍼티, 메소드를 사용 가능합니다.

타입 내부의 타입으로 선언된 중첩된 타입: 바깥 타입의 인스턴스 (여기서는 Person class의 인스턴스)를 선언하면, 내부의 타입 (PhysicalInformation, PersonalInformation) 구조체의 프로퍼티, 메소드를 사용할 수 있습니다.

제가 현재 알고 있는 지식은 이 정도 인 것 같습니다. 혹시 다른 차이도 알 수 있을까요???

2022-03-09 09:40 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +        }
"사람이 가지고 있는 특성이 아닌, 다른 인자 값이 들어오면 사람이 될 수 없다. "
라는 생각을 가지고 생성자 내부에 조건문을 만든다는 것이, 많은 분기분을 만든 것 같습니다,,

1. 생성자 코드 가독성
2. 중첩된 구조체(PhysicalInformation, PersonalInformaion) 대신, 외부에서 주입

위 두 가지를 고려하여. 코드의 가독성을 높여 다시 작성해 보겠습니다!

2022-03-10 08:12 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +
앗,,, 저 부분의 컨벤션이 맞지 않았습니다 ㅠㅠㅠ

2022-03-10 08:14 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    init?(socialSecurityNumber: String, name: String, age: Int, residence: String, phoneNumber: String, job: String?, school: String?, company: String?, height: Double, weight: Double, money: Int) {
Person 클래스가 외부에서 PersonInformation의 구조체 인스턴스를 '주입'받는 형식으로 코드를 수정하였습니다. 이를 통해, Person 클래스의 생성자를 새롭게 리팩토링 해보았습니다!

2022-03-10 08:17 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    deinit {
deinit 메소드
1. 오직 Class 타입에서만 (Struct, Enum X) 존재한다.
2. 클래스를 참조하는 RC(Reference Counting)이 0이 될 경우 
(아무도 이 클래스를 참조하지 않을 경우)
힙 영역에서 인스턴스에 대한 메모리 할당을 해제할 때, 실행되는 메소드로 알고 있습니다!

이 부분에 대해서 짚어주시어, 
메모리 구조
메모리 관리
ARC(Automatic Reference Counting)
에 대해 공부할 수 있었습니다. 감사합니다!

2022-03-10 08:27 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +        print("현재 \(personalInformation.name)이 보유한 돈은 \(money)입니다.")
넵! 
Person 클래스는 사람이 꼭 해야하는 '공통적인' 기능만을 담고 있는 것이 맞습니다.
buy라는 메소드는 '구매'라는 기능으로써,
이는, 소비자(customer)라는 Person 클래스를 상속받은 클래스를 선언해주는 것이
바람직한 것 같습니다!
객체지향프로그래밍-추상화 부분에 대해 짚어주시어 감사합니다!

2022-03-10 08:29 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    var barista: Person?
이렇게 작성한 이유
: Person 클래스가 '옵셔널'타입으로 선언하여 Person? 타입으로 barista를 선언하였었습니다.

Person 클래스의 생성자를 수정하며 '옵셔널'이 아닌 타입으로 Person 클래스를 수정하여 다시 리팩토링 하였습니다!

2022-03-10 09:32 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    var straw = 20
직접적으로 인스턴스의 프로퍼티에 접근하는 방법 대신에,
'카페의 기구들 세팅'을 하는 메소드를 하나 선언하여 초기화하였습니다!
이때, 저장 프로퍼티 -> 지연 저장 프로퍼티(lazy)로 선언하여,
메소드를 호출하여, 메소드를 호출할 때 프로퍼티들을 초기화하는 방식으로 진행해보았습니다!

2022-03-10 09:34 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +            }
컨벤션에 주의하도록 하겠습니다 ㅠㅠㅠㅠㅠㅠㅠ

2022-03-10 10:17 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +                } else {
문자열을 for in 반복문에서 사용하여, isNumber 함수를 이용해 숫자만 입력받고,
숫자가 아닌 다른 값이 들어올 경우 다시 외부반복문을 실행하는 코드를 작성해보았습니다!

또한, if let -> guard let을 활용하여 코드의 가독성을 높여보았습니다!

2022-03-10 10:29 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    var menu: [Coffee: String] = [:]
넵! 커피의 종류와 그에 대한 가격을 저장하는 딕셔너리입니다.
처음에, readLine() 메서드가 String? 타입을 반환하여 String으로 값을 저장하도록 하였습니다.

하지만, isNumber를 통해 가격을 숫자만 입력받게 한 후,
숫자에 대한 조건이 성립하였으니 가격의 값을 Int 타입 '강제 추출형 !'를 사용하여,
딕셔너리의 value로 저장하도록 수정하였습니다!

2022-03-10 10:39 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    func order(to barista: Person?, for customer: Person?) {
처음에 Person 타입을 선언할 때, 생성자를 '옵셔널'타입으로 선언하여 
Person? 타입으로 매개변수 타입을 지정하였었습니다.
Person의 생성자를 리팩토링하여, 위 매개변수 타입 역시 변경하였습니다!

2022-03-10 10:40 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    }
꼼꼼히 보겠습니다,,,,,

2022-03-10 10:46 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +                count += 1
해당 메소드는 손님이 커피 메뉴와 가격을 입력하면
어떠한 커피를 몇 잔 골랐고, 현재 계산할 가격을 얼만지 알려주는 메소드 입니다!

반복문에서 사용자에게 입력받은 값으로,
1. 커피 이름
2. 커피 갯수
3. 현재까지 지불해야 하는 돈(Pos 기계를 생각해보았습니다.)
세 정보를 제공해줍니다!

2022-03-10 11:14 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    func calculateNowPrice(_ coffeeName: String, _ coffeecount: String, _ menu: [Coffee: String]) {
프로퍼티로 menu 딕셔너리가 있는데 또 menu 딕셔너리를 주입받는 이유가 있을까요?! 
: 당시에 클래스 타입의 프로퍼티를 사용하는 것에 미숙했던 것 같습니다 ㅠㅠㅠ
menu를 인자로 받는 calculateNowPrice를 수정하였습니다!

현재 Argument Label에 와일드카드 패턴이 너무 들어가있어서 사용하는데 있어서 어떤 파라미터를 주입시켜줘야 하는지 명확하지가 않습니다... 
: 해당 메소드는 '커피이름(coffeeName)'과 '커피 잔 수(coffeeCount)'를 사용해 '현재까지 지불할 가격 계산' 메소드입니다.
와일드카드로 파라미터를 받으니 어떤 값을 넣을지 모호하여, 우선은 coffeeName, coffeeCount로 지정하였습니다!

2022-03-11 03:45 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +        static let coffeeList = [americano, caffeeLatte, caffeMocha, cappuccino, caramelMacchiato, espresso, hazlnutLatte, vienna]
오 새로운 개념을 알려주셔서 감사합니다!
protocol CaseIterable을 공식문서에서 찾아 공부해보았습니다.
CaseIterable 프로토콜의 allCases라는 프로퍼티를 통해 
case들을 collection으로 접근할 수 있었습니다!
이 개념을 적용하여 코드를 수정해보겠습니다!

2022-03-11 04:14 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +               }
다시 생각해보며 코드를 살펴보니, 
이 부분은 coffeeList 배열의 모든 요소들을 한번씩 검사만 하면 되므로
무한루프 같은 기능이 필요없어, while보다는 
for in으로 멤버를 하나씩 검색하여 사용하거나
forEach 구문을 사용하는 것이 좋을 것 같습니다.
코드가 길어져 코드를 작성하는 이유를 깊게 고민하지 않고,
'그냥 반복문을 돌려야 할 것 같으니 while을 사용하자!'라고 생각이 들었던 작성인 듯 합니다,,,,

2022-03-11 04:56 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    }
이 경우 역시, 전 code에서 Person을 옵셔널 타입으로 생각하여,
Person 클래스의 인스턴스를 받는 모든 매개변수에 옵셔널타입 Person?으로 작성해놨던 것 같습니다 ㅠㅠ
수정하였습니다!

2022-03-11 04:59 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    func playCoffeeShopGame(_ baristaPlayer: Person?, _ customerPlayer: Person?, _ coffeeShop: CoffeeShop) {
위 경우 역시 Person을 옵셔널 타입으로 생각하여 이렇게 작성하였습니다.

바리스타: 카페 생성자에서 받도록 수정하였습니다!
'카페게임'은 두 사람 인자가 있어야 하므로, 
(customerPlayer: Person, coffeeShop: CoffeeShop)로 매개변수를 수정하였습니다!
전달인자 레이블에서 '와일드카드 패턴'을 제거한 이유는,
게임에 들어갈 인자가 어떠한 것인지 사용자에게 알려주는 것이 중요하다고 생각하여
제거하였습니다!

2022-03-11 05:00 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +
삭제하겠습니다,,.,.,.,.,.

2022-03-11 05:11 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(cafeName: "yagombucks")
이 코드를 작성할 당시에 생각
클래스의 인스턴스를 let(상수)로 선언하면 내부의 프로퍼티도 변경 불가능하지 않을까?
-> 클래스의 내부 프로퍼티를 변경하고 싶을 경우는 var(변수)로 클래스 인스턴스를 선언해야겠다!!

피드백 해주신 사항을 보고 공부한 뒤 적용
공부 내용
* 메모리 구조
* 메모리 관리
* 클래스 vs 구조체
* 클래스와 구조체를 let으로 선언할 경우

클래스
: 클래스는 '참조'타입으로써 인스턴스를 생성시 메모리 구조(Code, Data, Heap, Stack) 중 'Heap' 영역에 
인스턴스의 메모리를 할당받는다!

구조체
: 구조체는 '값'타입으로써 인스턴스를 생성시 메모리 구조 중 'Stack'영역에 인스턴스의 메모리를 할당받는다!

클래스를 let으로 선언할 경우
let yujun = Person()
yujun이라는 상수는 'Stack' 위치에 (지역상수일 경우)
=> Person 인스턴스의 '주소값'을 저장하는 '상수'일 뿐

생성된 Person 인스턴스는 클래스 타입일 경우 '참조'타입이므로 'Heap' 위치에
Person프로퍼티의 내부 프로퍼티 역시 'Heap' 위치에

yujun이라는 상수는 '주소값'을 저장하며, Stack에 메모리 할당된 값이므로,
Person 인스턴스와는 다른 위치에 할당되어있다!
따라서, Person 클래스 내부 프로퍼티의 변수(var), 상수(let)에 따라 값을 바꿀 수도, 못 바꿀 수도 있다.

결론
: 클래스 인스턴스를 '상수'로 선언하여도, 내부 프로퍼티의 '값 변경'과는 무관하다!

적용
var misterLee = Person(socialSecurityNumber: "999999-1111111", name: "misterLee", age: 24, residence: "서울", phoneNumber: "010-1234-5678", height: 170.5, weight: 80.3, money: 100000)
var missKim = Person(socialSecurityNumber: "999999-4444444", name: "missKim", age: 20, residence: "경기도", phoneNumber: "010-5678-1234", height: 161.3, weight: 50.2, money: 100000)
var yagombucks = CoffeeShop(cafeName: "yagombucks")

위 3개의 값은 모두 '클래스'타입의 '인스턴스'를 생성하는 것이니,
let으로 선언하여도 상관없다!
만약에, misterLee, missKim 등의 주소값을 담는 상수가 다른 Person의 주소값을 담는 경우가 있다?!?! 
이럴 경우에는 변수(var)로 선언해야 한다. (하지만, 변수명이 misterLee, missKim 인데 상수로 해야할 것 같다.)

이러한 부분에 대해 정확히 짚어주셔서, 
클래스와 구조체, 메모리에 대해 공부해 볼 수 있는 좋은 시간이었습니다!!!!

2022-03-11 05:13 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +yagombucks.playCoffeeShopGame(misterLee, missKim, yagombucks)
이 부분은 위의 피드백에서 말씀드린 것 처럼,
사용자가 '이 부분에 어떤 인자가 들어가야 되지???'라는 생각이 무조건 들기 때문에
와일드 카드 패턴을 제거하였습니다!

2022-03-11 05:16 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +}
만약에 이중 하나라도 기본값 없이 선언만 될 경우에
구조체는 
'사용자 정의 이니셜라이저(init)을 정의하지 않을 경우에, 
멤버와이즈 이니셜라이저를 제공' 하는 것으로 알고 있습니다.

따라서, PersonalInformation의 구조체의 인스턴스를 생성할 경우에
멤버와이즈 이니셜라이저가 등장해 인자를 입력받으라고 xcode가 알려줄 것 같습니다!

2022-03-11 05:17 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +    var cafeName: String
카페의 이름은 상수값이 맞는 것 같습니다!

2022-03-11 07:21 UTC, SEO-YJ commented on CodeStarterCamp_Week3/main.swift
> +        static let coffeeList = [americano, caffeeLatte, caffeMocha, cappuccino, caramelMacchiato, espresso, hazlnutLatte, vienna]
이 부분은 사실 블로그에 열거형 내부에 배열을 넣는 코드가 static 키워드로 되어있어서
음,,, 그냥 이렇게 하는 거구나 하고 작성했는데,
static 키워드에 대해 공부해보니 static 키워드를 사용하는 용도가 있는데, 무지성으로 작성한 것 같습니다,,

class 내부의 static 키워드는 '오버라이딩이 되지 않는, 타입 메서드, 프로퍼티'가 필요할 때 붙이는 것입니다.
현재, coffeeList 배열은 class 내부에서 Coffee.coffeeList로 호출 가능하니,
static을 붙일 필요가 없는 것 같습니다.

아마, 필요한 경우가 있다면,
main로직이나, 다른 함수 내부에서
class의 인스턴스를 만들지 않고 타입 프로퍼티를 사용하고자 할 때? 사용할 것 같습니다!
이 부분은 caseIterable로 case 값들을 배열로 변환하여 사용했기에 제거하였습니다!

2022-03-11 08:43 UTC, SEO-YJ commented
@hrjy6278 
지스님! 안녕하세요! 
캠프 마지막 PR을 요청드립니다!
이번 PR이 코드 스타터 캠프를 진행하며 요청드리는 마지막 PR이 되어 아쉽습니다 ㅠㅠㅠ
항상 세세하고 꼼꼼한 리뷰와 생각해볼 것, 공부해 볼 것을 친절하게 제공해주셔서
캠프 기간 동안 너무 감사했습니다!!!
피드백을 통해, 코드를 작성하는 이유와 고민들이 매우매우 중요함을 배웠습니다 ㅎㅎㅎㅎ
수정한 내용들은 리뷰에 대댓글로 남겼습니다!

# Person
## protocol AnimalAct, protocol AnimalBody
저번 피드백에서 Person클래스의 생성자 매개변수로 외부에서 구조체의 인스턴스를 '주입'하는 것을 제안해주셔서
공부하던 중 '의존성 주입'에 대해 공부하여 적용해보았습니다.
Person의 상위 개념을 '동물'로 생각해보았고,
동물의 동작, 신체를 '프로토콜'로 정의해보았습니다.

## struct PersonAct, PersonBody
PersonAct는 AnimalAct, PersonBody는 AnimalBody의 상위 프로토콜을 통해 타입을 만들어보았습니다.
이를 통해 얻을 수 있는 효과는 다음과 같습니다!
* Person Class에서 PersonAct, PersonBody의 프로퍼티, 메서드를 사용시에
프로퍼티, 메서드의 변경이나 제거가 발생하면
기존: Person 클래스 코드 라인에서 에러
수정: 각 구조체 인스턴스 코드 라인에서 에러
로 인해, 어느 구조체에서 문제가 발생했는지 명확하게 알 수 있습니다.
* 결합도는 줄어들고, 코드의 재활용성이 올라갑니다!

## struct PersonInformation
위 구조체는
기존: 저장 프로퍼티에 기본값을 저장
수정: 구조체의 '멤버와이즈이니셜'을 통해, 값을 받음
으로 수정하였습니다.

personInformation의 프로토콜을 만들지 않은 이유는 
프로토콜로 상위 타입을 만들 수 없다고 생각했기 때문입니다.
동물 -> 사람의 관계를 '상위' '하위 관계로 생각해보았을때.
동물은 정보를 가질 수야 있지만, 사람처럼 '정보'를 꼭 가지고 있지는 않다고 생각하여
 personInformation은 구조체만 선언하였습니다.

## class Person
### personInformation, personBody 구조체 인스턴스를 받는 것을 '변수'로 선언한 이유
: 변수로 선언한 이유는 구조체는 '값 타입'이므로 RAM의 메모리 영역 중 'Stack'에 저장됩니다.
PersonInformation, PersonBody 구조체의 경우, 내부 프로퍼티에 변수가 있고,
이 값들을 변경할 경우가 있습니다.
 구조체를 let으로 선언할 경우 내부 프로퍼티의 값을 변경할 수 없기에 var로 선언하였습니다!

### personAct를 let으로 선언한 이유
: PersonAct 구조체의 인스턴스는 변할 이유가 없기에 상수로 선언하였습니다!

### init
생성자는 모두 외부에서 구조체의 인스턴스를 주입하는 방식으로 짜보았습니다.
이를 통해, 
1. 클래스 인스턴스 생성 시 매개변수의 갯수를 줄일 수 있다. 
2. 생성자 내부의 분기문을 제거하였다. 
4. 코드의 간결성이 높아진다. 
5. 를 생각하여 작성해 보았습니다.

### Person 클래스타입을 상속받은 Customer  class
Person class를 상속받은 Customer classs는 '구매'하는 메서드가 내부 메서드로 정의되어 있습니다.

# CoffeeShop
## Coffee 열거형
커피의 이름을 각 case에 나열하였습니다.
각 Case 값을 String 값으로 쓰고 싶기에 String 타입과
각 Case 값들을 배열로 만들어 반복문에 적용해 보고 싶기에 Protocol CaseIterable을 적용하였습니다.

## setCafeObject 내부 메서드
카페의 물건 내부 프로퍼티들은 setCafeObject 메소드를 이용해 초기화를 하는 방법으로 작성해보았습니다.
 lazy(지연 저장 프로퍼티)를 통해 카페의 물건을 세팅할 시점에 저장 프로퍼티 값을 초기화하도록 하였습니다.
 중요: lazy 키워드는 생성자에서 초기화 하지 않기 때문에 선언 시점에 기본값을 저장해주어야 합니다.

## decideCoffeePrice
1. 열거형의 Case값들을 map을 이용해 '배열'로 리턴하여 반복문에서 사용하였습니다.
2. isNumber 메소드를 이용하여 '숫자'가 아닌 다른 값이 입력될 경우, 다시 입력하도록 하였습니다.

수정 사항들은 
모두 리뷰에 대댓글로 남겼습니다!

지스님! 그동안 정말 감사했습니다!!!!!!

2022-03-13 02:45 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +}
만약 해당 Person 타입안에 PhysicalInformation 이란 타입이 중첩되어 있다면 해당 Information 인스턴스를 만들기 위해서는

`let jissPhysical = Person.PhysicalInformation()` 이런식으로 체이닝을 통해 접근을 해야 인스턴스를 만들 수 있습니다!

2022-03-13 02:47 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +    var straw = 20
이 부분은 왜 Lazy로 선언했는지 제가 코드를 한번 봐봐야 될 것 같네요 ㅎㅎ

2022-03-13 02:49 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +                count += 1
while 조건반복문을 쓰지 않고서 할 순 없을까요?

2022-03-13 02:51 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(cafeName: "yagombucks")
오오 메모리 구조까지 공부하시다니 대단하십니다 👍

2022-03-13 02:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +}
멤버와이즈 이니셜라이저를 공부하길 원했는데 딱 공부를 하셨군요! 좋습니다 💯

2022-03-13 02:53 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +        static let coffeeList = [americano, caffeeLatte, caffeMocha, cappuccino, caramelMacchiato, espresso, hazlnutLatte, vienna]
현재 static으로 선언된 타입은 enum 열거형입니다. 

enum 열거형에 인스턴스 프로퍼티를 할당 할 수 있는지

enum 열거형은 인스턴스를 만들 수 있는지 에 대해 공부해보시면 좋을것 같네요!

2022-03-13 03:52 UTC, hrjy6278 approved these changes
고생하셨습니다 유준님 👏🏻  제가 코드리뷰가 처음이라 설명을 퍼뜩못하는데도 잘따라와 주셨네요.

그간 부족한 코드리뷰를 찰떡같이 알아주셔서 감사했습니다 :)

의존성 주입도 배우시고,, 정말 남다르시네요. 저도 의존성주입 지키기가 너무힘든데 ㅠㅠ..

의존성주입을 왜하는지 궁금하시면 `SOLID 원칙`을 한번 찾아보시면 좋을 것 같아요 ㅎㅎ

그간 정말 고생많으셨고 앞으로 iOS 개발자로 만나길 기대하겠습니다.

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +    var personBody: PersonBody
코드를 자세히 보니 이 두개의 타입은 Struct타입이네요. 왜 Struct를 쓰셨는지 유준님의 생각이 궁금하네요!

클래스와 구조체의 차이는 무엇일까요?

유준님이 한번 더 생각 할 수 있게 말을하자면, 스위프트의 메모리 구조에 대해 공부하시고

클래스의 내부에 구조체타입의 프로퍼티가 있다고 칩시다.

만약 해당 클래스 Person이 인스턴스화 되어서 변수가 참조를 하게 됩니다.

`var jiss = Person()` 이때는 jiss라는 스택에있는 변수가 Person이라는 힙에있는 인스턴스를 참조하게 됩니다.

여기에서

`let yujun = jiss` 이렇게 되었을때 jiss의 주소값을 참조하게 되니 두개의 프로퍼티가 같은 Person 인스턴스를 가르키겠죠?

이때 구조체는 참조가 아니라 복사가 된다고 했습니다.
Person 인스턴스 프로퍼티로 정의된 PersonBody, PersonInformation 은 구조체이니 복사가 될까요? 스위프트에서는 어떻게 저장하게 될까요?

이 부분을 깊게 알고 싶으시면 Understanding Swift Performance WWDC를 한번 보시는걸 추천드려요!

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +    lazy var straw: Int = 0
이 부분은 왜 lazy로 선언하신건가요?

그리고 더 깊게 가보자면 이 프로퍼티를 외부에서 접근해야 할 일이 있을까요? 현재 셋팅하는 `setCafeObject()` 가 있으니 해당 프로퍼티를 외부에서 변경하는 행동을 하는 메서드를 만들었으니 직접적으로 변경을 못하도록 접근제어자를 사용하여 `private`으로 선언해두는게 좋을것 같네요 5주차에 배우셨죠?ㅎㅎ

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +            let bodyNameCountInteger = Int(bodyNameCount)
```
 if let bodyName = bodyName,
    let bodyNameCount = bodyNameCount,
    let bodyNameCountInteger = Int(bodyNameCount) {
            let bodyNameLiteral = bodyName
            ...
```

이렇게 해도 되겠네요!

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +                    self.cup = Int(cupSelect)!
코드를 자세히보니 전부 프로퍼티에 접근하는 곳에 self 키워드가 붙어있네요. self가 어떤건지 알고 계신가요? self, Self 대소문자를 구분할까요?ㅎㅎ

그리고 보통은 클로저에서 self를 사용할때를 제외하고는 `self` 키워드는 생략합니다! 그냥 보통의 암묵적인 룰이랄까요?ㅎㅎ;;

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +                    self.straw = Int(strawSelect)!
옵셔널 강제 추출은 앞으로 스위프트 코딩을 하실때 전부 지적받으실거예요.

진짜 모든수를 다써보고 강제추출말고는 방법이 없을때만 사용하시길 바랍니다.

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +                }
for문을 사용하여 문자열 하나하나를 `Character` 타입으로 비교하는것도 좋습니다. `Character` 타입이란걸 알기때문에 `strawSelectChar` 명칭은 좋지못하네요

저였다면 

```
 while true {
            var loopIsNumberCount = 0
            print("빨대 갯수:", terminator: " ")
            let userInput = readLine()
            
            guard let userInput = userInput,
                       let userStrawSeleted = Int(userInput) else {
                      print("잘못 된 입력입니다. 다시 입력해주세요!")
                      continue
            }
              straw = userStrawSelected
              break
```
```
            
while true {
            if let userInput = userInput,
               let userStrawSelected = Int(userInput)  {
                straw = userStrawSelected
                
              
            } else {
                print("잘못 된 입력입니다. 다시 입력해주세요!")
                continue
                }
            }
        }
}
```

이렇게 사용을 고려해봤을 것 같아요!

그리고 너무 중복되는 로직들이 빨대, 의자, 책상에 걸쳐서 로직이 중복되는 것 같아요. 이를 메서드로 중복되는 부분을 줄일 수 있지 않을까요?

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +        }
제 개인적인 취향은 if는 else가 없으면 잘 쓰지 않습니다. 아닐경우의 로직을 고려하지 않았거나, 놓친경우라고 생각할 수도 있기 때문입니다. 

만약 이 코드를 제가 봤을때 customer가 없을때는(옵셔널일경우) 아무런 실행이 되지않는 코드라고 보입니다. 만약 이게 진짜 서비스되는 앱이라고 생각해보면 커피 계산버튼을 눌렀는데 계산내역이 나오질 않겠죠? 그렇다면 유저입장에서 앱이 아무런 동작을 안하고 있는거라고 보여질 것 입니다. 이럴경우 보통은 다시 앱을 껐다 키거나, 계속 반복될시에 최악으로는 해당앱을 삭제 할 수도 있겠죠?

뭐 크래쉬가 안나는게 다행이라고는 생각합니다. 다만 `!` 옵셔널 강제 추출에서 언랩핑이 실패할 경우에는 정말로 앱이 꺼집니다. 그래서 지양하는 방법이라고 하는 것입니다!

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +    let cafeName: String
`String`타입을 반복문을 돌렸을때에 하나하나의 Element가 `Character` 타입입니다. 그렇다면 String은 `Character` 을 배열로 가지고 해당 배열을 `String`타입으로 바꾼걸까요? 문자열을 어떤방법으로 메모리에 저장할까요? 추후에 호기심이 생기시면 한번 공부해보시길..!

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +    func makeCoffee(for customer: Person?) {
최상위 메서드에서 논옵셔널을 주입받는데 이 부분은 왜 옵셔널 타입을 주입받을까요?

다른 곳에서 쓰일 걸 예상하고 이렇게 하셨을까요?

그렇담 옵셔널 타입일때의 로직을 `makeCoffee` 메서드가 가지고 있어야 하지 않을까요?

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +    func calculateNowPrice(coffeeName: String, coffeeCount: Int) {
5주차에 공부를 하셨으면 접근제어자에 조금 배우셨을거예요. 보통 클래스 내부에서만 쓰이는 메서드는 private 처리를 한답니다!

은닉화를 하는것이죵!

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +    func playCoffeeShopGame(customerPlayer: Person, coffeeShop: CoffeeShop) {
딱 이 부분만 접근제어자를 internal정도로 해주고 나머지 메서드는 private 처리하면 완벽하겠네요

2022-03-13 03:52 UTC, hrjy6278 commented on CodeStarterCamp_Week3/main.swift
> +        let coffeeList = Coffee.allCases.map({ "\($0)" })
고차함수 맵을 쓰셨군요.

사용해보시고 시도해보시는 것도 정말 좋은 방법입니다. 👍  그렇다면 고차함수가 어떻게 작동되는지 한번 공부해볼까요?

1. `map` 고차함수가 하는 기능은 무엇일까요?
2. `map` 다음의  `{  }` 코드블럭은 어떤역활을 하나요? 또한 무엇이라고 부르는지 아시나요?
3. `{ }` 코드블럭안의 `$0`은 어떤역활을 하게 되나요? `$0`을 안쓰고 할 수 있을까요?
4. map 고차함수를 동일하게 유준님이 만들어 보실 수 있을까요?

2022-03-13 03:52 UTC, merged