Week3 [STEP 2] 쿼카
yagom-academy/swift-starter-week3 pull request #7
Opened 2021-12-23 05:20 UTC by Quokkaaa

안녕하세요 글렌! @Journey36 
STEP2 PR보냅니당 ㅎㅎ
최대한 메서드 기능을 분리하려고 시도했던것같습니다. 잘한지는 모르겠지만 잘 부탁드려요
추가로 어려웠던점과 특이한 오류가 발생하여 조언을 구하고 싶어요!

# 어려웠던점
- `pickUpTable: [Coffee]?` 프로퍼티를 `pickUpTable()`메서드내에서 호출하려고 시도했으나 로직을 이해하기 어려운 nil값이 계속호출됩니다. 왜 nil이 나올까에대해서 궁금하여 외부에서 비슷한 형태로 코드를 만들어 출력해보았는데 `[프로젝트명.타입.case]` 이와같이 출력이 되는데 이부분과 연관이 있을까요 ?

# 궁금한점
<img width="924" alt="스크린샷 2021-12-23 12 40 34" src="https://user-images.githubusercontent.com/91132536/147190792-1888022b-ce73-4fa0-95b9-9aec5b4fcca2.png">

- 위와같이 나오는 에러문구가 잘 이해가 되지않습니다. 기존에 struct는 멤버와이즈 이니셜라이저를 컴파일러가 제공하기때문에 지워도 문제없을거라고 생각을 했으나 `init()`을 지우니 위와같은 에러가 나옵니다..`private totalSales`을 만 `private`을 지정해주었는데 왜 레벨이 같지않다라는 문구가 나오는지 잘 모르겠습니다. 이유가 궁금하네요..^^

2021-12-23 15:10 UTC, Journey36 requested changes
@Quokkaaa
쿼카님! 고생하셨습니다. 코드 확인했고, 코멘트 달아놨으니 확인 부탁드립니다.
그리고 어려웠고 궁금한 점에 대해 얘기해보면,

> `pickUpTable: [Coffee]?` 프로퍼티를 `pickUpTable()`메서드내에서 호출하려고 시도했으나 로직을 이해하기 어려운 nil값이 계속호출됩니다. 왜 nil이 나올까에대해서 궁금하여 외부에서 비슷한 형태로 코드를 만들어 출력해보았는데 `[프로젝트명.타입.case]` 이와같이 출력이 되는데 이부분과 연관이 있을까요 ?

왜 nil이 나올까에 대한 것은 해당 프로퍼티가 무엇으로 초기화 되는지 알아보면 좋을 것 같네요. 🙂 그리고 값이 이상하게 찍히는 이유는, case 자체는 값이 아니기 때문입니다!

> 위와같이 나오는 에러문구가 잘 이해가 되지않습니다. 기존에 struct는 멤버와이즈 이니셜라이저를 컴파일러가 제공하기때문에 지워도 문제없을거라고 생각을 했으나 `init()`을 지우니 위와같은 에러가 나옵니다..`private totalSales`을 만 `private`을 지정해주었는데 왜 레벨이 같지않다라는 문구가 나오는지 잘 모르겠습니다. 이유가 궁금하네요..^^

아 이 부분은 제가 실수했습니다..죄송합니다. 😭 멤버와이즈 이니셜라이저에 대해서 말씀드린다는 걸 그만 `private` 인 것을 깜빡하고 말씀드렸더라구요.! 왜 그런지에 대해서 [공식 문서](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#ID19)를 읽어보시면 답이 나와있습니다.ㅎㅎㅎ 미안해요!

2021-12-23 15:10 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        self.pickUpTable?.append(coffee)
`self.pickUpTabble`이 뭘로 초기화 됐죠?

2021-12-24 06:43 UTC, Quokkaaa commented on CodeStarterCamp_Week3/main.swift
> +class Person {
struct인 구조체로 지정했을경우 orderDrink메서드에서의 customer매개변수값이 변경이 불가능하여 class로변경하였습니다.

2021-12-24 07:00 UTC, Quokkaaa commented on CodeStarterCamp_Week3/main.swift
> +            customer.moneyPurse? -= coffee.price
원래 메서드의 매개변수는 상수로 이루어져있어 값을 변경하는게 불가능합니다. `struct`같은 경우에는 인스턴스를 생성할 당시에 정의한 타입의 값들을 복사하여 인스턴스화가 이루어 지지만 `class`는 주소의 값을 복사하지않고 참조하여 인스턴스화 되기때문에 `Person`이라는 주소의 `moneyPurse`프로퍼티에 값에 접근하여 값을 변경 할 수 있습니다.
고로 `misterkim`의 `instance`가 최초로 생성되었을 당시인 `moneypurse`프로퍼티 주소값에 접근하여 값을 변경하는 것이다. 라고 이해했습니다.

2021-12-24 07:39 UTC, Quokkaaa commented on CodeStarterCamp_Week3/main.swift
> +        self.pickUpTable?.append(coffee)
배열인 Coffee타입의 옵셔널로 타입 자체가 초기화 된것같아요 그리고 초기화될때는 case들인 연관값들을 가지게 되는것같아요

2021-12-24 09:28 UTC, Quokkaaa commented
@Journey36 
글렌!! 답변 감사드려요 덕분에 해답 바로 찾고 알아볼수있어서 좋았어요 ㅎㅎ

- 자꾸 `nil`이 나왔던분에 원인이 `case`가 값이 아니기때문에 `nil`이나왔어서 `rawValue`나 연산프로퍼티를 통해 값을 할당해야겠다고 판단했어요. 이 중 네이밍이 좋은 연산프로퍼티로 선택했습니다. 
그런데 궁금한점이 하나더 생겼어요 `[String]?` 옵셔널타입으로 지정해서 `guard let`으로 값을 빼와서 이용하려고 하는데도 `nil`이 나오러다구요 이는 옵셔널바인딩을 해야할때는 값을 전달해야하는데 배열 전체를 전달해서 `nil`이 출력이 된걸까요?

- 공식문서 참고해주신대로 이해한바로는 1. 멤버와이즈이니셜라이저로 생성될시 프로퍼티중 `private`접근제어자가 있을경우 초기화가 같이된 프로퍼티들도 `private`으로 간주한다.
2. 직접 수기로 `init()`을 생성하게되면 private로 설정된 프로퍼티가 존재하더라도 다른프로퍼티에 영향을 받지 않는다.
가 맞을까요..ㅎㅎ?

2021-12-24 21:04 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +class Person {
어떤 부분인지 자세하게 설명이 가능할까요?

2021-12-24 21:12 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +            customer.moneyPurse? -= coffee.price
좋네요! ㅎㅎ

그럼 70번 라인의 `moneyPurse` 뒤에 물음표가 있는데 이건 뭘까요? 🤔

2021-12-24 21:15 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        self.pickUpTable?.append(coffee)
이 부분에서 알 수 없는 nil 값이 나온다고 하셨죠? 아래에 있는 `guard let` 구문에서 바로 함수를 탈출할 것 같은데요?

2021-12-24 21:25 UTC, Journey36 approved these changes
@Quokkaaa 
안녕하세요, 쿼카님! 메리 크리스마스입니다. 🎄
전체적으로 확인했는데, 간단한 부분인데 너무 어렵게 생각하신 부분이 좀 있더라구요.
그러다보니 전체적으로 코드의 양도 증가됐네요... 😯
그리고 코멘트 남겨주신 부분을 확인했는데, 약간 이해를 잘못하고 계신 것 같아요.

> 자꾸 nil이 나왔던분에 원인이 case가 값이 아니기때문에 nil이나왔어서 rawValue나 연산프로퍼티를 통해 값을 할당해야겠다고 판단했어요. 이 중 네이밍이 좋은 연산프로퍼티로 선택했습니다.
그런데 궁금한점이 하나더 생겼어요 [String]? 옵셔널타입으로 지정해서 guard let으로 값을 빼와서 이용하려고 하는데도 nil이 나오러다구요 이는 옵셔널바인딩을 해야할때는 값을 전달해야하는데 배열 전체를 전달해서 nil이 출력이 된걸까요?

case가 값이 아니기 때문에 nil이 나온 것이 아닙니다! 제가 case가 값이 아니라고 했던 부분은, `프로젝트.타입.케이스` 형식으로 값이 출력되는 부분을 말씀드린 겁니다! nil이 나오는 이유는 따로 있어요. 그 부분은 옵셔널 타입의 프로퍼티가 무엇으로 초기화되는지 알면 충분히 쉽게 고칠 수 있는 문제입니다. 🙂 한 번 고민해보시면 좋겠네요! ㅎㅎㅎ

그리고 멤버와이즈 이니셜라이저와 접근제어자의 관계에 대해서는 이해하신 게 맞는 것 같네요. ㅎㅎ

2021-12-24 21:25 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +
원시값이 아닌 연산 프로퍼티로 이름을 설정한 이유가 있을까요?

2021-12-24 21:25 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: [String] = []
타입 자체를 변경하지 않고도 해결할 수 있는 부분일텐데, 타입 자체를 변경한 게 조금 아쉽네요. 😢

2021-12-26 12:43 UTC, Quokkaaa commented on CodeStarterCamp_Week3/main.swift
> +            customer.moneyPurse? -= coffee.price
옵셔널 프로퍼티에 접근할때 값이 있는지 물어보는 동작으로 이해하고 있어요

2021-12-26 13:09 UTC, Quokkaaa commented on CodeStarterCamp_Week3/main.swift
> +
rawValue를 사용하게되면 네이밍에 가독성이 떨어질 수 있어 연산프로퍼티로 지정하였습니다.

2021-12-26 15:20 UTC, Quokkaaa commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: [String] = []
Coffee로 시도했을때 case의 값만 나오지않고 프로젝트명.타입명.case명 이렇게 노출되서 조금 어려운데요
Coffee.RawValue타입으로 초기화를 했을때는 coffee의 case값만 출력되긴하는데 이러한 방법이 맞을까요 ? ^^

2021-12-26 15:33 UTC, Quokkaaa commented
@Journey36 글렌!!!
메리크리스마스 인사를 미리못해서 너무아쉽네요,,,,흑 부디 즐거운 크리스마스가 되셨기를바랍니당..ㅎㅎ!!

pickUpTable프로퍼티 Coffee.RawValue값으로 타입으로 초기화했을때 적절하게 값을 호출할 수 있고 nil이 나오는 부분지않게 하기위해 RawValue를 활용하여 값을 넣었습니다. 이와같은 방법으로 하는게 적절할지 궁금하네요!

2021-12-26 20:14 UTC, Journey36 requested changes
@Quokkaaa
안녕하세요, 쿼카님. 주말 잘 보내셨나요? 저는 잘 보냈습니다. ㅎㅎ
이번 스텝이 생각보다 진도가 안나가는 거 같아서 답답하실거예요. 하지만, 지금 제대로 알고 넘어가야 다음에 같은 실수를 반복하지 않습니다. 또, 반복한다 하더라도 해결의 실마리를 금방 찾을 수 있습니다.
제가 생각하기에 쿼카님이 이번 프로젝트를 진행 중에 헷갈려하시는 및 하셨던 부분은 크게 두 가지 같습니다.

1. 프로퍼티가 옵셔널일 때 어떤 값으로 초기화가 어떤 값으로 이루어지는가?
2. 열거형의 원시값과 그 선언은 어떻게 하는가?

한 번 함께 알아보는 시간이 있으면 좋을 것 같아요.

2021-12-26 20:14 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: [Coffee.RawValue] = []
어떤 의미로 `Coffe.RawValue` 타입을 사용하셨나요? 해당 타입을 선택하고 Opt + 클릭 해서 Quick Help를 읽어봅시다.

2021-12-26 20:14 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
>          print("\(customer.name) 님의 \(self.pickUpTable)가 준비되었습니다. 픽업대에서 가져가주세요.")
이 부분을 출력하면, 배열에 감싸져서 나오지 않나요?

2021-12-26 20:14 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: [Coffee.RawValue]? = []
이 부분이 옵셔널일 필요가 있을까요?

2021-12-27 15:12 UTC, Quokkaaa commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: [Coffee.RawValue]? = []
사실 옵셔널을 적용한 이유는 빈픽업테이블도 상상하여 적용했었는데요 ...ㅎㅎ
굳이 사용할필요는 없는것같기도 하네요!

2021-12-27 15:13 UTC, Quokkaaa commented on CodeStarterCamp_Week3/main.swift
>          print("\(customer.name) 님의 \(self.pickUpTable)가 준비되었습니다. 픽업대에서 가져가주세요.")
피드백 주신 first를 이용하여 출력 해보았습니다. 😄

2021-12-27 15:13 UTC, Quokkaaa commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: [Coffee.RawValue] = []
같은 타입이었는데 ....^^ 더 꼼꼼하게 보도록 노력해야겠어요!! 😅

2021-12-27 15:44 UTC, Journey36 reviewed
@Quokkaaa 
쿼카님! 코멘트 달았던 부분은 아마 Xcode의 순서상 오류가 있어서 그럴겁니다. 다시 한 번 확인하시고, 개선부탁드립니다! 변경사항이 확인되면 머지하겠습니다.

2021-12-27 15:44 UTC, Journey36 commented on CodeStarterCamp_Week3/main.swift
> +        self.pickUpTable.append(Coffee(rawValue: coffee.rawValue)!)
그냥 `self.pickUpTable.append(coffee)` 도 가능할텐데요?!

2021-12-28 06:15 UTC, Quokkaaa commented on CodeStarterCamp_Week3/main.swift
> +        self.pickUpTable.append(Coffee(rawValue: coffee.rawValue)!)
가능하네요ㅎㅎ
값을 추출하려면 `rawValue`가 사용될 수 있는 값이기도하고 담아야할 배열의 타입이 `Coffee`타입이다보니 `Coffee`타입으로 담아서 전달해야할 것같다는 생각을 했었습니다.

2021-12-28 11:04 UTC, merged