Week3 [STEP 1] inho
yagom-academy/swift-starter-week3 pull request #72
Opened 2022-04-26 06:01 UTC by inho-98

안녕하세요, @ye-ha
## STEP 1 과제 PR입니다! 
이번 과제에서 다루는 것들이 낯선게 많은 만큼 신경쓸게 많았습니다.
## 고민했던 것
#### 타입 정의 방식
- 우선 타입으로 구조체와 열거형을 사용했는데, 공식문서를 참고하여 클래스 대신 구조체를 사용했습니다. 문서에서 구조체는 추가 기능이 있는 만큼 복잡성이 높아져서 일반적인 상황에는 구조체 사용을 권장하고 있었습니다.
#### Person 타입
- name 프로퍼티는 한번 선언하면 바뀌지 않아서 상수, money 프로퍼티는 커피를 구매할때 바뀔 수 있어서 변수로 선언했습니다.
- `buyCoffee` 메소드 에서는 현재 가지고 있는 돈을 출력합니다.
#### CoffeeShop 타입
- 매출은 판매량에 따라 변하므로 변수, 메뉴판은 고정되어 있으므로(물론 메뉴가 추가될 수도 있지만..!) 상수로 선언했습니다.
- menuList 프로퍼티에서는 열거형으로 선언한 Coffee 타입을 딕셔너리의 키값으로 가집니다.
- 과제 설명에서 
  >pickUpTable 을 가질 수 있도록 해봅시다. (커피는 픽업테이블에 있을 수도 있고, 없을 수도 있습니다.)

   라고 되어있어서 Bool과 Bool? 중 고민했는데, 커피가 준비되지 않아도 픽업테이블이 없는 건 아니므로 그냥 Bool 타입에 초기값을 false 로 선언했습니다.
- barista 프로퍼티는 초기값이 필요하지 않은 것 같아 Person? 타입으로 선언했습니다.
- barista 프로퍼티가 옵셔널 타입이어서 `getOrder`과 `makeCoffee` 함수에서는 옵셔널 바인딩을 이용했고, 바리스타의 name 프로퍼티를 출력하도록 우선 구현했습니다.
#### 인스턴스 생성
- Person 과 CoffeeShop 의 인스턴스 모두 커피를 구매, 판매하는 과정에서 프로퍼티값이 변경될 수 있어서 변수로 선언했습니다.
---
### 조언을 얻고싶은 부분
- pickUpTable에 대한 설명을 제대로 이해하고 구현한 것인지 궁금합니다..!
- barista 프로퍼티 선언에 대한 다른 아이디어가 있을지 궁금합니다!
---
구조체, 클래스, 초기화, 프로퍼티 등 이번 수업관련된 공식문서를 천천히 보고있긴한데 더 많은 시간을 들여야 할것같아요.. 😂 이해가 다 되지 않더라도 읽어나가는게 당연히 도움이 되겠죠..? 😵‍💫

2022-04-27 01:10 UTC, ye-ha requested changes
고민했던 부분 적어주셔서 어떤 과정으로 코드를 짜셨는지 이해하기 수월했습니다. 
이유를 가지고 선택하는 과정, 아주 좋습니다. 😄👍

> pickUpTable에 대한 설명을 제대로 이해하고 구현한 것인지 궁금합니다..!

현재 코드에서 pickUpTable이 사용되고 있지 않아요. 언제 pickUpTable을 이용할 수 있을지 생각해보고 수정해봅시다! 

> barista 프로퍼티 선언에 대한 다른 아이디어가 있을지 궁금합니다!

지금도 좋습니다. 😄
 
> Coffee 타입을 CoffeeShop 타입 내부에 중첩시켜서 선언하는 것도 괜찮아보였는데 예하의 의견은 어떤지 궁금합니다!

좋은 생각이에요! CoffeeShop 에서 Coffee 를 이용하니까 내부에 가지고 있는 것도 좋죠.

> 구조체, 클래스, 초기화, 프로퍼티 등 이번 수업관련된 공식문서를 천천히 보고있긴한데 더 많은 시간을 들여야 할것같아요.. 😂 이해가 다 되지 않더라도 읽어나가는게 당연히 도움이 되겠죠..? 😵‍💫

그럼요. 천천히 읽어나가면 도움이 됩니다. 다만, 여러 부분을 한 번에 모두 이해하려고 하면 전부 이해가 안될 수 있어요. 숲부터 파악하시고 나무들로 접근하는 방법도 파악하는데 도움이 될 수 있어요.

2022-04-27 01:10 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(barista: misterLee)
프로퍼티 값이 변경될 수 있어서 변수로 선언해주셨다고 하는데, 해당되는 상황일 때 해주는 것이 좋습니다. 😄

2022-04-27 01:10 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +        }
안전하게 옵셔널 처리해주신 부분 좋습니다.👏👏👏 

getOrder에서 바리스타가 있는지 체크했는데, makeCoffee에서 다시 체크해야 할까요? 🤔

2022-04-27 08:13 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +
생성하는 타입이 Person 과 CoffeeShop이 달라서 무의식적으로 한줄을 띄운것 같습니다..! 붙이는 걸로 수정했습니다 :)

2022-04-27 08:14 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +    func getOrder() {
문서 다시 확인해보고 고민했는데, `getOrder` 을 `recieveOrder`로 변경할까 하다가 `name functions according to their side-effects` 관련해서, 메소드가 문서에서말하는 side-effect 를 일으키진 않은것 같아서 명사형인 `order`로 수정했는데 어떤가요? 🤔

2022-04-27 08:14 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Bool = false
그냥 선언만 하면 되겠다 싶었는데, 사용되지 않으면 선언할 이유가 없구나 싶기도 하네요..! `giveCoffee` 라는 함수를 만들어서 pickUpTable 값에 보고 출력하도록 함수를 추가했습니다!

2022-04-27 08:14 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(barista: misterLee)
Person의 인스턴스들은 let으로 변경했습니다!

2022-04-27 08:14 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +        }
말씀해주신 대로 불필요한것 같아서, getOrder 함수에서만 체크하도록 수정했습니다!

2022-04-27 08:22 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Bool = false
수정하고나서 보니까 menuList 에있는 값들도 아직 사용을 안했더라고요..! 다음 스텝에서 구현할것 같긴한데, 지금은 그냥 둬도 상관없을까요? 🤔

2022-04-27 08:23 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +
추가로 수정한 코드에서 
```
var yagombucks = CoffeeShop(barista: misterLee)
yagombucks.pickUpTable = true
```
인스턴스 생성하는 코드와 프로퍼티 변경하는 코드를 붙어있게 작성했는데, 저런 경우는 보통 어떻게 하나요?

2022-04-28 08:00 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +    }
열거형이 프로퍼티들 사이에 있네요. 일단 배치할 때 통일성이 있는게 좋습니다. 저는 열거형을 최상단에 배치하는 편입니다!

2022-04-28 08:02 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Bool = false
pickUpTable 값에 따라 커피를 받을 수 있도록 하는 수정, 좋습니다! 😄
메뉴리스트 값은 아직 사용하지 않아도 괜찮습니다!

2022-04-28 08:05 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +
이 경우는 정답이 없어서 인호님만의 스타일을 찾는 것이 좋습니다!
저는 함수 호출과 값을 할당해주는 부분을 개행하기도 했었는데, 지금은 코드 길이에 따라 붙이기도 합니다!

2022-04-28 08:05 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +    func getOrder() {
말씀해주신 네이밍 중 order가 가장 좋다고 생각됩니다!

2022-04-28 08:10 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +    }
안그래도 수정하면서 의식하긴 했는데, 역시 통일성있게 하는게 좋군요! 수정하겠습니다ㅎㅎ

2022-04-28 08:16 UTC, merged