Mission3: Step1: 타입과 인스턴스의 관계
yagom-academy/swift-starter-week3 pull request #74
Opened 2022-04-26 13:43 UTC by wolframhwang

@llghdud921 
안녕하세요 제리

일이 바빠서 오늘 밤에서야 PR을 드리네요 ㅎㅎ

Mission3의 Step1 관련 내용을 PR로 올려요.

- Person 타입을 정의하고, 공통적으로 가지는 특성을 **프로퍼티**, 그리고 공통 동작을 **메서드** 로 작성하는 것이 목표였어요
    - 저는 사람이 공통적으로 가지고 있는 것이 돈도 있겠지만 이름도 있다고 생각을 했어요 그래서 name / money 두 가지를 Person Class의 저장 프로퍼티로 정했어요
        - 이름은 기본적으로 쉽게 바뀌면 안되기 때문에 접근 제한자로 private를 사용했어요
        - 돈도 마찬가지로 중요한거고, 사용자의 행동에 의해서만 바뀌는 것으로 생각해서 역시 private로 접근 제한자를 설정했어요
    - Person은 이번 미션에서 Coffee를 주문하는 "**동작**"을 해요. 그래서 그 부분을 orderCoffee 메서드로 표현했어요.
        - 주문 자체는 어떤걸 "주세요" 라는 것이지, 돈을 내는 것이 포함 되어 있지 않아서, 이 부분에 대한 액션을 공통 메서드로 표현했어요!

- CoffeeShop 타입을 정의하고 저장 프로퍼티들의 타입을 부가적으로 생성했어요.
    - 미션 세계에서는 CoffeeShop은 바리스타를 가지고있고, 메뉴판과 pickUpTable 그리고 돈을 가지고있어요. 그래서 이 부분을 저장 프로퍼티로 지정해두었습니다.
        - PickUpTable과 CoffeeMenu는 각자 능동적인 역할을 할 필요가 있어서 객체로 생성했습니다!
        - 다만 Barista가 조금 모호한데요, 바리스타는 Person이 맞지만, Person과는 다른 역할을 하는 면이 분명히 존재하네요.
        - 그래서 이 부분은 추후에 Person을 상속받거나, Person을 Protocol 로 사용하는 Object로 만드는게 좋을지? 생각해봐야 할것같은데, 제리의 의견이 궁금해요
    - CoffeeShop은 Person으로부터 주문을 받고, 주문을 받으면 공통적으로 돈을 받을텐데, 이것을 저장해두기도 해야하고, 주문이 완료가 되면 PickUpTable에다가 커피를 놓기도 해야할테고, 바리스타 역시 고용을 해야할거에요.
    - 그래서 이러한 행동의 **책임**을 메서드로 구현해 두었습니다.
    
전체적으로 코드 구현한 부분에 대해서 다 적어봤는데요,
아무래도 네이밍이 조금 많이많이많이 고쳐야 할 것 같은데.. 이 부분은 제가 당장 떠오르는게 많지가 않아서... 따끔하게 혼내주시면 감사하겠습니다

코드리뷰 항상 감사합니다!

2022-04-27 15:37 UTC, llghdud921 requested changes
안녕하세요! 제리에요 :)
이번 Week3도 역시.... 잘하시네요... 
원래도 실력자이신것 같은데 해당 코드 스타터 캠프로 기본기를 탄탄하게 만들어드리고 싶네요!!ㅎㅎ 잘 부탁드립니당~

> 다만 Barista가 조금 모호한데요, 바리스타는 Person이 맞지만, Person과는 다른 역할을 하는 면이 분명히 존재하네요.
그래서 이 부분은 추후에 Person을 상속받거나, Person을 Protocol 로 사용하는 Object로 만드는게 좋을지? 생각해봐야 할것같은데, 제리의 의견이 궁금해요

오 맞아요! 저라면 Person class를 상속받거나 프로토콜로 만들어 채택한 Barista, Customer 타입을 만들 것 같아요!
진짜 실력자시네요..ㅎㅎ 
추가적으로 상속과 프로토콜의 차이를 알아보면 더 좋을 것 같아요! ( 필수는 아닙니다ㅎㅎ )

>아무래도 네이밍이 조금 많이많이많이 고쳐야 할 것 같은데..
오... 아녀 너무 잘하셨는데요? 지금 리뷰할거없어서 매우 당황 중입니다.... 🥲
다만 아직 기능이 구현되지 않은 메서드들이 많이 보이는데... 함수가 코드가 구현되어있지 않은 상태에서는 함수의 기능을 정확히 알지 못하여 네이밍을 판단하기는 어려울 것 같습니다ㅠ 
다음 스텝에서 차근차근 짚어드릴게요 :)

2022-04-27 15:37 UTC, llghdud921 commented on CodeStarterCamp_Week3/CoffeeMenu.swift
> +class CoffeeMenu {
타입을 class로 작성하신 이유가 있을까요?

2022-04-27 15:37 UTC, llghdud921 commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +class CoffeeShop {
이것도 class로 작성해주셨는데요!
왜 class로 작성하셨는지, class와 struct를 어떤 기준을 가지고 타입을 정의하시는지 궁금합니다!

2022-04-28 09:59 UTC, wolframhwang commented on CodeStarterCamp_Week3/CoffeeMenu.swift
> +class CoffeeMenu {
찾아보니 애플에서 구조체 사용을 권장하는 4가지 케이스가 있더라구요.
1. 연관된 간단한 값의 집합을 캡슐화하는 것만이 목적일 때
2. 캡슐화한 값을 참조하는 것보다 복사하는 것이 합당할 때
3. 구조체에 저장된 프로퍼티가 값 타입이며 참조하는 것보다 복사하는 것이 합당할 때
4. 다른 타입으로부터 상속받거나 자신을 상속할 필요가 없을 때

인데, 
하나하나 보자면
1. 연관된 값의 집합을 캡슐화 하는 것 뿐 아니라, 각자 객체로서 멤버변수를 활용해서 특정 액션을 해야할 책임이 있기 때문에 해당하지 않는다고 생각했어요.
2. 우리 "미션만" 생각한다면 2번에 해당할순 있지만, 공통적인 메뉴판이 필요할수 있다고 생각해서 해당하지 않는다고 생각했습니다.
3. 구조체에 저장된 프로퍼티가 value인 Dictionary타입이지만, 2번과 같이 용도를 고려하면 굳이 해당되지 않는다고 생각했습니다.
4. CoffeeMenu는 메뉴라는 클래스를 상속받는 것이라고 생각해서.. 애초에 해당하지 않는다고 생각했어요.

2022-04-28 10:00 UTC, wolframhwang commented on CodeStarterCamp_Week3/CoffeeMenu.swift
> +    private var coffeeListsInShop: [Coffee: Int] = [:]
객체지향에서 프로퍼티에 함부로 접근하게 하면안되니까요 ㅎㅎ;

2022-04-28 10:01 UTC, wolframhwang commented on CodeStarterCamp_Week3/CoffeeMenu.swift
> +            return -1
이 부분은 제가 빌드에러 없앨려고 넣은 코드라 추후에 Enum으로 에러코드 처리하는 방식으로 할생각이에요

2022-04-28 10:01 UTC, wolframhwang commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +enum Coffee {
이 부분이 조금 고민됐던건데 감사합니다

2022-04-28 10:02 UTC, wolframhwang commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +class CoffeeShop {
위의 CoffeeMenu와 똑같은 이유입니다.
구조체를 사용함으로서 얻을 이득이 없다고 판단했어요!

2022-04-28 10:02 UTC, wolframhwang commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    var todaysSalesMoney: Int
감사합니다!

2022-04-28 10:02 UTC, wolframhwang commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +        todaysSalesMoney = 0
초기화는..필수!

2022-04-28 10:08 UTC, wolframhwang commented
@llghdud921 

안녕하세요 제리

말씀해주셨던 것 중 고친게 두가지에요

1. Coffee의 분리
2. salseMoney의 리네이밍

나머지 질문들은 답글을 달았습니다!
확인 부탁드릴게요

2022-04-29 12:12 UTC, wolframhwang commented
@llghdud921 
안녕하세요 제리
밤늦게 PR Step2까지 제가 생각한 대로 작성한 패치를 전부 올렸습니다.

리뷰 부탁드릴께요!

2022-05-01 13:43 UTC, wolframhwang commented
@llghdud921 제리
오늘 디스코드에서 대화 나눴던 것들에 대해 반영했습니다.

1. PickUpTable / CoffeeMenu를 Struct로 구조를 변환했습니다.
2. 그리고, 불필요한 에러타입을 사용하지 않기 위해서 return 값을 Optional 을 사용해서 처리할수 있도록 구조를 변환했습니다.
3. 마지막으로, Person을 Protocol을 사용해서 하려고 했는데, 돈에 대한 변화와 초기화 부분 수정하는데에 비용이 많이 들것 같아서, Person을 부모로 상속받는 형태로 변경했습니다.

리뷰 한번 더 해주시면 감사하겠습니다!

2022-05-01 16:03 UTC, llghdud921 requested changes
안녕하세요~!
아침에 활동하시는 분에게 맨날 밤늦게 PR 답장을 드려 죄송합니다ㅎㅎ (알람을 꺼주세요..ㅎㅎ)
그리고 아까 말씀드린 부분 코멘트를 남기려고했는데 이미 변경하셔서 따로 안남겨 두었습니다~! ㅎㅎ

워낙 잘하셔서 코멘트 드릴것이 별로 없었지만.. 조금 남겨두었으니 확인부탁드릴게요 👍

2022-05-01 16:03 UTC, llghdud921 commented on CodeStarterCamp_Week3/PickUpTable.swift
> +        guard let orderManName = pickUpTable[coffee]?.removeFirst() else {
`pickTable[coffee]`에 값이 비어있는 상태로 `removeFirst`가 실행되면 어떻게 될까요?

2022-05-01 22:49 UTC, wolframhwang commented on CodeStarterCamp_Week3/Customoer.swift
> +        coffeeShop.insertOrderToPickUpTable(orderMan: name, coffee: coffee)
@llghdud921 
저도 동의합니다.
다만, order 자체는 name을 받아줄수 없어서 이렇게 했어요 이부분 확인 부탁드릴게요

2022-05-01 22:55 UTC, wolframhwang commented on CodeStarterCamp_Week3/PickUpTable.swift
> +        guard let orderManName = pickUpTable[coffee]?.removeFirst() else {
Fatal error: Can't remove first element from an empty collection

이렇게 나옵니다.

질문 주신 의도가 비어있는 상태를 확인할수 있게 추가하라는것 같은데요 맞을까요

2022-05-01 22:57 UTC, wolframhwang commented on CodeStarterCamp_Week3/PickUpTable.swift
> +        guard let orderManName = pickUpTable[coffee]?.removeFirst() else {
그런데.. 이 코드는 비어있는 상태에서 저 옵셔널 바인딩을 실행하지않아서요
CheckTable을 통해 빈 배열인지 확인을 먼저하고 pickUpTable에서 확인하는 부분인데
이 부분 고쳐야하나요?

2022-05-01 23:38 UTC, wolframhwang commented
@llghdud921 
리뷰해주신 부분 반영했습니다.
1. customer 리네이밍
2. pickuptable메소드 리네이밍

2022-05-02 00:19 UTC, merged

2022-05-02 00:20 UTC, llghdud921 commented
개선하신 부분 확인 완료했고 머지했습니다!
이번주도 화이팅해보아요! 😄