Week3 [STEP1] jeongmin(정민)
yagom-academy/swift-starter-week3 pull request #77
Opened 2022-04-26 20:32 UTC by jeongmin-l

@jaemuYeo 

안녕하세요 잼킹! 😁
3주차 STEP1 PR요청 드립니다!
이번 주도 열심히 배우겠습니다!! 💪

이번 스텝에서 enum의 case들을 메뉴판에 추가하는 방법에 대해 고민을 많이 했습니다..
그러다 보니 커밋의 상태가 좀 복잡해진 것 같습니다 😭

2022-04-27 11:14 UTC, jaemuYeo requested changes
week3의 첫 번째 PR 수고많으셨습니다!! 👏
private(set)을 통한 은닉화가 아주 인상깊었습니다.
은닉화를 한것과 안한것에 대한 기준을 어떻게 했는지에 대한 정민님의 생각이 궁금하군요!
커밋의 상태는 걱정하지말아요~
커밋 메시지는 정민님이 작성한 발자취를 남겨놓는 메시지이니
어떤게 변화되었는지만 알아볼 수 있으면 됩니다!
혹여나 스텝2로 갔는데 추가했던게 다시 필요가 없어질 경우 
또 다른 커밋이 남겠죠??

코드에 대한 부분은 코멘트 남겨놓았고,
CoffeeShop 타입의 메서드 중에 `커피를 만들어낼 수 있는` 동작은 없더군요!
추가해볼 수 있을까요?? 
마지막으로 CoffeeShop 파일에 오타가 있습니다~

2022-04-27 11:14 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +    func buyCoffee(type coffee: Coffee) {
type이라는 네이밍이 다소 어색해보여요🤔
커피만을 구매하는 buyCoffee보다 buy를 통해 매개변수로 어떤 것을 구매하는지 작성해보는건 어떨까요?

2022-04-27 11:14 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +struct CoffeeShop {
CoffeeShop 타입을 정의할때 클래스와 구조체 중 구조체를 사용하신 이유가 궁금합니다!

2022-04-27 11:14 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    var pickUpTable: Bool
이 곳에는 단순이 있는지 없는지가 아닌 어떤 커피가 있을수도 없을 수도 있지않을까요?

2022-04-27 11:14 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    var barista: Person?
barista 변수를 옵셔널 타입으로 하신 이유가 있으신가요?

2022-04-27 11:14 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    mutating func change(in coffee: Coffee, price: Int) {
chasge와 add 메서드에 대한 사용용도가 궁금하군요 😲
다음 스텝에서 기대해보겠습니다!

2022-04-27 11:14 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    mutating func add(menu: [Coffee: Int]){
띄어쓰기 확인해주세요!

2022-04-27 15:52 UTC, jeongmin-l commented on CodeStarterCamp_Week3/Person.swift
> +    init(name: String, height: Double, weight: Double, money: Int) {
역시 찜찜했던 부분들을 다 집어내 주시네요 😅
이 부분도 고민을 좀 했었는데
private(set) 변수와 기본 변수를 따로 분리해서 은닉화 된 변수는 상단에, 기본 변수는 하단에 두는 것이 좋을까 
아니면 초기화의 순서대로 변수를 적는 것이 좋을까 고민했습니다

초기화의 순서를 바꿀까 생각했었는데 이름,키,몸무게,소지한 돈 을 순서로 받는것이 
사람의 인스턴스를 생성할 때 좀 더 자연스럽다는 느낌을 받아서 순서는 바꾸지 않았습니다

그러다 보니 좀 생각이 섞여버린채로 굳어버린 것 같은데요 
private를 신경쓰지 않고 초기화의 순서대로 두는 것이 자연스러울까요?

2022-04-27 15:53 UTC, jeongmin-l commented on CodeStarterCamp_Week3/Person.swift
> +    func buyCoffee(type coffee: Coffee) {
아 그 방법이 더 깔끔해 보이는 것 같습니다! 😁 수정하겠습니다!!

2022-04-27 15:55 UTC, jeongmin-l commented on CodeStarterCamp_Week3/CoffeShop.swift
> +struct CoffeeShop {
위의 Person타입과 같은 이유로 다른 조건들을 제외 하고 나서
상속의 기능을 고려하지 않아 struct를 사용했습니다!

2022-04-27 15:59 UTC, jeongmin-l commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    var pickUpTable: Bool
제가 STEP1의 요구사항을 잘못 이해한 것 같습니다 😅
pickUpTable이 카페마다 존재하는지 존재하지 않는지를 생각했습니다 ㅎ...

Coffee의 옵셔널타입으로 변경하겠습니다!

2022-04-27 16:10 UTC, jeongmin-l commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    mutating func change(in coffee: Coffee, price: Int) {
change와 add는 CoffeeShop의 메뉴를 추가,변경하는 메서드 입니다!

처음에 열거형으로 커피를 나열했고 
```swift
enum Coffee: String {
    case americano, caffelatte, caffeMocha, caramelMacchiato
    
    var price: Int {
        switch self {
            case .americano, .caffelatte:
                return 2500
            case .caffeMocha, .caramelMacchiato:
                return 3000
        }
    }
}
```
이런식으로 switch로 각각의 가격을 받아와서 for문으로 dictionary에 넣을 생각 이었는데 이렇게 하려니 카페마다 메뉴와 가격이 다른데 고정이 된다는 생각이 들어서 change와 add 메서드를 만들게 되었습니다 

add를 통해서 dictionary를 받아 현재 갖고있는 메뉴와 머지했구 값이 중복될 경우 이전의 값을 새로 들어온 값으로 대체하게 했습니다.
change는 현재 가지고 있는 메뉴의 가격을 변경하기 위한 함수였습니다. Coffee타입의 값을 받아 그 메뉴가 존재한다면 받은 가격으로 값을 대체, 존재하지 않을 경우 문구를 프린트하고 종료 되는 함수 입니다.

이후 스텝에서는 사용하지 않을....지도...? 모르겠습니다 🧐
add함수는 메뉴추가 메서드니 둔다고 쳐도 change메서드는 없애는게 좋을까요?

2022-04-27 16:10 UTC, jeongmin-l commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    mutating func add(menu: [Coffee: Int]){
바로 수정하겠습니다!! 늘 이런게 하나씩 나오네요.. 🥲

2022-04-27 16:44 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +struct Person {
클래스 또한 protocol이 상속가능하답니다!!
protocol은 swift언어의 엄청난 무기예요 ㅎㅎ 조만간 배우실 겁니다 ☺️
또한 클래스는 참조타입, 구조체는 값타입이라는 것인데
그 부분에 대해서도 한 번 알아보셔요!
사실 이 부분은 정민님이 작성하신 것에 대한 이유가 단지 궁금했을 뿐입니다! 👍

2022-04-27 16:49 UTC, jaemuYeo commented on CodeStarterCamp_Week3/Person.swift
> +    init(name: String, height: Double, weight: Double, money: Int) {
이 부분에 대해서도 정민님의 컨벤션이 중요하다고 생각합니다!
사실 초기화할때 매개변수명도 프로퍼티와 다른 네이밍으로 하는 사례도 있고,
프로퍼티가 옵셔널이거나 기본값이 있을 경우에는 init에 포함하지 않기도 하니깐요!

2022-04-27 16:52 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    var barista: Person?
음,, 저는 개업을 했다면 어쨌건 손님을 받아야하니까 오너가 바리스타가 될수도 있을거란 생각을 했어요!
바리스타가 없는 카페는 카페가 아닐 수도 있지 않을까 생각했습니다 ㅎㅎ
정민님의 마음이 가는데로 두셔도 될것같아요!
단 나중에 옵셔널을 추출할 때 번거로울 수 있답니다 😀

2022-04-27 16:53 UTC, jaemuYeo commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    mutating func change(in coffee: Coffee, price: Int) {
좋은 시도입니다!! 다만 이번 스텝이 끝날 동안 사용할 일이 없는코드라면 지워야 겠지만 아쉬우니 다른 브랜치로 옮겨 놓으시고,
수정하셔도 좋을 것 같아요!

2022-04-27 16:56 UTC, jeongmin-l commented
은닉화를 하는 기준은 제가 생각하기에 함부로 바뀌어서는 안되는 정보인가 아닌가 였습니다!
Person타입의 이름과 돈은 막 바뀌면 속상할 것 같았고
CoffeeShop타입의 가게주인, 위치, 매출액, 메뉴와 같은 정보도 함부로 바뀌어서는 안된다고 생각했습니다

2022-04-27 16:56 UTC, jeongmin-l commented on CodeStarterCamp_Week3/Coffee.swift
> +enum Coffee: String {
감사합니다! 😁

2022-04-27 16:58 UTC, jeongmin-l commented on CodeStarterCamp_Week3/Person.swift
> +    private(set) var name: String
은닉화에 대해 말씀해주셔서 한번 알아보았습니다 😁

2022-04-29 01:04 UTC, jaemuYeo requested changes
Request changes

2022-04-29 01:35 UTC, jeongmin-l commented on CodeStarterCamp_Week3/CoffeShop.swift
> +    mutating func change(in coffee: Coffee, price: Int) {
사용할 일이 없을 것 같아 change메서드를 삭제했습니다!

2022-04-29 11:17 UTC, merged