Week3 [Step1] Onestar
yagom-academy/swift-starter-week3 pull request #78
Opened 2022-04-27 07:56 UTC by oneStar92

@oksunwoo 

# Step 3: 로또 당첨 번호를 회차별로 저장하고, 확인하자!

## Todo
- [x] Person 타입을 정의합니다.
* name, age, gender, hight, weight, money를 프로퍼티로 정의.
* 인사말, 자기소개, 한살증가, 돈계산 메서드 정의.
* 이니셜라이저는 name, age, gender, hight, weight값을 통해서 Person 생성. 하지만, 조건에 맞지 않는 값이 전달되면 nil반환. 
- [x] CoffeShop 타입을 정의합니다.
* cafeName, adress, sales, menu, pickUpTable, barista를 프로퍼티로 정의.
* 환영인사, 카페소개, 메뉴소개, 주문받기, 커피만들기, 커피upser하기 메서드 정의.
* 이니셜라이저
- [x] Coffe타입을 정의합니다.
* 이니셜라이저는 cafeName, adress값을 통해서 CoffeShop 생성. 하지만, 조건에 맞지 않는 값이 전달되면 nil반환. 
- [x] Person타입의 인스턴스로 misterLee, missKim을 생성해봅시다.
- [x] CoffeShop타입의 인스턴스로 yagombucks를 생성해봅시다.
- [x] yagombucks의 바리스타를 misterLee로 할당해봅시다.

# 궁금한점
1. 과거 학교에서 객체지향을 배울때 프로퍼티를 직접 값을 할당하고 얻는 방식은 좋지 않다고 배웠습니다. 즉, 프로퍼티를 private로 지정한 후 get, set메서드를 구현하여 해당 값을 추출하고 할당하는 방식이 올바르다고 배웠습니다. 이렇게 모든 프로퍼티를 메서드를 통해서 값을 추출하고 할당하는 형태로 구현해야 되는 건지 그렇게 하지 않아도 되는지 토니의 의견이 궁금합니다.
2. 주문받기, 커피만들기 함수에대해 질문이 있습니다. 코드 작성시 주문을 받게 되면 그 함수 내에서 커피만들기를 호출하는 것이 좋은 코드작성 인지 아니면 주문을 받고 해당 함수의 반환 값에 따라서 호출하는 것이 좋은 코드작성인지 궁금합니다.

2022-04-27 17:37 UTC, oksunwoo requested changes
우선 굉장히 어려운 내용일텐데도 불구하고 완성하고 PR까지 제출하신점 정말 칭찬드리고싶네요!👍

그리고 제가 원스타 코드를 3주간 리뷰하면서 느낀점인데, 오탈자가 많으신 편에 속합니다. 영어로 바꾸기 전에 한번 더 검색해보거나, 코드를 꼼꼼히 작성하는 습관을 가진다면 더 좋을 것 같아요! 오타는 아무래도 가독성과 직결되는 부분이니까요!
 또한, 가끔 요구사항에서 제시하는 것들을 빼놓으시는 경우가 있는데, 1,2주차는 적응기이고 문서를 코드로 담아내는 습관이 아직 익숙하지 않을 것이라고 생각되어 지적하지 않았습니다.  좋은 개발자의 자질 중 하나는 문서를 읽어내는 능력입니다. 현재는 요구사항이 많지 않아 누락된 부분을 금방 찾을 수 있지만, 요구사항이 길어지는 경우에는 누락된 부분을 찾기도 굉장히 어려울 것입니다. 지금부터라도 요구사항의 문서를 꼼꼼히 살펴보고 확인해나가는 습관을 길러보는 것은 어떨까요?

---
### 질문에 대한 대답
1. 굉장히 좋은 질문입니다! 아무래도 클래스 또는 구조체내에 프로퍼티에 직접 접근하는 것보다는 메서드를 통해 할당 및 구현하는 방식이 낫겠죠! 그런데 현재 단계에서는 아직 접근제어자를 배우지 않은 것으로 알고 있는데요! 나중에 학습하고 나서 리팩토링과정을 거쳐도 좋을 것 같아요! 원스타의 열정 정말 굉장합니다! 배우지 않은 부분을 스스로 생각해보고 고민하는 과정이 참 쉽지 않을텐데 말이죠! 그러면 아직 리팩토링을 하지 않으니, 원스타가 말씀해주신 방법과 직접 할당하고 추출하는 방법의 차이가 무엇인지, 왜 그렇게 사용을 추천하지 않는지 구글링을 통해 설명 부탁드립니다^^!

2. 주문 받기와 커피 만들기는 하는 동작부터 다른 것 같지않나요? 주문을 하고나서, 손님이 아 잠깐만요. 이걸로 바꿀수있나요? 라고 질문을 할때의 상황을 생각해보면 답은 간단할 것 같습니다. 만약 메서드가 한개라면, 주문을 하는 즉시 커피가 만들어지겠죠? 손님의 만족도는 떨어질수 있겠네요ㅎㅎ 또한, 대형 카페의 경우에는 주문 받는 사람과 커피 만드는 사람이 각각 있기도 하니까 저라면 원스타처럼 따로따로 만들 것 같습니다! 역할 분리에 대한 개념이 점점 잡히시는 것 같아요 👏 


---
추가적으로 다시한번 고생많으셨습니다. 이번스탭 까다로운 개념들이 있는 스탭인데 코드가 짜임새있고 눈에 읽기도 좋아서 정말정말 칭찬드리고 싶습니다!

2022-04-27 17:37 UTC, oksunwoo commented on CodeStarterCamp_Week3/main.swift
> +        }
_를 사용해주셨네요! 이것은 어떠한 경우에 사용하면 좋을까요?

바리스타가 있는지 없는지에 따라서 커피를 주문할 수 있을지 여부가 갈린 것 같아요!
에러와 같은 고민도 하신것 너무 좋습니다! 하지만, 옵셔널 바인딩이 무엇인지 다시 한번 생각해볼까요?

2022-04-27 17:37 UTC, oksunwoo commented on CodeStarterCamp_Week3/main.swift
> +            print("\(coffe)의 가격이 \(oldprice)에서 \(price)로 변경되었습니다.")
일반적으로 코드 한 라인에 .이 두번이상 들어가게 되면 가독성이 매우 떨어진다고 합니다.
어떻게 개선해보면 좋을까요?

그리고 상수명에서 대문자로 바뀌어야할 부분이 있는 것 같네요

2022-04-28 04:16 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +    var hight: Int
코드를 작성할때 꼼꼼히 확인해 보겠습니다... 오타가 많네요... 죄송합니다!

2022-04-28 04:34 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +}
enum을 사용한 이유는 성별을 값으로 받을때 남성, 여성 이렇게 두가지의 값만 받고싶어서 enum을 사용하였습니다.
enum과 struct의 차이점은 enum은 유사한 종류의 값들을 한 곳에 모아 정의한 것이고 struct는 프로퍼티와 메서드를 사용하여서 하나의 타입을 만들어 실체화 된 인스턴스를 생성하는 것 입니다.

2022-04-28 04:39 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +    }
mutating에 대해 잘못 이해하고 있었습니다. struct의 메서드에 mutating을 사용해야 되는줄 알았는데.
mutating은 값 타입인 sturct에서 값 타입의 프로퍼티를 수정하기 위해서 사용하는 키워드네요...
해당 내용을 바탕으로 코드 수정하겠습니다.

2022-04-28 04:39 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +    }
네! 알겠습니다.

2022-04-28 04:42 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +struct Person {
죄송합니다... CoffeeShop타입을 정의한 후 해당 메서드를 구현하려고 했는데 하지않았네요...
구현하겠습니다.

2022-04-28 04:43 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +}
코드에 있는 커피 오타는 전부 수정하였습니다.
레몬에이드 오타도 수정했습니다. 얼그레이는 저 철자가 맞지 않나요??

2022-04-28 04:43 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +    let cafeName: String
네이밍에 조금더 신경쓰도록 하겠습니다...

2022-04-28 04:43 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +    var adress: String
네 ㅠㅠ

2022-04-28 04:51 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +struct CoffeShop {
매출액은 sales로 네이밍하여서 프로퍼티로 지정해놨습니다.
해당부분 네이밍이 올바르지 않은 것 같아 수정하였습니다.

2022-04-28 04:53 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +            for (coffe, price) in self.menu {
self를 버릇처럼 사용하였습니다. 안좋은 습관인줄 모르고 사용하였습니다. 똑같은 이름의 파라미터를 전달받아서 사용할 때 구분을 짓기위해 사용하는 경우를 제외하고는 생략하겠습니다.

2022-04-28 04:53 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +    mutating func takeAnOrder(_ coffe: Coffe) {
넵 알겠습니다!!

2022-04-28 04:54 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +var yagombuks = CoffeShop(cafeName: "Yagom Bucks", adress: "서울시 강남구 강남대로 390")
수정하였습니다.

2022-04-28 04:55 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +            print("\(coffe)의 가격이 \(oldprice)에서 \(price)로 변경되었습니다.")
self를 생략해도 가능해보여서 생략하였습니다.
대문자로 바꾸었습니다.

2022-04-28 05:08 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +    }
이 메서드도 잠시 디자인만 해놓고 그냥 지나가 버렸네요.
저 당시 디자인 했을때 하나의 메서드에서 +, - 연산을 하도록 디자인 하기위해서 고민하던 과정에 잠깐 작성된 코드인데 그대로 PR을 했네요. 현재 sign을 통해서 +,-을 하는 것은 좋은방법이 아닌것 같아서 save와 spend로 나누어서 Money를 계산하도록 하였습니다.

2022-04-28 05:18 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +}
1. init은 initializer의 줄인말로 인스턴스의 생성 시 인스턴스가 꼭 가져야 할 초기값을 전달받는 역할을 합니다.
2. 아무래도 프로퍼티 선언 다음이 되겠네요... 수정하겠습니다.
3. init뒤의 물음표는 인스턴스 생성에 실패할 수 있다는 것을 뜻합니다.
4. init?은 초기값이 올바르지 않으면 해당 인스턴스가 제 역활을 하지 못할때 사용하는게 좋을 것 같습니다.
5. 현재 코드에서 초기값이 올바르지 않는경우, 코드에 작성한 경우은 Person 즉 사람일 수 없다고 판단하여 init?을 사용하여 실패할 수 있도록 하였습니다. 하지만 초기값이 해당 조건에 맞지 않아도 오류가 발생하진 않네요. 이런 경우엔 실패가능한 이니셜라이저 지양하는게 좋나요?

2022-04-28 05:23 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +    var barista: Person?
* pickUpTable의 경우 커피가 있을 수도 있고, 없을 수도 있다고 하여서 nil값을 가지도록 옵셔널로 선언하였습니다.
* barista의 경우 초기값이 필요 없고 나중에 바리스타를 지정되는 방식인 것 같아서 옵셔널을 사용하였습니다.

2022-04-28 05:25 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +        }
해당 부분이 없으면 카페명과 주소를 빈 문자열로 받게 된 경우. 이름이나 주소가 없는 카페가 생성됩니다.
하지만 코드의 동작은 오류를 발생하지 않습니다.

2022-04-28 05:30 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +                menuContents += "\(coffe.rawValue) : \(price)원\n"
Coffee Enum의 원시값인 string값을 받아 입력해주기위해 사용하였습니다.
사용하지 않아도 같은 결과가 입력되네요...
수정하겠습니다.

2022-04-28 05:52 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +    }
Update + Insert의 약어입니다.
Avoid abbreviations. 약어는 피하라고 되어있네요... 네이밍 수정하겠습니다.

2022-04-28 10:45 UTC, oneStar92 commented on CodeStarterCamp_Week3/main.swift
> +        }
옵셔널 바인딩은 옵셔널 값을 안전하게 추출하기 위해서 사용합니다. 코드를 잘못 작성하였네요... 수정하겠습니다.
_는 생략 혹은 사용하지않는 상수일때 사용합니다.

2022-04-28 12:04 UTC, oneStar92 commented
* PR하기전에 코드를 다시 확인하는 습관을 들이겠습니다. 죄송합니다 ㅠㅠ
***
* 질문사항
  * 실패가능한 이니셜라이저는 위와 같은 상황에는 쓸 필요가 없는건가요?? 제가 작성한 답변대로면 실패가능한 이니셜라이저는 사용하지 않아도 될거 같습니다. 근대 제 생각엔 사람이라는 객체를 실체화하는데 저러한 기본값의 제한 사항이 없다면 이게 올바른 실체화인지 궁금합니다.
  * pickUpTable과 barista의 경우 옵셔널을 사용에대해 질문이 있습니다. Step1의 요구사항인 pickUpTable은 커피가 있을수도 있고 없을수도 있다고 했습니다. 그래서 저는 pickUpTable을 옵셔널 Coffee 타입으로 정의하였고요. 토니의 리뷰본 후 다시 생각했을때도 결국 옵셔널로 사용하는 것 말고는 생각이 나지않아서 이렇게 질문드립니다. Barista의 경우 암시적 추출 옵셔널을 사용하는게 코드의 흐름상 맞다고 생각하는데 암시적 추출은 사용을 지양한다고 해서 옵셔널을 이용하게 되었는데. 이런경우 암시적 추출 옵셔널을 사용하는게 올바른 방법인가요?
***
* 질문에 대한 답변.
 직접 할당 및 변경하는 방식은 해당 프로그램 내에 있는 모든 함수들 가운데 변경되는 데이터와 관련된 함수들을 모두 추적해야 되는 어려움을 지니게 됩니다. 또한 올바르지 못한 방식으로 데이터나 함수를 변경 및 사용하게 되면 프로그래머의 의도와 다른 오류를 일으킬 수 있습니다. 하지만 접근제어자를 이용하여 정보은닉을 하게되면 외부 객체가 특정 객체의 데이터와 함수를 직접 접근하여 사용하거나 변경하지 못하므로 유지 보수와 소프트 웨어 확장시 오류를 최소화할 수 있습니다. 즉, 정보은닉을 하게되면 유지 보수에 용이하고 독립성과 확장성을 높여줍니다.

2022-05-01 11:16 UTC, oksunwoo requested changes
고생하셨습니다! 전반적으로 잘 짜임새가 있는 것 같군요!
그런데 원스타가 말씀해주신 init은 위치가 수정된 것 같지 않네요! 해당부분만 수정해주시면 머지하겠습니다!

---
### 질문사항
1. 실패가능한 이니셜라이저
- 이니셜라이저를 통해 인스턴스를 초기화할 수 없는 여러 가지 예외 상황이 있습니다. 대표적으로 이니셜라이저의 전달인자로 잘못된 값이나 적절치 못한 값이 전달되었을 때, 이니셜라이저는 인스턴스를 초기화에 실패할 수 있습니다. 그 외에도 여러 이유로 인스턴스 초기화에 실패할 수 있습니다. 원스타는 이 코드에서 값이 잘못들어올 수 있는 경우를 포함하여 다방면으로 생각하신 것 같습니다. 사실 저의 질문 의도는 그냥 원스타가 init? 을 기본 이니셜라이저라고 생각하고 계시나해서 여쭈어본거 였습니다!
 
2. pickUpTable
- pickUpTable은 저도 optional 사용이 맞다고 생각합니다. 코드의 작성 시 한줄한줄 모두 이유가 있어야만 하기에, 다른방법 사용의 추천이 아닌 바리스타와 픽업테이블만 옵셔널을 사용하신 이유를 묻고 싶었던 것 뿐입니다.
- 바리스타는 왜 암시적 추출을 사용하는것이 코드의 흐름에 맞다고 생각하신 이유가 혹시 무엇일까요?

2022-05-02 03:18 UTC, oneStar92 commented
* 답변
 바리스타 프로퍼티는 커피를 만드는 인스턴스에는 꼭 필요한 프로퍼티이지만 초기값을 할당하지 않아도 되는 프로퍼티라 생각해 암시적 추출이 더 맞다고 생각했습니다. 주말에 이렇게 저렇게 테스트를해봤습니다. 그 결과 옵셔널을 사용하여도 제가 머리속으로 생각했던 방식이랑 차이가 없었고 단지 암시적 추출을 사용하게 되면 아무 생각없이 프로퍼티를 사용하게 되면 런타임에 걸리는 등의 오류가 더 빈번히 발생하였습니다. 현재 저의 생각은 암시적 추출 사용을 지양하는게 맞는것 같습니다.

2022-05-02 04:53 UTC, merged