Week3 [Step 1] som
yagom-academy/swift-starter-week3 pull request #79
Opened 2022-04-27 10:19 UTC by jsa0224

@Jager-yoo 

좋은 저녁입니다! 저는 PR 보내고 저녁을 먹으러 가야겠어요! 
예거도 맛있는 저녁 드세요!!🤩

# 많이 고민한 부분🧐
처음에는 ```CoffeeShop```의 ```menu```를 따로 ```커피종류```, ```커피값```로 프로퍼티 정의를 했어요. 
그랬더니 석연치 않음을 느꼈습니다... 각각 ```커피종류```-```커피값```으로 나중에 사용되어야 할텐데, 이렇게 만들면 이상하겠더라고요.
```커피종류```는 만든 열거형에서 가져온다 쳐도... ```커피값```은 어디서 가져와야하지? 

그때 키와 값을 동시에 보관해주는 Dictionary가 생각났습니다. 
이미 만든 열거형을 key값으로 Dictionary을 생성했어요.
혼자 해보다가 한참을 해매서 [애플 개발자 포럼](https://developer.apple.com/forums/thread/12315)에서 도움을 얻었습니다.

# Class로 정의한 이유
아직 배우진 않았지만, Step2의 내용을 살짝쿵 보니... 제목부터가 '인스턴스는 서로 소통한다' ...
왠지 ```상속``` 기능을 사용해야될 거 같아서 Class로 타입을 정의했습니다. 

# main파일
인스턴스 생성을 main파일에 했는데, 맞는 방법인지는 모르겠어요.
플레이그라운드에서 코드를 구축하고, 과제 Xcode에 가져오는 방식으로 하고 있어서 소스파일을 만들고 하나씩 추가해보니...
딱히 main파일에는 코드를 넣을 게 없더라고요?? 그래도 main인데 비는 게 허전해보여서 인스턴스 생성 부분만 살짝쿵 넣어봤어요...()

# 여담😊
Person 타입에 어떤 프로퍼티를 넣을까, 고민하다가 요즘 MBTI가 유행이잖아요! 그래서 한 번 추가해봤습니다 ㅎㅎ
```misterLee```의 MBTI는 제 MBTI입니다 ㅎㅎ! 예거의 MBTI는 어떻게 되시나요~??

2022-04-27 15:23 UTC, Jager-yoo requested changes

2022-04-27 15:23 UTC, Jager-yoo commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    ]
조금 어려울 순 있지만..
이 부분은 멋지게 고쳐볼 수 있을 것 같아요.

지금 `Coffee 열거형`은 3가지 케이스를 넣어서, 아주 잘 만들어주셨는데요!
`coffeeMenu` 상수가 혼자 달랑~ 돌아다니는 게 좀 신경쓰여서요! 😅 

- 커피 열거형 내부에, `메뉴 딕셔너리 타입`을 반환해주는 `타입 연산 프로퍼티`를 만드는 거에요!
그러면 나중에 필요한 부분에서, `Coffee.menu` → 이렇게만 호출해줘도 딕셔너리가 빵~ 튀어나오게 되겠죠. 😄 

- 아 그리고, 열거형의 case 는 `소문자`로 변경해주셔야 합니다! ✔️ 

```swift
enum Coffee: String {
    case americano, caffeLatte, caramelMacchiato // 케이스 이름은 소문자로 바꾸기
    
    // 타입 - 연산 프로퍼티
    static var menu: [Coffee: Int] {
        return [.Americano: 4000, .CaffeLatte: 4500, .CaramelMacchiato: 5000]
    }
}

// 위와 같이, 만들어두면, 나중에 CoffeeShop 인스턴스 만들 때, 아래 처럼 쓸 수 있습니다.
let yagombucks = CoffeeShop(owner: "야곰", openingHours: "10:00 ~ 20:00", menu: Coffee.menu, barista: misterLee)
```

2022-04-27 15:23 UTC, Jager-yoo commented on CodeStarterCamp_Week3/Person.swift
> +    var getMoney: Int
- import 하고, 타입 선언부 사이에 `엔터 공백` 넣으면 좋겠습니다.
사실 메서드들이나, 이니셜라이저들 사이에서도 공백 있으면 좋아요. ㅎㅎ

- 클래스 → `구조체` 로 바꿔야할 필요성을 찾아보시고, 변경도 해보세요!

- `mbti` 프로퍼티 참 매력적으로 잘 만드셨어요~! 💘 
근데 MBTI → 이거는 `축약어` 잖아요?
스위프트에서 축약어는 소문자로 해야 할까요 대문자로 해야 할까요?
이 부분은 저도 [스타일쉐어 - 스위프트 스타일 가이드 - 약어](https://github.com/StyleShare/swift-style-guide#%EC%95%BD%EC%96%B4) 부분을 참고하면서 개발을 하고 있어요. 😄 
읽어보시고, 한 번 적용해보세요! (이해가 잘 안 된다면 질문해주셔도 돼요.)

- `getMoney` 라는 프로퍼티는 이름이 모호해요.
아마 사람이 갖고 있는 돈을 말씀하신 거겠죠? 근데 프로퍼티 이름이 아니라, 마치 메서드 이름 처럼.. 동사원형이 맨 앞에 와서 그렇게 느껴지나봐요. 😅 
한 번 다른 이름으로 변경해보시죠!! 🙏🏻

2022-04-27 15:23 UTC, Jager-yoo commented on CodeStarterCamp_Week3/Person.swift
> +    }
여기 이니셜라이저 굳이 2개 필요하지 않습니다!
제가 `CoffeeShop` 타입에서 이니셜라이저 1개로 줄인 방법 그대로
여기서는 솜이 직접 수정해보세요~~ 😄

2022-04-27 15:23 UTC, Jager-yoo commented on CodeStarterCamp_Week3/Person.swift
> +    }
이 메서드도, 확장성을 생각한다면
`어떤 커피`를 주문하는지 → 파라미터로 받으면 좋겠네요!

좀 더 어렵게 해본다면, 이 메서드 내부에서, 파라미터로 들어온 커피의 '가격'을 찾아낸 담에, 이 사람이 가진 돈 프로퍼티에서 마이너스 하는 식으로 동작하게 해도 재밌겠어요 ㅎㅎ

```swift
func buyCoffee(_ coffee: Coffee) {
    print("\(name)이 \(coffee)를 삽니다.")
    // 커피의 가격을 찾아서, 이 사람이 가진 돈 프로퍼티에서 차감함
    print("\(name)에게는 이제 \(getMoney)원이 남았어요.")
}
```

2022-04-28 07:14 UTC, jsa0224 commented on CodeStarterCamp_Week3/main.swift
> +let misterLee: Person = Person(name: "misterLee", age: 31, habit: "농구", mbti: "INFJ", getMoney: 20000)
인스턴스 선언에 대해서 더 찾아볼 걸 그랬어요. 저도 쓰면서 꼭 이렇게 해야하나? 조금 불편하다 라는 생각을 했었거든요. 이런 생각이 들 때마다 서치해봐야 더 발전할 수 있을텐데...🥺 다시 독학으로 돌아갈 때 조금 걱정이 되네요;) 좋은 팁 알려주셔서 감사합니다!

2022-04-28 07:19 UTC, jsa0224 commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +class CoffeeShop {
앗 플레이그라운드에서 바로 복붙한 코드라 그렇게 된 거 같아요. 수정했습니다!

2022-04-28 07:40 UTC, jsa0224 commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    var pickUpTable: Bool?
- sales가 매출이라는 뜻도 있지만 판매라는 뜻도 되서 애매한 거 같아요. 
그래서 이익이라는 profit이라는 단어로 변경했습니다:)

- 제가 컬렉션 타입의 선언문에 집착하고 있는 거 같아요 ㅎㅎ... 다양한 방법으로 선언할 수 있지만, 제 손에 익은 방법으로 하다보니 그렇게 된 것 같습니다. 확실히  ```[Coffee: Int]```으로 변경하니까 간결해졌네요👍

- ```pickUpTable```을 Bool타입으로 지정한 건 예거의 추리(?)가 맞습니다! 예거의 말씀대로 ```pickUpTable```을 ```Coffee?```로 하게 된다면 ```pickUpTable```은 앞으로 옵셔널 값을 가지게 되겠네요! 이렇게 바로 옵셔널을 활용해야하다니... ㅇ0ㅇ! 이해하고 넘어가길 잘한 것 같습니다😮

2022-04-28 07:57 UTC, jsa0224 commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    }
😵‍💫... 기본값이 있는 파라미터는 함수 호출 시 생략할 수 있다면, 타입에서도 마찬가지로 기본값이 있는 프로퍼티는 생략이 가능하다라는 뜻일까요? 두가지 이니셜라이저가 보이는 이유는 알겠어요! 클래스와 달리 구조체는 이니셜라이저를 하지 않아도 되니, 옵셔널을 정의하지 않은 두 프로퍼티가 뜨는 것이고, 전체는 init으로 이니셜라이저를 했기 때문에 프로퍼티가 다 뜨는 것 아닐까요?? 맞게 이해했는지 모르겠습니다...😵‍💫

2022-04-28 13:24 UTC, jsa0224 commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    }
아, 이미 Person에서 커피를 산다는 메서드가 있으니 중복이군요! 
파라미터 추가된 것도 확실히 어떤 커피를 주문했고, 그게 만들어지는 지 보이니까 좋은 것 같아요👍

2022-04-28 13:30 UTC, jsa0224 commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    ]
타입 프로퍼티, 연산 프로퍼티 각각 배웠는데 둘을 합쳐서 코드를 쓸 수도 있군요! 
코드의 활용은 무궁무진한 거 같아요😮!

앗!ㅎㅎ.. 대문자, 소문자 헷갈리기 시작했나봐요...ㅎㅎ 수정했습니다!

2022-04-28 14:07 UTC, jsa0224 commented on CodeStarterCamp_Week3/Person.swift
> +    }
넵 수정했습니다!

2022-04-29 09:05 UTC, jsa0224 commented
@Jager-yoo 

같이 스터디하시는 분들이 커밋은 코드 수정, 추가, 삭제할 때마다 하는 게 좋다고 하셔서 한 번 시도해봤는데 생각처럼 잘 되지는 않았어요😅
수정 완료하였습니다:)

2022-04-29 12:23 UTC, Jager-yoo commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    }
답변드립니다!

여기가 `구조체`라서 `멤버와이즈 이니셜라이저`를 활용할 수 있다는 점을 잊고 있었어요.. 
개발자가 구조체 내부에 이니셜라이저를 구현해두지 않더라도, 기본적으로 프로퍼티 각각에 대해(memeberwise), 컴파일러가 자동으로 이니셜라이저를 하나 만들어 주거든요.

> A memberwise initializer is an initializer that is automatically generated by the compiler for structs that don't define a custom initializer in their declaration.

이때, 프로퍼티를 `옵셔널`인 상태로 두거나, 기본값(default value)를 넣어놓으면, 그 프로퍼티에 대해서는 선택적으로 이니셜라이저를 만들 수 있어요.

즉, 아래와 같이 코드를 쓰면요

```swift
struct CoffeeShop {
    var owner: String
    var openingHours: String
    var coffeeShopSales: Int? // 옵셔널 프로퍼티
    var menu: [Coffee: Int] = [:] // (옵셔널 아님) 프로퍼티 기본값
    var pickUpTable: Coffee? // 옵셔널 프로퍼티
    var barista: Person? // 옵셔널 프로퍼티
    
    // 메서드들...
}
```

main.swift 에서는 이렇게 2개의 이니셜라이저가 등장합니다!

### ⭐ 결론적으로, `구조체`를 선택한다면, 이니셜라이저를 1개도 구현하지 않더라도, 2가지 버전의 이니셜라이저를 구현할 수 있네요.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/71127966/165943549-2b4be939-dca3-4980-a8bf-b2e15342c760.png">

2022-04-29 12:32 UTC, Jager-yoo commented on CodeStarterCamp_Week3/Person.swift
> +    var getMoney: Int
네 좋습니다! 잘 생각해주셨어요. 👏🏻 

- 제가 링크 드린 [Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)에 보면, 일단 `구조체`를 디폴트로 쓰고 클래스를 써야 하는 이유를 생각해보라는 내용이 있어요.
그니까, 굳이 클래스를 써야할 필요가 없으면 항상 구조체를 쓰면 되는 겁니다. 👍🏻 
솜도 앞으로 이 기준으로 구조체와 클래스를 따져 보시는 습관을 들여보시죠! ㅎㅎㅎ

![image](https://user-images.githubusercontent.com/71127966/165944350-afbd80bb-d80f-4b85-919e-52913f53bc5a.png)

- `축약어`도 잘 처리해주셨어요~!
만약 저였다면, 그냥 `MBTI` → 이렇게 통째로 대문자로 했을 듯 해요. ㅎㅎㅎ
왜냐면 이미 `Person` 이라는 구조체 내부의 프로퍼티이기 때문에, personal 이라는 형용사를 붙여주지 않더라도, 이미 사람의 특성(프로퍼티)인 걸 알 수 있기 때문이죠!

- `cash` 표현 좋네요! 😄

2022-05-02 04:03 UTC, Jager-yoo approved these changes

2022-05-02 04:04 UTC, Jager-yoo commented
다음 스텝과 묶어서 리팩토링 계속 진행하기로 했습니다!
머지합니다. 👍🏻

2022-05-02 04:04 UTC, merged