Week3 [Step1] duck
yagom-academy/swift-starter-week3 pull request #80
Opened 2022-04-27 12:36 UTC by Hong-seungju

@llghdud921  안녕하세요 제리
Week3의 step1 입니다.

2022-04-27 14:55 UTC, llghdud921 requested changes
안녕하세요~ 제리입니둥
벌써 Week3네요.. 지난 2주동안 정말 많이 성장하신 것 같아요 💯 
이번 코드보고 조금 놀랬답니당~ 👍 
그럼 Week3도 달려봅시다!!!!!!!!

### 조언 드릴 부분
- 제가 main.swift에 실행코드를 작성하라고 말씀드렸는데요! 한단계 더 나아가봅시다!
- 현재 프로젝트는 Command line Tool 프로젝트로 main.swift에 실행코드를 작성되면 커맨드에 코드실행이 출력되는 형태에요!
![스크린샷 2022-04-27 오후 11 51 10](https://user-images.githubusercontent.com/40068674/165546765-e3ca6663-092b-48b3-ab3d-c8101eca456c.png)
- 따라서 main.swift에는 실행코드만 작성을 해주시면 되구요!
- 주로 프로젝트를 구성할때 하나의 타입은 하나의 파일로 작성을 한답니다 (관리가 쉽도록)
- 그래서 Person.swift, CoffeeShop.swift 등등 파일을 만들고 그안에 해당 타입코드를 작성해주시면 타입별로 보기 편해 리팩토링하기 좋은 프로젝트가 될 것 같아요 :)

2022-04-27 14:55 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +struct Person {
해당 타입을 struct로 작성하신 이유가 무엇인가요?

2022-04-27 14:55 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +    var money: Int
상수, 변수 선언이 정말 잘 되어있어요 👍

2022-04-27 14:55 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +    init(name: String, age: Int, money: Int) {
struct에는 memberwse init이 존재하는 데 해당 init을 만들어주셨네요! 이유가 있을까요?

2022-04-27 14:55 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +    func personInformation() {
함수의 기능과 함수명이 일치하지 않는 것 같습니다ㅠ
함수가 어떤 기능을 하는지 생각해보면서 다시 네이밍해보아요~

2022-04-27 14:55 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Bool? = false
요구사항에 pickUpTable에 커피를 올려둘 수 있다고 하였는데요!
이를 토대로 pickUpTable의 타입을 다시한번 생각해봅시다!! 

옵셔널은 잘하셨어요 👍   커피가 있을수도 있고 없을수도 있는 픽업테이블이랍니당~

2022-04-27 14:55 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +    var coffeMenu: Dictionary<String, Int> = ["아메리카노": 4000, "에스프레소": 2500, "바닐라라떼": 4500, "복숭아스무디": 5000, "아인슈패너": 5000, "카페라떼": 4500, "딸기스무디": 5000, "시그니쳐초콜릿": 6000]
코드를 보면 "아메리카노"와 enum Coffee의 case와 매우 유사한데요!
Coffee를 활용해서 타입을 작성해볼 수 있을 것 같아요 :)

2022-04-27 14:55 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +enum Coffee:String {
```suggestion
enum Coffee: String {
```
`:` 뒤에는 한칸을 띄워주세요 :)

2022-04-27 14:55 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +    func buyCoffe() {
오타가 있네요!!

2022-04-27 14:55 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +    func makeCoffe() {
요기두 👀

2022-04-27 14:55 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +struct CoffeeShop {
이것도 struct로 작성해주셨네요! 왜 struct를 사용하신 걸까요? :)

2022-04-27 23:34 UTC, Hong-seungju commented on CodeStarterCamp_Week3/main.swift
> +struct Person {
상속을 사용하지 않으니 굳이 Class를 쓸 필요가 없다고 생각했습니다. 
Swift 가이드 라인에서 상속을 받을 필요가 없다면 구조체를 사용하는걸 권장한다고 해서 구조체를 사용하였습니다.

2022-04-27 23:34 UTC, Hong-seungju commented on CodeStarterCamp_Week3/main.swift
> +    var money: Int
감사합니다.😁

2022-04-27 23:35 UTC, Hong-seungju commented on CodeStarterCamp_Week3/main.swift
> +    func personInformation() {
넵 수정하겠습니다. PersonIntroduce 가 괜찮을 것 같습니다.

2022-04-27 23:36 UTC, Hong-seungju commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Bool? = false
넵^^

2022-04-27 23:37 UTC, Hong-seungju commented on CodeStarterCamp_Week3/main.swift
> +    var coffeMenu: Dictionary<String, Int> = ["아메리카노": 4000, "에스프레소": 2500, "바닐라라떼": 4500, "복숭아스무디": 5000, "아인슈패너": 5000, "카페라떼": 4500, "딸기스무디": 5000, "시그니쳐초콜릿": 6000]
넵 수정하겠습니다.

2022-04-27 23:37 UTC, Hong-seungju commented on CodeStarterCamp_Week3/main.swift
> +enum Coffee:String {
수정하겠습니다.

2022-04-27 23:37 UTC, Hong-seungju commented on CodeStarterCamp_Week3/main.swift
> +    func buyCoffe() {
수정하겠습니다.

2022-04-27 23:37 UTC, Hong-seungju commented on CodeStarterCamp_Week3/main.swift
> +    func makeCoffe() {
수정하겠습니다.

2022-04-27 23:37 UTC, Hong-seungju commented on CodeStarterCamp_Week3/main.swift
> +struct CoffeeShop {
위와 마찬가지로 상속을 사용하지 않으니 굳이 Class를 쓸 필요가 없다고 생각했습니다.
Swift 가이드 라인에서 상속을 받을 필요가 없다면 구조체를 사용하는걸 권장한다고 해서 구조체를 사용하였습니다.

2022-04-27 23:38 UTC, Hong-seungju commented on CodeStarterCamp_Week3/main.swift
> +    init(name: String, age: Int, money: Int) {
뭔가.. 확실하게 초기화를 해주고 싶어서 만들었습니다.

2022-04-28 02:04 UTC, llghdud921 commented on CodeStarterCamp_Week3/main.swift
> +    func personInformation() {
함수명이니 introduce()라고만 정해주어도 좋겠네요!

2022-04-28 11:11 UTC, Hong-seungju commented
@llghdud921 안녕하세요 제리~~
step1 수정본 입니다.

2022-04-29 02:36 UTC, llghdud921 requested changes
안녕하세요 duck
간단하게 코멘트 드렸고 수정해주시면 바로 머지처리 하겠습니다~! 고생하셧어요~~

2022-04-29 02:36 UTC, llghdud921 commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    var pickUpTable: Coffee?
```suggestion
   var pickUpTable: Coffee?
```
변수선언앞에 공백이 있네요~

2022-04-29 02:36 UTC, llghdud921 commented on CodeStarterCamp_Week3/enumCoffeeMenu.swift
> +var menu: [Coffee: Int] = [.아메리카노: 4000, .에스프레소: 2500, .바닐라라떼: 4500, .복숭아스무디: 5000, .아인슈패너: 5000, .카페라떼: 4500, .딸기스무디: 5000, .시그니쳐초콜릿: 6000]
`menu`는 `CoffeeShop`안에 있는것이 적절하다고 생각합니다

2022-04-29 03:24 UTC, Hong-seungju commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    var pickUpTable: Coffee?
수정하겠습니다.

2022-04-29 03:25 UTC, Hong-seungju commented on CodeStarterCamp_Week3/enumCoffeeMenu.swift
> +var menu: [Coffee: Int] = [.아메리카노: 4000, .에스프레소: 2500, .바닐라라떼: 4500, .복숭아스무디: 5000, .아인슈패너: 5000, .카페라떼: 4500, .딸기스무디: 5000, .시그니쳐초콜릿: 6000]
아! 제가 위의 코멘트에 대한 이해를 잘못하고 있었습니다. 수정하겠습니다.

2022-04-29 10:56 UTC, Hong-seungju commented
@llghdud921  안녕하세요 제리!
CoffeeShop 타입과 열거형 커피 타입 수정본 입니다.

2022-04-30 02:11 UTC, llghdud921 commented
넵! 머지하고 다음스텝으로 넘어갑시다~~

2022-04-30 02:11 UTC, merged