Week3 [STEP 2] inho
yagom-academy/swift-starter-week3 pull request #83
Opened 2022-04-29 07:47 UTC by inho-98

안녕하세요, @ye-ha 🙂 이번 PR도 잘부탁드립니다ㅎㅎ
# Step 2 PR
새로운 과제를 구현하기 위해 지난 코드에서 바뀐부분이 꽤 많습니다!
## 고민했던 것
**구조체에서 클래스 변경** 
- 지난 스텝에서는 모두 구조체를 이용했었는데, 이번에는 클래스로 전부 변경했습니다. 커피를 barista 가 추출해야 하므로 Barista 라는 타입을 새로 만들고 Person 타입을 상속한 뒤, 새로운 프로퍼티와 메소드를 추가하는 방식을 이용하기 위해 클래스를 사용했습니다.

**Person 클래스**
- 구조체에서 클래스로 변경되어서 `init()` 함수를 추가했습니다.
- `buyCoffee()`함수를 `buy(_ coffee, at coffeeShop)`함수로 변경하였습니다. 손님이 주문을 할 때, 메뉴 이름과 본인 이름을 말해야 하기 때문에(출력결과를 위해) 두 매개변수를 주고, 호출할 때 함수 이름과 argument label의 의미가 잘 전달되도록 했습니다.

**CoffeeShop 클래스**
- barista 변수에 옵셔널 Barista 타입, customer 변수에 옵셔널 Person 타입을 지정했습니다. ( 커피샵을 초기화할 때, 직원과 손님을 모를 수도 있어서)
- Person 클래스에서 Coffee 열거형에 접근하도록 하기 위해 CoffeeShop 안에서 꺼냈습니다.
- 기존의 order 함수에 Coffee 타입 매개변수를 추가하여 주문받은 메뉴를 알 수 있도록 했습니다.
- 주문을 받을 때는 옵셔널 바인딩을 통해 직원이 있는지, 손님이 있는지, 손님이 고른 메뉴의 가격이 메뉴판에 있는지 확인합니다.
- 주문을 받을때 손님의 잔액이 커피가격보다 높아야 하므로 두 값을 먼저 비교하고, 잔액이 더 높다면 메뉴를 주문할 수 있습니다.
- 주문이 들어가는 과정은 실제와 비슷하게, 결제를 하고(잔액에서 빠져나가는 과정) 커피를 만들고 완료되면 픽업하게 됩니다.
- 주문이 끝난 후에는 매출이 올라가고, 픽업테이블의 음료가 없어지므로 `pickUpTable = false` 코드가 실행됩니다.

## 해결되지 않은 점 🤔
- 12번 코드에서 name 을 상수로 선언하고 싶은데, 그렇게 하면 21번 코드 `coffeeShop.customer?.name = name` 에서 에러가 발생하는데, 에러를 구글링해도 이유를 못찾았습니다..
- CoffeeShop을 구조체로 하고, order 함수앞에 mutating 을 붙여서 코드를 작성했었는데, 그렇게 하면 22번코드에서 `Cannot use mutating member on immutable value: 'coffeeShop' is a 'let' constant` 에러가 뜹니다..! 에러 내용을 찾아봤을 때 구조체의 값타입 때문에 생긴거로 대충은 이해가 되고 클래스로 고치면 해결되는 건 알게됐는데, 작동원리는 정확하게 모르겟습니다 🥲

## 조언을 얻고 싶은 부분 🙋‍♂️
- 잔액을 출력하는 코드가 과제에는 `{커피가격}원만큼 부족합니다.` 라고 나와있었는데, 문맥상 부족한 금액을 나타내는게 나을것 같아서 결과를 조금 수정했습니다..!
- order 함수에서 옵셔널 바인딩 부분이 적절하게 쓰인건지..? 궁금합니다!
- 타입과 인스턴스를 활용해서 코드를 작성하는게 아직 많이 낯설어서,, 타입과 인스턴스 활용에 대한 더 나은 방법이나 아이디어가 있는지도 궁금합니다!
---
문제를 풀 때, 실제 상황에 대입하면서 진행했고 제대로 구현은 됐는데 어딘가 얻어걸린 느낌도 조금 있는거 같아서.. 부족해 보이는 부분 있으면 많은 피드백 부탁드립니다!! 😆

2022-04-29 12:20 UTC, ye-ha requested changes
> 12번 코드에서 name 을 상수로 선언하고 싶은데, 그렇게 하면 21번 코드 coffeeShop.customer?.name = name 에서 에러가 발생하는데, 에러를 구글링해도 이유를 못찾았습니다..


> CoffeeShop을 구조체로 하고, order 메소드 앞에 mutating 을 붙여서 코드를 작성했었는데, 그렇게 하면 22번코드에서 Cannot use mutating member on immutable value: 'coffeeShop' is a 'let' constant 에러가 뜹니다..! 에러 내용을 찾아봤을 때 구조체의 값타입 때문에 생긴거로 대충은 이해가 되고 클래스로 고치면 해결되는데, 작동원리는 정확하게 모르겟습니다 🥲

이 부분은 함수의 파라미터에 대해 알아보시면 해결하실 수 있습니다! 😄

> order 함수에서 옵셔널 바인딩 부분이 적절하게 쓰인건지..? 궁금합니다! 

if let의 사용이 궁금하신게 맞나요? 해당 부분의 옵셔널 바인딩은 잘 처리해주셨습니다. 👍

> giveCoffee 메소드 안에 조건문을 걸었는데, 코드상으로는 giveCoffee 호출 바로 위에서 pickUpTable 값을 주기 때문에 조건문이 없어도 잘 작동합니다. 과제 설명에는 pickUpTable에 커피가 올려지면 다음과 같은 문구가 출력됩니다.이렇게 나와있어서 의미상 조건문을 추가했는데 그대로 둬도 좋을까요?

코멘트에도 남겼는데, Property Observer를 공부해보시면 도움이 되실 거예요. 

> 타입과 인스턴스를 활용해서 코드를 작성하는게 아직 많이 낯설어서,, 타입과 인스턴스 활용에 대한 더 나은 방법이나 아이디어가 있는지도 궁금합니다!

잘해주셨어요. 👍 코멘트 남긴 내용을 바탕으로 기능 분리, 객체 간 메세지 전달이 더 잘되도록 수정해봅시다. 😄

2022-04-29 12:20 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +    var coffeeReady = false
Bool타입의 변수가 어떤 네이밍을 가지면 좋은지 API Design Guidelines를 참고해서 변경해보면 좋을 것 같습니다. 😄

2022-04-29 12:20 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +        if let worker = barista, let buyer = customer, let coffeePrice = menuList[coffee] {
옵셔널 바인딩을 할 때 여러 조건을 한 번에 줄 수 있죠. 👏👏

2022-04-29 12:20 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +    var customer: Person?
커피숍이 손님을 (프로퍼티로) 가져야 할까요?🤔

2022-04-29 12:20 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +            pickUpTable = false
많은 기능이 포함되어 있어서 메서드로 분리할 수 있겠어요!

2022-04-29 12:20 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +class Barista: Person {
바리스타가 사람을 상속받고 있군요! 바리스타도 커피를 살 수 있죠! 좋은 시도입니다. 👏 
상속을 했던 다른 의도도 있을까요? 
상속을 어떤 경우에 할까요?

2022-04-29 12:20 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
>          if pickUpTable == true {
현재는 픽업테이블을 체크해서 true일 때 커피가 준비되었다는 문구를 출력하는군요. 

현실에서는 직원이 픽업테이블에 커피를 두고, 커피가 준비되었다는 안내가 되고, 손님이 와서 커피를 가져가고, 픽업테이블이 비워집니다. 
해당 부분을 반영해서 출력 이후의 행동을 할 수 있도록 수정해볼까요? 

추가로 `Property Observer` 개념을 공부해보시면, 이번 스텝에서 유용하게 활용할 수 있으실 거예요.

2022-04-29 12:20 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +missKim.buy(.milkTea, at: yagombucks)
바리스타가 커피를 만들어야 하는데, 바리스타는 야곰벅스에 바리스타로 지정되는 일만 하고 있어요. 
사실상 손님이 커피를 주문하며, 만들고, 출력까지 다 하고 있네요! 
각자가 자신의 일을 할 수 있도록 해주세요. 😄

2022-05-02 01:18 UTC, inho-98 commented
안녕하세요! @ye-ha 🙂
지난 코드에서 수정이 꽤 많아서 새로 코멘트로 다시 한번 정리하려 합니다! 위에 코멘트 달아주신 내용 최대한 반영해서 코드를 수정했기 때문에 설명에 같이 포함하겠습니다! 이번 수정에서는 지난 PR때 작성했던 코드의 근거를 생각해보고, 나름 이유를 생각해가며 작성했습니다.

## 고민했던 것
### Person 타입 클래스에서 구조체 변경 및 Barista 클래스 제거
- 지난번엔 Barista 라는 클래스 타입을 만들고 Person을 상속받도록 했습니다. 그렇게 했던건 직관적으로 바리스타가 사람이니 Person을 상속받고 추가 기능을 만들어 주면 기능 분리 측면에서 좋아보였습니다. 그런데 코드 안에서 Barista가 Person의 프로퍼티나 메소드를 이용하지 않았고, Barista의 기능은 CoffeeShop 내부에 매서드로 구현해도 무방해서, 클래스를 없애도 된다고 판단했습니다.
- Person을 구조체로 바꾼뒤에는 Step1 처럼 불변 프로퍼티인 이름과, 가변 프로퍼티인 돈을 정의했습니다.
### CoffeeShop 클래스 수정
- **customer 프로퍼티 사용 여부** -> 위에 코멘트에서 커피숍이 손님을 가져야 하냐고 질문해주셨습니다! 문맥상 가지고 있지 않아도 구현할 수 있다고 이해돼서 프로퍼티를 가지지 않고 코드를 작성하도록 했었는데요(최종 커밋한 코드랑은 다릅니다!), 중간에 작성했던 코드를 보면
```
class Person {
    let name: String
    var money: Int

    init(name: String, money: Int) {
        self.name = name
        self.money = money
    }

    func buy(_ coffee: Coffee, at coffeeShop: CoffeeShop) {
        coffeeShop.order(coffee, from: self)  // 2. 주문을 할 때 인스턴스 자신을 전달합니다.
    }
}

class CoffeeShop {
    var sales: Int = 0
    let menuList: [Coffee: Int] = [.americano: 4000, .latte: 4500, .milkTea: 4500, .vanillaLatte: 5000, .strawberryLatte: 5500]
    var pickUpTable: Bool = false
    var barista: Barista?

    func order(_ coffee: Coffee, from customer: Person) {  // 1. 메소드에서 매개변수로 Person 타입을 받습니다.
        if let worker = barista, let coffeePrice = menuList[coffee] {
            if customer.money < coffeePrice {
                print("잔액이 \(coffeePrice - customer.money)원만큼 부족합니다. ")
            } else {
                worker.makeCoffee()
                worker.giveCoffee(to: customer.name)
                pickUpTable = false
                customer.money -= coffeePrice
                sales += coffeePrice
            }
        }
    }
}
``` 
위 주석의 설명대로 두 인스턴스 간에 데이터를 주고받도록 구현을 하고, 타입 내에는 손님 프로퍼티를 없앨 수 있었습니다. 그런데 저렇게 했을때 문제는, order 함수 내에서만 손님의 정보에 접근이 가능해서, 모든 코드가 함수 내에서만 작성되어야 했습니다. 
커피숍 타입 내부에서 기능을 분리하기 위해 메소드와 프로퍼티 감시자를 사용하고, 그 안에서 손님의 정보에 대한 접근이 필요해서 커피숍이 손님을 프로퍼티로 가지도록 수정했습니다!
- **pickUpTable 프로퍼티 감시자** -> 프로퍼티 감시자에 대해 이해했고, 픽업 테이블에 커피가 준비된 후에 손님이 호출되므로, didSet을 사용했습니다. 그 안에서는 pickUpTable이 true인지 확인한 뒤 문구가 출력되고, 음료는 사라지므로 false 값을 줍니다.
- **barista 타입 변경** -> 바리스타는 옵셔널 Person 타입에서 Person타입으로 변경되었는데, 카페가 생기는 시점에 당연히 직원이 있어야 하므로 인스턴스를 초기화 할때 같이 값을 주는게 좋다고 판단했습니다.
- **order 함수 내부** -> 손님의 잔액을 확인한뒤 커피를 만드는 것과 매출상승 및 손님의 지출 부분을 메소드로 나눠서 작성했습니다.
makeCoffee 함수에서는 바리스타가 커피를 만들고 픽업 테이블에 올립니다. (픽업 테이블에서는 프로퍼티 감시자로 진행)
calculate 함수에서는 손님의 지출과 매장의 매출이 발생합니다.
- **CoffeeShop이 클래스인 이유** -> 지난 과제 PR에서 
> CoffeeShop을 구조체로 하고, order 메소드 앞에 mutating 을 붙여서 코드를 작성했었는데, 그렇게 하면 22번코드에서 Cannot use mutating member on immutable value: 'coffeeShop' is a 'let' constant 에러가 뜹니다..! 에러 내용을 찾아봤을 때 구조체의 값타입 때문에 생긴거로 대충은 이해가 되고 클래스로 고치면 해결되는데, 작동원리는 정확하게 모르겟습니다 🥲

이런 에러가 있었는데요, 이유를 (조금 더) 이해하게 됐습니다!  Person 타입의 `func buy(_ coffee: Coffee, at coffeeShop: CoffeeShop)`함수에서 매개변수로 들어온 coffeeShop은 상수인데, 함수 내에서 호출되는 order 메소드가 CoffeeShop 을 구조체로 정의하면 mutating, 가변 메소드가 되어야 하는데, 상수값을 가변 메소드를 이용해서 변경할 수 없으니 에러가 뜬다고 이해했습니다! (구조체의 인스턴스가 값 이므로) 그런데 buy 메소드 내에서
```
func buy(_ coffee: Coffee, at coffeeShop: CoffeeShop) {
        var cafe = coffeeShop
        cafe.order(coffee)
    }
```
coffeeShop을 변수에 담고 가변 메소드를 실행할 수는 있는데, 구조체는 값이 복사되기 때문에, 원본 인스턴스가 바뀌는 게 아니어서 문제가 됩니다. 따라서 원본 인스턴스를 수정하기 위해 커피숍을 class 타입으로 선언했습니다.

## 조언을 얻고싶은 부분
- 각 인스턴스의 기능을 분리하면서도 필요한 정보를 주고받도록 하는 과정이 생각보다 어려워서 신경을 많이 썼는데요, 지난 PR처럼 Barista 타입이 있고 그안에 커피를 만드는 메소드가 있는것도 기능 분리 차원에선 더 좋아보이긴 했습니다. 정답이라고 할만한 기준이나 관점은 없을 것 같은데, 제 코드를 계속 보다보니 판단이 더 흐려지는 것같아서 예하의 의견이 너무 궁금합니다..ㅎㅎ😵‍💫
- 지난 마지막 코멘트에서 
> 바리스타가 커피를 만들어야 하는데, 바리스타는 야곰벅스에 바리스타로 지정되는 일만 하고 있어요.
사실상 손님이 커피를 주문하며, 만들고, 출력까지 다 하고 있네요!
각자가 자신의 일을 할 수 있도록 해주세요. 😄

이렇게 남겨주셨는데, 각자 할 일은 잘 분리되어 있고, 저 부분이 인스턴스랑 메소드 호출 부분이라 그렇게 보였다고 생각했는데요, 지금도 기능 분리가 제대로 안된건지, 수정할 부분이 있는지 궁금합니다! 🤔

---
주말동안 고민 많이 해보고 코드를 작성했는데, 많이 막히기도 했던것 같아요..! 뭔가 수정은 하려는데 내가 뭘 의도하는 건지 모를때도 있었고, 판단이 잘 안서기도 해서 그런 부분들을 다시 정리하는 느낌으로 코멘트를 작성해서 좀 길게 된것 같아요..ㅎㅎ 양해 부탁드립니다..😅👍

2022-05-02 02:16 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +        coffeeShop.order(coffee)
커피숍 타입에 손님의 이름을 전달하기 위함이었는데, 불필요했던 코드로 판명나서 제거됐습니다. 🤓

2022-05-02 02:16 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +class Barista: Person {
바리스타가 사람니까 해당 타입을 상속받아도 되겠다 싶어서 클래스로 바꾸고 상속을 했는데, 코드에서 보니 Person의 프로퍼티와 메서드를 사용하지 않아서 Barista 타입은 없앴습니다.
제가 생각하는 상속은 예를들어, 애플이 아이폰 14 시리즈를 코드로 만든다 할때, 모든 14시리즈의 공통점을 묶어 부모 클래스로 정의한 뒤, 각 모델에 따라서 자식 클래스에 특성과 기능을 추가하는 식으로 적용할것 같습니다!

2022-05-02 02:16 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +    var coffeeReady = false
찾아보고 isCoffeeReady 라는 이름으로 바꿨는데요, 코드를 수정하면서 저 프로퍼티는 삭제됐습니다!

2022-05-02 02:16 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +            pickUpTable = false
조건문에서 손님의 잔액을 확인한뒤, 커피를 만드는 것과 매출상승 및 손님의 지출 부분을 메서드로 나눠서 작성했습니다.
makeCoffee 함수에서는 바리스타가 커피를 만들고 픽업 테이블에 올립니다. (픽업 테이블에서는 프로퍼티 감시자로 진행)
calculate 함수에서는 손님의 지출과 매장의 매출이 발생합니다.

2022-05-02 02:16 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
>          if pickUpTable == true {
알려주신 덕분에 프로퍼티 감시자를 이용했습니다!

픽업 테이블에 커피가 준비된 후에(true 값 할당) 손님이 호출되므로, 흐름상 didSet을 사용했습니다. 
그 안에서는 pickUpTable이 true인지 확인한 뒤 문구가 출력되고, 음료는 사라지므로 false 값을 줍니다.

2022-05-02 02:16 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +missKim.buy(.milkTea, at: yagombucks)
지난 코드에 대해서도 마찬가지이긴 한데, 각자 할 일은 분리를 했는데, 저 부분이 인스턴스랑 메소드 호출 부분이라 그렇게 보였다고 생각했는데요(잔액이 부족한 상황을 보여주기 위해 구매 매서드를 여러번 호출해서..?), 지금도 기능 분리가 제대로 안된건지, 수정할 부분이 있는지 궁금합니다! 🤔

2022-05-02 02:45 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
>      }
CoffeeShopt 클래스가 손님을 프로퍼티로 가지고 있습니다. 

위에 코멘트에서 커피숍이 손님을 가져야 하냐고 질문해주셨을 때 문맥상 가지고 있지 않아도 구현할 수 있다고 이해돼서 프로퍼티를 가지지 않고 코드를 작성하도록 했었는데요(최종 커밋한 코드랑은 다릅니다!), 중간에 작성했던 코드를 보면
```
class Person {
    let name: String
    var money: Int

    init(name: String, money: Int) {
        self.name = name
        self.money = money
    }

    func buy(_ coffee: Coffee, at coffeeShop: CoffeeShop) {
        coffeeShop.order(coffee, from: self)  // 2. 주문을 할 때 인스턴스 자신을 전달합니다.
    }
}

class CoffeeShop {
    var sales: Int = 0
    let menuList: [Coffee: Int] = [.americano: 4000, .latte: 4500, .milkTea: 4500, .vanillaLatte: 5000, .strawberryLatte: 5500]
    var pickUpTable: Bool = false
    var barista: Barista?

    func order(_ coffee: Coffee, from customer: Person) {  // 1. 메소드에서 매개변수로 Person 타입을 받습니다.
        if let worker = barista, let coffeePrice = menuList[coffee] {
            if customer.money < coffeePrice {
                print("잔액이 \(coffeePrice - customer.money)원만큼 부족합니다. ")
            } else {
                worker.makeCoffee()
                worker.giveCoffee(to: customer.name)
                pickUpTable = false
                customer.money -= coffeePrice
                sales += coffeePrice
            }
        }
    }
}
```
위 주석의 설명대로 두 인스턴스 간에 데이터를 주고받도록 구현을 하고, 타입 내에는 손님 프로퍼티를 없앨 수 있었습니다. 그런데 저렇게 했을때 문제는, order 함수 내에서만 손님의 정보에 접근이 가능해서, 모든 코드가 함수 내에서만 작성되어야 했습니다.

커피숍 타입 내부에서 기능을 분리하기 위해 메소드와 프로퍼티 감시자를 사용하고, 그 안에서 손님의 정보에 대한 접근을 위해서 커피숍이 손님을 프로퍼티로 가지도록 선택했습니다!

2022-05-02 02:45 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +    var customer: Person?
아래 코멘트에 답변 남겼습니다! 😁

2022-05-02 02:46 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +    var customer: Person?
아래 코멘트에 남겼습니다! 😁

2022-05-02 11:24 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +            pickUpTable = false
기능을 분리하신 점, 좋습니다! 
더 분리할 부분이 있을지, 각자 자기의 역할에 맞는 행동을 하고 있는지 생각해봅시다. 🤔 

1. calculate 함수가 coffeeshop 내부에 있습니다. coffeeshop이 손님의 잔고에 직접적으로 영향을 줘도 괜찮을까요?
2. order 함수도 coffeeshop 내부에 있습니다. order 함수에서 손님의 잔고를 체크하고 있는데.. coffeeshop이 손님의 잔고를 체크해도 괜찮을까요?

2022-05-02 11:28 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +missKim.buy(.milkTea, at: yagombucks)
행동을 하는 주체가 누구인지 생각해보면 좋습니다. 
구두로 전달드렸듯이 코드로 표현하기 전, 현실에서 커피를 주문할 때 어떤 과정을 거쳐서 주문하고 수령하게 되는지 세세하게 단계를 나누어서 생각해봅시다.😄

2022-05-02 11:33 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
>      }
구두로 전달해드렸듯이 주문을 받을 때 손님 하나를 통째로(?) 전달받을 필요가 없습니다. 
필요한 정보만 요청하고 주고 받는 것이 좋습니다! 
그리고 손님의 잔고를 변경할 수 있는 것은 오로지 손님 뿐입니다! 
실제로 어떤 과정을 거쳐서 커피를 주문하게 되는지, 특정 행동을 누가 하는지 생각해봅시다. 😄

2022-05-04 05:13 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +missKim.buy(.milkTea, at: yagombucks)
행동의 주체를 구분하고, 과정을 자세하게 적었습니다. 
손님
1. 음료를 마실 카페를 정한다.
2. 매장에서 메뉴판을 확인한다.
3. 마시고 싶은 메뉴와 가격을 확인한다.
4. 잔고와 음료 가격을 비교하여 주문이 가능한지 파악한다.
5. 주문이 가능하면 음료를 주문한다.
6. 손님의 잔고가 음료 가격만큼 줄어든다.
7. 주문이 안되면 금액이 부족하다고 출력한다.
8. 음료가 준비됐을 때 (손님이 호출됐을때) 음료를 받는다.

매장
1. 손님에게서 주문할 음료 (와 이름) 을 받는다.
2. 바리스타에게 주문 정보를 준다.
3. 바리스타가 주문 들어온 음료를 만든다.
4. 바리스타가 준비된 음료를 픽업 테이블에 올린다.
5. 픽업 테이블에 음료를 올리면 손님을 호출한다.
6. 음료는 없어지고 픽업테이블이 비워진다.
7. 매장의 매출이 음료 가격만큼 오른다.

2022-05-04 07:27 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +missKim.buy(.milkTea, at: yagombucks)
1. 손님이 매장에서 메뉴판을 보고 음료를 고른다
2. 손님이 음료 값을 낼수 있는지 잔고를 확인한다
3. 매장에게 주문한다.
4. 매장에서 손님의 커피 종류 주문을 받는다. 
5. 주문을 받고 바리스타에게 메뉴를 알려준다.
6. 바리스타가 음료를 만든다.
7. 바리스타가 음료가 완성되면 픽업테이블에 올린다.
8. 픽업테이블에서 손님을 호출한다.
9. 손님이 음료를 가져간다.

2022-05-04 08:02 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +missKim.buy(.milkTea, at: yagombucks)
구두로 피드백드리며, 함께 주문하는 순서와 손님-바리스타(매장) 간의 상호작용에 대해 이야기나누었습니다. 😄

2022-05-04 08:16 UTC, inho-98 commented
네이밍 몇개 더 구체적으로 수정했습니다! `isAvailable` -> `isCoffeeAvailable`,  `calculate` -> `increaseSales`
그리고 코드 살짝 변경한게 있어서 코드에 코멘트 같이 남기겠습니다.

2022-05-04 08:19 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +    }
아까 얘기해 주신대로, 결제 자체도 메서드로 분리하는게 좋을것같습니다!

2022-05-04 08:19 UTC, inho-98 commented on CodeStarterCamp_Week3/main.swift
> +        }
구매하는 매서드 내에서, 이전에는 커피숍에 해당 메뉴의 가격이 없어도 지출이 되었는데, 
CoffeeShop 타입의 order 메소드에서 불리언 리턴값을 주어서 커피가 메뉴에 있을때만 구매할 수 있도록 수정했습니다!

2022-05-04 09:19 UTC, merged