Week3 [Step1] 윤세영
yagom-academy/swift-starter-week3 pull request #86
Opened 2022-04-29 12:11 UTC by ssyoun4092

@oksunwoo 

지금까지 가장 고민 많이한 스텝이면서 동시에 정말 재밌게 수행한 스텝입니다! 
마치 퍼즐푸는거 같기도 하고, 게임하는거 같기도 하고 시간 정말 훅 지나갔어요!

> # class vs struct
이 부분 역시 고민했습니다만, class로 타입을 정의한 이유는 상속받을 수 있어서입니다!
+ Step에서는 나오진 않지만 Perosn이라는 이름에서부터 상속할 여지가 충분히 있다고 판단했습니다. CoffeeShop도 마찬가지구요!
+ 다만, 애플공식문서에는 struct를 기본적으로 상용하라고 하지만.. 상속을 위해 class를 포기하지 못했습니다!

> # class 내부에서 var or let
+ Person 클래스의 프로퍼티.
    + 사람의 이름과 나이는 변하지 않는다고 생각했습니다(물론 개명을 하거나 해가 바뀌면 나이가 바뀌지만 여기서는 고려하지 않을게요..!)
    + money는 사고 팔 때 당연히 변하는 값이므로 변수로 설정하였습니다.
+ CoffeeShop 클래스의 프로퍼티
    + 매출액을 의미하는 sales는 매달 변하므로 변수로 설정하였습니다.
    + coffeeMenu는 조금 고민했는데, 차후 메뉴가 추가될 수 있다고 생각되어 변수로 설정하였습니다.
    + barista 마찬가지로 고용하거나 해고당할 수 있어서 변수로 설정하였습니다.
    + pickUpTable은 프로퍼티 감시자로 정했기 때문에 변수로 설정하였습니다.
        + 어제 막 배운 didSet을 사용해보았습니다. 제가 느끼기엔 pickUpTable과 찰떡인것 같더라구요!

> # enum에서 원시값과 연관값
DM에서 보았듯이, Coffee의 종류들을 만들 때, 연관값으로 이름과 가격을 같이 묶으려고 했습니다. 
```swift
enum CoffeeMenu {
    case americano(name: String, price: Int)
    case capouccino(name: String, price: Int)
    case latte(name: String, price: Int)
}
```
+ 이런식으로요! 그 이유는 메뉴이름과 가격은 쌍이니까 같이 묶어야겠다라고 생각을 했습니다. 그러나, 굳이 그럴 필요가 없었습니다
    + 우선 price에만 접근하기가 상당히 까다로웠습니다. 'if case let'이라는 것을 활용한다면 할 수야 있었지만, 케이스 하나하나마다 다 해줘야했기에 상당히 비효율적이었습니다.

+ 원시값을 활용하여, 위의 문제를 잘 해결했습니다.
    + CoffeeShop의 init에서 CoffeeMenu의 케이스를 받아올 수 있도록 하였고, 인스턴스를 생성할 때 해당 음료메뉴와 가격을 같이 초기화하여 딕셔너리 타입으로 저장하였습니다.
    + 이렇게 하니, rawValue라는 메소드를 사용해서 해당 케이스의 원시값을 호출하여 pickUpTable의 didSet에서 활용하였고, 주문받는 함수인 getOrder 함수에서 편하게 주문들어온 음료의 가격에 접근할 수 있었습니다.

> 추가사항
+ 사실 저희가 음료를 주문하면 사이즈도 정해야하고, 아이스로 할건지 핫으로 할건지도 정하기 때문에 좀 더 현실적인 메소드를 만들어 보았습니다!

> 질문사항
+ main 파일안에 다 넣는게 맞나요..? 메인파일이 아닌 다른파일로 나눠서 정리한다면, 정리 기준은 어떻게 되는지 알고 싶습니다. class 타입별로, enum타입별로 정리하는지 아니면 Person관련된것, Coffee 관련된것 등 의미별로 나누는지 알고 싶습니다!

2022-05-01 13:39 UTC, oksunwoo requested changes
우선 쉽지않은 스탭이였을텐데 정말 고생많이하셨습니다! class와 struct에 대한 고민까지 하시고, 상속도 조사해보셨군요! 그렇다면 상속은 어떤경우에 쓰일까요??
추가적으로 아이스와 핫 구현까지 재밌고 보기좋은 코드였습니다.

---
### 질문에 대한 답변
아직은 command line tool에서 작업을 하고 있고, 본격적으로 앱개발이 시작되게 되면 파일을 분리하기 시작할 겁니다. 여기서는 main이 실행이 되는 곳이니, 사실 지금 만드신 class나 enum 같은 타입들은 main이 아닌 파일에 작성하는 것이 조금 더 깔끔해질 것으로 생각됩니다. 개인별로 차이가 있으나, 각 모델 별로 파일을 분리하기도 하고, 아니면 연관된 것끼리 묶어서 파일을 분리하기도 합니다.

2022-05-01 13:39 UTC, oksunwoo commented on CodeStarterCamp_Week3/main.swift
>  }
세영님께서 저에게 help를 요청하셔서 일단 rawValue를 가르쳐 드렸지만, 사실 enum의 rawValue를 특정값을 저장하려는 목적으로 사용하는 것은 올바르지 않습니다. enum의 rawValue는 case를 생성하기 위한 값으로, case가 유일해야합니다. 무슨 뜻이냐면, 현재코드에서 Ice는 300이고, hot은 0 자체를 의미하고 있다는 뜻입니다. 정리하자면, enum의 rawValue는 identifier입니다.

혹시 연산프로퍼티에 대해 배우셨을까요? 그럼 먼저 연산프로퍼티가 무엇인지 간략하게 설명부탁드립니다!

2022-05-01 13:39 UTC, oksunwoo commented on CodeStarterCamp_Week3/main.swift
> +    }
didSet을 활용해주셨네요!
혹시 이게 무엇인지 알고계신가요?
그리고 self도 사용해주셨는데 self가 무엇인지, 그리고 저기에 왜 사용하셨는지 설명부탁드려요!

2022-05-01 13:39 UTC, oksunwoo commented on CodeStarterCamp_Week3/main.swift
> +let yagombucks = CoffeeShop(coffeeMenuWithPrice: [.americano: 4500, .capouccino: 4800, .latte: 5000], barista: misterLee)
여기 가운데에 있는 공백은 무엇을 의미하나요?

2022-05-01 13:39 UTC, oksunwoo commented on CodeStarterCamp_Week3/main.swift
> +        print("감사합니다 주문하신 음료 총 가격은 \(price)원 입니다~")
스위프트에서 get으로 시작하는 네임은 많이 지양하는 편입니다. 문서 첨부해드릴테니 한번 참고해보세요! 저는 그냥 order라고 해도 좋을 것 같네요. 


https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html
Use “get” only for methods that return objects and values indirectly. You should use this form for methods only when multiple items need to be returned.

2022-05-01 13:41 UTC, oksunwoo commented on CodeStarterCamp_Week3/main.swift
> +    }
음... 여기서는 buy(coffee: CoffeeMenu)와 같이 이미 만들어본 커피메뉴 타입을 적용시켜 보는 것은 어떨까요?

2022-05-02 05:36 UTC, ssyoun4092 commented on CodeStarterCamp_Week3/main.swift
> +    let money: Int
엇... 바로 수정하겠습니다!

2022-05-02 05:58 UTC, ssyoun4092 commented on CodeStarterCamp_Week3/main.swift
>  }
> 궁금한 점!
raw Value에 대해서 구글링을 해보았는데, 사용방법이라던지 호출방법 등이 주로 있고 왜 rawValue를 사용하는지 등은 안나오더라구요..
그래서 추측하는거지만, 토니 말씀처럼 identifier 개념으로 본다면, 가격 값처럼 값이 변할 여지가 많을 때에는 rawValue를 사용하는게 부적절하다는 건지 알고싶습니다! 

연산 프로퍼티라는 키워드로 enum 타입을 한번 수정해보았습니다!

연산프로퍼티란

    + 실제 값을 갖지 않지만, get과 set을 이용하여 다른 프로퍼티의 값을 연산하고 반환하는 프로퍼티입니다.
    + 값을 저장하지 않기 때문에 반드시 변수로 선언되어야 하고, 타입을 반드시 명시해줘야합니다.
    + getter
        + get이라는 키워드를 사용하고, 값을 가져와서 연산하고 반환하는 역할을 합니다. return문이 필요합니다.
        + set을 안쓰는 읽기전용 연산프로퍼티를 사용한다면, get은 생략해도 됩니다.(제 코드에서는 get을 생략하지 않고 사용했습니다!)
    + setter
        + set이라는 키워드를 사용하고, 파라미터로 받은 값을 연산하여 다른 저장프로퍼티에 값을 저장합니다.
        + set은 연산 프로퍼티내에서 불필요하면 사용하지 않아도 무방합니다.

2022-05-02 06:13 UTC, ssyoun4092 commented on CodeStarterCamp_Week3/main.swift
> +    }
### didSet
didSet, willSet은 프로퍼티 감시자로, 해당 프로퍼티의 값을 계속 지켜보고 있다가 값이 변하자마자 해당 구문이 실행됩니다.
didSet은 값이 변하자마자 호출되고, willSet은 값이 변하기 직전 호출됩니다.
즉, willSet 구문 실행 -> 값이 변함 -> didSet 구문 실행 순으로 이어집니다.

### self
self는 자신의 인스턴스를 표현하는데 사용합니다. 
클래스 내부에서 프로퍼티를 사용할 때 어느 클래스의 프로퍼티를 사용하는지 모를 수 있습니다. 
이때 self를 사용하여 자기 자신 인스턴스의 프로퍼티를 표시하기 위해 사용하고 있습니다. 

self.pickUpTable은 CoffeeShop 클래스에 있는 pickUpTable 프로퍼티를 가르키고 있습니다!
사용한 이유는 didSet 구문 안에서 pickUpTable에 접근할 때 self를 사용해서 접근해야하는줄 알았습니다.. 근데 생략해도 접근이 가능하네요..ㅎ

2022-05-02 06:14 UTC, ssyoun4092 commented on CodeStarterCamp_Week3/main.swift
> +let yagombucks = CoffeeShop(coffeeMenuWithPrice: [.americano: 4500, .capouccino: 4800, .latte: 5000], barista: misterLee)
Person타입의 인스턴스를 생성한 것과 CoffeeShop 타입의 인스턴스를 생성한 것을 구분하기 위해 공백을 두었습니다!
붙이는게 나을까요??

2022-05-02 06:14 UTC, ssyoun4092 commented on CodeStarterCamp_Week3/main.swift
> +        print("감사합니다 주문하신 음료 총 가격은 \(price)원 입니다~")
넵 참고하겠습니다!

2022-05-02 06:14 UTC, ssyoun4092 commented on CodeStarterCamp_Week3/main.swift
> +    }
적용해보았습니다!

2022-05-02 14:38 UTC, oksunwoo commented on CodeStarterCamp_Week3/main.swift
>  }
예를 들면, case one = 1 과 같이 one은 1이고, 그에 대한 유일한 identifier 겠죠. 하지만 가격과 같은 경우는 카페라떼가 5000원일수도, 카페모카가 5000원일 수도 있는점에서 보아 rawValue에 값을 할당하는 것은 좋지 않아보인다는 의견입니다.

지금은 연산프로퍼티로 너무 잘 해결해주셨는데, 이 부분은 이번 스탭에서는 그냥 rawValue에 할당하고 넘어갔어도 되는건데, 나중에 프로토콜을 배우게 되어 CustomStringConvertible을 사용하시게 되면 조금 더 깔끔해질 수 있습니다. 이렇게 사용할 수도있구나 하고 넘어가주세요. 이런게 있구나 정도면 될 것 같습니다.

2022-05-02 14:39 UTC, oksunwoo commented on CodeStarterCamp_Week3/main.swift
> +let yagombucks = CoffeeShop(coffeeMenuWithPrice: [.americano: 4500, .capouccino: 4800, .latte: 5000], barista: misterLee)
저는 똑같이 변수의 선언인데 중간에 공백은 무엇이지 하고 질문차 여쭤본 거 였습니다ㅎㅎ 세영님 편하신대로 하시는게 좋습니다

2022-05-02 14:42 UTC, oksunwoo requested changes
고생하셨습니다. 공도 많이 들이시고 깔끔한 코드입니다만....PR요청을 메인브랜치에다가 해주셨네요..ㅎㅎ

2022-05-02 14:42 UTC, oksunwoo commented on CodeStarterCamp_Week3/main.swift
>  }
사용하는 곳에서는 어떤식으로 읽힐 것 같나요?
그리고 사람이 구매하는 곳은 그대로네요!

2022-05-03 00:42 UTC, ssyoun4092 commented on CodeStarterCamp_Week3/main.swift
>  }
makeCoffee(coffee: )로 읽히네요..! 적절한 전달인자 추가해서 수정했습니다!
사람이 구매하는 것을 왜 못봤을까요..ㅎㅎ 수정했습니다!

2022-05-03 04:49 UTC, merged