Week3 [Step2] BaDook2
yagom-academy/swift-starter-week3 pull request #89
Opened 2022-04-30 18:50 UTC by BaDook2

@Jager-yoo 
질문
1. 리드미 파일을 읽어보시면 아시겠지만 바리스타의 돈이 0원인데 원래는 없다(nil)는 가정을 해보고 싶어 money를 Int?를 넣었다가 missKim의 소지금을 변경하지 못해서 질문드립니다. 옵셔널 타입의 값을 바꿀 방법은 없나요? (1을 더한다는 등)

p.s. 만약 md파일의 줄바꿈이 안나눠져 있다면....잘 모르겠습니다. 제가 봤을 때는 main 파일은 줄바꿈이 안되어 있던데 혹시나해서 일단 올립니다. 그리고 md파일을 깃헙에서 직접 수정해서 커밋해봤는데....스페이스바를 여러번 눌러야 다음줄로 넘어가지는데....이게 오류인지 뭔지 모르겠습니다. 몇 번 더 해봐야 알 것 같습니다.

2022-05-01 11:21 UTC, Jager-yoo commented
안녕하세요 바둑이님~!
금방 `스텝2` 제출해주셨군요. 😄 

PR 문서로 질문해주신 점에 대해, 먼저 답변 드리고, 코드 단위로 들어갈게요~!

> 리드미 파일을 읽어보시면 아시겠지만 바리스타의 돈이 0원인데 원래는 없다(nil)는 가정을 해보고 싶어 money를 Int?를 넣었다가 missKim의 소지금을 변경하지 못해서 질문드립니다.
> 옵셔널 타입의 값을 바꿀 방법은 없나요? (1을 더한다는 등)

- Person 타입의 money 프로퍼티를 옵셔널 타입인 `Int?`로 선언하는 걸 고민하셨군요.
만약 그렇게 하신다면, missKim 의 소지금을 변경하려고 시도할 때 마다, `옵셔널 바인딩`을 해서 값에 접근하셔야 할 겁니다.
코드가 상당히 복잡해지겠죠!
굳이 옵셔널이 아니어도 `값의 없음`을 표현할 수 있다면 (소지금 == 0), 굳이 옵셔널로 만들지 않는 게 훨씬 깔끔한 방법이 아닐까 생각합니다! 🤔

2022-05-01 11:47 UTC, Jager-yoo requested changes

2022-05-01 11:47 UTC, Jager-yoo commented on README.md
> +값을 참조학 위해서는 구조체보다는 클래스가 훨씬 수월하기 때문에 전부 클래스로 바꾸어주었습니다.
구조체에서 `클래스`로 바뀐 거 확인했습니다. 👍🏻 
바둑이는 왜 `값을 참조하기 위해서` 구조체보다 클래스가 훨씬 수월하다고 생각하신 거에요~?

근거를 조금 더 구체적으로 코멘트로 달아주실 수 있을까요? 😄

2022-05-01 11:47 UTC, Jager-yoo commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(consumer: missKim, barista: misterLee)
여기 missKim, misterLee 는 `상수` 로 선언해주셨는데
야곰벅스는 `var(변수)` 로 선언해주셨더라구요!

근데 구조체 → 클래스로 타입 선언을 변경했기 때문에
이제 야곰벅스도 `let(상수)`로 선언해도 멀쩡하게 작동합니다. 😄 

```swift
// let(상수) 로 선언해도 잘 작동합니다.
let yagombucks = CoffeeShop(consumer: missKim, barista: misterLee)
```

어떻게 그럴 수 있을까요?
let 으로 선언했음에도, 야곰벅스(커피샵) 내부의 `sales`, `pickUpTable` 프로퍼티를 변경할 수 있는 건 어째서 일까요?
바둑이님이 고민해보고 코멘트 달아주세요!!! 👍🏻

2022-05-01 11:47 UTC, Jager-yoo commented on CodeStarterCamp_Week3/main.swift
> +yagombucks.takeOrder(consumer: missKim, coffee: .americano, barista: misterLee)
이 부분 잘 해주셨는데요!

요구사항을 보면, 커피샵이 스스로 주문 메서드를 실행하는 게 아니고
`손님(missKim)`이 `커피를 구매하는 메서드`를 실행해서 → 순차적으로 로직이 돌아가는 것으로 보입니다. 🤔 

<img width="793" alt="image" src="https://user-images.githubusercontent.com/71127966/166144155-f244ead0-5010-4d5c-a7e3-38480fa45055.png">

손님이 자신의 인스턴스 메서드를 통해, 마시고 싶은 커피와 주문하는 커피샵을 `파라미터`로 받게 하면 어떨까요? ㅎㅎㅎ

2022-05-01 11:47 UTC, Jager-yoo commented on CodeStarterCamp_Week3/BusinessDesign.swift
> +        }
## 1️⃣ 조건문의 중첩 피하기

if-let 옵셔널 바인딩 잘 해주셨습니다!
menu 프로퍼티가 `딕셔너리`라서, 값을 꺼낼 때 `옵셔널`을 달고 나오죠. ㅎㅎㅎ

제가 코멘트 드리고 싶은 점은
여기서 `if문`이 2번 중첩됐다는 것입니다.
if-let 도 결국에 if문이고, 옵셔널 바인딩이 성공했을 때 또 다시 if문으로 분기처리를 진행해주셨는데요!

아무래도 조건문이 2중~3중으로 들어가는 건 가독성도 안 좋아지고 코드 흐름을 읽기 어려워진다고 생각합니다. 😅 

어떻게 하면 `중첩 없이` 옵셔널 바인딩도 성공하면서, if문 분기처리도 할 수 있을까요?
바로바로... `guard-let` 스타일로 가능합니다. ㅎㅎㅎ 한 번 리팩토링 해보시죠!

## 2️⃣ 중요한 걸 if문에 붙이고, 예외처리를 else로 옮기기

if-else 구문을 통해 `예외처리` 까지 잘 해주셨는데요! 👏🏻 
주문에 성공한 경우가 if문 바로 뒤에 오지 않고, else절로 빠져 있는 게 좀 어색하게 느껴집니다. 🤔 

성공하는 경우(더 일반적이고, 중요한 처리)를 먼저 다뤄주고
예외적인 경우를 else절로 빼는 게 좀 더 일반적인 처리가 아닐까 싶어요!

만약 실패하는 경우를 먼저 걸러내는 스타일을 선호하신다면
if문이 아니라, `guard문`을 사용하시면 더 좋겠습니다. 😄

2022-05-01 22:55 UTC, BaDook2 commented on README.md
> +값을 참조학 위해서는 구조체보다는 클래스가 훨씬 수월하기 때문에 전부 클래스로 바꾸어주었습니다.
구조체는 값 타입이기 때문에 외부 함수에서 사용할 수 없는 것 같습니다. (아마 방법은 있을 것 같은데 어떻게 할 수 있는 지는 모르겠습니다.)
예를 들어
struct example {
    var number = 1
}
func changeNumber(example: example) {
    example.number = 3
}
와 같이 코드를 작성하면 'example is a 'let' constant'라는 오류가 발생하는데 이를 바탕으로 함수는 구조체를 '상수'로 인식한다?로 짐작했습니다. 그래서 '상수'같은 '값'타입이 아닌 클래스 타입으로 선언함으로써 '참조'타입으로 넘겨주었더니 오류가 사라지는 것을 확인했고 구조체보다는 클래스가 수월하다고 생각했습니다.

2022-05-01 23:09 UTC, BaDook2 commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(consumer: missKim, barista: misterLee)
검색을 해도 안나오기에 확실히는 모르겠으나 아마도
구조체는 '값'타입이기 때문에 구조체로 생성된 인스턴스 자체가 let과 var에 영향을 많이 받는 것 같습니다. 그러나
클래스는 '참조'타입이기 때문에 생성된 인스턴스의 타입(위 예제의 경우 CoffeeShop타입)과 이니셜라이저에만 let과 var가 영향을 주는 것 같습니다.

2022-05-02 05:42 UTC, Jager-yoo commented on README.md
> +값을 참조학 위해서는 구조체보다는 클래스가 훨씬 수월하기 때문에 전부 클래스로 바꾸어주었습니다.
ㅎㅎㅎ 구조체는 `값 타입`이라 외부에서 `사용`은 가능한데, `변경`이 어려워요.
바둑이님이 만든 예시에서, 외부 함수(changeNumber) 에서 Example 구조체의 number 를 변경하려면,
Example 구조체의 인스턴스를 만들 때 `var(변수)`로 선언해야 합니다. (변경이 가능하도록)

2022-05-02 05:57 UTC, Jager-yoo commented on CodeStarterCamp_Week3/main.swift
> +var yagombucks = CoffeeShop(consumer: missKim, barista: misterLee)
잘 분석해주셨습니다! 👍🏻 
값 타입은 인스턴스를 let, var 중에 어떤 거로 선언하는 지에 따라 `변경 가능 여부`가 결정됩니다.
시도해보셨듯이, 구조체를 let 으로 선언하면, 아무리 var 프로퍼티를 가졌다고 하더라도, 변경이 안 되죠. 😄 

`참조 타입`인 클래스는 인스턴스를 생성해서 let, var 에 담으면, 인스턴스 자체가 담기는 게 아니라, 그 인스턴스를 가리키는 `메모리 주소`가 담깁니다.
따라서 let 으로 인스턴스를 담더라도, 변경할 수 없는 건 `메모리 주소` 일 뿐이지, 그 인스턴스에 접근해 var 프로퍼티를 변경하는 건 여전히 가능한 것입니다!

- 해당 내용은 공식문서 - [Stored Properties of Constant Structure Instances](https://docs.swift.org/swift-book/LanguageGuide/Properties.html) 에 조금 언급되어 있습니다.
- 좀 더 딥하게 파본 내용은 [이 블로그](https://velog.io/@ryan-son/Swift-%EA%B5%AC%EC%A1%B0%EC%B2%B4%EC%99%80-%ED%81%B4%EB%9E%98%EC%8A%A4-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0%EC%9D%98-%EC%83%81%EC%88%98%EC%99%80-%EB%B3%80%EC%88%98-%EC%84%A0%EC%96%B8%EC%97%90-%EB%94%B0%EB%A5%B8-%EA%B0%92-%EB%B3%80%EA%B2%BD-%EA%B0%80%EB%8A%A5-%EC%97%AC%EB%B6%80%EC%97%90-%EB%8C%80%ED%95%9C-%EA%B3%A0%EC%B0%B0) 참고해보셔도 좋겠네요!

![image](https://user-images.githubusercontent.com/71127966/166190559-17c86d32-a461-4579-8387-886468cbfdc1.png)

2022-05-02 06:49 UTC, Jager-yoo commented on README.md
> +     print("메뉴에 없는 주문입니다.") 이 코드도 처음에 코드를 작성할 때 넣고싶었는데 옵셔널을 다룰 방법을 몰라서 우왕자왕 했었습니다..
ㅎㅎㅎ 이런 솔직한 회고 넘 좋아요!! 👍🏻

2022-05-02 06:49 UTC, Jager-yoo commented on CodeStarterCamp_Week3/BusinessDesign.swift
>      }
order 메서드의 argument label `at` 주신 점!
정말 센스 좋네요. ㅎㅎㅎ 👍🏻 

바둑이님이 디스코드 DM 으로 질문 주신 점에 대해 어떻게 고칠지 고민해봤습니다!
> 아 깃헙에서 push하고 질문을 어떻게 작성하는지 몰라서 여기에다가 적습니다.
> main파일 코드를 보시면 yagombuks()의 파라미터를 보시면 consumer에 missKim을 넣어주는데 혹시 yagombuks()의 파라미터를 barista 하나만 받고 (그러니까 CoffeeShop 클래스 내부에 var consumer: Person을 생략하고) 출력을 지금과 똑같이 할 수 있는 방법이 있을까요?

이 메서드를 아래 처럼 고쳐봤어요.
- 일단, 주문할 때 `메뉴` 확인하는 거랑, `잔고` 확인하는 건, 커피샵이 해줄 문제가 아니라, 주문하는 소비자가 스스로 체크해야 하는 문제잖아요?
그런 점을 코드에 반영했어요. 😄 
즉, 예외처리는 소비자가 스스로 다 하고, 안전한 경우에만 커피샵의 주문 메서드를 호출하는 식으루요!
- 그리고 커피샵이 `consumer` 프로퍼티를 갖지 않게 하려면, `takeOrder` 메서드의 파라미터로, 소비자의 이름과, 돈을 받게 하면 될 것 같아요.
이것도 현실적으로 생각해보면, `블루보틀` 같은 카페 가면, 카드도 건내면서, 자기 이름도 말해야 하거든요. 🤔 그런 모습을 반영해봤어요. ㅋㅋㅋ

```swift
func order(coffee: Coffee, at coffeeShop: CoffeeShop) {
    // 메뉴를 잘 확인하는 건 가게의 책임이 아니라, 소비자의 책임
    guard let price = coffeeShop.menu[coffee] else {
        print("메뉴에 없는 주문입니다.")
        return
    }
    
    // 돈이 충분한지 판단하는 것도 커피샵의 문제가 아니라, 소비자의 책임
    // 카페에서 주문할 때, 자기 통장 잔고는 자기가 확인하잖아요? 알바한테 확인해달라고는 안 하니까요. ㅎㅎ
    if price <= money {
        print("\(name)이(가) \(coffee)를 주문했습니다.")
        money -= price
        coffeeShop.takeOrder(coffee: coffee, name: name, pay: price) // 주문할 때, 이름과 돈을 함께 파라미터로 넘기기
    } else {
        print("잔액이 \(price - money)원만큼 부족합니다.")
    }
}
```

2022-05-02 06:49 UTC, Jager-yoo commented on CodeStarterCamp_Week3/BusinessDesign.swift
> +    var consumer: Person
이제 `consumer` 프로퍼티는 삭제해도 됩니다!
손님을 1명만 받는 게 아니니까, 이런 프로퍼티는 만들면 번거롭다는 거!
바둑이님도 느끼셨을 거라 생각합니다. 😄

2022-05-02 06:49 UTC, Jager-yoo commented on CodeStarterCamp_Week3/BusinessDesign.swift
> +    }
예외처리를 소비자가 스스로 하도록 만들었기 때문에
이제 커피샵의 메서드는 깔끔해집니다. 😄 

그리고 가게의 매출(sales)이 늘어나는 건, 소비자가 하는 게 아니라, 가게가 직접 하는 게 맞는 것 같아서, 여기에 배치했어요.
`makeCoffee` 메서드를 호출할 때, 소비자의 이름과 커피 메뉴를 함께 넘기면 됩니다!

```swift
func takeOrder(coffee: Coffee, name: String, pay: Int) {
    print("커피샵: \(coffee)주문이 들어왔습니다.")
    sales += pay // 가게의 매출은 여기서 올림 (소비자는 돈만 파라미터로 건냄)
    makeCoffee(customerName: name, coffee: coffee) // 파라미터 이름 좀 더 명확하게 바꿔봤어요!
}
```

2022-05-02 06:49 UTC, Jager-yoo commented on CodeStarterCamp_Week3/BusinessDesign.swift
> +    }
여긴 이렇게 수정해봤어요!
참고로 커피샵의 `print문`에는 모두 `"커피샵: ~"` 이라는 메시지를 맨 앞에 붙여놨어요.
메시지를 소비자가 내는 건지, 아니면 커피샵이 내는 건지 정확하게 알아볼 수 있도록요. ㅎㅎ

```swift
func makeCoffee(customerName: String, coffee: Coffee) {
    print("커피샵: \(barista.name) 바리스타가 커피를 만들고 있습니다.")
    pickUpTable = coffee
    print("커피샵: \(customerName) 님의 커피가 준비되었습니다. 픽업대에서 가져가주세요.")
}
```

2022-05-03 04:39 UTC, Jager-yoo approved these changes

2022-05-03 04:41 UTC, Jager-yoo commented
수정 내용 확인했어요!
정말 잘 만들어주셨습니다. ㅎㅎㅎ 💐

2022-05-03 04:42 UTC, merged