Week3 [STEP 1] JM.Y
yagom-academy/swift-starter-week3 pull request #9
Opened 2021-12-23 16:21 UTC by JungmoYu

@Neph3779 안녕하세요 네프!

wee3/step1PR 작성합니다.

이번주에 공부한 pattern 을 사용해보고싶었는데, enum이 나오길래 한번 사용해봤습니다.
그리고 다음 스텝의 내용을 확인하지 않고, Step1의 조건에 대해서만 고민하여 작성하다보니 step2에서 코드가 많이 바뀔수도 있겠지만.
우선 현재까지의 내용을 기반으로 PR작성합니다.

감사합니다!

2021-12-23 16:24 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +
struct, class를 하나씩 써보고 싶었는데
우선 커피숍이 뭔가 나중에 상속의 개념을 받아쓰기에 더 적절할 것 같아서 `CoffeShop`을 class로 `Person`을 struct로 구현해봤습니다.

그리고 몇가지 메써드는 본체만 구현하고 속의 내용을 구현하지는 않았습니다.
예를들어 makeCoffee메써드의 경우 추후 어떻게 어떤 주문을 받아서 어떤 음료를 만들것이다! 하는 내용을 반영하여 만드는게 어떨까 생각하여 이렇게 빈 메써드로 만들어봤습니다.

2021-12-23 16:28 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +}
`Coffee` 타입의 경우 열거형으로 구현하라고 되어는 있는데,
여기서 가격을 연관값으로 가지게 구현해 보았습니다.

데이터타입을 다른 형식으로(예를들어서 또 생각해봤던 방식이 있기는 한데 - (String, Int) 형태의 튜플 ), 사실 아직 어떤식으로 데이터 타입을 만들어야겠다. 라는 확고한 느낌이 서지는 않습니다. 그래서 우선 최근에 공부한 기념으로.. enum(associated value)를 사용해봤습니다.

2021-12-24 00:07 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +
다른 캠퍼분에게도 드렸던 피드백이지만 struct안에 class변수가 있으면 성능적으로 좋지 않습니다 😂
https://developer.apple.com/videos/play/wwdc2016/416/
이 wwdc는 두고두고 돌려보게 될테지만.. 천천히 한 번정도 이해가 안되더라도 보시는걸 추천드려요~

2021-12-24 00:08 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +
pattern은 어떤 패턴을 말씀해주시는걸까요?

2021-12-24 00:19 UTC, Neph3779 requested changes
안녕하세요 정모님!
여러가지 패턴에 대해 학습해보셨군요!
피드백을 남겨드렸으니 읽어주시면 감사하겠습니다~!
조금만 더 이야기해보다가 다음 스텝으로 넘어가도 좋을 것 같아요!

2021-12-24 00:19 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +}
연관값을 코드에서 어떤 형식으로 쓰게 될까요?

2021-12-24 00:19 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +    var money: UInt
UInt의 사용 좋네요~!

2021-12-24 00:19 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +    let pickUpTable: String = "This is pick up table!"
이 변수는 왜 필요한건가요?

2021-12-24 00:19 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +            print(orderedItem)
이 부분이 어떻게 작동하는지 설명해주실 수 있으신가요?

2021-12-24 01:29 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +    let pickUpTable: String = "This is pick up table!"
pickUpTable을 말씀하시는건가요?
음료를 올려 둘 픽업테이블을 만들라고 하셔서 만들긴 했는데, 제 생각엔 나중에 꽉차있다/그렇지 않다 의 개념으로 사용하진 않을까? 라는 생각을 했었습니다.

또는 몇 개의 픽업대를(array?) 만들고, 몇 번의 픽업대에서 음료를 가져가라고 안내한다는 등의 사용을 예상했습니다.

그래서 아직 어떻게 사용할지 모르기 때문에 위와같이 String type 상수로 만들어두었습니다.

2021-12-24 01:34 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +            print(orderedItem)
```swift
func takeOrder(item: Coffee?) {
        if case .some(let orderedItem) = item {
            print(orderedItem)
        } else { print("주문을 받지 않았습니다.") }
}
```

위 코드에서 매개변수인 item이 Coffee타입의 optional이기 때문에, optional pattern으로 동작하는걸로 이해하고 사용했습니다.

옵셔널 패턴이며 동시에 연관값을 가지는 열거형-케이스 패턴으로, orderedItem 이라는 상수에 .some이 갖는 연관값이 할당되는 패턴입니다.

그런데 옵셔널의 정의 : 열거형으로 `case none` , `case some`이렇게 둘 이며, some의 경우 Wrapped라는 타입의 연관값을 가짐을 알 수 있었고, 그렇기에 `orderedItem` 자리에는 some의 연관값인 값(여기서는 Coffee 타입의 한 케이스)가 할당될 것으로 생각했습니다.

그렇기 때문에 실제로 `print(orderedItem)` 이 부분을 확인하면 예를들어서 americano(price: 4500) 이러한 값으로 출력됨을 확인했습니다. 

제가 이해하고 사용한 방법이 맞을까요?

2021-12-24 01:35 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +
지금 제가 만든 struct를 보았을때 피드백 주신, class 변수가 있는것인지 당장 이해가 되지 않습니다 ㅜㅜ 이 부분은 더 공부해 보도록 하겠습니다!

보내주신 링크는 꼭 확인해보도록 하겠습니다.

2021-12-24 01:38 UTC, JungmoYu commented on CodeStarterCamp_Week3/Type.swift
> +}
제가 여기서 사용한 의도는 나중에 가격정보같은것을 사용하여 매출액에 포함한다던지, 또는 고객에게 총 주문한 음료들의 총액을 계산하여 알려준다던지...이러한 계산들을 할 때 사용할 의도로 만들었습니다!

패턴을 잘 사용하여 연관값을 상수(또는 변수)로 할당하여 사용해야 할 것 같습니다.
마치 아래의 `takeOrder(item: Coffee?)`함수처럼이요!

아직 구체적으로 어떻게 사용해야할 지는 모르겠습니다.. 여러가지 시도를 해 봐야할 것 같습니다!

2021-12-24 01:39 UTC, JungmoYu commented
피드백 감사드립니다.
남겨주신 피드백들에 대하여 제 의견을 남겨두었습니다! 감사합니다!

2021-12-26 20:41 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +    let pickUpTable: String = "This is pick up table!"
미래를 생각하는 것은 좋지만 오버엔지니어링이 되지 않도록 항상 유의해주시면 더 좋을 것 같아요~

2021-12-26 20:53 UTC, Neph3779 commented on CodeStarterCamp_Week3/Type.swift
> +            print(orderedItem)
네 맞습니다~
https://useyourloaf.com/blog/swift-if-case-let/
위 링크에 추가적으로 공부해볼법한 내용들이 잘 정리되어 있어서 공유드려요~

2021-12-26 20:54 UTC, Neph3779 commented
안녕하세요 정모님! 이번 스텝도 잘 해주셨어요!
if case let 구문이 잘 사용되지는 않지만 이번기회에 공부해보신 것 같네요! 👍
그럼 다음 스텝도 화이팅입니다!!

2021-12-26 20:54 UTC, merged

2021-12-27 13:14 UTC, JungmoYu commented
피드백 감사드립니다!
그리고 올려주신 링크들도 확인하여 더 좋은 코딩을 하도록 노력해보겠습니다!