Week3 [step3] duck
yagom-academy/swift-starter-week3 pull request #95
Opened 2022-05-02 12:37 UTC by Hong-seungju

@llghdud921 
안녕하세요 제리~
CoffeeShop은 Class 타입으로 변경하였습니다. 변경한 이유는  구조체는 값타입이기에 값의 복사가 이루어져서. 변수를 할당하면 복사가 일어나고 복사된 값을 가져오는것이기에 원본 인스턴스에는 반영이되지 않아 class를 사용했습니다.

2022-05-04 07:20 UTC, llghdud921 requested changes
안녕하세요~ duck
제가 리뷰한줄 알고 있었는데... 안했더라구요... 늦게 리뷰드려 죄송합니다...

- github 사용
<img width="360" alt="스크린샷 2022-05-04 오후 4 17 33" src="https://user-images.githubusercontent.com/40068674/166637496-ac7f49c1-54e4-494e-a9bc-1626e809c828.png">
  제가 지난번에 git push -f 를 사용해보라고 말씀드렸는데 여전히 반영이 되어있지 않더라구요ㅠ
  다음번에 같이 화면공유해보면서 다시 이야기 해봅시당

- 현재 로직은 커피를 구매 시 Person의 money가 줄어들지 않고 있는 것 같아요! 
   이 부분을 개선해보면서 로직을 재구성해보는 것이 좋을 것 같습니다 👍

2022-05-04 11:30 UTC, Hong-seungju commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +        }
넵 수정하겠습니다.

2022-05-04 11:32 UTC, Hong-seungju commented on CodeStarterCamp_Week3/CoffeeShop.swift
> +    func makeCoffee(_ coffee: Coffee, _ person: Person) {
감사합니다👍

2022-05-04 11:32 UTC, Hong-seungju commented on CodeStarterCamp_Week3/Person.swift
> +        coffeeShop.getOrder(coffee, self)
감사합니다👍

2022-05-04 11:33 UTC, Hong-seungju commented on CodeStarterCamp_Week3/Person.swift
> +    mutating func buyCoffee(_ coffee: Coffee, _ coffeeShop: CoffeeShop) {
값 타입의 인스턴스 메서드에서 자신 내부의 값을 변경하고자 할 때 사용하는 키워드, 인스턴스 메서드에서 프로퍼티를 수정하기 위해서 mutating을 사용하여 메서드 내에서 프로퍼티를 변경할 수 있어서 사용합니다..

2022-05-04 12:56 UTC, Hong-seungju commented
@llghdud921  안녕하세요 제리!
아까 DM으로 질문했던 것으로 인해 Person을 Class로 변경하였습니다.

2022-05-05 02:01 UTC, merged

2022-05-05 02:02 UTC, llghdud921 commented
duck 수정된 부분 잘 보았습니다!
duck의 코드는 깔끔하고 알아보기 쉬워서 좋은 것 같아요 👍  고생하셨습니다!!