Week 1 [STEP 3] Oh Sung Ah
yagom-academy/swift-starter-week3 pull request #97
Opened 2022-05-03 10:00 UTC by delight010

@jaemuYeo 

바리스타가 여러명일지도 모른단 생각에 배열로 작성을 했습니다.

`var barista: [Person]?`

처음에는 이렇게 작성했으나 인스턴스를 생성할 때 
자동으로 배열을 초기화시켜주지않아 `.append`를 해도 오류가 계속 떴습니다.

`var barista:  [Person] = []`
미리 초기화를 하니 `.append`도 잘 동작했어요!

열거형에 원시값을 바로 넣어줘도 되지만,
개별로 관리하고 싶어서 CoffeeShop의 menu를 딕셔너리 형태로 만드는 것을 택했습니다!

또한 사람이 방문한 커피샵도 매개변수로 받아, 커피샵을 통해 가격을 가져오는 방법을 사용했어요

2022-05-03 15:08 UTC, jaemuYeo requested changes
안녕하세요 성아님! 타입설계를 아주 잘 해주셨군요 👍
몇 가지 생각을 코멘트로 남겨두었습니다!!
객체별로 파일을 만들어 저장하고, main에서 인스턴스를 생성 후 실행하는 방법도 있답니다😊
질문드리고 싶은 것은 클래스와 구조체중 클래스로 선택하신이유를 묻고싶어요~!
그리고 객체만 3개에 Person, CoffeeShop 객체에 하나씩 메서드가 구현되었는데
커밋은 3개뿐이군요 😭
조금 귀찮더라도 커밋을 설계단위를 잘 쪼개어 남기는 연습도 매우 중요하답니다!!
위 내용에 대해 얘기나눠보고 특별한 수정사항이 없을 경우 머지 진행하겠습니다😀

2022-05-04 08:10 UTC, delight010 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Bool?
커피가 있는가 없는가로 생각하고 참, 거짓으로 구분할 수 있는 Bool을 선택했습니다~
문제 자체가 잘 이해가 안되요. 원래대로라면 nil이 들어갈 수 있는 타입이라면 되는 건가요?ㅠㅠ

2022-05-04 10:00 UTC, delight010 commented
@jaemuYeo 
잼킹님 말씀해주신 메소드명과 매개변수명이 더 간결하고 보기 편해서 변경했습니다!
Person내의 커피사는 메소드 내부의 가격 변수도 coffeePrice -> price로 더 간결하게 바꾸었어요!
pickUpTable 변수는 제가 문제를 잘못이해하고 있어서, 타입을 변경했습니다!

타입 Person, CoffeeShop 둘 다 계속 변할 수 있는 인스턴스를 가지고 있어서
클래스를 선택해서 구현했습니다!

2022-05-04 11:03 UTC, jaemuYeo commented
pickUpTable 타입에 대한 문제는 나중에 어떻게 쓰이냐에 따라 Bool이 될 수 도 있고,
제가 생각했던 Coffee? 타입이 될 수도 있을 거같아요!!
단지 성아님의 생각을 여쭤보았습니다~ 제가 틀렸을 수도 있구요!!
네이밍도 훨씬 보기 좋아진 것 같아요 👍
스텝1 머지 진행 하고 다음 스텝에서 인스턴스의 활용을 기대하겠습니다!

2022-05-04 11:03 UTC, merged