Week3 [STEP 1] wonbi
yagom-academy/swift-starter-week3 pull request #98
Opened 2022-05-03 20:21 UTC by wonbi92

@ye-ha 

## 고민한 부분

### 현실 커피 주문 과정
- 더 세밀하게 생각도 해봤지만, 일단은 과제에 주어진 정도 내에서 생각해보려고 했습니다. 메뉴를 선택하고, 돈을 지불하고, 커피를 받는 순으로 생각해봤습니다.  

- 커피숍은 주문을 받고, 돈을 받고, 주문 받은 메뉴를 만들고, 픽업대에 올려놓는 순으로 생각했습니다.

### 커피숍과 사람은 클래스인가 구조체인가?
- 사람은 개개인의 특성이 다르기 때문에 참조 타입인 클래스를 사용할 순 없다 판단하였습니다. 

- 커피숍도 마찬가지의 이유로 각 커피숍 별 바리스타와 현재 주문 상황, 매출액 등이 다 다를 수 있기 때문에 참조 타입을 사용하는것은 적절하지 않다 판단하였습니다.

## 해결 안된 부분

### 열거형의 연관 값
- 처음에는 각 커피의 가격, 컵의 사이즈, 찬음료인지 차가운 음료인지, 등등의 연관 값을 넣어서 커피를 좀 더 세세하게 구분하고자 하였습니다.

- 그런데 제가 연관 값을 잘 활용하지 못한 상태였기에 이를 억지로 활용하다 보니 오히려 코드를 짜는데 더 큰 어려움들이 많이 생겼습니다.
- 예를 들어 각 연관 값을 상수로 빼내어 이를 활용하는 방법이라던가.. 이런 부분들의 방법 자체는 알았지만 이 코드에 녹이는 것까지는 하지 못했습니다.

## 조언을 얻고 싶은 부분

### 어디까지 해야 하는가..
- 위와 같은 이유로 열심히 만들어 두었던 커피 열거형을 모두 지우고 간단하게 원시 값과 커피 가격을 호출해주는 함수를 만들어서 사용하는 방법을 선택했습니다.

- 과제에서 제시한 부분들은 나름대로 풀었다고 생각하지만, 이렇게 타협하는 게 괜찮은 건지 조금 의문이 듭니다. 저 연관 값을 활용하는 게 맞는 판단이었을까요?

2022-05-04 07:18 UTC, ye-ha requested changes
원비님, 이번 스텝은 더 열심히 진행해주셨군요. 원비님의 고민과 열정이 느껴집니다. 고생하셨습니다. 👍
배우는 것이 더 많고, 원비님이 잘 소화해주시는 만큼 코멘트가 많습니다. 
이해되지 않거나 함께 이야기를 나눠보고 싶은 부분은 코멘트에 남겨주세요! 

> 현실 커피 주문 과정
더 세밀하게 생각도 해봤지만, 일단은 과제에 주어진 정도 내에서 생각해보려고 했습니다. 메뉴를 선택하고, 돈을 지불하고, 커피를 받는 순으로 생각해봤습니다.
커피숍은 주문을 받고, 돈을 받고, 주문 받은 메뉴를 만들고, 픽업대에 올려놓는 순으로 생각했습니다.

고민하신 흔적을 볼 수 있었습니다. 👍 어떤 순서를 생각하신 건지 알 수 있게 인스턴스를 통해 메서드를 호출하는 부분을 추가해주세요! 😄

> 커피숍과 사람은 클래스인가 구조체인가?
사람은 개개인의 특성이 다르기 때문에 참조 타입인 클래스를 사용할 순 없다 판단하였습니다.
커피숍도 마찬가지의 이유로 각 커피숍 별 바리스타와 현재 주문 상황, 매출액 등이 다 다를 수 있기 때문에 참조 타입을 사용하는것은 적절하지 않다 판단하였습니다.

고민하신 점, 좋습니다! 👍 해당 부분은 값타입과 참조타입을 더 공부해보시는 것을 추천합니다. 😄

> 해결 안된 부분
열거형의 연관 값
처음에는 각 커피의 가격, 컵의 사이즈, 찬음료인지 차가운 음료인지, 등등의 연관 값을 넣어서 커피를 좀 더 세세하게 구분하고자 하였습니다.
그런데 제가 연관 값을 잘 활용하지 못한 상태였기에 이를 억지로 활용하다 보니 오히려 코드를 짜는데 더 큰 어려움들이 많이 생겼습니다.
예를 들어 각 연관 값을 상수로 빼내어 이를 활용하는 방법이라던가.. 이런 부분들의 방법 자체는 알았지만 이 코드에 녹이는 것까지는 하지 못했습니다.

내가 더 표현할 수 있는 부분이 있을지, 더 활용해보면 좋을 개념이 있을지 고민해보신 점 좋습니다 👏👏👏👏
다만, 이번 스텝은 컵의 사이즈나 음료의 온도 등을 고려하며 구현하는 스텝이 아닙니다. 스텝의 목표인 **객체 사이의 관계와 상호작용**에 대해 고민하며 배울 수 있도록, 스텝에서 제시한 내용보다 더 많은 내용을 구현하지 않으시는 것이 좋다고 생각합니다. 

> 조언을 얻고 싶은 부분
�어디까지 해야 하는가..
위와 같은 이유로 열심히 만들어 두었던 커피 열거형을 모두 지우고 간단하게 원시 값과 커피 가격을 호출해주는 함수를 만들어서 사용하는 방법을 선택했습니다.
과제에서 제시한 부분들은 나름대로 풀었다고 생각하지만, 이렇게 타협하는 게 괜찮은 건지 조금 의문이 듭니다. 저 연관 값을 활용하는 게 맞는 판단이었을까요?

코멘트로 남겼지만 한 번 더 말씀드리면, 이미 CoffeeShop이 메뉴 리스트(메뉴와 가격)를 갖고 있습니다! Coffee enum에서 또 가져야 할까요? 
추가로 열거형은 어떤 경우에 사용하면 좋을까요?

2022-05-04 07:18 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Array<Coffee>?
pickUpTable은 왜 Array<Coffee>? 타입인가요? 
현재 코드에서 어떤 역할도 하고 있지 않습니다. 우리가 커피를 주문할 때 언제 pickUpTable을 사용하는지 생각해서 수정해봅시다!

2022-05-04 07:18 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +    var orderQueue: (who: Person, menu: Coffee)?
튜플을 사용해주셨군요! 👍

2022-05-04 07:18 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +        barista = who
who라는 네이밍이 어색합니다.. 다른 이름으로 바꿔볼 수 있을까요? 🤔

2022-05-04 07:18 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +        menuPan[what] = what.price()
what이라는 이름이 어색합니다.

2022-05-04 07:18 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +        print("\(from)님이 주문하신 메뉴는\(menu.rawValue)입니다.")
from이라는 이름과 사용이 어색합니다.

2022-05-04 07:18 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +        if let orderQueue = orderQueue {
안전하게 언래핑해주셨군요! 👏
orderQueue 라는 네이밍이 어색합니다.. 네이밍에 타입을 잘 넣지 않는데요. 어떻게 바꿔볼 수 있을까요?

2022-05-07 14:41 UTC, wonbi92 commented on CodeStarterCamp_Week3/main.swift
> +    var menuPan: Dictionary<Coffee, Int> = [:]
메뉴판 너무 무지성한 네이밍이긴 했네요.. ㅋㅋ 다시 수정했습니다. 열거형에서 가격을 가지는건 열거형을 좀 더 활용해보고 싶어서 였는데, 다시보니 굳이 필요없는 부분인거 같아서 수정하였습니다.

2022-05-07 14:42 UTC, wonbi92 commented on CodeStarterCamp_Week3/main.swift
> +    }
일단 써놓고 나중에 구현하려고 했는데 그대로 까먹어버렸네요.. ㅠㅠ

2022-05-07 14:43 UTC, wonbi92 commented on CodeStarterCamp_Week3/main.swift
> +    init(sales: Int, barista: Person) {
이 프로퍼티는 과제에서 제시했던 "매출액" 입니다. 조금 더 알기 쉽게 `salesRevenue`로 수정했습니다.

2022-05-07 14:44 UTC, wonbi92 commented on CodeStarterCamp_Week3/main.swift
> +var yagomBucks: CoffeeShop = CoffeeShop(sales: 0, barista: misterLee)
넵! 변수 뒤에 타입 어노테이션을 해주는게 습관으로 남아서.. 그래도 이게 통일성이 있는게 좋을거 같아 뒷부분을 `.init`으로 수정해서 가독성을 좀 더 높혔습니다.

2022-05-07 14:49 UTC, wonbi92 commented on CodeStarterCamp_Week3/main.swift
> +var yagomBucks: CoffeeShop = CoffeeShop(sales: 0, barista: misterLee)
1. 96 번을 띄운건 과제에서 `misterLee`와 `missKim`을 선언하는 것과 `yagomBucks`를 선언하는 것을 각각 한줄 씩 표현해서 그 과정을 따라서 가다보니 한줄을 띄우게 되었습니다. 큰 의미를 두고 띄운것은 아닌데 이런 부분들에 주의할 필요가 있나요?
2. 넵 사는 과정을 호출해서 다시 올렸습니다!

2022-05-07 14:50 UTC, wonbi92 commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Array<Coffee>?
넵 픽업 테이블에 하나의 커피만 두는 것이 아니라 여러 주문이 밀리면 그 밀린 주문들의 음료가 쌓이는걸 생각해서 Array로 했었습니다. 코드를 수정하는 과정에서 이를 구현하는건 너무 복잡하고, 주제에서도 많이 벗어나는거 같아, `Coffee`값을 가지도록 수정했습니다.

2022-05-07 14:52 UTC, wonbi92 commented on CodeStarterCamp_Week3/main.swift
> +        barista = who
넵 수정했습니다.

2022-05-07 14:52 UTC, wonbi92 commented on CodeStarterCamp_Week3/main.swift
> +        menuPan[what] = what.price()
이 역시 수정했습니다

2022-05-07 15:00 UTC, wonbi92 commented on CodeStarterCamp_Week3/main.swift
> +        if let orderQueue = orderQueue {
주문 대기열 이라는 뜻으로 `orderQueue`라는 네이밍을 했었는데요. 네이밍에 타입을 잘 넣지 않는다는 말이 어떤 뜻인지 잘 이해가 안되네요.. ㅜㅜ 언래핑 한 이후에 사용하는 `orderQueue.menu.rawValue`라는 표현식도 제 생각에는 큰 문제가 없다고 판단됩니다. 제가 생각하지 못한 부분이 있을까요??

2022-05-09 06:59 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +yagomBucks.settingPrice(menu: .americano, .latte, .mocha, .macchiato, price: 4000, 4500, 4500, 5000)
이 줄에서 에러가 발생합니다. 😭

2022-05-09 06:59 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +        if let orderQueue = orderQueue {
Queue 라는 타입이름이 들어가있다는 의미였습니다!

2022-05-09 07:02 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +yagomBucks.settingPrice(menu: .americano, .latte, .mocha, .macchiato, price: 4000, 4500, 4500, 5000)
이게 제 xcode 버젼의 문제일지도 모르겠어요. 원비님은 문제없는 상황이 맞나요?

2022-05-09 07:09 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +var yagomBucks: CoffeeShop = CoffeeShop(sales: 0, barista: misterLee)
의미 있는 코드 작성! 중요하죠. 개행도 코드의 일부니까요. 그렇기에 각자 자기 만의 가독성을 위한 규칙이 있답니다. 규칙이 있으면 통일성도 생기고요. 😄

2022-05-09 07:16 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +    var pickUpTable: Array<Coffee>?
`pickUpTable`이 `Coffee`가 아닌 다른 타입이어도 코드에서 역할을 충분히 해줄 수 있을 것 같아요. 현재 코드에서는 `Bool`도 좋을 것 같고요!

2022-05-09 07:17 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +            print("먼저 주문을 해주십시오.")
안전한 검증 좋습니다. 다만, 이 코드가 세 번 이상 반복되고 있어요. 미리 한 번만 검증할 수 있을까요? 🤔

2022-05-09 07:22 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +var yagomBucks: CoffeeShop = CoffeeShop(sales: 0, barista: misterLee)
기존의 코드는 'Person타입을 생성하는구나. 이름은 뭐구나.' 이렇게 바로 읽히는데, 
`var misterLee: Person = .init(name: "misterLee", money: 0)` 
위의 변경해주신 코드는 읽다가 다시 돌아가서 무엇을 생성하는지 봐야 하고, 타입 Person을 확인해도 다시 인자를 확인해주어야 해서 가독성이 더 떨어졌다고 생각됩니다. 😭 문장처럼 술술 읽히는 네이밍을 권장하는 것, 코드도 같습니다.

2022-05-09 07:25 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +            payment += orderedMenuPrice
메뉴 가격을 더해주고 있네요! 의도된 것이죠?

2022-05-09 07:28 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +    var payment: Int = 0
payment 프로퍼티가 주문하는 메뉴의 가격을 담고 있어요. Person이 주문하는 메뉴의 가격을 계속 저장하고 있을 필요가 있을까요? 🤔

2022-05-09 07:34 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +yagomBucks.settingPrice(menu: .americano, .latte, .mocha, .macchiato, price: 4000, 4500, 4500, 5000)
다중 가변 매개변수를 활용하셨군요! 👏👏

2022-05-09 07:34 UTC, ye-ha commented on CodeStarterCamp_Week3/main.swift
> +missKim.pickUp(where: yagomBucks)
각 역할에 맞게 하는 일을 분리하신 점, 아주 좋습니다. 👍

2022-05-09 07:36 UTC, merged